### ISSUE TITLE
Rust-analyzer gives a syntax error on attributes in if expr

### ISSUE THREAD

**Issue by GrayJack** [rust-analyzer/rust-analyzer#4886] opened 2020-06-15 04:55 UTC
I get a `Syntax error: attributes are not allowed on IF_EXPR`, but since Rust 1.43 it is allowed.

I'm using 017331a53c1eeaa1253d2829165627bfa27dc124 right now

**Comment by lnicola** [comment] 2020-06-15 06:13
Duplicate of #4386.

**Closed by lnicola** 2020-06-15 06:13 UTC
