### ISSUE TITLE
Command Run Analyzer (Ctrl+R) conflict with VSC key bindings

### ISSUE THREAD

**Issue by andreevlex** [rust-analyzer/rust-analyzer#1480] opened 2019-07-04 13:02 UTC
Key binding `Ctrl+R` concflict with VSC system.
menu File -> Open Recent -> More...

**Comment by SomeoneToIgnore** [comment] 2020-02-17 19:13
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/2733

**Closed** 2020-02-18 08:40 UTC
