### ISSUE TITLE
Expand derive assist

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2109] opened 2019-10-28 14:38 UTC
It would be really cool if RA could expand a `derive`, for cases like when you need to switch from a `#[derive(Debug)]` to a manual implementation because you added a non-`Debug` field. This could probably work for `Clone`, `Debug` and `Hash`.

Bonus points if it could invoke `cargo expand` or something like that and work for any custom derive. Dumping the output of `#[derive(Deserialize, Serialize)]` into a source file is so tempting at times (because it avoids the proc macro).

**Comment by matklad** [comment] 2019-10-28 16:13
dupe of #1256

**Closed by matklad** 2019-10-28 16:13 UTC
