### ISSUE TITLE
Closing brace of format! argument not highlighted

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#4696] opened 2020-06-01 21:16 UTC
The bug appears for all [formatting traits](https://doc.rust-lang.org/std/fmt/index.html#formatting-traits) except `Display` and `Debug`, and for all [formatting macros](https://doc.rust-lang.org/std/fmt/index.html#related-macros).

Screenshot using the [`Pointer`](https://doc.rust-lang.org/std/fmt/trait.Pointer.html) trait (note that the closing brace is orange instead of blue):

![macros](https://user-images.githubusercontent.com/15658558/83454334-4f251c00-a45c-11ea-8db3-70def7ecdbfd.png)

**Comment by kiljacken** [comment] 2020-06-02 18:07
Might be caused by #4658, would you mind checking with a build from before that was merged?

**Comment by Aloso** [comment] 2020-06-02 19:19
@kiljacken that's very possible. To make sure, I'll have to clone and build rust-analyzer, because nightly builds other than the latest one are not available in VS Code or GitHub. This will take a while on my low-end PC :)

**Comment by Aloso** [comment] 2020-06-02 21:46
@kiljacken I removed the rust-analyzer extension, cloned rust-analyzer, reverted #4658 and executed `cargo xtask install`, but the bug still appears. It seems that #4658 is not at fault.

**Comment by ltentrup** [comment] 2020-06-07 21:02
This issue was caused by a bug in the format specifier lexer. I opened a pull request with a fix

**Closed** 2020-06-08 09:13 UTC
