### ISSUE TITLE
Problems with inline hints with proc_macro 

### ISSUE THREAD

**Issue by barvirm** [rust-analyzer/rust-analyzer#8547] opened 2021-04-16 22:58 UTC
Rust-analyzer knows the correct type, but inline hint shows different types.
Is this problem with configuration, or I inline hint cannot resolve types creates in proc_macro?

```
/*
#[throws(i32)]
fn foo(x: bool) -> i32 {
    if x {
        0
    } else {
        throw!(1);
    }
}

// expanded code
fn bar(x: bool) -> Result<i32, i32> {
    if x {
        Ok(0)
    } else {
        Err(1)
    }
}
*/
// --------------------------------------------------
#[derive(Debug)]
struct Xerror;

#[throws(Xerror)]
fn foo(i: i32) -> i32 {
    if i < 0 {
        Err(Xerror)?;
    }
    i
}

fn main() {
    let _x = foo(32);  // this shows inline hint as i32, but correct type is Result<i32, Xerror>
}
```

**Comment by Veykril** [comment] 2021-04-16 23:03
We don't expand attribute macros yet. Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6029.

**Closed by Veykril** 2021-04-16 23:03 UTC
