### ISSUE TITLE
Implement multi workspace/multiple crate cargo check support

### ISSUE THREAD

**Issue by kiljacken** [rust-analyzer/rust-analyzer#2792] opened 2020-01-10 22:02 UTC
While trying to fix #2780 I had some thoughts about how `cargo check` watching interacts with multi-workspaces and multiple-project-in-single-workspace setups.

Having multiple workspaces is in theory simple: Just launch a watcher for each workspace, and then figure out how to multiplex the result channels. Should be doable, with not too large an amount of work.

The main issue comes with having multiple projects inside a single workspace. Because multiple crates that don't share a cargo workspace could depend on each other, we can't naively run a cargo check instance for each crate.

And here's where i need somebody to check my thoughts: It seems that the thing we need to do, to solve both issues, is to run a check watcher for each crate where:
* The crate lives in an open workspace.
* The crate is a purely a root in the crate graph, that is, not other crate depends on it.

Which doesn't sound too bad. There is one small problem, which is probably a solved problem in graph theory: For the second condition to be checked quickly, we need to be able to invert the crate graph, so that instead of mapping from `crate -> dependencies` it maps `crate -> crates depending on it`.

The above seems to make sense in my head, but I'd love hear peoples opinions. These things tend to turn out better and simpler when multiple heads come together.

**Comment by kiljacken** [comment] 2020-01-10 22:12
Hmm, we'd still have problems with locking per cargo workspace, but the above would ensure that every crate would eventually get diagnostics.

**Comment by DianaNites** [comment] 2020-02-18 07:38
Any progress here? Lack of diagnostics for all but the first VSCode workspace is a frequent pain point for me.

**Comment by Ten0** [comment] 2020-04-14 08:49
For the single-workspace, multi-project setup, wouldn't it trigger the `cargo check` locks (`Blocking waiting for file lock on build directory`), and thus hurt performance? If so, what about adding an option to `cargo` where it wouldn't stop checking whatever it can check even if one project failed? This way, even with a single `cargo check` on the workspace, every crate that can compile or is the cause of non-compilation would still get diagnostics.

**Comment by danilaml** [comment] 2020-08-27 00:42
Would be nice to have the support for this like in the IntelliJ plugin. Or at least a way to switch the "current" Cargo project in the workspace.

**Comment by jonas-schievink** [comment] 2020-12-18 22:01
Since https://github.com/rust-analyzer/rust-analyzer/pull/6027 we support multiple `cargo check` processes, and will spawn one per client workspace. I don't think it supports multiple *Cargo* workspaces (or crates without workspace) in the same client workspace though.

**Comment by matklad** [comment] 2021-04-23 10:45
> I don't think it supports multiple Cargo workspaces (or crates without workspace) in the same client workspace though.

@jonas-schievink hm, my understanding is that this issue is completely fixed though? We spawn `cargo check` for each separate linked project, and that's all there's to do, no?

I'd close this issue, but I am confused by your comment, so maybe I am missing something?

If anything, this works too well: https://github.com/rust-analyzer/rust-analyzer/issues/8631 :rofl:

**Comment by jonas-schievink** [comment] 2021-04-23 12:56
Hmm, yeah, I think this might be a case of confusing terminology. Workspace can mean "Cargo workspace", "client workspace", or "whatever rust-analyzer considers a workspace".

**Closed by jonas-schievink** 2021-04-23 12:56 UTC
Labels: S-actionable

**Comment by MolotovCherry** [comment] 2023-06-04 16:37
If anyone comes from google, the way to do this is:
In `.vscode/settings.json`:
```json
{
    "rust-analyzer.linkedProjects": [
        "path/to/Cargo.toml",
        "another/path/to/Cargo.toml"
    ]
}
```
