### ISSUE TITLE
unresolved extern crate test in benchmark

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7040] opened 2020-12-25 21:37 UTC
![image](https://user-images.githubusercontent.com/33961674/103142301-56b25800-4701-11eb-92af-db8267d67031.png)

seems rust-analyzer cannot find test crate with feature gate. [click me to see reproducible example](https://github.com/casbin/casbin-rs/blob/master/benches/benchmark.rs)

**Reproduce**:

1. create an empty project, create benches directory and `benches/benchmark.rs`
2. add the following code
    ```
    #![feature(test)]
    extern crate test;
    ```
3. line 2 reporting `unresolved extern crate` error

**Comment by Veykril** [comment] 2020-12-25 21:42
Duplicate of #6714

**Closed** 2020-12-25 21:43 UTC
