### ISSUE TITLE
Support native inlay hints in VS Code 1.65

### ISSUE THREAD

**Issue by Diegorro98** [rust-analyzer/rust-analyzer#11619] opened 2022-03-04 18:43 UTC
VS Code 1.65 has been released and with it Inlay Hint provider API has been released (https://github.com/microsoft/vscode/issues/32856)
Maybe its a good idea to implement the already existing inlay hints on this extension thru the mentioned API.

**Comment by lnicola** [comment] 2022-03-04 18:45
Duplicate of #2797.

If you want, you can test #11445. Unfortunately, the native ones are less nice than our implementation, but we'll probably merge that anyway next week.

**Closed by lnicola** 2022-03-04 18:45 UTC
