### ISSUE TITLE
file still locked even after exit of vim, vscode

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8653] opened 2021-04-25 01:52 UTC
sometimes  I would like to quit vim and & run only cargo check to do a final check. This often happens when we would like to commit our code, but it looks that rust-analyzer doesn't have a good control of this, some processes are still running so the files are still locked for a pretty long time.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/33961674/115977555-f1397f80-a5ab-11eb-88c0-3ae81b27a7ef.png">

**Comment by GopherJ** [comment] 2021-04-25 01:53
I also see other people encountering this during a live coding demo, it often confuses people as we need to check which process is still running and is taking up the lock.

**Comment by bjorn3** [comment] 2021-04-25 07:42
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5258

**Closed by bjorn3** 2021-04-25 07:42 UTC
