### ISSUE TITLE
Goto definition of implementation of trait is not accurate.

### ISSUE THREAD

**Issue by wasd96040501** [rust-analyzer/rust-analyzer#10153] opened 2021-09-05 07:19 UTC
https://github.com/rust-analyzer/rust-analyzer/blob/c16e6474f9e4d11d967e5309735b0e673f4c24da/crates/ide/src/goto_definition.rs#L176-L178
When I run goto definition of `.try_to_nav`, it navigate to
https://github.com/rust-analyzer/rust-analyzer/blob/c16e6474f9e4d11d967e5309735b0e673f4c24da/crates/ide/src/display/navigation_target.rs#L74-L76
which seems not accurate. Because `def` is in clear definition `Definition`. So It should navigate to implementation of `.try_to_nav`
https://github.com/rust-analyzer/rust-analyzer/blob/c16e6474f9e4d11d967e5309735b0e673f4c24da/crates/ide/src/display/navigation_target.rs#L202-L204

**Comment by flodiebold** [comment] 2021-09-05 07:29
Duplicate of #4558.

**Closed by flodiebold** 2021-09-05 07:29 UTC
