### ISSUE TITLE
proc macro server crashed

### ISSUE THREAD

**Issue by Volker-Weissmann** [rust-analyzer/rust-analyzer#9341] opened 2021-06-19 20:57 UTC
I'm not sure if this might be a case of "proc macros are not supported: #6029", but because an explicit error message is shown, I don't think so.
The code below makes vscode show me
```
proc macro server crashedrust-analyzermacro-error
```
if I hover above the `tex_expr` line.

Rust analyzer language server output:
```
[ERROR proc_macro_api::process] proc macro server crashed, server process state: Ok(Some(ExitStatus(ExitStatus(139)))), server request error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
```

Rust analyzer client output:
```
INFO [6/19/2021, 10:49:19 PM]: Extension version: 0.2.621
INFO [6/19/2021, 10:49:19 PM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'stable', askBeforeDownload: true },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  files: { watcher: 'client', excludeDirs: [] },
  highlighting: { strings: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    run: true,
    linksInHover: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [6/19/2021, 10:49:19 PM]: PersistentState: {
  lastCheck: undefined,
  nightlyReleaseId: undefined,
  serverVersion: '0.2.621'
}
INFO [6/19/2021, 10:49:19 PM]: Using server binary at /home/volker/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

```shell
$ "/home/volker/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu" --version
rust-analyzer 28e32fe40 2021-05-31 stable
```

main.rs:
```rust
#[macro_use]
extern crate math_dsl_macro;
fn main() {
    tex_expr!("1+2");
}
```
Cargo.toml:
```toml
[package]
name = "bug"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math_dsl_macro = { git = "https://gitlab.com/volkerweissmann/math_dsl_macro.git", rev = "78e657687bf50b3f407a537f1b4b59a66ad8755d" }
```

**Comment by flodiebold** [comment] 2021-06-19 21:37
Probably a duplicate of #8925. Are you using rust nightly?

**Comment by Volker-Weissmann** [comment] 2021-06-19 23:13
Yes

```
$ rustc --version
rustc 1.55.0-nightly (ce1d5611a 2021-06-18)
```

**Comment by lnicola** [comment] 2021-06-20 03:09
Yeah, they're currently broken in nightly.

**Closed** 2021-06-20 03:08 UTC
