### ISSUE TITLE
Go-to-definition on a trait function should go to the implementation, not the declaration

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#6567] opened 2020-11-17 03:58 UTC
I ran across this in rustdoc, but I'm sure it's easy to reproduce in small codebases.

Pressing F12 on `clean` in https://github.com/rust-lang/rust/blob/9b2b02a840f358bcadef5c3ae861d2852da20b3d/src/librustdoc/clean/mod.rs#L1110 goes to https://github.com/rust-lang/rust/blob/9b2b02a840f358bcadef5c3ae861d2852da20b3d/src/librustdoc/clean/mod.rs#L54. It should instead go to https://github.com/rust-lang/rust/blob/9b2b02a840f358bcadef5c3ae861d2852da20b3d/src/librustdoc/clean/mod.rs#L889.

**Comment by jyn514** [comment] 2020-11-17 03:58
Github should really show the code previous across git repositories :/

**Comment by flodiebold** [comment] 2020-11-17 11:00
Duplicate of #4558.

**Closed by flodiebold** 2020-11-17 11:00 UTC
