### ISSUE TITLE
Incorrect `implement missing members` implementation

### ISSUE THREAD

**Issue by CrazyRoka** [rust-analyzer/rust-analyzer#10994] opened 2021-12-12 13:48 UTC
**rust-analyzer version**: 7d6fcbc0b 2021-12-06 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

I am working with https://github.com/bevyengine/bevy, module `bevy_ecs` (You can see full path on the video below).
`Implement missing members` incorrectly typed the function for `StageLabel` trait:
`fndynclone(&self) ....`

https://user-images.githubusercontent.com/19844144/145714858-ed14d796-8c61-4290-b9ee-e3e4945c9441.mp4

**Comment by flodiebold** [comment] 2021-12-12 14:08
Duplicate of #6588.

**Closed by flodiebold** 2021-12-12 14:08 UTC
