### ISSUE TITLE
Invoking derived default() for tuple struct declared in function produces "Expected 1 argument, found 0"

### ISSUE THREAD

**Issue by TedDriggs** [rust-analyzer/rust-analyzer#7256] opened 2021-01-12 16:27 UTC
rust-analyzer version: 0.2.449

```rust
fn repro() {
    #[derive(Default)]
    struct EvidenceVisitor(String);
    let mut evidence_visitor = EvidenceVisitor::default();
}
```

This puts an error spanning `EvidenceVisitor::default()` which says "Expected 1 argument, found 0"

Adding a second member updates the error to "Expected 2 arguments, found 0"

Changing to an explicit `impl Default for EvidenceVisitor` doesn't change the error.

Changing to a unit struct or named struct makes the error disappear.

Moving the struct declaration outside the function body makes the error disappear. In the real code, I have the struct inside the function declaration because the whole function is `cfg`-gated, but the repro doesn't depend on conditional compilation.

**Comment by lnicola** [comment] 2021-01-12 16:29
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1559.

**Comment by TedDriggs** [comment] 2021-01-12 16:39
Ah, sorry. I looked for the error I got and found #5502 but didn't find that one.

**Comment by flodiebold** [comment] 2021-01-12 16:57
Hmm there seems to be something going wrong with the name resolution there though, i.e. it looks like we resolve the `EvidenceVisitor::default` to the `EvidenceVisitor` constructor? We do have some basic support for function-local things which may be going wrong here, so I think it's worth checking whether there's something additional going on.

**Comment by jonas-schievink** [comment] 2021-03-12 15:40
This no longer occurs, but we still don't support local impls properly

**Comment by jonas-schievink** [comment] 2021-08-20 23:51
This is all fixed now

**Closed by jonas-schievink** 2021-08-20 23:51 UTC
Labels: S-actionable, A-diagnostics
