### ISSUE TITLE
VS Code - automatic update sluggish

### ISSUE THREAD

**Issue by Robbepop** [rust-analyzer/rust-analyzer#7254] opened 2021-01-12 14:34 UTC
Since some days (or maybe 1-2 weeks now) auto updating the `rust-analyzer` plugin for VS Code is super sluggish.
Earlier it took maybe a few seconds to complete but since that time it already takes well over half an hour just for the simple download of the new update files. Oftentimes the download even gets stuck and I have to restart it.
Never had this problem with `rust-analyzer` before.

**Comment by lnicola** [comment] 2021-01-12 14:38
Is updating the extension slow, or downloading the new `rust-analyzer` binary? I assume the latter, since the extension is about 193 KB.

How fast is downloading from GitHub for you? Try getting a `gz` file from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-01-11.

**Comment by lnicola** [comment] 2021-01-17 13:38
@Robbepop did you try that?

**Comment by Robbepop** [comment] 2021-01-17 13:46
Hey sorry for not replying - I forgot.
Downloading files indeed seems to be a bit slower but not to the point I saw in `rust-analyzer` where most downloads (~80% of them in total) got completely stuck after ~10-30 minutes.
I resolved my issues (temporarily) by simply restarting the download after a minute when I see that it is slowing down instead of keeping up speed even though this means approx. 5-10 restarts per `rust-analyzer` update. A colleague of mine also reported that this works for them.

**Comment by lnicola** [comment] 2021-01-17 13:48
Can you test from a different network (e.g. at home)?

**Comment by Robbepop** [comment] 2021-01-17 13:51
I am at home (home office). Tried over wifi and ethernet cable. Both equally slow. When a download (finally) is successful the whole update takes roughly 4-5 minutes.

**Comment by majidazimi** [comment] 2021-01-18 21:38
I can confirm, updating early in the week, is terribly slow and most of the times doesn't even make any progress.

**Comment by lnicola** [comment] 2021-01-19 08:10
@Veetaha do you have any idea about this? The download and uncompression code hasn't changed lately, and neither did the Node version used by Code.

**Comment by FrankenApps** [comment] 2021-01-19 13:30
I do have exactly that same problem for about two weeks. How do I restart the download of the `rust-analyzer` binary?

**Comment by lnicola** [comment] 2021-01-19 13:59
@FrankenApps you can download a release binary from
https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-01-18 and
copy it under the path from
https://rust-analyzer.github.io/manual.html#vs-code (look below the
screenshot).

You can download a `gz` file since they're smaller.

**Comment by lnicola** [comment] 2021-01-21 15:02
I've extracted our download code to https://github.com/lnicola/ra-dl-test, can you test it?

**Comment by FrankenApps** [comment] 2021-01-23 17:21
I have tested your download handler.
Never took more than 2-3 seconds on my network.
To test it, I downloaded `rust-analyzer-linux` multiple times without any problems on my macOS pc.
Even when the download is fast enough, so that it succeeds in VSCode, it is never even close as fast as it is with the node script.

**Comment by lnicola** [comment] 2021-01-23 17:24
By never as slow, do you mean ten seconds instead of three, or minutes?

I think we send too many progress notification to Code, but that wouldn't explain this issue. Are you using some sort of proxy or VPN?

**Comment by FrankenApps** [comment] 2021-01-23 18:15
By not as slow I mean around 5 minutes. Basically the same timeframe as mentioned by @Robbepop. 
I do not use a proxy or VPN.

**Comment by lnicola** [comment] 2021-01-23 18:16
Which Code version are you using?

@Veetaha if you're still around and have any idea about this, it would be much appreciated.

**Comment by FrankenApps** [comment] 2021-01-23 18:18
Code Version:
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

**Comment by lnicola** [comment] 2021-01-24 14:16
Filed #7415 to send fewer progress reports to Code, but I'm pretty sure it won't help here.

**Comment by Veetaha** [comment] 2021-01-25 04:47
Hi @lnicola, sorry, I've been at very low availability lately, I can't promise anything about resolving this issue =(.

From what I see here I may conclude:
- There are 3 people reporting slow download performance, so the chances of a transient network error coincidence are low
- I don't see right away any changes to `node-fetch` version and our `net.ts` code that could cause this bug
- vscode still uses the same nodejs.12 major version, so I doubt that there could be something happening in node's stdlib

I suppose we need more debug logs to diagnose what the anomalies are and what could potentially cause them because I (and probably @lnicola too) cannot reproduce this locally and deduce the core of the problem from this issue thread.

Some information that might be helpful in the context of this issue:
- All extensions in vscode share the same process and nodejs runtime (thus, node's event loop is also shared)

Just for reference, downloads are working fine for me (the gzipped server binary is downloaded within ~5 seconds) though I use pretty crappy wifi and 100 Mbit internet.
Here are the specs from vscode info (I use `vscode-insiders`):
<details>
<summary>Specs</summary>

```
Version: 1.53.0-insider
Commit: 1a6eef3170be2a11751ee50d450328d458f7bfac
Date: 2021-01-15T05:14:07.888Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-38-generic
```
</details>

**Comment by lnicola** [comment] 2021-01-25 08:17
Thanks for chiming in and no worries of course. You do raise a good point about other extensions possibly interfering with this. Even other software on the computer (like an antivirus) could have an effect.

Another two differences are:

 - my test repo already has the fix in #7415 applied
 - I'm downloading the Linux binary, not the MacOS one (I don't know which platform @Robbepop is using)

And this apparently started after adding in support for Windows or MacOS ARM binaries (which did change the client code, but only a little).

> though I use pretty crappy wifi and 100 Mbit internet

Nah, GitHub is still slow-ish even on a 1 Gbps connection.

**Comment by Robbepop** [comment] 2021-01-25 18:31
> I don't know which platform @Robbepop is using

I am also using linux.

May off-topic but: Today I noticed that `rust-analyzer` VS Code plugin stopped automatically updates for me since 13 days already.
I cannot even manually choose from the versions and according to the `rust-analyzer` weekly there has been 2 updates since then. Any ideas? Maybe my config broke after I tried to fix the sluggish downloads speeds.
![2021-01-25-193041_1742x641_scrot](https://user-images.githubusercontent.com/8193155/105749548-d4a59100-5f43-11eb-875b-f194963b24c1.png)

**Comment by lnicola** [comment] 2021-01-26 03:45
That happens when you have an incompatible (old) version of Code, but I don't remember us changing the minimum required version.

**Comment by Robbepop** [comment] 2021-01-31 11:06
My version is 1.52.1 which seems to be from Nov 2020 but still newest there is at the moment.

**Comment by FrankenApps** [comment] 2021-01-31 11:50
I just wanted to follow up and report that the latest updates worked fine for me.

**Comment by Robbepop** [comment] 2021-01-31 12:24
Yeah the original issue seems to be resolved for me. When I was downloading the outdated 0.2.449 multiple times to debug why I cannot have the newer one, the download speed was again within seconds.

**Closed** 2021-01-31 12:46 UTC
Labels: A-vscode, S-unactionable
