### ISSUE TITLE
Add support for let chains

### ISSUE THREAD

**Issue by c410-f3r** [rust-analyzer/rust-analyzer#11320] opened 2022-01-19 18:18 UTC
See https://github.com/rust-lang/rust/pull/88642.

**Comment by ChayimFriedman2** [comment] 2022-01-21 01:42
I would like to work on that. How should I synchronize the changes to ungrammer and rust-analyzer?

**Comment by ChayimFriedman2** [comment] 2022-01-21 06:13
Parsing turns out to be quite complex. The problem is that [the `let` syntax can appear inside parentheses (`if (let pat = expr)`)](https://github.com/rust-lang/rfcs/blob/master/text/2497-if-let-chains.md#facilitating-for-macro-authors). This is to facilitate for macros, as stated in the RFC.

The problem is especially tricky since we cannot know if `let` is allowed in this position until we finish parsing it, becauses parentheses can be also tuples: `if (let true = true, false) {}` is invalid, but `if (let true = true) {}` is valid.

rustc chose [to implement this as an expression kind](https://github.com/rust-lang/rust/blob/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/compiler/rustc_parse/src/parser/expr.rs#L1298) and [later verify that `let` is indeed valid there](https://github.com/rust-lang/rust/blob/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/compiler/rustc_ast_passes/src/ast_validation.rs#L955-L988).

We don't have a validation pass to the AST. But it may be necessary to introduce it.

What do you think? Do you have an other way?

**Comment by Veykril** [comment] 2022-01-21 10:08
Macros strike once more, way to go making the language a bit more inconsistent yet again 🙄

We did have a validation pass but disabled it for the time being(I don't recall the reason). If we don't reject the let expression for now where its disallowed that is fine.

**Comment by TennyZhuang** [comment] 2022-01-23 17:49
Is it possible to implement let without parentheses first? It’s the main usecase, and the macro is corner case.

**Comment by ChayimFriedman2** [comment] 2022-01-23 20:04
@TennyZhuang This is quite useless since if you want to implement it using the exisiting infra you will need to rewrite it anyway and if you want to create `let` expressions, like I did, it is almost no work to support parentheses. I'm also pretty close to closing thus, hope for today.

**Comment by ChayimFriedman2** [comment] 2022-01-24 02:54
I finished the work (I think), but I cannot send a PR until rust-analyzer/ungrammar#45 is merged and published since Cargo can't update Cargo.lock until then.

**Closed** 2022-02-21 09:44 UTC
Labels: S-actionable, A-parser

**Comment by c410-f3r** [comment] 2022-02-21 10:42
Thank you @ChayimFriedman2

**Comment by ChayimFriedman2** [comment] 2022-04-07 06:03
After I implemented all of this, now [the Rust developers want to forbid parentheses in `let` chains](https://github.com/rust-lang/rust/pull/95008)! 😭 

At least we can issue a better error... Though I am not sure parsing it is required to do that.
