### ISSUE TITLE
Rust-analyzer is extremely slow to index uom

### ISSUE THREAD

**Issue by bheisler** [rust-analyzer/rust-analyzer#7953] opened 2021-03-09 23:09 UTC
I'm working on a project which uses the [uom](https://crates.io/crates/uom) crate. Rust-analyzer was always very slow to index this crate, but recently it's become unusable. Rust-analyzer has been stuck, pinning one CPU, on "indexing: 87/596 (uom)" for a full hour, and none of its usual features work until indexing is complete.

(I'm afraid I don't know precisely when this happened; I haven't worked on this project much since November. It was usable then.)

It does eventually work - in fact, it completed indexing as I'm typing this bug report - but an hour-long start-up time is not a great user experience. The rust-analyzer process is also using 1.7GB of memory.

I'm using version 0.2.513 of rust-analyzer in VSCode 1.54.1.

**Comment by Veykril** [comment] 2021-03-09 23:23
The crate in question uses a lot of ([heavily recursive?](https://github.com/iliekturtles/uom/blob/master/src/storage_types.rs)) mbe macros so I imagine this might have been caused by https://github.com/rust-analyzer/rust-analyzer/pull/7513
cc @edwin0cheng

**Comment by edwin0cheng** [comment] 2021-03-09 23:26
Yeah, I think it is related to new mbe parser too.

**Comment by phiresky** [comment] 2021-03-13 16:33
Same for me. I've not yet seen rust analyzer complete indexing on my project, it's just stuck on uom. Reverting to 2021-02-01 fixes it

**Comment by edwin0cheng** [comment] 2021-03-13 23:26
#7994 may fix it.

**Comment by edwin0cheng** [comment] 2021-03-16 01:05
[triage] I tested it and it is not stuck. However, there is some macro are not expanded correctly. Here is the test code :

```rust
use uom::si::f32::*;
use uom::si::length::kilometer;
use uom::si::time::second;

fn main() {
    let _length = Length::new::<kilometer>(5.0);
    let _time = Time::new::<second>(15.0);
 } 
```

**Comment by bheisler** [comment] 2021-03-16 12:58
Yes, see also: https://github.com/rust-analyzer/rust-analyzer/issues/6537

**Comment by Logarithmus** [comment] 2021-04-26 18:18
> #7994 may fix it.

Unfortunately, it didn't. `uom` is basically unusable with `rust-analyzer`, one CPU core is always loaded eternally.

**Comment by jonas-schievink** [comment] 2021-12-12 15:21
Since the perf issue was fixed, closing this in favor of https://github.com/rust-analyzer/rust-analyzer/issues/6537

**Closed by jonas-schievink** 2021-12-12 15:21 UTC
Labels: A-macro, S-actionable, A-perf
