### ISSUE TITLE
Project not reloaded if Cargo.toml edited in background

### ISSUE THREAD

**Issue by MikailBag** [rust-analyzer/rust-analyzer#5675] opened 2020-08-06 12:06 UTC
Steps to reproduce:
1. Add dependency using `cargo-edit`, e.g. 
```bash
cargo add anyhow
```
2. Rust-analyzer does not provide completions for anyhow.

**Comment by kjeremy** [comment] 2020-08-06 12:11
I think the reloading is triggered by a file save. We should probably add it to the VFS instead.

**Comment by malaire** [comment] 2020-11-27 11:08
If I edit Cargo.toml manually in Sublime Text 3 to add dependency and then save it, rust-analyzer doesn't notice that until I close and restart Sublime Text 3. (This could be a bug in Sublime Text 3 integration, I don't know.)

**Comment by flodiebold** [comment] 2020-12-22 11:06
Duplicate of #5333.

**Closed by flodiebold** 2020-12-22 11:06 UTC
Labels: S-actionable
