### ISSUE TITLE
Procedural macro attributes are not supported

### ISSUE THREAD

**Issue by whaqzhzd** [rust-analyzer/rust-analyzer#6758] opened 2020-12-08 05:26 UTC
rust can be compiled, but ra says these fields don't exist.

This is the smallest demo 
[proc_attributes_bug.zip](https://github.com/rust-analyzer/rust-analyzer/files/5657046/proc_attributes_bug.zip)

**Comment by bjorn3** [comment] 2020-12-08 06:37
Proc macro attributes are not yet supported.

**Comment by whaqzhzd** [comment] 2020-12-08 08:53
Thank you for taking your valuable time to answer this question ~ is there any way to temporarily block the rust-analyzer error messages in vscode until rust-analyzer is supported.

**Comment by lnicola** [comment] 2020-12-08 09:12
You can only selectively disable them:

```json
    "rust-analyzer.diagnostics.disabled": [
        "no-such-field"
    ]
```

**Comment by whaqzhzd** [comment] 2020-12-08 09:14
Thank you

**Comment by lnicola** [comment] 2020-12-20 14:55
Duplicate of #6029

**Closed by lnicola** 2020-12-20 14:55 UTC
Labels: A-macro
