### ISSUE TITLE
include! concat! env! OUT_DIR not auto completing

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#4482] opened 2020-05-16 15:04 UTC
Hey!

I tried to use the latest nightly of `rust-analyzer` (as of approximately May 15) within VSCode to see if I could get auto complete for some constants that were generated in a `build.rs`.

The [rust-analyzer tests](https://github.com/rust-analyzer/rust-analyzer/blob/348cbc054c91dbdae3633d5f401a1187e79232ee/crates/rust-analyzer/tests/heavy_tests/main.rs#L591-L607) suggest that it works in `main.rs` - and I'm seeing it work when I create a new project and try to auto-complete within `main.rs`.

As soon as I start to stray from that I lose auto-complete.

For example, if I move the `include!` call to `mod bindings` and type `bindings::` I can no longer auto complete the constants.

Is this a known limitation at this time - or am I perhaps misconfigured? I have the setting to check out dirs on startup turned on.

I could whip up an example project (or rust-analyzer test case if you can point me into the right direction?) if needed - but as far as I can tell as soon as you start trying to import `include!`d types from other modules the auto complete stops working.

Thanks and cheers!

---

```
$ rustc -V
rustc 1.45.0-nightly (2454a68cf 2020-05-04)
```

**Comment by edwin0cheng** [comment] 2020-05-16 19:14
Do you enabled : `rust-analyzer.cargo.loadOutDirsFromCheck` ? It is off by default .

**Comment by chinedufn** [comment] 2020-05-16 21:20
Yup sure did ! I checked the check box in the VSCode rust-analyzer extension settings.

Not sure if it matters, but I originally ran into this in my project’s cargo workspace but I verified that I get the same issues in a non workspace as well.

**Comment by edwin0cheng** [comment] 2020-05-16 21:29
> I could whip up an example project

Yeah, a minimal reproducible example will be nice to have to help here. !

**Comment by chinedufn** [comment] 2020-05-18 12:59
![image](https://user-images.githubusercontent.com/2099811/82215688-cb105780-98e5-11ea-89ad-a3967fb7b2f9.png)

Sure!

Everything is captured in the attached screenshot. I expected the pictured auto-complete to include `GENERATED_CONSTANT`.

Here's a repository with the code above: https://github.com/chinedufn/rust-analyzer-issue-4482

**Comment by flodiebold** [comment] 2020-05-18 13:30
Hm, could it be a problem with relative paths, since the path inside the `generated_constants` module will be relative to `src/generated_constants`? :thinking:

**Comment by chinedufn** [comment] 2020-05-18 14:26
@flodiebold thanks for the help! Sorry, I'm not quite getting what you're asking?

**Comment by flodiebold** [comment] 2020-05-18 14:35
I'm just speculating about the reason for the bug :wink:

**Comment by chinedufn** [comment] 2020-05-19 14:09
@edwin0cheng anything happen to ring a bell in terms of what might be happening?

Cheers!

**Comment by edwin0cheng** [comment] 2020-05-19 14:19
No idea, and this week I am a bit busy, but I think I will be investigating  this weekend.

**Comment by chinedufn** [comment] 2020-05-19 14:46
Awesome - no rush at all - thanks!

**Comment by edwin0cheng** [comment] 2020-05-25 14:00
Oh , I just tested it in master(00172d0b5) and it works: 

![4482](https://user-images.githubusercontent.com/11014119/82819548-1ffa3200-9ed3-11ea-956d-41b11b58253a.gif)

**Comment by lnicola** [comment] 2020-05-25 14:02
@edwin0cheng is that the Windows 95 default background color? :joy_cat:

**Comment by chinedufn** [comment] 2020-05-25 14:57
@edwin0cheng just upgraded to the latest nightly and that example works for me!

However, here's an example that does not work:

![image](https://user-images.githubusercontent.com/2099811/82823976-81d87e80-9e76-11ea-96c4-6f0c9f4df294.png)

I've updated the repository with the code in this screenshot.

**Comment by edwin0cheng** [comment] 2020-05-25 15:04
Um.. It works for me too : 

![4482_2](https://user-images.githubusercontent.com/11014119/82824455-eed22f80-9edb-11ea-9069-29b3d40b9185.gif)

You may need to reload the VSCode after adding `tests` folder.

**Comment by chinedufn** [comment] 2020-05-25 15:26
Ah nice that works!

So I'm still seeing issues in my real crate such as:

![image](https://user-images.githubusercontent.com/2099811/82826091-725b3480-9e7a-11ea-9b96-37b0c14ab4eb.png)

But I suppose I can open separate issues for them with reproducible examples.

I'll give it some time then come back to `rust-analyzer` in case the issue happens to resolve itself like this issue did (just to avoid trying to reproduce this).

Thanks so much!

**Closed** 2020-05-25 15:27 UTC
