### ISSUE TITLE
Can't resolve struct generated from proc_macro

### ISSUE THREAD

**Issue by SarthakSingh31** [rust-analyzer/rust-analyzer#7990] opened 2021-03-13 01:12 UTC
### Problem

Rust analyzer raises `unresolved import` whereas cargo check raises no errors.

### Minimal Reproducible Example

```rust
// src/test.rs
#[salsa::query_group(TestStorage)]
pub trait TestQueryGroup: salsa::Database  {
    fn test(&self) -> u32;
}

fn test(_: &dyn TestQueryGroup) -> u32 {
    unimplemented!()
}
```

```rust
// src/main.rs
mod test;
use test::TestStorage; // unresolved import

#[salsa::database(TestStorage)]
struct MyDatabase {
    storage: salsa::Storage<Self>,
}

impl salsa::Database for MyDatabase {}

fn main() {}
```

```toml
# Cargo.toml
[dependencies]
salsa = "0.16"
```

### Settings

I have enabled `rust-analyzer.procMacro.enable` and `rust-analyzer.cargo.runBuildScripts`.

### Versions

`rustc 1.50.0 (cb75ad5db 2021-02-10)`
`rust-analyzer e8c8039`

### Other info
Source code of the proc_macro used: https://github.com/salsa-rs/salsa/blob/1917a2a37b9d54e71e87a66a8c312e4c87abf558/components/salsa-macros/src/query_group.rs#L14

**Comment by jonas-schievink** [comment] 2021-03-13 01:34
duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6029

**Closed by jonas-schievink** 2021-03-13 01:34 UTC
