### ISSUE TITLE
Type deduction is broken with GAT

### ISSUE THREAD

**Issue by zirconium-n** [rust-analyzer/rust-analyzer#9940] opened 2021-08-18 08:14 UTC
Code:

```rust
#![feature(generic_associated_types)]

trait Flatten {
    type Container<T>;

    fn lift<T>(t: T) -> Self::Container<T>;
    fn flatten<T>(this: Self::Container<Self::Container<T>>) -> Self::Container<T>;
}

struct Opt;

impl Flatten for Opt {
    type Container<T> = Option<T>;

    fn lift<T>(t: T) -> Self::Container<T> {
        t.into()
    }

    fn flatten<T>(this: Self::Container<Self::Container<T>>) -> Self::Container<T> {
        this.flatten()
    }
}

struct V;

impl Flatten for V {
    type Container<T> = Vec<T>;

    fn lift<T>(t: T) -> Self::Container<T> {
        vec![t]
    }

    fn flatten<T>(this: Self::Container<Self::Container<T>>) -> Self::Container<T> {
        this.into_iter().flatten().collect()
    }
}

```

1. For the code as is, type deduction failed on `this`. 
2. If I remove the `impl Flatten for V` part, `this` in `impl Flatten for Opt` part will be deducted as `Option<Opt>` which is not correct.

**Comment by flodiebold** [comment] 2021-08-18 08:55
Duplicate of #9673.

**Closed by flodiebold** 2021-08-18 08:55 UTC
