### ISSUE TITLE
Path attribute showing "unresolved module"

### ISSUE THREAD

**Issue by Dhs92** [rust-analyzer/rust-analyzer#6425] opened 2020-10-31 20:15 UTC
```rust
#[cfg_attr(windows, path = "os/windows.rs")]
#[cfg_attr(target_os = "linux", path = "os/linux.rs")]
mod os;
```
Is showing `unresolved module`, while the program compiles without error using `cargo build`

rust-analyzer version: v0.2.360
Visual Studio Code version: 1.50.1

**Comment by Dhs92** [comment] 2020-11-04 01:08
Still occurring on v0.2.368

`#[path="foo.rs"]` appears to work as intended, but conditional paths do not.

**Comment by flodiebold** [comment] 2020-11-04 16:39
Duplicate of #5548.

**Closed by flodiebold** 2020-11-04 16:39 UTC
