### ISSUE TITLE
Refactor / Fixing `NavigationTarget` 

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1166] opened 2019-04-19 09:05 UTC
While i try to fix the bug in #1149 , i found that there are some problems on current `NavigationTarget` implementation:

#### `FileId and TextRange`

https://github.com/rust-analyzer/rust-analyzer/blob/8887782c4ab97d22f3d5c10e142407e4371c5c61/crates/ra_ide_api/src/display/navigation_target.rs#L17-L24

What file and text range should it be stored in macro expansion case ? Do we want to use HirFileId instread ?

#### `description` and `doc`
When client request a hover / goto-definition event, `doc_text_for` is called:
https://github.com/rust-analyzer/rust-analyzer/blob/2fc2d4373b2c4e96bebf320a84270eee3afe34aa/crates/ra_ide_api/src/display.rs#L74-L82

Should we store an `AstItemDef<N>` in `NavigationTarget` directly? The `nav.docs` and `nav.description` will ask for an `SyntaxNode` [code](https://github.com/rust-analyzer/rust-analyzer/blob/8887782c4ab97d22f3d5c10e142407e4371c5c61/crates/ra_ide_api/src/display/navigation_target.rs#L265) to compute the text of description and doc : 

https://github.com/rust-analyzer/rust-analyzer/blob/8887782c4ab97d22f3d5c10e142407e4371c5c61/crates/ra_ide_api/src/display/navigation_target.rs#L265-L273

In macro expanded case, `node.range` and `node.kind` will not be matched. (I doubt even `db.parse` return a fully expanded tree, there will still not be matched.) 

On the other hand, here is the how description of node is generated:

https://github.com/rust-analyzer/rust-analyzer/blob/8887782c4ab97d22f3d5c10e142407e4371c5c61/crates/ra_ide_api/src/display/navigation_target.rs#L275-L293

What should we do if the node is a `ast::SourceTree` ? in #1149 , the `tokio` path is a `ast::SourceTree`, that's why when hover on it, that's no information shown.

**Comment by matklad** [comment] 2019-04-19 09:08
Yeah, in general IDE code is not yet well-prepared to handle macros. See also this Zulip thread:

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/MBE.3A.20mapping.20spans.20in.20IDE

I think the strategy here is to fix all these issues one by one :)

**Comment by matklad** [comment] 2019-04-19 09:21
So, the overall constraint here is that the client (the editor), does not know about the macros, it knows (rightfully) only about source files. So all code `display` should only use `FileId` (and not `HirFileId`). 

So if, for example, goto defenition resolves to a node inside a macro-generated file, the nav target should contain the text range of defenition name inside *macro invocation*. If the name is fully synthesized inside the macro, goto def should point to the whole macro invocation

Reproducing example from the Zullip:

```
macro_rules! s {
    ($i:ident) => { struct $i; }
}

s!(Foo); // arrive at the `Foo` token

fn foo(_: Foo) { // press go to definition on `Foo` here

}
```

Here a case where we can't map ident cleanly:

```
macro_rules! m {
    () => { struct Foo; }
}

m!(); # arrive at the whole `m!();` invocation

fn foo(_: Foo) {} // press go to definition on `Foo` here
```

To be able to do this, we need an ability to transform ranges through macro expansion. Specifically, `HirFileId` has a method to get the originating file. We should extend it to also return a transform of the syntax ranges.

Going through specific issues:

>FileId and TextRange

In display, we must use FileId, and correct TextRanges. Correct means that we try to map a token in the expansion to the token in the original macro invocation, but, if that fails, we fallback to the range of the incvocation itself. 

>description and doc

As the `FIXME` implies, this method should not exist because it does not make sense in the current codebase (it did a while back). Docs and description should be computed for hir definitions like `hir::Function`, etc. `NavigationTarget` is purely an UI concept, using it to extract semantic information is wrong. This seems like it could be fixed in a targeting refactoring PR. Similarly, `fn node` should probably not exits as a method of `NavigationTarget`.

**Comment by matklad** [comment] 2019-04-19 09:23
The plan of action here:

* review `NavigationTarget` and other stuff in `display` to make sure it doesn't try to do semantic analysis (this is not really macro-related)
* fix the goto definition test by threading ranges maps throughout the analyzer
* refactor the rest of the ide_api to use the right ranges
* refactor the HirFileId API such that it is very hard to accidentally use range from macro-expansion with the original file

**Comment by edwin0cheng** [comment] 2019-04-19 09:47
Yeah, I like the "one by one" approach , let me try to describe the last point (I think it is simplest one) : 

Implement a function for transformation origin FileId and a TextRange to `MacroFileId` and its range :

```rust
HirFileId::transform_macro_range(file: FileId, _range: TextRange) -> Option<HirField, TextRange>
```  

Use this function in `NavigationTarget::node` to find the correct Node. (We will remove `fn node` finally but i think we still keep it in the beginning)

The next step will be remove the `as_source_file` and create a new struct which combined a TextRange and a FileID and use it instead in `display` mod (prevent using range from macro-expansion with the original file)  ?

**Comment by matklad** [comment] 2019-04-19 10:01
Hm, I think it should be rather 

```
fn original_file_and_range(&self, range: TextRange) -> (HirFileId, TextRange)
```

* we can transform ranges in two directions, so it's important to make the name reflect that we go from expansion to the original file
* this funciton should never fail I guess: the fall back would be the range of macro call


>Use this function in NavigationTarget::node to find the correct Node. 

I think we should go in the opposite direction. NavTarget has the original file, but we actually had the macro expanded file at the time where we've constructed the `NavTarget`. That is, if we fix `node` we get the flow of `macro code -> source file -> macro code`, while, ideally, it should look like `macro code`. So that's why I think that starting with refactoring `NavTarget` first should be easier

**Closed** 2019-12-05 10:42 UTC
