### ISSUE TITLE
"cargo metadata failed: No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by samuela** [rust-analyzer/rust-analyzer#3118] opened 2020-02-12 08:32 UTC
I'm trying to work on a project that the RLS extension has no problem handling but I'm getting an odd error from rust-analyzer that is pretty unhelpful:
```
rust-analyzer failed to load workspace: cargo metadata failed: No such file or directory (os error 2)
```
What file or directory could not be found? Why couldn't it be found even though RLS works without a hitch?

I'm running the VSCode extension remotely (Docker) with VSCode Insiders and rust-analyzer at commit 759100fb0dcb41518f2a593dae5de5bbedd07776.

**Comment by Veetaha** [comment] 2020-02-12 09:55
@samuela, thank you for the report! Can you please describe the directory structure of the project you open in VSCode that fails?

**Comment by samuela** [comment] 2020-02-12 18:41
It's https://github.com/samuela/rustybox. The Cargo.toml is in the root and then the entrypoint (rustybox.rs) is also in the root. I know that it's conventional to put things in `src/` but this is how c2rust spit things out for better or worse. It still works fine with the rest of the rust toolchain.

**Comment by Veetaha** [comment] 2020-02-12 20:05
May I ask you to dump `VSCode > Help > About` window output here?

**Comment by Veetaha** [comment] 2020-02-12 20:32
Cloned the repo, installed the specified version of rust-analyzer, freshly installed the following `code-insiders`:
```
1.43.0-insider
f4c95d5b9cfb2265f1730d564df1709533eff55e
x64
```
But couldn't reproduce the error...
I guess we will have to wait until better logging (#3119) is not landed...

**Comment by samuela** [comment] 2020-02-12 23:19
Here's the About info
```
Version: 1.43.0-insider
Commit: f4c95d5b9cfb2265f1730d564df1709533eff55e
Date: 2020-02-12T05:45:29.569Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```

FWIW there's also an info message "workspace loaded, 0 rust packages".

**Comment by samuela** [comment] 2020-02-12 23:31
Also getting this on `5e464d058b5043c663b0fe14bd9291c7b7b44d43`.

**Comment by samuela** [comment] 2020-02-12 23:57
Here's what I'm seeing in the Output pane:
```
[ERROR ra_lsp_server::main_loop] loading workspace failed: cargo metadata failed: No such file or directory (os error 2)
[ERROR ra_project_model] failed to get rustc cfgs: No such file or directory (os error 2)
[ERROR ra_lsp_server::main_loop] overly long loop turn: 749.734893ms
[Error - 11:55:50 PM] Request textDocument/formatting failed.
  Message: No such file or directory (os error 2)
  Code: -32603 
[Error - 11:55:52 PM] Request textDocument/formatting failed.
  Message: No such file or directory (os error 2)
  Code: -32603 
```

**Comment by marcogroppo** [comment] 2020-02-13 08:10
@samuela can you run `cargo` and `rustc` from the Docker container? Maybe the files that rust-analyzer can't find are these binaries

**Comment by matklad** [comment] 2020-02-13 09:39
It might make sense to retry after https://github.com/rust-analyzer/rust-analyzer/pull/3119 is merged: it should give a better error message.

**Comment by samuela** [comment] 2020-02-14 02:46
@marcogroppo Yes, I can `cargo` and `rustc` without a problem. They're included in my PATH via `.zshrc`:
```zsh
export PATH="$HOME/.cargo/bin:$PATH"
```
Not sure if it matters that I'm using zsh...

**Comment by lnicola** [comment] 2020-02-14 06:09
Does it work if you start Code from a terminal?

**Comment by samuela** [comment] 2020-02-14 06:56
@lnicola Yeah I'm guessing it's a PATH issue. I'm starting VSCode on my laptop and then going through the whole "remote connect -> attach to running Docker container" song-and-dance. It prob doesn't help that the Docker container is on a remote machine, connected via SSH and `DOCKER_HOST`. I'm not sure what that means for the env variables that VSCode sees. For example, I also had to explicitly set the full path to `ra_lsp_server`:
```json
{
    "rust-analyzer.raLspServerPath": "/root/.cargo/bin/ra_lsp_server"
}
```
even though `ra_lsp_server` is actually in `PATH`. Not sure what I could be doing differently to get around this...

**Comment by marcogroppo** [comment] 2020-02-14 08:02
@samuela ok, it's definitely a `PATH` issue. Maybe you could try following these instructions to set the `PATH` inside the container: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-environment-variables

**Comment by samuela** [comment] 2020-02-14 08:19
@marcogroppo I can try that. I wanted to avoid messing with `devcontainer.json` stuff, but open to it if that resolves the issue. I just can't figure out how to set this up for a container that already exists/is running...

**Comment by Veetaha** [comment] 2020-02-14 08:29
@samuela We merged #3119, this means me should get a better error message here now. Might I ask you to retry reproducing the bug having installed rust-analyzer from latest master commit now?

**Comment by samuela** [comment] 2020-02-14 18:21
@Veetaha Sure thing, I'm now seeing an error popup:
```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /root/rustybox/Cargo.toml
```
and the same info popup:
```
workspace loaded, 0 rust packages
```

**Comment by samuela** [comment] 2020-02-14 18:23
Here's the "Rust Analyzer Language Server" stuff in the Output panel:
```
[ERROR ra_lsp_server::main_loop] loading workspace failed: Failed to read Cargo metadata from Cargo.toml file /root/rustybox/Cargo.toml
[ERROR ra_project_model] failed to get rustc cfgs: Failed to get output from rustc --print cfg -O
```

**Comment by Veetaha** [comment] 2020-02-14 19:27
@samuela May I ask you to try running the following command from `/root/rusytbox` and from  `/root` directories (CWD) and send the output of both of these ones?
```
cargo metadata --format-version 1 --all-features --manifest-path /root/rustybox/Cargo.toml
```

**Comment by samuela** [comment] 2020-02-14 19:53
So this is interesting. When I run it in the VSCode Terminal pane I get a whole gob of json output as expected but when I SSH in and attach to the container I get 
```
root@196c35e56dcf:~/rustybox# cargo metadata --format-version 1 --all-features --manifest-path /root/rustybox/Cargo.toml
bash: cargo: command not found
```
So for some reason the container's default shell is still bash even though VSCode Terminal opens up zsh. So then the question is which one is rust-analyzer using and why? Bash presumably?

**Comment by samuela** [comment] 2020-02-14 19:55
I tried adding `export PATH="$HOME/.cargo/bin:$PATH"` to my `.bashrc` in the container to no avail.

**Comment by marcogroppo** [comment] 2020-02-14 19:58
> So then the question is which one is rust-analyzer using and why? Bash presumably?

`/bin/sh`, probably?

**Comment by samuela** [comment] 2020-02-14 20:01
If I run 
```
bash$ sh
sh$ cd /root/rustybox
sh$ cargo metadata ...
...
```
it works, but perhaps that's because it's inheriting env vars for the parent bash session.

**Comment by samuela** [comment] 2020-02-14 20:05
I also tried putting `export PATH="$HOME/.cargo/bin:$PATH"` in my `~/.profile` in the hopes it would be read by /bin/sh, but rust-analyzer/VSCode isn't picking up on that either.

**Comment by marcogroppo** [comment] 2020-02-14 20:06
@samuela I'm just guessing, but IMHO VSCode by default will try to run something as `docker run -ti IMAGE /bin/sh`. You can probably override this somehow...

**Comment by lnicola** [comment] 2020-02-15 07:21
I think you can set environment variables in the Dockerfile? Our at least in devcontainer.json.

**Comment by GuzTech** [comment] 2020-03-04 22:30
I've just installed rust-analyzer from the VS Code marketplace, and I have the same problem:

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-17T09:32:31.598Z
Electron: 6.1.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.7-zen1-1-zen
```

and the output of the rust-analyzer is:

```
[ERROR rust_analyzer::main_loop] loading workspace failed: Failed to read Cargo metadata from Cargo.toml file /home/oguz286/Projects/Rust/rcw/Cargo.toml
    
    Caused by:
        0: Failed to run `cargo metadata --manifest-path /home/oguz286/Projects/Rust/rcw/Cargo.toml`
        1: No such file or directory (os error 2)
        2: No such file or directory (os error 2)
[ERROR ra_project_model] failed to get rustc cfgs: Failed to get output from rustc --print cfg -O
```

I just did `cargo new rcw` so it's a clean project.

**Comment by lnicola** [comment] 2020-03-04 22:31
Can you try running Code from a terminal?

**Comment by matklad** [comment] 2020-03-04 22:32
Is rustc in PATH for the proceeds which starts the server?

**Comment by GuzTech** [comment] 2020-03-04 23:18
> Can you try running Code from a terminal?

Yup

> Is rustc in PATH for the proceeds which starts the server?

How do I check that?

```
echo $PATH                                                                                                                          ✔  
/home/oguz286/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
```

**Comment by Gaelan** [comment] 2020-03-10 05:28
This is also an issue on macOS, where there's no trivial way to set environment variables for GUI apps.

**Comment by cdisselkoen** [comment] 2020-03-10 17:52
Also having this issue on macOS with an otherwise ordinary setup.

Perhaps there could be a VSCode extension setting for the `cargo` path, similar to how there's already a setting for the `rust-analyzer` server path, rather than having the server rely on the current `PATH` environment variable which is hard to set for VSCode extensions on macOS?

**Comment by marco-neumann-jdas** [comment] 2020-03-11 09:39
Related stackoverflow question on why this is an issue for Mac users that is not as easy to fix as on Linux or Windows:
https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x

**Comment by Veetaha** [comment] 2020-03-11 10:39
I guess it does make sense to add a config for each of `rustc` and `cargo` executable paths.

**Comment by samuela** [comment] 2020-03-11 17:27
Does anyone know how the current RLS plugin gets this to work?

**Comment by Veetaha** [comment] 2020-03-11 18:11
This is interesting. RLS [**depends on** cargo as a package](https://github.com/rust-lang/rls/blob/521498cd95c1389ef208d256acd2a1e4ca618cf0/Cargo.toml#L33). I suppose they don't use `cargo` cli then...?

**Comment by Veetaha** [comment] 2020-03-11 18:55
Also, rls doesn't do anything fancy with `rustc`. One difference is that it [checks `$RUSTC` env var](https://github.com/rust-lang/rls/blob/521498cd95c1389ef208d256acd2a1e4ca618cf0/rls/src/build/rustc.rs#L400) for a path to `rustc`.

**Comment by fbucek** [comment] 2020-03-12 08:50
I have same problem: rust-analyzer report problem running command `cargo manifest --manifest-path xxxx` from VSCode ( macOS ), but when paste command into command line it works correctly, I can see json with metadata.
RLS and building and everything works as expected. No plugin has problem with PATH.

When I debug code, it runs correctly:

`cargo build --bin=monitorapp --message-format=json` this works and cargo is correctly used.

**Comment by lnicola** [comment] 2020-03-12 08:51
@fbucek does it work if you run Code from a terminal?

**Comment by fbucek** [comment] 2020-03-12 08:56
Yes, when I paste exactly same command to VSCode terminal or system terminal it works as expected.

**Comment by lnicola** [comment] 2020-03-12 09:00
I meant starting Code from the terminal (e.g. `code` or `Code`).

**Comment by fbucek** [comment] 2020-03-12 09:05
@lnicola Ok now I got it.

Running from terminal -> rust-analyzer works - `workspace loaded, 322 packages`

Running using ( Fork -> Open in Visual Studio Code - from GUI app ) does not work  - `workspace loaded, 0 packages` + error.

**Comment by matklad** [comment] 2020-03-12 12:15
The 90% solution here is to try to detect rustc/cargo in standard
installation paths without any additional configs.

**Comment by tarkah** [comment] 2020-03-20 22:02
I'm facing this issue as well on the following:

```
Version: 1.44.0
Commit: ffbb280a36607e3fea73577e616d006a92f6fb5b
Date: 2020-03-10T02:52:30+02:00
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.7-150.current
```

I'm able to work around this by running from terminal:

```
code-oss --enable-proposed-api matklad.rust-analyzer
```

Is there a permanent workaround for this so I can just launch from the `.desktop` entry?

**Comment by lnicola** [comment] 2020-03-20 22:08
You can edit the .desktop file in order to both enable the semantic tokens API and to set PATH so that rust-analyzer is able to find cargo. For the latter, I prefer setting it in ~/.pam_environment, though.

**Comment by tarkah** [comment] 2020-03-20 22:14
Thanks for the tips. I only have `~/.cargo/bin` set in my PATH through my `.profile` file. What does setting it in `.pam_environment` do differently? Weird that `code-oss` can't find cargo unless launched from the command line.

**Comment by lnicola** [comment] 2020-03-20 22:17
.profile is sourced by your shell. If you run Code from a desktop environment, the shell does not have to come into play, as some of these can launch programs without invoking it.

.pam_environment is loaded at login by PAM.

**Comment by lnicola** [comment] 2020-03-20 22:20
See https://askubuntu.com/questions/144968/set-variable-in-desktop-file for editing a .desktop file.

@Veetaha you also wanted this?

**Comment by tarkah** [comment] 2020-03-20 22:32
Got it working, thanks! Ended up just creating a wrapper script and launched that from the custom `.desktop` file saved to `~/.local/share/applications/`

**Comment by waylandc** [comment] 2020-04-02 15:39
Archlinux 5.5.13
rustc 1.42.0
cargo 1.42.0
emacs 27.0.9

Also got same error when trying to use emacs daemon. I added a PATH env var to my systemd service file to ensure it found cargo and seems to have fixed it for me.

note - on exact same Rust project, I didn't get this error if I ran emacs alone (without the daemon).

`[Unit]
Description=Emacs: the extensible, self-documenting text editor
Documentation=man:emacs(1) info:Emacs


[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(progn (setq kill-emacs-hook nil) (kill-emacs))"
Restart=on-failure
Environment=DISPLAY=:%i
Environment=HOME=/home/wayc
**Environment=PATH=/home/wayc/.cargo/bin:/usr/local/bin:/usr/bin:/bin**
TimeoutStartSec=0

[Install]
WantedBy=default.target
`

**Comment by lnicola** [comment] 2020-04-03 14:26
On Unix, we could sniff `/etc/passwd` for the user's shell, spawn it, get the configured `PATH` and look there for the binaries. But it seems a bit overkill.

**Comment by cedeerwe** [comment] 2020-05-05 06:58
I am failing to find a solution in this thread, is there currently some clean workaround for this? I have installed the `rust-analyzer` extension on my VSCode, both `rustc` & `cargo` can be run from the terminal and `rust-analyzer` fails due to all the same reasons from this thread.

What should I do? Running Ubuntu 18.04.

**Comment by cdisselkoen** [comment] 2020-05-05 17:09
For me (on macOS) the workaround I've been using is to start VSCode via `code <dirname>` or `code .` from the terminal, rather than launching it from the Dock or Alfred (ie the taskbar or search thingy on Ubuntu).

**Comment by bjorn3** [comment] 2020-05-05 17:12
You can use `launchctl setenv PATH $PATH` to set `PATH` for all programs, including those not launched from the terminal.

**Comment by cdisselkoen** [comment] 2020-05-05 17:19
> You can use `launchctl setenv PATH $PATH` to ...

Adding that line to the end of my `.profile` (which I know is executed by my shell) did not solve the problem for me, but the launching-from-terminal workaround does.

Regardless, if someone wants to actually fix this in rust-analyzer, I'll remind people that @matklad (primary maintainer here IIUC) commented farther above in this thread that
> The 90% solution here is to try to detect rustc/cargo in standard
installation paths without any additional configs.

I imagine this wouldn't be terribly difficult to make a PR for.  Maybe I'll get around to making a PR for this soon.

**Comment by Veetaha** [comment] 2020-05-05 18:29
I think setting `CARGO=${HOME}/.cargo/bin/cargo` will work, `rust-analyzer should respect the value of this variable.
https://github.com/rust-analyzer/rust-analyzer/blob/a4778ddb7a00f552a8e653bbf56ae9fd69cfe1d3/crates/ra_project_model/src/cargo_workspace.rs#L341

**Comment by cdisselkoen** [comment] 2020-05-05 18:34
@Veetaha the problem is that `$CARGO`, like `$PATH`, is not inherited correctly (i.e. `.profile` is not read) when VSCode is launched in certain ways on macOS.

**Comment by Veetaha** [comment] 2020-05-05 18:36
Okay guys, let me tackle thsi

**Comment by cdisselkoen** [comment] 2020-05-05 18:36
Actually I'm already working on a fix

**Comment by Veetaha** [comment] 2020-05-05 18:36
Cool, thanks!

**Comment by Veetaha** [comment] 2020-05-05 18:39
@cdisselkoen 
There is also minor code duplication of this function in `flycheck`.
https://github.com/rust-analyzer/rust-analyzer/blob/a4778ddb7a00f552a8e653bbf56ae9fd69cfe1d3/crates/ra_flycheck/src/lib.rs#L338-L340
I am not sure where is the right place for this function to land. My gut feeling is that we should have a shared simple `ra_cargo` module for this stuff, let's see what @matklad can advise if any.

**Comment by cdisselkoen** [comment] 2020-05-05 18:43
I'm also not sure if https://github.com/rust-analyzer/rust-analyzer/blob/a4778ddb7a00f552a8e653bbf56ae9fd69cfe1d3/editors/code/src/cargo.ts#L79 in JS-land will need to be fixed as well.  I'm not too familiar with VSCode extensions, or frankly, NodeJS at all.

**Comment by Veetaha** [comment] 2020-05-05 18:50
Let's not bother with this one, for now. You can ask for help in the PR regarding TypeScript part, I am sure I or any other people will respond

**Comment by cdisselkoen** [comment] 2020-05-05 19:05
^ the above commit partially fixes the problem, but I now get an error about finding `rustc` at https://github.com/rust-analyzer/rust-analyzer/blob/a4778ddb7a00f552a8e653bbf56ae9fd69cfe1d3/crates/ra_project_model/src/sysroot.rs#L117
We may need a similar solution for finding a path to `rustc`.

**Comment by Veetaha** [comment] 2020-05-05 19:13
Right, I think we can generalize this for a bit passing the env variable, executable name and standard location name so we can also cover `rustc` and `rustup`.

**Closed** 2020-05-08 10:21 UTC

**Comment by hzbd** [comment] 2021-01-12 15:57
```
// "rust-analyzer.cargo.features": [
//     "rust-analyzer"
// ],
```
it works.

**Comment by BroJenuel** [comment] 2023-08-30 07:36
. if your in windows.. I recommend setting up your wsl subsystem...
check if cargo is installed or not..

if your still using wsl subsystem but still does not work check if your have installed rust and cargo..

**Comment by BennoCrafter** [comment] 2024-01-07 16:04
> @marcogroppo Yes, I can `cargo` and `rustc` without a problem. They're included in my PATH via `.zshrc`:
> 
> ```shell
> export PATH="$HOME/.cargo/bin:$PATH"
> ```
> 
> Not sure if it matters that I'm using zsh...

thank u so much dude

**Comment by zeshantech** [comment] 2024-07-06 01:38
I was facing the same issue, and this command worked for me.

```bash
curl https://sh.rustup.rs -sSf | sh
export PATH="$HOME/.cargo/bin:$PATH
```
