### ISSUE TITLE
infering type form vec! broken in 0.2.489

### ISSUE THREAD

**Issue by Pawel82S** [rust-analyzer/rust-analyzer#7765] opened 2021-02-23 14:57 UTC
After last update of rust analyzer type inference of vectors created by vec! macro is broken.
![vec macro type inference](https://user-images.githubusercontent.com/19608299/108861505-93aaa600-75ef-11eb-9ea2-2633cd5ff699.png)
[vectors.zip](https://github.com/rust-analyzer/rust-analyzer/files/6029671/vectors.zip)

VSCode information:
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-09T22:05:01.942Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.15-1-MANJARO

**Comment by lnicola** [comment] 2021-02-23 15:00
Dupe of #6837.

**Closed by lnicola** 2021-02-23 15:00 UTC
