### ISSUE TITLE
Incorrect comma flip in macros

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#7780] opened 2021-02-25 07:11 UTC
rust-analyzer version: unreleased (20a911f)

Original:
```rust
    assert_eq!(node.insert(code2, mask), InsertResult::NoMatch);
```

Expected result:
```rust
    assert_eq!(InsertResult::NoMatch, node.insert(code2, mask));
```

Actual result: 
```rust
    assert_eq!(node.insertInsertResult, (code2, mask)::NoMatch);
```

P.S.: Just in case, I'm using `pretty_assertions = 0.6.1` crate

**Comment by Veykril** [comment] 2021-02-25 09:06
Duplicate of #7693

**Closed by Veykril** 2021-02-25 09:06 UTC
