### ISSUE TITLE
Wrong name resolution in intrusive-rs

### ISSUE THREAD

**Issue by kiljacken** [rust-analyzer/rust-analyzer#2840] opened 2020-01-14 15:01 UTC
I'm getting a similar error on `intrusive-collections`.

Steps to reproduce:
- git clone https://github.com/Amanieu/intrusive-rs.git
- Open in vscode
- Open src/linked_list.rs

It will show the following errors, but only if the linked_list.rs file is open:
```
{
	"resource": "/home/amanieu/code/intrusive/src/linked_list.rs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Missing structure fields:\n- link1\n- link2\n",
	"source": "rust-analyzer",
	"startLineNumber": 1366,
	"startColumn": 21,
	"endLineNumber": 1369,
	"endColumn": 10
}
{
	"resource": "/home/amanieu/code/intrusive/src/linked_list.rs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "no such field",
	"source": "rust-analyzer",
	"startLineNumber": 1367,
	"startColumn": 13,
	"endLineNumber": 1367,
	"endColumn": 30
}
```
[linked_list.rs](https://github.com/Amanieu/intrusive-rs/blob/master/src/linked_list.rs)

_Originally posted by @Amanieu in https://github.com/rust-analyzer/rust-analyzer/issues/2799#issuecomment-573356222_

**Comment by edwin0cheng** [comment] 2020-01-14 15:06
My wild guess is the `intrusive_adapter!` expand incorrectly. I will take a look later.

**Comment by kiljacken** [comment] 2020-01-14 15:11
The issue is funciton local item support. The `Obj` struct resolves to the one in the `mod tests` scope instead of the function local redefinition.

**Comment by kiljacken** [comment] 2020-01-14 15:13
So this is different symptoms of #1559

**Comment by edwin0cheng** [comment] 2020-01-14 15:29
I am glad to hear there is no bug in that complicated `intrusive_adapter!` macro-rules ! 😃

**Comment by jonas-schievink** [comment] 2021-03-25 13:19
@kiljacken We now support local items, and I don't see any diagnostics on the current version of that file. I'm not sure what commit you were using though, so I can't reproduce this precisely.

**Comment by kiljacken** [comment] 2021-03-27 11:17
@jonas-schievink Not "my" issue, just split out the comment from @Amanieu. I can try to replicate if he's not around though, although I probably won't have much better luck then you.

**Comment by Amanieu** [comment] 2021-03-27 16:32
This issue no longer reproduces, you can close it.

**Closed** 2021-03-27 16:33 UTC
Labels: A-nameres, S-unactionable
