### ISSUE TITLE
Inlay type annotations aren't shown on VSCode startup.

### ISSUE THREAD

**Issue by 0xd4d** [rust-analyzer/rust-analyzer#3057] opened 2020-02-08 16:55 UTC
Version: 3e1d97790be166f8735607c552a94a28ab9b09b8

Add this
```rust
fn main() {
	let i = 123;
	let u = 123u32;
}
```
- restart VSCode
- Wait for rust-analyzer to load
- No inlay type annotations are shown until you save it or type something. I expect to see this without having to save the file:
```rust
fn main() {
	let i: i32 = 123;
	let u: u32 = 123u32;
}
```

**Comment by Veetaha** [comment] 2020-02-10 19:35
I think this may be the problem in VSCode client extension, thank you for the report!

**Comment by SomeoneToIgnore** [comment] 2020-02-17 18:51
Should this also be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/3173 ?

At least for me, when I open any of my projects and wait long enough, inlay hints appear.

**Comment by Veetaha** [comment] 2020-02-17 19:00
@SomeoneToIgnore I did look into this issue yesterday. What I found is that this is caused by the startup time of `ra_lsp_server`. The requests for inlay hints just wait for the response from the lsp server, but they do eventually appear once it responds.

**Comment by lnicola** [comment] 2020-02-17 19:01
It does take its time, though. I started Code with a loaded project and an open file (more of them, actually). The hints were displayed after about 280 seconds.

**Comment by SomeoneToIgnore** [comment] 2020-02-17 19:02
I propose to change the issue title at least, since it's misleading.

**Comment by lnicola** [comment] 2020-02-17 19:20
Actually, they don't show up at all. I kept only one open file and waited for 350 seconds. They show up in a "hello, world" project, though. Also, this:

```
requests:
   11 rust-analyzer/inlayHints            1145ms
   14 rust-analyzer/inlayHints            640ms
   16 rust-analyzer/inlayHints            55ms
   21 rust-analyzer/inlayHints            270ms
   32 rust-analyzer/inlayHints            140ms
   37 textDocument/codeAction             54940ms
*   8 rust-analyzer/inlayHints            1ms
    9 rust-analyzer/inlayHints            1ms
   10 rust-analyzer/inlayHints            2ms
   12 textDocument/codeAction             1083ms
```

**Comment by lnicola** [comment] 2020-02-17 19:28
And they showed up after 75 seconds on the next try. I don't know what's happening here :-(.

**Comment by matklad** [comment] 2020-02-17 19:47
I've actually fixed this today I think, optimistically closing!

(but keep in mind that you do need to wait a 30 second-ish for the initial analysis)

**Closed by matklad** 2020-02-17 19:47 UTC
