### ISSUE TITLE
When a crate has `src` in its path, rust-analyzer panics

### ISSUE THREAD

**Issue by msalib** [rust-analyzer/rust-analyzer#5833] opened 2020-08-20 18:18 UTC
For example, if I have a crate called `foo` and I place it in `/home/msalib/src/bar/foo` with files likes ``/home/msalib/src/bar/foo/Cargo.toml` and ``/home/msalib/src/bar/foo/src/lib.rs`, rust-analyzer will panic.

**Comment by bjorn3** [comment] 2020-08-20 18:24
What is the panic message?

**Comment by lnicola** [comment] 2020-12-22 14:33
Triage: can't reproduce.

@msalib does this still happen?

**Comment by lnicola** [comment] 2021-01-26 13:26
Closing for now. Feel free to reopen if you run into this again.

**Closed by lnicola** 2021-01-26 13:26 UTC
Labels: S-unactionable
