### ISSUE TITLE
Incorrect type inference, mixing up `Option::map()` and `Iterator::map()`

### ISSUE THREAD

**Issue by rossmacarthur** [rust-analyzer/rust-analyzer#4467] opened 2020-05-15 13:58 UTC
Example code, very clearly `_repo` and `_owner` here are both `Option<String>` 😕.

```rust
fn main() {
    let path = "rust-lang/rust";
    let mut split = path.rsplit('/');
    let _repo = split.next().map(ToString::to_string);
    let _owner = split.next().map(ToString::to_string);
}
```

But it seems that rust-analyzer mixes up `Option::map()` and `Iterator::map()`

![image](https://user-images.githubusercontent.com/17109887/82057637-f4519d80-96c3-11ea-83d2-ddbc6c933000.png)

Additionally, if I cmd + click on the .map() function here it takes me to the `Iterator::map()` definition.

**Comment by flodiebold** [comment] 2020-05-15 15:52
> very clearly _repo and _owner here are both `Option<String>`
It's apparently not that clear to rust-analyzer ;) The problem is the `split.next()` call, apparently we don't think that `split` is an iterator, so we can't resolve `next` and don't know the return type, and then `Iterator::map` is a better guess since that unknown type might implement `Iterator`.

The `Iterator` impl has a where clause `P: Pattern<Searcher: ReverseSearcher>`, and apparently we can't normalize the projection `<char as Pattern>::Searcher`, so the where clause doesn't hold. I haven't looked further into it yet.

**Comment by flodiebold** [comment] 2020-05-29 13:47
This works now if you write it with `|x| x.to_string()` instead of `ToString::to_string`; that's a separate problem (built-in implementations of Fn for function types) which will also be fixed by Chalk in due time.

**Closed by flodiebold** 2020-05-29 13:47 UTC
Labels: A-ty
