### ISSUE TITLE
"could not resolve macro 'm'" when macro imported into function directly

### ISSUE THREAD

**Issue by hrydgard** [rust-analyzer/rust-analyzer#7437] opened 2021-01-25 23:46 UTC
![image](https://user-images.githubusercontent.com/130929/105780011-dd13c100-5f6f-11eb-902a-d6c21175cd9f.png)

Here's a very simple repro:

`src/main.rs:`
```
extern crate a;

fn main() {
    use a::m;
    m!{};
}
```

`Cargo.toml`: 
```
[package]
name = "repro"
version = "1.0.0"
[dependencies]
a = { path = "a" }
```

`a/src/lib.rs`:
```
#[macro_export]
macro_rules! m {
    () => {};
}
```

`a/Cargo.toml`:
```
[package]
name = "a"
version = "1.0.0"
[dependencies]
```

With the above, `cargo run` works just fine while rust-analyzer chokes on the use of the macro.

**Comment by Veykril** [comment] 2021-01-25 23:57
Local imports aren't yet supported at all unfortunately

Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1165

**Closed by Veykril** 2021-01-25 23:57 UTC
