### ISSUE TITLE
VS Code extension fails to start server

### ISSUE THREAD

**Issue by APlagman** [rust-analyzer/rust-analyzer#1198] opened 2019-04-23 05:33 UTC
I'm running Arch.
Installed via
```
git clone https://github.com/rust-analyzer/rust-analyzer && cd rust-analyzer
cargo install-code
```
Opened Rust VS Code workspace, Output panel, Rust Analyzer Language Server, shows
```
[Error - ##:##:## PM] Starting client failed
Launching server using command ra_lsp_server failed.
```
Log (Window) shows
```
[renderer1] [error] spawn ra_lsp_server ENOENT: Error: spawn ra_lsp_server ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[renderer1] [error] Launching server using command ra_lsp_server failed.
```
I tried setting `"rust-analyzer.raLspServerPath": "~/.cargo/bin/ra_lsp_server"` in settings.json, but that didn't have any apparent effect.

NPM: 6.9.0
Node: v11.14.0
VS Code: 1.33.1

**Comment by edwin0cheng** [comment] 2019-04-23 06:12
> `cargo install-code`
What is the output of this command? Is `ra_lsp_server` built successfully?

**Comment by jens1o** [comment] 2019-04-23 07:21
I also have this problem, and it compiled successfully.

**Comment by edwin0cheng** [comment] 2019-04-23 07:45
@jens1o Does it also not work in `rust-analyzer` workspace itself?

**Comment by matklad** [comment] 2019-04-23 12:39
Can't reproduce locally, here's a check list of things:

* can I run `ra_lsp_sever` from command line?
* is `ra_lsp_server` in PATH?
* is `ra_lsp_sever` in PATH for VS Code (desktop envirnoment might end up with a path slightly different from shell)
* does setting the complete path (without `~`) in settings help?

If all of the above fails, then I don't have any hypothesis as to what is going on. Some further debugging steps:

* set `RA_LOG_DIR=/tmp/rust-analyzer-log` and `RUST_LOG=trace` env vars to see if we manage to acutually launch the process
* launch VS Code extension under debugger to check if problem is in TypeScript. F5 in this repository should launch the debugger. THe entry point of the extensions is here: https://github.com/rust-analyzer/rust-analyzer/blob/e2835b46f6928eda21b7edb44f305f20473a3a98/editors/code/src/extension.ts#L123

**Comment by jens1o** [comment] 2019-04-23 13:10
> Does it also not work in rust-analyzer workspace itself?

Yeah.

> If it still doesn't works, would you try to change rust-analyzer.raLspServerPath to point to a full-path, something like:

That works! Thank you!

**Comment by matklad** [comment] 2019-04-23 13:17
Glad to hear that @jens1o ! Opened https://github.com/rust-analyzer/rust-analyzer/issues/1199 for better diagnostics.

Optimistically closing this issue under the assumption that @APlagman is seeing the same issue. If it is not the case, please reopen!

**Closed by matklad** 2019-04-23 13:17 UTC
