### ISSUE TITLE
Type inference fails with local 'use Trait', but works with top-level one

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#4619] opened 2020-05-26 11:20 UTC
### To reproduce
1. Open the following program in VSCode:
    ```rust
    // [dependencies]
    // rand = "0.7"

    use rand::seq::SliceRandom;
    fn main() {
        let x = [1].choose(&mut rand::thread_rng());
    }
    ```
2. Mouse hover over "x".
3. Now change change the program to
    ```rust
    fn main() {
        use rand::seq::SliceRandom;
        let x = [1].choose(&mut rand::thread_rng());
    }
    ```
4. Mouse hover over "x" again.

### Expected result

In both cases `x: Option<&i32>`.

### Actual result

In the first case `x: Option<&i32>`, in the second `x: {unknown}`.

```
rust-analyzer version: 2020-05-25 (fbb8b88)
```

**Comment by flodiebold** [comment] 2020-05-26 11:22
Duplicate of #1165.

**Closed by flodiebold** 2020-05-26 11:22 UTC
