### ISSUE TITLE
rust-analyzer failed to load workspace again

### ISSUE THREAD

**Issue by rsignavong** [rust-analyzer/rust-analyzer#6020] opened 2020-09-16 20:28 UTC
Sorry to reopen this issue #4172 but the issue is still running and is not due to local toolchain installation.
It is more the difference of folders of `rust-src` between stable and nightly.

I have both stable and nightly and both have `rust-src` component installed but the folder inside rust-src is not the same for both toolchains.

In stable, rust-src contains an `src` folder and the requested `libcore` folder inside to load the workspace.
In nightly, rust-src contains only `library` and so rust-analyzer still tries to load `src/libcore` in nightly active toolchain.

And so the following still error occurs:
```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /Users/.../workspace/.../Cargo.toml. Is rust-src installed?:
 could not find libcore in sysroot path `/Users/.../.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src`
```

**Comment by bjorn3** [comment] 2020-09-16 21:00
What rust-analyzer version are you using?

**Comment by rsignavong** [comment] 2020-09-16 21:06
I tried the latest release `0d03fe6`.
And just now I tried with `3877421` built from source master branch, I still got the same error.

**Comment by bjorn3** [comment] 2020-09-16 21:18
What is the output of `ls -R $(rustc --print sysroor)/lib/rustlib/src/rust`?

**Comment by rsignavong** [comment] 2020-09-16 22:13
There are many lines with the `-R` option.

Here is what I have
```
~ on ☁️  us-east-1
❯ rustup override set stable
info: using existing install for 'stable-x86_64-apple-darwin'
info: override toolchain for '/Users/rockysignavong' set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.46.0 (04488afe3 2020-08-24)


~ on ☁️  us-east-1
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/rockysignavong/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (directory override for '/Users/rockysignavong')
rustc 1.46.0 (04488afe3 2020-08-24)


~ on ☁️  us-east-1
❯ ls $(rustc --print sysroot)/lib/rustlib/src/rust

 Cargo.lock   src

~ on ☁️  us-east-1
❯ rustup override set nightly
info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/rockysignavong' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.48.0-nightly (6af1bdda5 2020-09-15)


~ on ☁️  us-east-1
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/rockysignavong/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (directory override for '/Users/rockysignavong')
rustc 1.48.0-nightly (6af1bdda5 2020-09-15)


~ on ☁️  us-east-1
❯ ls $(rustc --print sysroot)/lib/rustlib/src/rust

 Cargo.lock   library

```

**Comment by rsignavong** [comment] 2020-09-16 22:15
as you can see, there is `src` in `stable` and `library` in `nightly`

**Comment by rsignavong** [comment] 2020-09-16 22:18
and using grep `libcore`
```
~ on ☁️  us-east-1
❯ rustup override set stable
info: using existing install for 'stable-x86_64-apple-darwin'
info: override toolchain for '/Users/rockysignavong' set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.46.0 (04488afe3 2020-08-24)


~ on ☁️  us-east-1
❯ ls -R $(rustc --print sysroot)/lib/rustlib/src/rust | rg libcore

libcore
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/alloc:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/array:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/ascii:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/char:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/hash:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/num:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/num/dec2flt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/num/flt2dec:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/benches/num/flt2dec/strategy:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/char:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/convert:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/fmt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/fmt/rt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/hash:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/adapters:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/iter/traits:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/macros:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/mem:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/num:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/num/dec2flt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/num/flt2dec:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/num/flt2dec/strategy:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/prelude:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/slice:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/sync:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/task:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/fmt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/hash:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/num:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/num/dec2flt:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/num/flt2dec:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/tests/num/flt2dec/strategy:
/Users/rockysignavong/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/unicode:

~ on ☁️  us-east-1
❯ rustup override set nightly
info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/rockysignavong' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.48.0-nightly (6af1bdda5 2020-09-15)


~ on ☁️  us-east-1
❯ ls -R $(rustc --print sysroot)/lib/rustlib/src/rust | rg libcore


~ on ☁️  us-east-1
❯
```

**Comment by sunjay** [comment] 2020-09-17 00:22
It looks like this issue is being caused by the recent reorg of the rust-lang/rust repo. As mentioned in the original issue, the `src` directory is now named `library`. 

I ran `rustup update` so the info below is with `rustc 1.48.0-nightly (6af1bdda5 2020-09-15) (from rustc 1.48.0-nightly (a1947b3f9 2020-09-10))`.

rust-analyzer is trying to find the path:

```
~/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
```

But the actual path that exists is:

```
~/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library
```

If anyone else is looking to temporarily work around the solution just to get their setup working again, you can use:

```
ln -s ~/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library ~/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
```

Simply renaming the directory to `src` will probably work too, though I haven't tried that.

**Comment by rsignavong** [comment] 2020-09-17 07:45
I didn't think that aliasing will work as I thought rust-analyzer was looking for `libcore` that doesn't exist inside `library` but I tried @sunjay temporary solution and it works! 👍 

Thank you!

I hope this will be fixed soon.

**Comment by lnicola** [comment] 2020-09-17 10:02
This should have been fixed in https://github.com/rust-analyzer/rust-analyzer/pull/5586. Do you have a `RUST_SRC` environment variable?

**Comment by rsignavong** [comment] 2020-09-17 13:53
I have `RUST_SRC_PATH` and changing `src` to `library` didn't work.
So I added `RUST_SRC` that target library and it works without the symlink `src -> library` (that I removed before testing).

Here is my `.zshrc` config for rust
```
# Rust
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export RUST_SRC="$(rustc --print sysroot)/lib/rustlib/src/rust/library"
```

**Comment by lnicola** [comment] 2020-09-17 13:54
Try unsetting those.

**Comment by rsignavong** [comment] 2020-09-17 13:59
It works without those environment variable. Thank you! 👍 
I thought it was mandatory to specify those. I don't really remember why I needed to set `RUST_SRC_PATH`, maybe for RLS and Racer.

**Closed** 2020-09-17 14:01 UTC

**Comment by sunjay** [comment] 2020-09-17 14:04
Ah! Yup. I had that variable too. It used to be mandatory for RLS. Thanks @lnicola! 🎉

**Comment by wojciechkepka** [comment] 2020-10-08 07:15
Same for me! Issue resolved :) Thanks @lnicola

**Comment by Nevsden** [comment] 2020-10-28 08:44
For me setting the `RUST_SRC_PATH` environment variable to `C:\Users\<USERNAME>\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust` did the fix.

**Comment by flodiebold** [comment] 2020-10-28 09:31
That would help, but it'd still be better to unset it completely.

**Comment by Nevsden** [comment] 2020-10-28 09:39
I'm curious what you mean with unsetting it completely. I am not aware that I had it set before. Or am I missing something?

**Comment by flodiebold** [comment] 2020-10-28 09:52
If `RUST_SRC_PATH` isn't set, rust-analyzer should discover the path automatically if you're using rustup. Using the variable should only be necessary if you're getting the standard library sources some other way. Make sure you're using the newest rust-analyzer version (you can check using the "Rust Analyzer: Show RA Version" command); then if the problem still occurs, it will tell you "(`RUST_SRC_PATH` might be incorrect, try unsetting it)" in the error message if you've still got the variable set somewhere.

**Comment by ntn888** [comment] 2020-11-09 10:52
those variables are not set for me but i'm getting the error! pls help

**Comment by ntn888** [comment] 2020-11-09 10:52
ls $(rustc --print sysroot)/lib/rustlib/src/rust/src
ls: cannot access '/home/ajit/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src': No such file or directory

**Comment by flodiebold** [comment] 2020-11-09 12:24
That's the old path, it's not supposed to exist. Please check that you're using the newest rust-analyzer version using the "Show RA version" command, provide the full error message and the rustc version, and check whether `$(rustc --print sysroot)/lib/rustlib/src` exists.

**Comment by ntn888** [comment] 2020-11-09 17:51
thanks for your prompt response! i switched to compiling the rust-analyser from source and this fixed the problem. i guess the binary download isn't updated yet. thanks again.

**Comment by uninhm** [comment] 2021-05-31 03:50
I'm getting that error!! I don't have RUST_SRC_PATH nor RUST_SRC set

```
[I] unai@unai-pc ~/P/R/myproject (master)> ls /usr/lib/rustlib/
rustc-src  x86_64-unknown-linux-gnu
```
