### ISSUE TITLE
Can't infer deseralized Result type

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#8508] opened 2021-04-13 14:59 UTC
```rust
pub fn test<R: Read>(mut reader: R) -> Result<Vec<i32>, bincode::Error> {
    let mut list = Vec::new();
    loop {
        // Inferred as Result<!, Box<ErrorKind, Global>>
        let elem = bincode::deserialize_from(&mut reader); 

        let elem = match elem.map_err(|err| *err) {
            Ok(task) => task,
            Err(bincode::ErrorKind::Io(err)) if err.kind() == io::ErrorKind::UnexpectedEof => break,
            Err(err) => return Err(Box::new(err)),
        };
        list.push(elem);
    }
    Ok(list)
}
```

**Comment by cynecx** [comment] 2021-04-24 17:21
This is a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7626.

**Closed** 2021-04-27 12:18 UTC
Labels: A-ty, S-actionable
