### ISSUE TITLE
Implementations code lens doesn't like generics

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6218] opened 2020-10-13 17:34 UTC
![image](https://user-images.githubusercontent.com/308347/95895570-88b74d80-0d93-11eb-9dfb-464405074a14.png)

**Comment by SomeoneToIgnore** [comment] 2020-10-13 18:01
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5781

**Closed** 2020-10-13 18:04 UTC
