### ISSUE TITLE
Huge memory consumption and it continues growing

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#2052] opened 2019-10-24 04:22 UTC
![image](https://user-images.githubusercontent.com/576863/67453271-c3e5db80-f66d-11e9-8508-b641131778ae.png)
![image](https://user-images.githubusercontent.com/576863/67453320-e5df5e00-f66d-11e9-933e-0ee6942c5927.png)

**Comment by matklad** [comment] 2019-10-24 05:19
In this form, the issue is not actionable: it is not a trivially reproducible problem (I don't think I've ever seen something quite like this myself), so there must be something special about your particular environment which makes rust-analyzer misbehave. At the same time, there are zero details about such environment. 

@davyzhang could you provide a little more info about this:

* does this happens for any projects you are working on, or only for some?
* what is the minimal project where this behavior is observed?
* how long does it take to reach these unbelievable levels of memory consumption?

Sorry for sounding a little cranky: I haven't had my first cup of pu'er yet :) But it is a little dispiriting to get an issue which describes a serious problem, without providing any means to debug it.

**Comment by matklad** [comment] 2019-10-24 08:36
Hm, I thin I've reproduced this now actually! So looks like the crucial bit of info that was missing is that its a recent *regression*.

**Comment by matklad** [comment] 2019-10-24 08:43
Looks like the chalk is to blame: https://gist.github.com/matklad/c6320c19b08afc8e6d8ca8612354d5b8

**Comment by davyzhang** [comment] 2019-10-24 08:59
Sorry for the quick issue, I actually update, compile, and use analyzer every day :) So I thought you guys would soon find this problem just as I did. Next time I will provide more useful information before I submit an issue.

**Comment by matklad** [comment] 2019-10-24 11:18
https://github.com/rust-analyzer/rust-analyzer/pull/2059 fixes semi-related problem, which should make this issue rarer in practice.

**Comment by Robbepop** [comment] 2019-11-08 13:47
@matklad any news about this? the problem for me is still pretty significant although I have the feeling it has slightly improved.

**Comment by matklad** [comment] 2019-11-08 13:56
The root cause (chalk allocating in a loop) is not yet fixed iirc. @flodiebold do we have an issue on the chalk repo which tracks this? Or only they Zulip thread?

**Comment by flodiebold** [comment] 2019-11-08 15:01
Only the Zulip thread, as far as I know.

**Comment by piotr-szpetkowski** [comment] 2019-11-08 21:47
@matklad I've just experienced the issue while looking at `Iterator` trait definition. It caused memory usage to quickly skyrocket and after a while it has triggered OOMK:

```
[10717.403818] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
[10717.404125] [  13894]  1000 13894  3539510  1760443 26292224  1377237           300 ra_lsp_server
[10717.404127] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=ra_lsp_server,pid=13894,uid=1000
[10717.404169] Out of memory: Killed process 13894 (ra_lsp_server) total-vm:14158040kB, anon-rss:7041772kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by matklad** [comment] 2019-11-08 21:51
zulip thread in question: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/infinite.20stack.20growth.20in.20chalk

**Comment by bkchr** [comment] 2020-01-14 08:37
I'm still seeing this very regularly. Do you need something to reproduce this?

**Comment by estin** [comment] 2020-01-21 21:25
Same problem for me on `commit de2409702ba639f06cf340f5e3f3b7e671021d1b`

Check for reproduce https://gist.github.com/estin/393600a78a2891164aaa9db453d88e84

I found it by using nvim + coc.vim + coc-rust-analyzer on my https://github.com/estin/cywad
All available system memory used. Only killing ra helps...

Sorry for my poor English.

**Comment by jonas-schievink** [comment] 2020-06-17 22:26
The chalk bug is now fixed. @estin's panic still happens, but memory usage looks normal. Closing as fixed.

I've reduced the panic and will open a new bug report.

**Closed by jonas-schievink** 2020-06-17 22:26 UTC
Labels: E-unknown

**Comment by jonas-schievink** [comment] 2020-06-17 22:29
Filed https://github.com/rust-analyzer/rust-analyzer/issues/4931
