### ISSUE TITLE
[mockall] autocomplete works partly

### ISSUE THREAD

**Issue by n-bes** [rust-analyzer/rust-analyzer#7988] opened 2021-03-12 20:56 UTC
Possible dup

```#[automock]``` no autocomplete:
![image](https://user-images.githubusercontent.com/11599814/110997231-2ab48380-838e-11eb-9f28-2b5d9ab484d0.png)

```mock!``` autocomplete works:
![image](https://user-images.githubusercontent.com/11599814/110997188-196b7700-838e-11eb-830e-ba710b20efe0.png)

```rust
fn main(){

}

use mockall::{automock, mock, predicate::*};

trait MyTrait {
    fn foo(&self, x: u32) -> u32;
}

mock!{
    pub MyStruct{}
    impl MyTrait for MyStruct {
        fn foo(&self, x: u32) -> u32{
            return 42;
        }
    }
}

#[automock]
trait NotWorkingTrait {
    fn foo(&self, x: u32) -> u32;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mytest() {
        let mut not_working_mock = MockNotWorkingTrait::new();
        let mut mock = MockMyStruct::new();
    }
}
```

**Comment by flodiebold** [comment] 2021-03-12 21:17
Duplicate of #6029.

**Closed by flodiebold** 2021-03-12 21:17 UTC
