### ISSUE TITLE
Generated bindings not showing up as intellisense suggestions

### ISSUE THREAD

**Issue by Sibz** [rust-analyzer/rust-analyzer#5992] opened 2020-09-13 00:07 UTC
I am using the library `godot-rust` and while everything runs fine, there is no intellisense happening for the (generated) types provided by the package.

This can reproduced by cloning my example repository here:
https://github.com/Sibz/godotrust-bugdemo
This may need LLVM installed in order to compile.

On line 15 I have picked an example method that should hint, but does not.
The description for this struct is here: https://docs.rs/gdnative/0.9.0-preview.0/gdnative/api/rigid_body/struct.RigidBody.html

I have contacted the developer and he is aware of the issue but believes the issue probably lies with rust-analyser - it should be able to pick up the bindings generated but it doesn't.

The code compiles and runs fine.

**Comment by bjorn3** [comment] 2020-09-13 05:36
Try enabling `rust-analyzer.cargo.loadOutDirsFromCheck`.

**Comment by Sibz** [comment] 2020-09-14 02:41
Thank you for your reply. I tried the following combinations (because the first didn't work) in my code workspace settings:
```json
"rust.rust-analyzer.cargo.loadOutDirsFromCheck": true
"rust-analyzer.cargo.loadOutDirsFromCheck": true
"rust-analyzer.cargo": {
	"loadOutDirsFromCheck": true
}
"rust.rust-analyzer.cargo": {
	"loadOutDirsFromCheck": true
}
```

**Comment by matklad** [comment] 2020-10-15 11:41
Hm, this works for me as intended:

with  `"rust-analyzer.cargo.loadOutDirsFromCheck": true`

![image](https://user-images.githubusercontent.com/1711539/96118413-c202d100-0eeb-11eb-856e-1b786c859328.png)

with  `"rust-analyzer.cargo.loadOutDirsFromCheck": false`

![image](https://user-images.githubusercontent.com/1711539/96118471-d5ae3780-0eeb-11eb-8ca9-91ee9ead8237.png)

Couple of hypothesis why this migth be the case:

* perhaps `cargo check` running from rust-analyzer failed due to some differnece in env variables? It took me a while to convince nixos to biuld the example
* " I tried the following combinations" feels suspicious. There should be completion for VS Code options, if you don't get it, perhaps something is misconfigured. 

As I can't repro this locally, closing -- seems to be an env specific issue

**Closed by matklad** 2020-10-15 11:41 UTC
Labels: E-unknown

**Comment by problame** [comment] 2021-03-03 10:14
Why is `rust-analyzer.cargo.loadOutDirsFromCheck` not enabled by default? I spent several months in a project with bindgen-generated bindings and became unnecessarily frustrated with RA.

**Comment by lnicola** [comment] 2021-03-03 10:18
There's a discussion in https://github.com/rust-analyzer/rust-analyzer/issues/6448.
