### ISSUE TITLE
Add code action to replace `if` with `bool::then` method

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#9796] opened 2021-08-06 01:19 UTC
This would apply to `if` expressions with a single `else` branch, where the consequent is of the form `Some(expr)` and the alternative is `None`.

Before:

```rust
let exclamation_mark = "Hello!".chars().enumerate().find_map(|(idx, c)| {
    if$0 c.is_ascii_punctuation() {
        Some(idx)
    } else {
        None
    }
});
```

After:

```rust
let exclamation_mark = "Hello!"
    .chars()
    .enumerate()
    .find_map(|(idx, c)| c.is_ascii_punctuation().then(|| idx));
```

Edit: I realised that [`Iterator::position`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.position) is a better way to do what I was doing in this example, but then the `if` would disappear, so the example still stands :)

**Comment by Veykril** [comment] 2021-08-06 10:19
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8413 ( just realized I called it `Option::then` in there by accident)

**Closed by Veykril** 2021-08-06 10:19 UTC
Labels: S-actionable, A-assists

**Comment by arzg** [comment] 2021-08-06 11:05
Ah, makes sense then why my search didn’t turn up any results.
