### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by yshui** [rust-analyzer/rust-analyzer#10772] opened 2021-11-16 01:09 UTC
Stack trace:

```
thread 'main' panicked at 'internal error: entered unreachable code', crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/mod.rs:256:5

stack backtrace:

   0: rust_begin_unwind
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panicking.rs:106:14
   2: core::panicking::panic
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panicking.rs:47:5
   3: <proc_macro_srv::abis::abi_1_56::proc_macro::bridge::api_tags::Method as proc_macro_srv::abis::abi_1_56::proc_macro::bridge::rpc::DecodeMut<S>>::decode
   4: <proc_macro_srv::abis::abi_1_56::proc_macro::bridge::server::Dispatcher<proc_macro_srv::abis::abi_1_56::proc_macro::bridge::server::MarkedTypes<S>> as proc_macro_srv::abis::abi_1_56::proc_macro::bridge::server::DispatcherTrait>::dispatch
   5: <proc_macro_srv::abis::abi_1_56::proc_macro::bridge::closure::Closure<A,R> as core::convert::From<&mut F>>::from::call
   6: proc_macro::bridge::closure::Closure<A,R>::call
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/closure.rs:27:18
   7: proc_macro::bridge::client::TokenStream::into_iter::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:244:25
   8: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:336:47
   9: proc_macro::bridge::client::BridgeState::with::{{closure}}::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:293:17
  10: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  11: proc_macro::bridge::client::BridgeState::with::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:291:13
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/thread/local.rs:399:16
  13: std::thread::local::LocalKey<T>::with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/thread/local.rs:375:9
  14: proc_macro::bridge::client::BridgeState::with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:290:9
  15: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:329:9
  16: proc_macro::bridge::client::TokenStream::into_iter
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:237:17
  17: proc_macro::token_stream::<impl core::iter::traits::collect::IntoIterator for proc_macro::TokenStream>::into_iter
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/lib.rs:293:22
  18: <proc_macro2::imp::TokenStream as core::iter::traits::collect::IntoIterator>::into_iter
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.32/src/wrapper.rs:314:41
  19: proc_macro2::token_stream::<impl core::iter::traits::collect::IntoIterator for proc_macro2::TokenStream>::into_iter
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.32/src/lib.rs:1289:24
  20: syn::buffer::TokenBuffer::inner_new
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.81/src/buffer.rs:53:19
  21: syn::buffer::TokenBuffer::new2
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.81/src/buffer.rs:112:9
  22: <F as syn::parse::Parser>::parse2
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.81/src/parse.rs:1207:19
  23: syn::parse::Parser::parse
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.81/src/parse.rs:1161:9
  24: syn::parse_macro_input::parse
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.81/src/parse_macro_input.rs:139:5
  25: thiserror_impl::derive_error
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-impl-1.0.30/src/lib.rs:28:17
  26: core::ops::function::FnOnce::call_once
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/ops/function.rs:227:5
  27: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:410:40
  28: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:377:26
  29: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/scoped_cell.rs:80:33
  30: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  31: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/scoped_cell.rs:80:9
  32: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:325:35
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/thread/local.rs:399:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/thread/local.rs:375:9

  35: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter

             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:325:9
  36: proc_macro::bridge::client::run_client::{{closure}}
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:370:9

  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panicking.rs:406:40
  39: __rust_try
  40: std::panicking::try
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panicking.rs:370:19
  41: std::panic::catch_unwind
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
  42: proc_macro::bridge::client::run_client
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:369:5
  43: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/proc_macro/src/bridge/client.rs:410:13

  44: proc_macro_srv::abis::abi_1_56::proc_macro::bridge::server::run_server
  45: proc_macro_srv::abis::abi_1_56::Abi::expand
  46: proc_macro_srv::dylib::Expander::expand
  47: proc_macro_srv::ProcMacroSrv::expand
  48: proc_macro_srv::cli::run
  49: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Caused by: https://github.com/yshui/docconfig/blob/0a534db4b3d940fd83e492844a74c6a7f9ba1856/docconfig_derive/src/lib.rs

**Comment by pacak** [comment] 2021-11-16 09:20
Which version of rust-analyzer? What do you need to do to trigger the problem?

**Comment by lnicola** [comment] 2021-11-16 09:22
CC #10769

**Comment by yshui** [comment] 2021-11-16 10:32
@pacak 73668334f05c3446b04116ccc3156240d2d8ab19, i just opened the file in nvim with lsp support.

**Comment by robot-head** [comment] 2021-11-17 04:52
Hitting the same bug I think: 
```
thread 'main' panicked at 'internal error: entered unreachable code', crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/mod.rs:422:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: <proc_macro_srv::abis::abi_1_58::proc_macro::bridge::TokenTree<G,P,I,L> as proc_macro_srv::abis::abi_1_58::proc_macro::bridge::rpc::DecodeMut<S>>::decode
   4: <proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::Dispatcher<proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::MarkedTypes<S>> as proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::DispatcherTrait>::dispatch
   5: <proc_macro_srv::abis::abi_1_58::proc_macro::bridge::closure::Closure<A,R> as core::convert::From<&mut F>>::from::call
   6: proc_macro::bridge::closure::Closure<A,R>::call
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/closure.rs:27:18
   7: proc_macro::bridge::client::TokenStream::into_iter::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:244:25
   8: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:336:47
   9: proc_macro::bridge::client::BridgeState::with::{{closure}}::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:293:17
  10: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  11: proc_macro::bridge::client::BridgeState::with::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:291:13
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/thread/local.rs:399:16
  13: std::thread::local::LocalKey<T>::with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/thread/local.rs:375:9
  14: proc_macro::bridge::client::BridgeState::with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:290:9
  15: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:329:9
  16: proc_macro::bridge::client::TokenStream::into_iter
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:237:17
  17: proc_macro::token_stream::<impl core::iter::traits::collect::IntoIterator for proc_macro::TokenStream>::into_iter
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/lib.rs:259:22
  18: <proc_macro2::imp::TokenStream as core::iter::traits::collect::IntoIterator>::into_iter
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.27/src/wrapper.rs:314:41
  19: proc_macro2::token_stream::<impl core::iter::traits::collect::IntoIterator for proc_macro2::TokenStream>::into_iter
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.27/src/lib.rs:1267:24
  20: const_format_proc_macros::utils::Peekable2<core::ops::range::Range<u8>>::new
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/const_format_proc_macros-0.2.22/src/utils.rs:37:19
  21: const_format_proc_macros::parse_utils::ParseBuffer::new
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/const_format_proc_macros-0.2.22/src/parse_utils.rs:18:20
  22: const_format_proc_macros::parse_utils::MyParse::parse_token_stream_1
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/const_format_proc_macros-0.2.22/src/parse_utils.rs:362:26
  23: const_format_proc_macros::__concatcp_impl
             at /home/mattstone/.cargo/registry/src/github.com-1ecc6299db9ec823/const_format_proc_macros-0.2.22/src/lib.rs:54:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/ops/function.rs:227:5
  25: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:410:40
  26: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:377:26
  27: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/scoped_cell.rs:80:33
  28: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  29: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/scoped_cell.rs:80:9
  30: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:325:35
  31: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/thread/local.rs:399:16
  32: std::thread::local::LocalKey<T>::with
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/thread/local.rs:375:9
  33: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:325:9
  34: proc_macro::bridge::client::run_client::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:370:9
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panic/unwind_safe.rs:271:9
  36: std::panicking::try::do_call
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:406:40
  37: __rust_try
  38: std::panicking::try
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:370:19
  39: std::panic::catch_unwind
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panic.rs:133:14
  40: proc_macro::bridge::client::run_client
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:369:5
  41: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/proc_macro/src/bridge/client.rs:410:13
  42: proc_macro_srv::abis::abi_1_58::proc_macro::bridge::server::run_server
  43: proc_macro_srv::abis::abi_1_58::Abi::expand
  44: proc_macro_srv::dylib::Expander::expand
  45: proc_macro_srv::ProcMacroSrv::expand
  46: proc_macro_srv::cli::run
  47: rust_analyzer::try_main
  48: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by twitchax** [comment] 2021-11-17 07:49
+1 here, as well, when using `async_trait` for me.

**Comment by Dessix** [comment] 2021-11-17 08:22
If you're having this, just upgrade your rust toolchain at or past 2021-11-15; it doesn't occur on nightly-2021-11-16 for me.

**Comment by twitchax** [comment] 2021-11-17 08:27
Can confirm @Dressix's suggestion addresses the issue.

**Comment by yshui** [comment] 2021-11-17 19:00
So a bug in upstream compiler?

**Comment by lnicola** [comment] 2021-11-18 08:27
See also #10799.

For a couple of days we picked the 1.58 ABI for `1.57`.

**Comment by jonas-schievink** [comment] 2021-11-29 18:32
This one should have been fixed by #10799 and shipped in today's release, so closing.

Please let us know if it still occurs on more recent rust-analyzer versions.

**Comment by lnicola** [comment] 2021-11-29 18:42
Didn't #10799 ship last week?

**Comment by jonas-schievink** [comment] 2021-11-29 18:44
Oh, that's right

**Comment by pinpox** [comment] 2022-01-24 09:49
Still running into this issue.
```
rust-analyzer --version
rust-analyzer 2021-12-27
```

**Comment by SuperCuber** [comment] 2022-02-28 15:45
Still running into this on derive from crates for example thiserror::Error on windows.
```
$ ./rust-analyzer.exe --version
rust-analyzer 4e72700e3 2022-02-28 stable
```

![](https://owo.whats-th.is/2RDLBb1.png)

It has been this way consistently for a while in many crates. Error in `lsp.log` identical to one in the issue.

**Comment by bjorn3** [comment] 2022-02-28 15:51
Which rustc version do you use?

**Comment by jonas-schievink** [comment] 2022-03-23 16:22
The original rocket issue seems to occurs because https://github.com/rust-lang/rust/pull/87264 adds a new `proc_macro` API, but the Rust version still stays the same, so our mechanism to detect the right ABI does not work.

I'm tempted to close this as wontfix. Perhaps we should turn proc macros off when using a nightly Rust version, and have a setting to force-enable it?

**Comment by jonas-schievink** [comment] 2022-03-23 20:59
Can you provide a reproduction? I couldn't reproduce this when I tried

**Comment by SuperCuber** [comment] 2022-03-23 21:05
@jonas-schievink 
![error with versions](https://owo.whats-th.is/2ry9TJN.png)

**Comment by jonas-schievink** [comment] 2022-03-24 11:41
Still can't reproduce this, at least not on Linux. Can you set `RUST_BACKTRACE=1` and open a new issue containing a backtrace? This thread covers 3 separate bugs already.

**Comment by SuperCuber** [comment] 2022-03-24 15:55
> Still can't reproduce this, at least not on Linux. Can you set `RUST_BACKTRACE=1` and open a new issue containing a backtrace? This thread covers 3 separate bugs already.

I can't seem to reproduce this with the exact same versions on linux either, although based on paths in OP's log it can happen there as well. I get a `proc macro "Error" not expanded` message instead, I guess that's expected behavior (?)

When you say backtrace, do you mean an `lsp.log` like OP provided?

**Comment by SuperCuber** [comment] 2022-03-24 16:26
> I'm not sure what lsp.log is, if that's where rust-analyzer's stderr ends up, then that's where the stack backtrace should show up, yeah.

Cool, I'll post that.

> The "Restart server" command usually fixes this for me. 

This message is persistent for me, but the log shows nothing... Hmm. I'll post the output on windows then, but I'll guess this is the same underlying issue.

**Comment by SuperCuber** [comment] 2022-03-24 18:29
@jonas-schievink  created #11812

**Comment by JBA-Khalifa** [comment] 2022-03-28 11:42
> If you're having this, just upgrade your rust toolchain at or past 2021-11-15; it doesn't occur on nightly-2021-11-16 for me.

This worked for me

**Comment by jonas-schievink** [comment] 2022-03-28 11:59
Given that the only reproduction on stable is now tracked in #11812, closing this as wontfix as mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/10772#issuecomment-1076533915

**Closed by jonas-schievink** 2022-03-28 11:59 UTC
Labels: A-macro, S-actionable, Broken Window, C-bug
