### ISSUE TITLE
Async move blocks not resolving properly

### ISSUE THREAD

**Issue by Nashenas88** [rust-analyzer/rust-analyzer#5676] opened 2020-08-06 13:58 UTC
In the following code:
```rust
use async_std::task::block_on;
use std::future::Future;

struct A<T> {
    #[allow(dead_code)]
    val: T,
}

impl<T> A<T> {
    fn new(fut: impl Future<Output = T>) -> Self
    {
        A {
            val: block_on(fut),
        }
    }
}

impl A<()> {
    fn extra_fn(&self) {}
}

async fn returns_unit() {}

fn main() {
    let a = A::new(async move { });
    a.extra_fn();

    let b = A::new(returns_unit());
    b.extra_fn();
}
```
`extra_fn` in `a.extra_fn();` is not resolved because the type of `a` is `A<Future::Output<()>>`, but it is resollved in `b.extra_fn();` because the type of `b` is `A<()>`.

The type of `a` should resolve to `A<()>`.

**Comment by flodiebold** [comment] 2020-08-06 14:00
Duplicate of #4018.

**Closed by flodiebold** 2020-08-06 14:00 UTC
