### ISSUE TITLE
Doc links to std are broken

### ISSUE THREAD

**Issue by HKalbasi** [rust-analyzer/rust-analyzer#10208] opened 2021-09-11 16:03 UTC
When you hover on something in std, like `String`:

The String type is the most common string type that has ownership over the contents of the string. It has a close relationship with its borrowed counterpart, the primitive **str**.

There is a link to str:
https://docs.rs/alloc/*/alloc/str/index.html

Which is broken and it should be:
https://doc.rust-lang.org/std/primitive.str.html

It is not specific to primitives and every link to std documentation is affected, another example is extend:
https://docs.rs/core/*/core/iter/traits/collect/trait.Extend.html

But it should be:
https://doc.rust-lang.org/std/iter/trait.Extend.html

**Comment by bjorn3** [comment] 2021-09-11 19:08
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10082

**Closed by bjorn3** 2021-09-11 19:08 UTC
