### ISSUE TITLE
"Jump to definition" should jump to a trait impl when the concrete type is known.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#7754] opened 2021-02-22 15:59 UTC
Example program:

```
struct S(i32);

impl Default for S {
    fn default() -> Self {
        Self(42)
    }
}

fn main() {
    let s = S::default();
}
```

Jump-to-definition on the `default` call should (IMO) go to its implementation in the `impl` block, not in the definition of the `Default` trait.

**Comment by Veykril** [comment] 2021-02-22 16:42
I think this is a dupe of #4558

**Comment by flodiebold** [comment] 2021-02-22 17:18
Yes.

**Closed by flodiebold** 2021-02-22 17:18 UTC
