### ISSUE TITLE
"Go to definition" vs cargo registry temp files footgun

### ISSUE THREAD

**Issue by kornelski** [rust-analyzer/rust-analyzer#9952] opened 2021-08-19 13:54 UTC
If I jump to definition of a type that is from an external crate, I may end up editing Cargo's temporary file. Can rust-analyzer do something to stop that?

"Go to definition" technically correctly opens the file where the type is defined, wherever it comes from, even if it's a crates.io crate or a Cargo git dependency cloned to a temp dir. The functionality is legitimately useful for `path` dependencies, and could conceivably be useful for crates.io crates as a way to inspect their implementation details or read doc comments without switching to a web browser.

However, it's also problematic in case I accidentally edit files of crates.io crates' checkout. That may unexpectedly affect other projects, or just lead to wasted effort editing a temp file that may get deleted at any time. I especially got bitten by a `git` Cargo dependency which was my code I wanted to edit, but I haven't noticed that it wasn't the right checkout location. 

Can rust-analyzer help here? For example, could it detect when analyzing a file in `CARGO_HOME` and inject a warning in the file "hey, this is Cargo's private file, don't edit it!".

**Comment by lnicola** [comment] 2021-08-19 13:58
Duplicate of #5847.

**Closed by lnicola** 2021-08-19 13:58 UTC

**Comment by kornelski** [comment] 2021-08-19 14:16
The issue #5847 is about changing behavior or VSCode. I'm not using VSCode, but Sublime Text 4.

**Comment by Veykril** [comment] 2021-08-19 14:24
The problem here lies more with the language server protocol as it doesn't let us specify that the client should open anything in read only mode. The VSCode issue there is more about not allowing extensions to open files in read-only mode which prevents us from implementing this requirement in the VSCode extension.

In this case you can ask in the repo of the sublime extension if they can do something in their custom extension code for this.
