### ISSUE TITLE
use std::f64 cause Not found for f64:: methods

### ISSUE THREAD

**Issue by Dushistov** [rust-analyzer/rust-analyzer#10490] opened 2021-10-08 22:58 UTC
I tested 545b068a7720374a13e04db24e0bef6237822f2a .

For code bellow rust-analyzer works fine. Emacs + rust-analyzer can jump to atan2 implementation,
can show documentation for `f64::atan2` and so on.
But if I uncomment `use std::f64;` rust-analyzer stop recognize `f64::atan2`,
can not jump to it's implementation, doesn't show documentation and so on.
Obviously `rustc` stable compiles both variants just fine.

```
//use std::f64;
fn main() {
    let x = f64::atan2(1.0, 0.0);
    println!("Results: {}", x);
}
```

**Comment by jonas-schievink** [comment] 2021-10-09 15:03
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6082

**Closed by jonas-schievink** 2021-10-09 15:03 UTC
