### ISSUE TITLE
unresolved import for package in a git subfolder

### ISSUE THREAD

**Issue by imerkle** [rust-analyzer/rust-analyzer#6481] opened 2020-11-06 15:55 UTC
main.rs

`use rocket_contrib::json::Json;` //unresolved import

cargo.toml

`rocket_contrib = {git="https://github.com/SergioBenitez/Rocket/"}`

**Comment by lnicola** [comment] 2020-11-06 15:57
Duplicate of #6407.

**Closed by lnicola** 2020-11-06 15:57 UTC
