### ISSUE TITLE
`use Enum::*` confuses type inference

### ISSUE THREAD

**Issue by kornelski** [rust-analyzer/rust-analyzer#5533] opened 2020-07-25 12:22 UTC
```rust
enum Enum {
    Bar(u32)
}

fn main() {
    let e = Enum::Bar(1);
    use Enum::*;
    match e {
        Bar(_i_am_unknown) => {}
        Enum::Bar(_works_fine) => {}
    }
}
```

In vscode hint for `_i_am_unknown` is `{unknown} | u32`. The `_works_fine` variable gets `u32 | u32` hint. The `{unknown}` variable doesn't get type-based autocomplete, etc.

<img width="347" alt="borks" src="https://user-images.githubusercontent.com/72159/88456898-b6b68100-ce79-11ea-907a-0346725848e7.png"> <img width="347" alt="works" src="https://user-images.githubusercontent.com/72159/88456897-b61dea80-ce79-11ea-9b2d-e040b6e0951c.png">

**Comment by lnicola** [comment] 2020-07-25 12:24
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1165.

**Closed by lnicola** 2020-07-25 12:24 UTC
