### ISSUE TITLE
Derive assist

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#9792] opened 2021-08-05 01:53 UTC
For instance, if you try to use `==` on an enum that doesn't implement PartialEq/Eq, RA will tell you that you need to implement it.

It would be nice if RA provided an assist add the `#[derive()]` for us, for types defined in our workspace.

**Comment by jonas-schievink** [comment] 2021-08-05 20:27
We just display rustc's diagnostic, which does not include that sort of suggestion. Closing as a duplicate of https://github.com/rust-lang/rust/issues/85845.

**Closed by jonas-schievink** 2021-08-05 20:27 UTC

**Comment by jonas-schievink** [comment] 2021-08-05 20:28
Also I should probably note that there already is an "Add `#[derive]`" assist that helps a bit with this. We also have auto-completion for `PartialEq` in the derive list.
