### ISSUE TITLE
Rename not applied to trait impls.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#4517] opened 2020-05-19 21:49 UTC
```
trait T {
    fn f();
}

struct S;

impl T for S {
    fn f() {}
}

fn main() {}
```

Rename `f` in `T` to `f2`. Note that the implementation in `S` is not renamed.

**Comment by lnicola** [comment] 2020-05-20 04:54
Duplicate of #4201.

**Closed by lnicola** 2020-05-20 04:54 UTC
