### ISSUE TITLE
Struct member suggestions are flanky on windows

### ISSUE THREAD

**Issue by mrpink76** [rust-analyzer/rust-analyzer#11343] opened 2022-01-25 21:32 UTC
**rust-analyzer version**: 5f13d6af9 2022-01-25 nightly

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

**vscode version**: Version: 1.63.2 (user setup) (Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3, OS: Windows_NT x64 10.0.22000)

The starting point is the following:

```rust
struct Test {
    pub field : String,
}

fn main() {
    println!("Hello, world!");
    let x = Test { field: "".to_string()};
    // cursor is placed directly after x on the next line
    let a = x
}
```

When writing ".fi" fast, the suggestion for "field" is not beeing shown.

If first write the "." and then after a short wait write "fi". The success rate is much higher.

Tried the same thing on vscode on macos (macbook pro) and there I could not reproduce the issue.

The bug happens quite frequently on windows.

A related issue is that the suggestion might disapear if you write two or more aditional characters quickly, that is go from "let a = x.fi" to "let a = x.fiel". It seems to work if you only write one character and then waits for the suggestion before writing another character.

**Comment by Veykril** [comment] 2022-01-28 10:51
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10187

**Closed by Veykril** 2022-01-28 10:51 UTC

**Comment by mrpink76** [comment] 2022-01-28 14:44
@Veykril I don't think this is a duplicate of "10187" since this bug is reproducible with a very small code base (hello world size). 
This behavior is limited to Windows (no issues in macos/darwin).

**Comment by Veykril** [comment] 2022-01-28 16:55
We have plenty more of these kinda issue, but here is a windows specific one of which this might be a duplicate actually https://github.com/rust-analyzer/rust-analyzer/issues/3973
(Truth be told I picked the first one of these that I could find when closing this)

Other related ones https://github.com/rust-analyzer/rust-analyzer/issues/7560 https://github.com/rust-analyzer/rust-analyzer/issues/10263
