### ISSUE TITLE
"Fill Struct Fields" - Wrong Insert Location in Nested Tuples

### ISSUE THREAD

**Issue by theduke** [rust-analyzer/rust-analyzer#7302] opened 2021-01-16 22:01 UTC
I regularly run across cases where "Fill struct fields" messes up the file by inserting the fields at the wrong location. 

Often in early `use` statements on top of the file.

I'm sure there are multiple cases where this can happen, but I was able to isolate a particular simple example.

```rust
struct S {
    x: bool,
}

fn f() {
    let x = vec![
        (
            S{
// >>>  Autocomplete triggered here
            }
        )
    ];
}
```

Actual output:

```rust
struct S {
   // >>> Inserted below
    x: bool, x: ()
}

fn f() {
    let x = vec![
        (
            S{

            }
        )
    ];
}
```

Version: `rust-analyzer 52fa926`

**Comment by Veykril** [comment] 2021-01-16 23:11
The problem here is the surrounding macro call, duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5393

**Closed by Veykril** 2021-01-16 23:11 UTC
