### ISSUE TITLE
rust-analyzer conflicts with vscodevim

### ISSUE THREAD

**Issue by AlseinX** [rust-analyzer/rust-analyzer#2951] opened 2020-01-30 10:43 UTC
When the rust-analyzer extension(release 2020-01-29) is installed, vscodevim extenstion is not working properly.
When pressing a key in normal mode, it does not work as normal mode commands but inserts a character directly.
I do think it should be fixed by rust-analyzer rather than vscodevim, because it makes no sense that a code analyzing extension breaks a input binding extension and rust-analyzer seems to work out of its scope as a code analyzing extension.

**Comment by kiljacken** [comment] 2020-01-30 10:56
Duplicate of #1831, you can disable enhanced typing as mentioned in the documentation :) Closing

**Closed by kiljacken** 2020-01-30 10:56 UTC

**Comment by dakom** [comment] 2020-02-10 10:36
Setting `"rust-analyzer.enableEnhancedTyping": false` in vscode's `settings.json` did not work for me, I still get a buggy conflict

**Comment by matklad** [comment] 2020-02-10 10:58
Yep, we switched to a different impl of this functionality:

https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#installation-from-sources

>Note #1831: If you are using the popular Vim emulation plugin, you will likely need to turn off the rust-analyzer.enableEnhancedTyping setting. (// TODO: This configuration is no longer available, enhanced typing shoud be disabled via removing Enter key binding, see this issue)


Sorry for the, khm, suboptimal documentation. I plan to spend this week overhauling the docs.
