### ISSUE TITLE
"Rename symbol" in Sublime Text only changes the last occurrence

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#5915] opened 2020-08-29 21:23 UTC
### To reproduce
0. Set up rust-analyzer for Sublime using these instructions: https://rust-analyzer.github.io/manual.html#sublime-text-3
1. Open the following program in Sublime:
    ```rust
    fn main() {
        let x = 0;
        let y = x;
        let z = x;
    }
    ```
2. Use `LSP -> Rename Symbol` action from the context menu on any occurrence of `x`.
3. Enter `xx` as the new name.

### Expected result
```rust
fn main() {
    let xx = 0;
    let y = xx;
    let z = xx;
}
```

### Actual result
```rust
fn main() {
    let x = 0;
    let y = x;
    let z = xx;
}
```

----
### Version info
 * rust-analyzer e65d48d
 * Sublime Text 3.2.2, build 3211
 * LSP Sublime package, 0.11.4 with rust-analyzer language server enabled

**Comment by matklad** [comment] 2020-08-31 12:45
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4901#issuecomment-644675309

**Closed by matklad** 2020-08-31 12:45 UTC
