### ISSUE TITLE
Command 'rust-analyzer.onEnter' not found

### ISSUE THREAD

**Issue by PsiACE** [rust-analyzer/rust-analyzer#3212] opened 2020-02-18 04:07 UTC
Due to network issues, I temporarily stayed in the 2019-02-11 version, and I got "command'rust-analyzer.onEnter not found" when I tried to enter a newline in vscode.

In fact, I didn't get a newline either, obviously, we affected the normal operation of the editor.

**Comment by PsiACE** [comment] 2020-02-18 04:13
Currently if I need a newline, I have to use `shift + enter` or` ctrl + enter` instead of `enter` directly

**Comment by Veetaha** [comment] 2020-02-18 08:32
What is the reason to suppose this is connected with the network issues?

**Comment by lnicola** [comment] 2020-02-18 08:34
I think they're saying they're on last week's release for unrelated reasons.

See #3013.

**Comment by Veetaha** [comment] 2020-02-18 08:35
Okay, this is weird, onEnter should actually be found

**Comment by PsiACE** [comment] 2020-02-18 13:44
I did not manually set / install any key bindings. This is where I am confused.

**Comment by lnicola** [comment] 2020-02-18 13:52
Just to make sure, can you try to uninstall the extension, check the contents of `~/.vscode/extensions`, then install it again from the Marketplace?

**Comment by Jasper-Bekkers** [comment] 2020-02-21 22:23
I just ran into this issue - it's only on one of my projects so far. It happens to be a project that requires nightly to build, but I'm not sure if it's a red herring or not.

**Comment by Jasper-Bekkers** [comment] 2020-02-21 22:27
Just created a new project which also failed and it doesn't require nightly. Currently disabled rust analyzer (vscode extension).

**Comment by lnicola** [comment] 2020-02-21 22:39
@Jasper-Bekkers can you peek at your `%USERPROFILE%\.vscode\extensions` or `~/.vscode/extensions` directory to see how the `rust-analyzer` extension is called?

**Comment by Jasper-Bekkers** [comment] 2020-02-21 22:41
There are two folders there: `matklad.rust-analyzer-0.1.20200211` and `matklad.rust-analyzer-0.1.20200217` (this is on windows fwiw).

**Comment by lnicola** [comment] 2020-02-21 22:44
@Veetaha how is this possible? :smile:

Still, the `onEnter` keybinding was added in 23ef22dd48, before the Feb 11 release. But it might be good idea to remove both and do a clean install of the extension?

**Comment by Veetaha** [comment] 2020-02-22 07:02
VSCode doesn't remove extensions right away even when you press `Uninstall`. It might be the case that VSCode didn't remove the previous version of `rust-analyzer`, but it should not be used anyway...

**Comment by Veetaha** [comment] 2020-02-22 07:13
It would be great if someone ran
```
rm -rf ~/.vscode/extensions/matklad.rust-analyzer-0.1.20200217
# and 20200211 version if it exists
rm -rf ~/.config/Code/User/globalStorage/matklad.rust-analyzer
```
Did a reinstallation of the latest `rust-analyzer` extension from the marketplace and provided a reproduction for this issue...
Though, anyway, I am working on replacing this command with something that doesn't override keybindings or conflict with other extensions to avoid such problems in the firtsplace...

**Comment by ValarDragon** [comment] 2020-02-25 13:18
I ran into the same issue. Running the rm -rf commands @Veetaha provided, and reinstalling from the marketplace fixed the issue for me.

**Comment by matklad** [comment] 2020-02-25 13:19
I believe this is fixed in the latest release

**Closed by matklad** 2020-02-25 13:19 UTC

**Comment by scambier** [comment] 2022-07-16 19:08
The issue is still present. The keybinding is automatically re-added when you delete it, even when VSCode is started in safe mode. The only way to get rid of it is to close VSCode, edit the keybindings.json with another editor, set it to read-only, and reopen VSCode.
