### ISSUE TITLE
Fill struct field assist in macro inserts fields in wrong location

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#7003] opened 2020-12-22 15:23 UTC
```rust
struct CoolStruct {
    field: i32
}

fn foo() {
    let structs = vec![
        CoolStruct {
            <|> // <-- Invoked here
        }
    ];
}
```

Becomes

```rust
struct CoolStruct {
    field:  field: ()i32
}

fn foo() {
    let structs = vec![
        CoolStruct {
            
        }
    ];
}
```

**Comment by lnicola** [comment] 2020-12-22 15:26
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4314

**Closed by lnicola** 2020-12-22 15:26 UTC
