### ISSUE TITLE
Assertion failure when viewing a file that was deleted

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#7504] opened 2021-02-01 00:04 UTC
```
thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::inject::doc_comment
   3: ide::syntax_highlighting::highlight
   4: std::panicking::try
   5: ide::Analysis::highlight_range
   6: rust_analyzer::handlers::handle_semantic_tokens_range
   7: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 7:02:22 PM] Request textDocument/definition failed.
  Message: file not found: /home/joshua/src/yottadb/YDBRust/src/context_api/tests.rs
  Code: -32603
```
Steps to reproduce: Check out https://gitlab.com/jyn514/YDBRust/-/commit/afd6e66c73030dff19e465d8493a4c2f247a6990, open `src/context_api/tests.rs`, then check out https://gitlab.com/jyn514/YDBRust/-/commit/cf544736b8366bdfd3dac7b472dfbbdcb61b14bb.

**Comment by lnicola** [comment] 2021-02-01 15:10
Duplicate of #7299.

**Closed by lnicola** 2021-02-01 15:10 UTC
