### ISSUE TITLE
structs defined in a function cannot be intellisensed (resolved) in that function

### ISSUE THREAD

**Issue by enihcam** [rust-analyzer/rust-analyzer#7598] opened 2021-02-08 14:48 UTC
![image](https://user-images.githubusercontent.com/7010097/107235387-98078880-6a5f-11eb-8bb0-812e85d521ca.png)

**Comment by lnicola** [comment] 2021-02-08 14:49
Duplicate of #1559.

**Closed by lnicola** 2021-02-08 14:49 UTC
