### ISSUE TITLE
"!!MISSING: command!!

### ISSUE THREAD

**Issue by willparsons** [rust-analyzer/rust-analyzer#7910] opened 2021-03-08 06:40 UTC
![image](https://user-images.githubusercontent.com/10012418/110283939-dbaacf00-7fd8-11eb-9ce8-0fd5b28d1fa4.png)

Hi, not sure if this is actually down to rust-analyzer as I've seen some talk about OmniSharp and VSCode being the culprit. Wondering if anyone has come across this before. 

If it helps I'm using gdnative on the stable toolchain and now I see this "missing" text.

**Comment by Veykril** [comment] 2021-03-08 09:08
Duplicate of #3538

Does this appear as soon as you put the derive on a struct?

**Comment by willparsons** [comment] 2021-03-08 10:14
Sorry about the dupe, couldn't find another issue.

It depends, sometimes after rust-anazlyer does a cargo check it will go or when I open VSCode.

**Comment by jonas-schievink** [comment] 2021-03-08 15:48
closing in favor of https://github.com/rust-analyzer/rust-analyzer/issues/3538

**Closed by jonas-schievink** 2021-03-08 15:48 UTC
