### ISSUE TITLE
Missing documentation for AST types

### ISSUE THREAD

**Issue by theotherphil** [rust-analyzer/rust-analyzer#1647] opened 2019-08-04 09:31 UTC
It would be easier for beginners (like me!) to find their bearings if the AST types had comments explaining what the types represented and giving examples. For example: what exactly is a NominalDef?

This probably doesn't remain an issue for long for any single contributor, and can be answered with a bit of digging, but more documentation would definitely lower the barrier to entry.

**Comment by matklad** [comment] 2019-08-05 10:07
Yeah, that's true.

I wonder what's the best way to add it: there are a *lot* of AST types, and
they are generated. I think a good template would be

```
StructDef is `struct A { b: () }`
```

or

```
FieldDef is `b: ()` in `struct A { b: () }`
```

**Comment by theotherphil** [comment] 2019-08-11 10:00
Sounds good. I've got a few things in flight at the moment, but I'll have a go at this when they're done if no-one else has picked it up.

**Comment by Veetaha** [comment] 2020-03-23 13:01
duplicate of #3682

**Closed** 2020-03-23 13:08 UTC
Labels: E-hard, good first issue
