### ISSUE TITLE
Fill Struct Assist Error in `vec!`

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#4565] opened 2020-05-22 05:10 UTC
Hello!

Using the "Fill Struct Assist" within the `vec!` macro (and very likely other macros, though to be honest, i don't use many other macros regularly which might be similar) produces the odd result of slapping the internals of the struct near the top of the file (I am not sure why exactly at that point). 

Input code:
![image](https://user-images.githubusercontent.com/31973761/82633260-83245580-9baf-11ea-8bb3-bd21f49f7cf7.png)

Output result:
![image](https://user-images.githubusercontent.com/31973761/82633277-8f101780-9baf-11ea-93a5-afcd3014ed07.png)

Code in text form (I just wanted to show I was using the assist with pictures for clarity):

Input:
```
use super::{AnotherThing, Something};

struct Foo {
    bar: (),
    baz: (),
}

fn test() {
    let x = vec![Foo {
        
    }];
}
```
Output after running `Fill Struct Fields`:
```
use super::{AnotherThin{ bar: (), baz: ()} Something};

struct Foo {
    bar: (),
    baz: (),
}

fn test() {
    let x = vec![Foo {
        
    }];
}
```

Thank you all for all your hard work! This isn't that big of a deal, but Fill struct fields is the assist I use the most, and I really feel it when I lose access to it! Thank you again!

**Comment by flodiebold** [comment] 2020-05-22 08:50
Duplicate of #4314.

**Closed by flodiebold** 2020-05-22 08:50 UTC
