### ISSUE TITLE
Incorrect string syntax highlighting in attributes in VS Code

### ISSUE THREAD

**Issue by brendanzab** [rust-analyzer/rust-analyzer#6042] opened 2020-09-20 23:46 UTC
When using logos, I get the following broken syntax highlighting:

![Screen Shot 2020-09-21 at 9 40 44 am](https://user-images.githubusercontent.com/695077/93724930-8deb0780-fbee-11ea-9843-08d7c9d52b3d.png)

Original source for replication purposes:

```rust
#[derive(Debug, Clone, Logos)]
enum Quoted<'source> {
    #[regex(r#"[^\\"']+"#)]
    Text(&'source str),
    #[token("\\")]
    StartEscape,
    #[token("\'", |_| Quote::Single)]
    #[token("\"", |_| Quote::Double)]
    End(Quote),

    #[error]
    Error,
}

#[derive(Debug, Clone, Logos)]
enum Escape {
    #[token("\\", |_| '\\')]
    #[token("n", |_| '\n')]
    #[token("r", |_| '\r')]
    #[token("t", |_| '\t')]
    #[token("0", |_| '\0')]
    #[token("\'", |_| '\'')]
    #[token("\"", |_| '\"')]
    Single(char),
    #[token("u")]
    StartUnicodeEscape,
    #[token("x")]
    StartAsciiEscape,

    #[error]
    Error,
}

#[derive(Debug, Clone, Logos)]
enum UnicodeEscape<'source> {
    #[regex(r"\{[0-9a-fA-F]*\}", |lexer| &lexer.slice()[1..(lexer.slice().len() - 1)])]
    CharCode(&'source str),
    #[token("\'", |_| Quote::Single)]
    #[token("\"", |_| Quote::Double)]
    End(Quote),

    #[error]
    Error,
}
```

A workaround (suggested by @Kixiron and [seen in the wild in Crunch](https://github.com/Kixiron/crunch-lang/blob/e51945a8c3ecddb49c072de83b372373de0d4b39/crates/crunch-parser/src/token.rs#L26)) is to add `// workaround highlighting: "` to the offending lines:

```diff
 #[derive(Debug, Copy, Clone, PartialEq)]
 enum Quote {
     Single,
@@ -33,7 +61,7 @@ enum QuotedLiteral {

 #[derive(Debug, Clone, Logos)]
 enum Quoted<'source> {
-    #[regex(r#"[^\\"']+"#)]
+    #[regex(r#"[^\\"']+"#)] // workaround highlighting: "
     Text(&'source str),
     #[token("\\")]
     StartEscape,
@@ -53,7 +81,7 @@ enum Escape {
     #[token("t", |_| '\t')]
     #[token("0", |_| '\0')]
     #[token("\'", |_| '\'')]
-    #[token("\"", |_| '\"')]
+    #[token("\"", |_| '\"')] // workaround highlighting: "
     Single(char),
     #[token("u")]
     StartUnicodeEscape,
```

**Comment by bjorn3** [comment] 2020-09-21 05:45
Does this also happen when the rust-analyzee extension is disabled? If so then this issue is likely caused by an incorrect regex in the language definition of vscode.

**Comment by brendanzab** [comment] 2020-09-21 06:08
Ahh yeah, it seems like it is still doing something similar with rust-analyzer disabled:
<img width="443" alt="Screen Shot 2020-09-21 at 4 07 43 pm" src="https://user-images.githubusercontent.com/695077/93736772-afff7c80-fc24-11ea-8938-af45308cda85.png">

**Comment by lnicola** [comment] 2020-09-21 06:15
I think there's another issue about the same thing. But is the built-in grammar still used if semantic highlighting is enabled?

**Comment by bjorn3** [comment] 2020-09-21 08:42
The rust-analyzer extension ships with a grammar that is I believe adapted from the built-in grammar of vscode. I think it only has some tweaks to better make it match what semantic highlighting would output. (#4397) I am not sure if semantic highlighting enhances or replaces the output of the vscode grammar.

**Comment by matthewess** [comment] 2020-09-30 14:37
Hi all! I'm not sure if this problem is necessarily caused by rust-analyzer, but it seems like maybe rust-analyzer could fix it? VS Code ships with a rust grammar that is pulled from atom which incorrectly excludes raw string literals from attributes. I have opened a [PR here](https://github.com/zargony/atom-language-rust/pull/154), but as far as I can tell it hasn't been noticed or picked up. I'm using a local version of this change to make my own syntax highlighting work properly. Perhaps this could be implemented in rust-analyzer with semantic highlighting?

**Comment by brendanzab** [comment] 2020-09-30 14:40
Yeah, seems like the project is looking for maintainers? zargony/atom-language-rust#144

**Comment by matklad** [comment] 2020-10-15 11:02
@dustypomerleau is this fixed by the new grammar?

**Comment by dustypomerleau** [comment] 2020-10-15 11:38
@matklad Nearly. Cases 2 and 3 are ok:

<img width="757" alt="Screen Shot 2020-10-15 at 22 24 16" src="https://user-images.githubusercontent.com/6304651/96117511-ee433f80-0f35-11eb-8903-1c253e957463.png">

Case 1 still needs a little work:

<img width="750" alt="Screen Shot 2020-10-15 at 22 25 56" src="https://user-images.githubusercontent.com/6304651/96117568-031fd300-0f36-11eb-8258-894f66598f6b.png">

The way that strings and chars are included in attributes is allowing them to gobble up the closing `]` of the attribute itself. I will have a look.

**Closed** 2020-10-17 22:45 UTC
Labels: E-unknown, S-actionable
