### ISSUE TITLE
Rust analyzer shows {uknown} type for Vec<somemodule::StructName>

### ISSUE THREAD

**Issue by nokola** [rust-analyzer/rust-analyzer#4160] opened 2020-04-26 16:39 UTC
RA: nightly (I'm sure I saw this on official too) https://github.com/rust-analyzer/rust-analyzer/commit/fe99a29ad1226dd3f6801ea4bdb575506324be07
Rust: 1.43
Windows 10, VS Code 1.44.2

**Steps to reproduce:**
1. Create empty Rust app in VS code
2. Paste in main.ts:
```rust
pub struct Renderer {
    uniforms_ok: shader::Uniforms,
    uniforms_vec_issue: Vec<shader::Uniforms>,
}
impl Renderer {
    pub fn flush(&mut self) {
        let uniforms_ok = &mut self.uniforms_ok; // OK
        let uniforms_vec_issue = &mut self.uniforms_vec_issue[0]; // FAIL - type shows as "unknown"
        // uniforms_vec_issue. // error, uncomment to see no intellisense for "uniforms_vec_issue." since it's considered of type unknown
    }
}

mod shader {
    pub struct Uniforms {
        pub some_int: u32,
    }
}

fn main() {
    println!("Hello, world!");
}
```

**Expected:**
`uniforms_vec_issue` resolves as `&mut Uniforms`

**Actual:**
`uniforms_vec_issue` resolves as `&mut {unknown}`

![image](https://user-images.githubusercontent.com/6869225/80313742-d61e0f00-87a1-11ea-86bb-c8cdc7c59949.png)

**Comment by flodiebold** [comment] 2020-04-27 18:19
Duplicate of #2534

**Closed by flodiebold** 2020-04-27 18:19 UTC
Labels: A-ty

**Comment by flodiebold** [comment] 2020-04-27 18:20
I.e. I think it would get inferred correctly if you use `0usize` instead of `0`.

**Comment by nokola** [comment] 2020-04-28 05:11
Yes, 0usize fixes the issue! thanks for the pointer
![image](https://user-images.githubusercontent.com/6869225/80449425-fd74f900-88d3-11ea-8ecf-2596e26ed3ff.png)
