### ISSUE TITLE
`use` statements in blocks are not used to inform autocompletion or type inference

### ISSUE THREAD

**Issue by zrneely** [rust-analyzer/rust-analyzer#5335] opened 2020-07-12 20:10 UTC
I noticed that `use` statements that occur inside blocks are not being used to inform autocompletion or type inference. For example, this doesn't give completions or display types on `file.` or `File::`:

```rust
fn main() {
    let result = {
        use std::{fs::File, io::Read};

        let mut file = File::open("test.txt").unwrap();
        let mut buf = [0; 16];
        file.read_exact(&mut buf[..]).unwrap();
        buf
    };
}
```

![image](https://user-images.githubusercontent.com/5863146/87255604-14da7180-c441-11ea-98b9-d21a72a7c70c.png)

Whereas this does:

```rust
use std::{fs::File, io::Read};

fn main() {
    let result = {
        let mut file = File::open("test.txt").unwrap();
        let mut buf = [0; 16];
        file.read_exact(&mut buf[..]).unwrap();
        buf
    };
}
```

![image](https://user-images.githubusercontent.com/5863146/87255598-08561900-c441-11ea-98e7-f0c0873012d5.png)

I noticed this while using the rust-analyzer plugin for VS Code, version 0.2.232. Apologies if this is a duplicate issue or isn't sufficiently descriptive. I'm a happy user of rust-analyzer, but I don't have much knowledge about commonly used terminology so I may have missed something while searching the issue tracker.

**Comment by flodiebold** [comment] 2020-07-12 20:22
Duplicate of #1165.

**Closed by flodiebold** 2020-07-12 20:22 UTC
