### ISSUE TITLE
rust-analyzer holds file locks on Windows

### ISSUE THREAD

**Issue by brennie** [rust-analyzer/rust-analyzer#4626] opened 2020-05-26 19:54 UTC
I'm repeatedly running into an issue on Windows using rust-analzyer with VSCode. If I attempt to `git checkout` or `git rebase` and git needs to remove a directory (for eg a module), the git operation will fail due to not having permissions to access the file in question. This is very frustrating and means I need to close VSCode (and then sometimes kill `rust-analayzer-windows.exe` due to #4168) to run git operations.

**Comment by eminence** [comment] 2020-05-27 02:47
I've not been able to reproduce this.   Can you provide some more info about your system (version of Windows, file system you're using, are you using git from the command line, or using VS Code, or some VS Code plugin, what's the exact error that you receive).

**Comment by kjeremy** [comment] 2020-05-27 13:03
Which version of rust-analyzer are you running? I can't reproduce this.

**Comment by brennie** [comment] 2020-05-27 16:09
I'm using git on the commandline and VSCode for editing.

STR:
1. `cargo init --bin .`
2. `git add .; git commit -m "initial commit"`
3. Open directory in vscode with the rust-analyzer extension
4. Add `src/foo.rs` with `mod bar`.
    Add `src/foo/bar.rs`.
    Add `mod foo` to `main.rs`
5. `git add .; git commit -m "Second commit"`
6. `git checkout HEAD^`
7. `git checkout master`

Output (from 6 onwards)
```
Barret@THEOBROMA ~\W\temp [master] $ git checkout HEAD^
Note: switching to 'HEAD^'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7d8297d Initial commit
> git checkout master
error: cannot stat 'src/foo': Permission denied
```

**Comment by brennie** [comment] 2020-05-27 16:10
The following error also shows up in VSCode:
![image](https://user-images.githubusercontent.com/156585/83045045-10820280-a013-11ea-93ad-75f50dedb619.png)

**Comment by matklad** [comment] 2020-07-11 23:56
I haven't seen this reported by anyone else, so I would hazard the guess that it's some peculiarity of the setup. 

The error from VS COde seems suspicious -- I don't think we can ever send such message. Are you sure that it's rust-analyzer and not something else? We generally don't use file system in any interesting way.

**Comment by kjeremy** [comment] 2020-07-12 00:02
I got a big fat warning message today that git 2.25 (?) has problems with vscode. Maybe that's what you hit? I think we can close this.

**Closed** 2020-07-12 00:03 UTC

**Comment by brennie** [comment] 2020-07-15 19:47
I have switched to the rust-analyzer extension (from the rust extension using rust-analyzer) and I havent hit this at all lately.
