### ISSUE TITLE
rust-analyzer waiting for code actions although none specified for it

### ISSUE THREAD

**Issue by jost-s** [rust-analyzer/rust-analyzer#11430] opened 2022-02-07 10:29 UTC
Using rust-analyzer with VSCode, it's waiting for code actions every time I save a Rust file and blocks cargo from building. It happens because I've configured "format on save" as code action for ESLint.

Searching for the problem on the VSCode repo, the answer is that the rust-analyzer shouldn't be waiting for code actions, because none have been specified for it. (https://github.com/microsoft/vscode/issues/89745)

In the rust-analyzer forum I saw that someone raised this issue as well but didn't get an answer: https://users.rust-lang.org/t/vs-code-extension-stays-forever-in-saving-file-rs-getting-code-actions-from-rust-anlyzer/51920

**STR:**
* install rust-analyzer for VSCode
* install ESLint extension for VSCode
* add eslint code action to `settings.json`:
```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
},
```
* set up new Rust project `cargo init`
* edit `main.rs` and save

**Expected**:
Rust file is saved instantly without awaiting code actions.

**Actual**:
```sh
Blocking waiting for file lock on build directory
```
<img width="466" alt="image" src="https://user-images.githubusercontent.com/28270981/152768937-914a4ece-7c8a-46cc-92ab-a7304f02dc4d.png">

**rust-analyzer version**: v0.2.932

**rustc version**: rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by DanielHZhang** [comment] 2022-04-07 04:07
There seems to be a regression in the pre-release extension between versions `0.3.1005` and `0.3.1004` that causes this issue to reoccur (hanging when saving files while `"source.fixAll.eslint"` is set).

**Comment by lnicola** [comment] 2022-04-09 05:28
Duplicate of #11933.

**Closed** 2022-04-09 05:29 UTC
Labels: A-vscode, C-support
