### ISSUE TITLE
rustanalyzer crashes in vscode

### ISSUE THREAD

**Issue by Yatekii** [rust-analyzer/rust-analyzer#2748] opened 2020-01-04 21:43 UTC
Hi!

I am getting this stacktrace:

```
thread '<unnamed>' panicked at 'clear_strands_after_cycle invoked on strand in table without a selected subgoal: Canonical { value: ExClause { subst: [?0 := StructId(782)<^0, ^1>, ?1 := ^2], ambiguous: false, constraints: [], subgoals: [Positive(InEnvironment { environment: Env([]), goal: ProjectionEq((AssocTypeId(5896))<^0, {error}> = ^2) }), Positive(InEnvironment { environment: Env([]), goal: Implemented(^0: TraitId(443)<{error}>) })], answer_time: TimeStamp { clock: 0 }, floundered_subgoals: [] }, binders: [Ty(U0), Ty(U0), Ty(U0)] }', /home/yatekii/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/logic.rs:835:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  14: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  15: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  16: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  17: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  18: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  19: chalk_engine::forest::Forest<C>::solve
  20: ra_hir_ty::traits::trait_solve_query
  21: salsa::runtime::Runtime<DB>::execute_query_implementation
  22: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<DB,Q,MP>::read
  24: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  25: salsa::QueryTable<DB,Q>::get
  26: ra_hir_ty::infer::InferenceContext<D>::resolve_ty_as_possible
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::check_call_arguments
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  30: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  31: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  32: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  33: ra_hir_ty::infer::infer_query
  34: salsa::runtime::Runtime<DB>::execute_query_implementation
  35: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  36: salsa::derived::slot::Slot<DB,Q,MP>::read
  37: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  38: ra_hir::code_model::Function::diagnostics
  39: ra_hir::code_model::Module::diagnostics
  40: ra_ide::diagnostics::diagnostics
  41: std::panicking::try::do_call
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  43: ra_db::CheckCanceled::catch_canceled
  44: ra_ide::Analysis::diagnostics
  45: ra_lsp_server::main_loop::handlers::publish_diagnostics
  46: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Canceled
[Info  - 10:40:05 PM] Connection to server got closed. Server will restart.
[Error - 10:40:05 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
thread 'main' panicked at 'clear_strands_after_cycle invoked on strand in table without a selected subgoal: Canonical { value: ExClause { subst: [?0 := StructId(573)<^0, ^1>, ?1 := ^2], ambiguous: false, constraints: [], subgoals: [Positive(InEnvironment { environment: Env([]), goal: ProjectionEq((AssocTypeId(10874))<^0, {error}> = ^2) }), Positive(InEnvironment { environment: Env([]), goal: Implemented(^0: TraitId(338)<{error}>) })], answer_time: TimeStamp { clock: 0 }, floundered_subgoals: [] }, binders: [Ty(U0), Ty(U0), Ty(U0)] }', /home/yatekii/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/logic.rs:835:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  14: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  15: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  16: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  17: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  18: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  19: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  20: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  21: chalk_engine::forest::Forest<C>::solve
  22: ra_hir_ty::traits::trait_solve_query
  23: salsa::runtime::Runtime<DB>::execute_query_implementation
  24: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  25: salsa::derived::slot::Slot<DB,Q,MP>::read
  26: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  27: salsa::QueryTable<DB,Q>::get
  28: ra_hir_ty::infer::InferenceContext<D>::resolve_ty_as_possible
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::check_call_arguments
  30: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  31: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  32: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  33: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  34: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  35: ra_hir_ty::infer::infer_query
  36: salsa::runtime::Runtime<DB>::execute_query_implementation
  37: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<DB,Q,MP>::read
  39: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  40: ra_hir::code_model::Function::diagnostics
  41: ra_hir::code_model::Module::diagnostics
  42: ra_ide::diagnostics::diagnostics
  43: std::panicking::try::do_call
  44: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  45: ra_db::CheckCanceled::catch_canceled
  46: ra_ide::Analysis::diagnostics
  47: ra_lsp_server::main_loop::handlers::publish_diagnostics
  48: ra_lsp_server::main_loop::loop_turn
  49: ra_lsp_server::main_loop::main_loop
  50: ra_lsp_server::main
  51: std::rt::lang_start::{{closure}}
  52: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  53: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  54: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  55: std::panicking::try
             at src/libstd/panicking.rs:265
  56: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  57: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  58: main
  59: __libc_start_main
  60: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
[Info  - 10:40:30 PM] Connection to server got closed. Server will restart.
[Error - 10:40:30 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
thread 'main' panicked at 'clear_strands_after_cycle invoked on strand in table without a selected subgoal: Canonical { value: ExClause { subst: [?0 := StructId(147)<^0, ^1>, ?1 := ^2], ambiguous: false, constraints: [], subgoals: [Positive(InEnvironment { environment: Env([]), goal: ProjectionEq((AssocTypeId(8287))<^0, {error}> = ^2) }), Positive(InEnvironment { environment: Env([]), goal: Implemented(^0: TraitId(432)<{error}>) })], answer_time: TimeStamp { clock: 0 }, floundered_subgoals: [] }, binders: [Ty(U0), Ty(U0), Ty(U0)] }', /home/yatekii/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/logic.rs:835:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  14: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  15: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::clear_strands_after_cycle
  16: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  17: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  18: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  19: chalk_engine::forest::Forest<C>::solve
  20: ra_hir_ty::traits::trait_solve_query
  21: salsa::runtime::Runtime<DB>::execute_query_implementation
  22: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<DB,Q,MP>::read
  24: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  25: salsa::QueryTable<DB,Q>::get
  26: ra_hir_ty::infer::InferenceContext<D>::resolve_ty_as_possible
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::check_call_arguments
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  30: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  31: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  32: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  33: ra_hir_ty::infer::infer_query
  34: salsa::runtime::Runtime<DB>::execute_query_implementation
  35: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  36: salsa::derived::slot::Slot<DB,Q,MP>::read
  37: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  38: ra_hir::code_model::Function::diagnostics
  39: ra_hir::code_model::Module::diagnostics
  40: ra_ide::diagnostics::diagnostics
  41: std::panicking::try::do_call
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  43: ra_db::CheckCanceled::catch_canceled
  44: ra_ide::Analysis::diagnostics
  45: ra_lsp_server::main_loop::handlers::publish_diagnostics
  46: ra_lsp_server::main_loop::loop_turn
  47: ra_lsp_server::main_loop::main_loop
  48: ra_lsp_server::main
  49: std::rt::lang_start::{{closure}}
  50: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  51: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  52: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  53: std::panicking::try
             at src/libstd/panicking.rs:265
  54: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  55: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  56: main
  57: __libc_start_main
  58: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:[Info  - 10:40:56 PM] Connection to server got closed. Server will restart.
[Error - 10:40:56 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/yatekii/.vscode/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)

```

when running it with the vscode plugin.

My project is on current nightly and runs on diesel & rocket, if this helps any :)

Best,
Yatekii

**Comment by matklad** [comment] 2020-01-06 14:17
Another upstream chalk issue, not sure if a duplicate of some existing one, or something new.

**Comment by Yatekii** [comment] 2020-01-06 15:15
Hey! Sorry if this is a dupllicate, but I didn't feel comfortable enough with the rust-analyzer state to determine this on my own, so I just filed a new issue to be sure :)

**Comment by matklad** [comment] 2020-01-06 15:16
@Yatekii sorry, I was confusing! Reporting issue is always good, especially if you can get a stacktrace! My comment was more a note to myself :0

**Comment by Yatekii** [comment] 2020-01-06 15:18
Heh, no worries ;) Great work, I really like ra so far :)

**Comment by matklad** [comment] 2020-01-06 16:07
So, this looks like a new issue. The next steps here are:

* get a reprodution in a form in a crate with cargo.toml and deps
* get a minimal reproduction as a crate which only depends on std/core
* get a minimal reproduction as a rust-analyzer test case

An example of this minimization process is https://github.com/rust-lang/chalk/issues/301

**Comment by lnicola** [comment] 2020-12-21 11:35
@Yatekii are you still seeing this?

**Comment by Yatekii** [comment] 2020-12-21 11:49
I am not aware of having this issue anymore :)

**Closed** 2020-12-21 11:50 UTC
Labels: A-ty, E-unknown, S-actionable
