### ISSUE TITLE
Spurious unresolved-import for items generated by proc-macro attributes

### ISSUE THREAD

**Issue by toasteater** [rust-analyzer/rust-analyzer#7467] opened 2021-01-27 19:39 UTC
rust-analyzer extension version 0.2.465 reports unresolved-import for items generated by proc-macro attributes, even though both `rust-analyzer.cargo.loadOutDirsFromCheck` and `rust-analyzer.procMacro.enable` are enabled. The code compiles without problem.

## Reproduction example

In a `proc-macro` crate using `quote`:

```rust
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream {
    (quote::quote! {
        pub struct GeneratedStruct;
        pub const GENERATED_CONST: i32 = 42;
        pub fn generated_fn() {}
    }).into()
}
```

The consumer crate in the same workspace:

```rust
#[macro_use]
extern crate my_proc_macro;

use bar::{GeneratedStruct, GENERATED_CONST, generated_fn}; // unresolved-import

mod bar {
    #[foo]
    const A: () = (); // Doesn't matter. Just a random item to throw at the macro.
}
```

**Comment by lnicola** [comment] 2021-01-27 19:40
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6029.

**Comment by lnicola** [comment] 2021-01-27 19:41
But anyway, thanks for the issue report, it's lovely ❤️ .

**Closed by lnicola** 2021-01-27 19:40 UTC

**Comment by toasteater** [comment] 2021-01-27 19:48
Sorry for the duplicate. I only searched for unresolved-import and didn't realize that this is actually a more general problem. Thanks for pointing to the existing issue.
