### ISSUE TITLE
Null response on signature help after whitespace

### ISSUE THREAD

**Issue by bstaletic** [rust-analyzer/rust-analyzer#8522] opened 2021-04-14 22:03 UTC
Given

    fn test(_a:i8, _b:i8){}
    fn main() {
        // This works.
        test(<CURSOR>
    }

Requesting `textDocument/signatureHelp` works as expected. However, if a user inserts a space and the client then re-requests `textDocument/signatureHelp`, with the new location, the response is null. I.e.

    fn test(_a:i8, _b:i8){}
    fn main() {
        // Null response
        test( <CURSOR>
    }

Here are the messages exchanged between ycmd and rust-analyzer:

```
2021-04-14 23:35:04,083 - DEBUG - TX: Sending message: b'Content-Length: 1332\r\n\r\n{"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"experimental":{"serverStatusNotification":true,"statusNotification":true},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true}}},"initializationOptions":{},"processId":6540,"rootPath":"/home/bstaletic/work/test/r","rootUri":"file:///home/bstaletic/work/test/r"}}'
2021-04-14 23:35:04,085 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"selectionRangeProvider":true,"hoverProvider":true,"completionProvider":{"triggerCharacters":[":",".","\'"]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite"],"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">"]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"workspace":{"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.rs","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}},"callHierarchyProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","enumMember","typeParameter","function","method","property","macro","variable","parameter","angle","attribute","boolean","brace","bracket","builtinType","characterLiteral","colon","comma","constParameter","dot","escapeSequence","formatSpecifier","generic","label","lifetime","parenthesis","punctuation","selfKeyword","semicolon","typeAlias","union","unresolvedReference"],"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","consuming","unsafe","attribute","trait","callable","intraDocLink"]},"range":true,"full":{"delta":true}},"experimental":{"joinLines":true,"ssr":true,"onEnter":true,"parentModule":true,"runnables":{"kinds":["cargo"]}}},"serverInfo":{"name":"rust-analyzer","version":"2021-04-05"}}}'
2021-04-14 23:35:04,086 - DEBUG - TX: Sending notification: b'Content-Length: 52\r\n\r\n{"jsonrpc":"2.0","method":"initialized","params":{}}'
2021-04-14 23:35:04,086 - DEBUG - TX: Sending notification: b'Content-Length: 86\r\n\r\n{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}'
2021-04-14 23:35:04,087 - DEBUG - TX: Sending notification: b'Content-Length: 226\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"rust","text":"fn test(_a:i8, _b:i8){}\\nfn main() {\\n    test(\\n}\\n","uri":"file:///home/bstaletic/work/test/r/src/main.rs","version":1}}}'
2021-04-14 23:35:04,093 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":0,"method":"workspace/configuration","params":{"items":[{"section":"rust-analyzer"}]}}'
2021-04-14 23:35:04,094 - DEBUG - TX: Sending response: b'Content-Length: 40\r\n\r\n{"id":0,"jsonrpc":"2.0","result":[null]}'
2021-04-14 23:35:04,197 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":1,"method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/home/bstaletic/work/test/r/**/*.rs"}]}}]}}'
2021-04-14 23:35:04,200 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":1,"jsonrpc":"2.0","result":null}'
2021-04-14 23:35:04,227 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"rust-analyzer/status","params":{"status":"readyPartial"}}'
2021-04-14 23:35:04,256 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":2,"method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/home/bstaletic/work/test/r/**/*.rs"}]}}]}}'
2021-04-14 23:35:04,258 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":2,"jsonrpc":"2.0","result":null}'
2021-04-14 23:35:04,264 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"rust-analyzer/status","params":{"status":"loading"}}'
2021-04-14 23:35:04,271 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"rust-analyzer/status","params":{"status":"ready"}}'
2021-04-14 23:35:04,353 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}},"severity":1,"source":"rustc","message":"mismatched closing delimiter: `}`\\nmismatched closing delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}}},"message":"closing delimiter possibly meant for this"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}}},"message":"unclosed delimiter"}]},{"range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}},"severity":4,"source":"rustc","message":"closing delimiter possibly meant for this","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]},{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}},"severity":4,"source":"rustc","message":"unclosed delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]}],"version":1}}'
2021-04-14 23:35:04,366 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}},"severity":1,"source":"rustc","message":"mismatched closing delimiter: `}`\\nmismatched closing delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}}},"message":"closing delimiter possibly meant for this"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}}},"message":"unclosed delimiter"}]},{"range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}},"severity":4,"source":"rustc","message":"closing delimiter possibly meant for this","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]},{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}},"severity":4,"source":"rustc","message":"unclosed delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]},{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}},"severity":1,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"this function takes 2 arguments but 0 arguments were supplied\\nexpected 2 arguments","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":8},"end":{"line":3,"character":1}}},"message":"supplied 0 arguments"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":0,"character":3},"end":{"line":0,"character":7}}},"message":"function defined here"}]},{"range":{"start":{"line":2,"character":8},"end":{"line":3,"character":1}},"severity":4,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"supplied 0 arguments","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}}},"message":"original diagnostic"}]},{"range":{"start":{"line":0,"character":3},"end":{"line":0,"character":7}},"severity":4,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"function defined here","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}}},"message":"original diagnostic"}]}],"version":1}}'
2021-04-14 23:35:08,356 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[{"range":{"start":{"line":2,"character":9},"end":{"line":2,"character":9}},"severity":1,"source":"rust-analyzer","message":"Syntax Error: expected expression"},{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":9}},"severity":1,"code":"mismatched-arg-count","codeDescription":{"href":"https://rust-analyzer.github.io/manual.html#mismatched-arg-count"},"source":"rust-analyzer","message":"Expected 2 arguments, found 0"},{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}},"severity":1,"source":"rustc","message":"mismatched closing delimiter: `}`\\nmismatched closing delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}}},"message":"closing delimiter possibly meant for this"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}}},"message":"unclosed delimiter"}]},{"range":{"start":{"line":1,"character":10},"end":{"line":1,"character":11}},"severity":4,"source":"rustc","message":"closing delimiter possibly meant for this","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]},{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":9}},"severity":4,"source":"rustc","message":"unclosed delimiter","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":3,"character":0},"end":{"line":3,"character":1}}},"message":"original diagnostic"}]},{"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}},"severity":1,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"this function takes 2 arguments but 0 arguments were supplied\\nexpected 2 arguments","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":8},"end":{"line":3,"character":1}}},"message":"supplied 0 arguments"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":0,"character":3},"end":{"line":0,"character":7}}},"message":"function defined here"}]},{"range":{"start":{"line":2,"character":8},"end":{"line":3,"character":1}},"severity":4,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"supplied 0 arguments","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}}},"message":"original diagnostic"}]},{"range":{"start":{"line":0,"character":3},"end":{"line":0,"character":7}},"severity":4,"code":"E0061","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0061"},"source":"rustc","message":"function defined here","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":8}}},"message":"original diagnostic"}]}],"version":1}}'
2021-04-14 23:35:12,488 - DEBUG - TX: Sending message: b'Content-Length: 181\r\n\r\n{"id":2,"jsonrpc":"2.0","method":"textDocument/signatureHelp","params":{"position":{"character":9,"line":2},"textDocument":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs"}}}'
2021-04-14 23:35:12,489 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":2,"result":{"signatures":[{"label":"fn test(_a: i8, _b: i8)","parameters":[{"label":[8,14]},{"label":[16,22]}],"active_parameter":0}],"activeParameter":0}}'
2021-04-14 23:35:13,625 - DEBUG - TX: Sending notification: b'Content-Length: 230\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"fn test(_a:i8, _b:i8){}\\nfn main() {\\n    test( \\n}\\n"}],"textDocument":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","version":2}}}'
2021-04-14 23:35:13,625 - DEBUG - TX: Sending message: b'Content-Length: 182\r\n\r\n{"id":3,"jsonrpc":"2.0","method":"textDocument/signatureHelp","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs"}}}'
2021-04-14 23:35:13,724 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":3,"result":null}'
```

The last 5 messages should explain the issue. This is a problem, because ycmd treats null results as "close the signature help popup".

Currently using this rust-analyzer (latest from rustup):
```
rust-analyzer --version
rust-analyzer 2021-04-05
```

but I was also able to repro with https://github.com/rust-analyzer/rust-analyzer/commit/10a243ea55565a0dd1de52f8f802c3e3a7bfef54

**Comment by theli-ua** [comment] 2021-04-16 20:28
I can reproduce this in vscode as well

**Comment by theli-ua** [comment] 2021-04-16 20:30
Note, that noobody noticed that is probably because vscode autoadds closing parentheses and it does work correctly in that case

**Comment by Veykril** [comment] 2021-04-16 20:34
I imagine we merely fail a token lookup or similar, as with the space in there the cursor is surrounded by whitespace tokens only. Will take a look.

**Comment by theli-ua** [comment] 2021-04-16 20:42
Even with closing parentheses ra fails with this snippet:
```
fn test(_a:i8, _b:i8) -> u8 {1}
fn main() {
    // Null response
    assert_eq!(1, test(1, <cursor>))
}
```

(tested in vscode)

**Comment by Veykril** [comment] 2021-04-16 20:46
Ye so the problem is that the cursor is on a whitespace token in this case, the whitespace isnt part of the function call expression which causes this to fail.

> 
> 
> Even with closing parentheses ra fails with this snippet:
> 
> ```
> fn test(_a:i8, _b:i8) -> u8 {1}
> fn main() {
>     // Null response
>     assert_eq!(1, test(1, <cursor>))
> }
> ```
> 
> (tested in vscode)

This is a bit suprising that this fails though. Does this happen only with the macro present?

**Comment by theli-ua** [comment] 2021-04-16 20:48
>Does this happen only with the macro present?

It seem to work regardless of spaces with a nested function call instead of macro

**Comment by Veykril** [comment] 2021-04-16 20:53
Okay thats a different issue then, though it should work inside macros 🤔

**Comment by Veykril** [comment] 2021-04-16 21:00
#8546 fixes this issue, it might also actually fix the macro problem though I can't easily check that right now as I don't know what the exact cause is. Tomorrow's nightly will tell.

**Closed** 2021-04-16 21:08 UTC

**Comment by bstaletic** [comment] 2021-04-17 06:22
That was quick. Thanks!
