### ISSUE TITLE
RA shows unused attribute warning for all #[inline] annotations

### ISSUE THREAD

**Issue by Robbepop** [rust-analyzer/rust-analyzer#3345] opened 2020-02-27 12:01 UTC
I think this is a bug in RA since `rustc` doesn't have any problems with the same attributes.
![2020-02-27-125958_1110x298_scrot](https://user-images.githubusercontent.com/8193155/75443217-38ed5880-5961-11ea-8832-7efa1e599034.png)

**Comment by bjorn3** [comment] 2020-02-27 12:14
According to the screenshot, the warning does come from rustc. Can you give some more context about what code gives the warning?

**Comment by Robbepop** [comment] 2020-02-27 12:34
I re-checked and `rustc` (stable, beta and nightly) really doesn't result in warnings.
However, for the projects I have checked (several) I receive those warnings that you can see.
You can test that for example with one of the smaller projects.
For example this is the line in the screenshot:
https://github.com/Robbepop/string-interner/blob/master/src/lib.rs#L210

**Comment by edwin0cheng** [comment] 2020-02-28 10:29
@Robbepop I just tested the `string-interner` repository you mentioned, but I can't reproduce it. (No errors or warnings). Do you enable any feature flags or something special (e.g. cargo clippy? rust version etc..)

**Comment by phil-opp** [comment] 2020-02-28 10:36
I also encountered this issue. For me, the issue occurs for https://github.com/rust-osdev/x86_64, but only when I change the "Rust-analyzer > Cargo-watch: Command" from `check` to `clippy`.

**Comment by Robbepop** [comment] 2020-02-28 16:56
> 
> 
> I also encountered this issue. For me, the issue occurs for https://github.com/rust-osdev/x86_64, but only when I change the "Rust-analyzer > Cargo-watch: Command" from `check` to `clippy`.

In my case from what I can see this setting is still `check`.

**Comment by lnicola** [comment] 2021-01-25 18:15
@Robbepop does this still happen?

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it).

**Comment by Robbepop** [comment] 2021-01-25 18:24
Hard to redo the original checks since the repository I linked to has changed quite significantly.
However, I cannot remember this bug having appeared so I guess we are good to close this issue. ;)

**Closed** 2021-01-25 20:28 UTC
Labels: S-actionable
