### ISSUE TITLE
Can't resolve type if the type is imported in the same function:

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#4719] opened 2020-06-02 22:24 UTC
**How to reproduce:**

```rust
fn _foo() {
    use std::borrow::Cow;
    let _ = Cow::Borrowed("?");
}
```

Move your cursor over `Cow::Borrowed`. The tooltip just says `{unknown}`. The same applies to nested functions, e.g.

```rust
fn _foo() {
    use std::borrow::Cow;

    fn _bar() {
        let _ = Cow::Borrowed("?");
    }
}
```

In `impl` blocks within a function I got no type information _at all_, which is a separate issue.

**Comment by bjorn3** [comment] 2020-06-02 22:30
Duplicate of #1165.

**Closed by bjorn3** 2020-06-02 22:30 UTC
