### ISSUE TITLE
Support Different Vscode Versions

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [rust-analyzer/rust-analyzer#1410] opened 2019-06-16 05:47 UTC
Without looking to through your code I'm thinking for installing thee vscode extensions it only looks for binary `code`. Void Linux repos only contains vscode binary `code-oss` (I believe if you compile it yourself that this is the name also) and there is a growing number of `vscodium` users as well.

**Comment by DJMcNab** [comment] 2019-06-16 07:46
Duplicate of #1323. You can use the workarounds discussed there.

**Comment by matklad** [comment] 2019-06-16 08:09
yeah, if the binary is not named `code`, one should follow the manual installation instructions from the docs:

https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/README.md#vs-code

**Closed by matklad** 2019-06-16 08:09 UTC
