### ISSUE TITLE
Cannot activate rust-analyzer: bootstrap error.

### ISSUE THREAD

**Issue by miyaasa** [rust-analyzer/rust-analyzer#8960] opened 2021-05-24 09:02 UTC
When I open any workspace of Rust with VSCode, this error occurs.

> INFO [2021/5/24 17:57:39]: Extension version: 0.2.610
INFO [2021/5/24 17:57:39]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: false,
    maxLength: 25,
    parameterHints: false,
    typeHints: true
  },
  updates: { channel: 'stable', askBeforeDownload: true },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  files: { watcher: 'client', excludeDirs: [] },
  highlighting: { strings: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    run: true,
    linksInHover: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: { extraArgs: [], overrideCommand: null },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [2021/5/24 17:57:39]: PersistentState: {
  lastCheck: 1618763542243,
  nightlyReleaseId: 41596390,
  serverVersion: '0.2.599'
}
ERROR [2021/5/24 17:57:40]: Bootstrap error [Error: ENOENT: no such file or directory, mkdir 'C:\C:\Users\Miya\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\C:\\Users\\Miya\\AppData\\Roaming\\Code\\User\\globalStorage\\matklad.rust-analyzer'
}

**Comment by lnicola** [comment] 2021-05-24 09:04
Duplicate of #8956.

**Closed by lnicola** 2021-05-24 09:04 UTC
