### ISSUE TITLE
Improve "Go to Definition" for code included with include! (e.g. bindgen bindings)

### ISSUE THREAD

**Issue by jschwe** [rust-analyzer/rust-analyzer#11851] opened 2022-03-30 13:17 UTC
Currently "Go to definition" on a symbol / function generated by bindgen brings you to the `include!(...)` macro, where the bindings were included. I think it would be a great addition if rust-analyzer could also support directly opening the bindings rust file and showing the symbol there. 
Typically the bindings.rs file would be in `OUT_DIR`, e.g. for `include!(concat!(env!("OUT_DIR"), "/bindings.rs"))`, but since rust_analyzer already seems to be parsing the bindings.rs file to some extent, maybe this is simple to implement?

**Comment by flodiebold** [comment] 2022-03-30 13:40
Duplicate of #3767.

**Closed by flodiebold** 2022-03-30 13:40 UTC
