### ISSUE TITLE
Macros not resolving

### ISSUE THREAD

**Issue by MaxBeaud** [rust-analyzer/rust-analyzer#6847] opened 2020-12-12 20:13 UTC
At the beginning of my program: use statement and start of the main function, rust-analyzer tells me it has failed to import certain macros. However this is purely rust-analyzer as the program can compile with no problem and the compiler throws no error.

![Screenshot 2020-12-12 151040](https://user-images.githubusercontent.com/45009344/101993933-6440fa00-3c8c-11eb-9db8-c137361bf738.png)
![Screenshot 2020-12-12 151056](https://user-images.githubusercontent.com/45009344/101993936-65722700-3c8c-11eb-8a15-c65422e7acd2.png)
![Screenshot 2020-12-12 151312](https://user-images.githubusercontent.com/45009344/101993955-8e92b780-3c8c-11eb-968a-f4e5d0a6859d.png)

**Comment by erichgess** [comment] 2020-12-13 00:13
I'm having the same issue, but enabling those two features did not resolve the errors.

**Comment by flodiebold** [comment] 2020-12-13 12:09
This is probably a duplicate of #6716. It should be fixed on nightly, or with the release tomorrow.

**Comment by erichgess** [comment] 2020-12-13 14:13
I updated my VSCode settings to use nightly (VSCode now shows the version as `rust-analyzer version: nightly (4998807)`), but I still get the error.

**Comment by AngelOfSol** [comment] 2020-12-13 15:20
I tried updating to nightly, because I have a similar issue, but some macro imports are still broken for me:
![image](https://user-images.githubusercontent.com/5393082/102016004-bc2f3d80-3d2c-11eb-80d8-353f76b73deb.png)

RA tends to highlight them only when a file that has the errors in question gets opened, and it only seems to be broken for one package (in my case).

**Comment by flodiebold** [comment] 2020-12-13 16:30
@AngelOfSol do you have the settings mentioned above turned on?

@erichgess Can you provide more information about *which* errors you're still seeing? These errors aren't all the same bug.

**Comment by AngelOfSol** [comment] 2020-12-13 18:47
@fannheyward Yes I do, this is my settings list:
```JSON
{
    "editor.formatOnSave": true,
    "workbench.colorTheme": "Monokai Pro (Filter Spectrum)",
    "vim.useCtrlKeys": false,
    "window.zoomLevel": 0,
    "rust-analyzer.excludeGlobs": [
        "resources/*",
    ],
    "rust-analyzer.checkOnSave.overrideCommand": null,
    "rust-analyzer.files.watcher": "notify",
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.files.exclude": [
        "resources/*"
    ],
    "editor.fontSize": 18,
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.cargo.allFeatures": true,
    "rust-analyzer.updates.channel": "nightly"
}

**Comment by rimutaka** [comment] 2020-12-15 01:16
**Version**: v0.3.415-nightly

Doesn't seem to resolve any macro's for me at all.
```rust
use tracing::{info, trace};
info!(
            "Loading config file for file_types from {} and munchers from {}",
            file_type_dir, muncher_dir
        );
```
error: `could not resolve macro 'callsite'`

![image](https://user-images.githubusercontent.com/5926028/102155248-0d336300-3ee0-11eb-90a9-526393cfb138.png)

**Comment by flodiebold** [comment] 2020-12-15 12:52
@rimutaka I can't reproduce this. Note that function-local imports don't work, but if the `use` is outside the function, the `tracing::info` macro works for me. Please open a separate issue with a minimal reproduction if you're still experiencing this on current nightly.

@MaxBeaud Is this still happening for you on the current version?

**Comment by AngelOfSol** [comment] 2020-12-15 16:14
Here's a git repo that is a minimal repro of my issue: https://github.com/AngelOfSol/strum-macro-not-resolve

**Comment by yaymukund** [comment] 2020-12-16 15:52
I experience the same behavior when using `crossterm`'s `queue!()` macro. Rust analyzer complains that `write_ansi_code` isn't found. Here's a minimal repro which also includes a png of my error in vim:

https://git.sr.ht/~yaymukund/crossterm-macro-not-resolve

**Comment by flodiebold** [comment] 2020-12-16 16:07
@AngelOfSol This might be caused by the way the strum proc macro is defined, since we [don't support cfg_attr](https://github.com/rust-analyzer/rust-analyzer/issues/5548) yet. Could you open a separate issue for your problem?

@yaymukund The `queue!` macro expands to a local `use $crate::{write_ansi_code, Command}` internally, and we don't support local imports yet (#1165).

**Comment by wpbrown** [comment] 2020-12-17 02:33
I've been using nightly for months and seeing the issues from cfg_attr on strum, but as of latest nightly now also seeing no macros working even `slog::info`, similiar to @rimutaka  above.

**Comment by flodiebold** [comment] 2020-12-17 10:20
@wpbrown can you please provide a minimal reproduction, in a separate issue?

**Comment by flodiebold** [comment] 2020-12-17 10:24
I'm going to close this issue because I believe the original problem was fixed, and this is becoming a general dumping ground for macro error false positives.

**Closed by flodiebold** 2020-12-17 10:24 UTC
Labels: A-macro, S-unactionable

**Comment by MaxBeaud** [comment] 2020-12-19 04:00
@flodiebold In my case, I just downloaded the rust-analyzer update on vsCode and my using statement errors are gone. Furthermore the update for some reason caught some oddities it didn't before and has fixed some UB I could not for the life of me find out what it's cause was. I realize this issue is closed however, thank you.
