### ISSUE TITLE
Show warning for files which are not linked to any module

### ISSUE THREAD

**Issue by jgarvin** [rust-analyzer/rust-analyzer#5181] opened 2020-07-01 18:21 UTC
I upgraded emacs `lsp-mode` and now I can't lookup definitions of standard library types. I've wiped all my emacs installed packages and the problem persists, which makes me wonder if rust-analyzer is storing state anywhere I might need to clean. Restarting analyzer hasn't fixed it either. Does analyzer have a config file? Does it have anything it caches to disk? Is the whole world rescanned from scratch every time analyzer restarts? Running the latest release on Linux.

**Comment by lnicola** [comment] 2020-07-01 18:23
There's no persistence and configuration is done via LSP. Can you check that you still have `rust-src` installed?

**Comment by jgarvin** [comment] 2020-07-01 18:26
Yep: `info: component 'rust-src' is up to date`

I noticed just now trying to test it can find `RefCell` and `Rc`, but not `Box` or `Result` or `Option`. Maybe its only prelude types? That it can find some definitions I think means the server binary must be in `PATH`.

**Comment by jgarvin** [comment] 2020-07-01 18:34
I figured it out, I had earlier changed my main.rs to not have `mod foo;` anymore, and I was trying to lookup definitions inside `foo.rs`. Adding `mod foo;` back fixes it. Is this a bug or intended?

**Comment by lnicola** [comment] 2020-07-01 18:37
I think it ignores the file, so I'm surprised that some stuff works. In the future you might get a "You're editing a file outside of the project, did you forget a `mod foo`?", but...

**Comment by jgarvin** [comment] 2020-07-01 18:45
Making a new bar.rs file and later adding a `mod bar;` to another file to import is probably a really common workflow. I think people will be confused if completion doesn't work right away. Maybe it should be inferred to be part of the project by virtue of being in the same workspace?

**Comment by bjorn3** [comment] 2020-07-01 19:46
If you add `mod bar;` first, rust-analyzer will give a quick fix to make `bar.rs`.

**Comment by matklad** [comment] 2020-07-11 11:14
closing as a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/4917

**Closed by matklad** 2020-07-11 11:14 UTC
Labels: E-hard
