### ISSUE TITLE
Panic at 'index out of bounds: the len is 2 but the index is 2'

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-analyzer/rust-analyzer#10179] opened 2021-09-07 21:46 UTC
When editing a pacticular project I keep getting this panic message from RA (b73b32147 2021-09-06 stable, VS Code, Arch Linux). Here is the error output in VS code: [&lt;gist&gt;](https://gist.github.com/WaffleLapkin/ff5acdc7adf6a39fc5828c962962543a).

Repro: 
```bash
; git clone https://github.com/WaffleLapkin/sudoku-solve.git && cd sudoku-solve && git switch --detach d57e314f70b55040698ffb60ed84e47d071c7650
; rust-analyzer --version
rust-analyzer b73b32147 2021-09-06 dev
; rust-analyzer analysis-stats .
Database loaded:     965.22ms, 68minstr (metadata 640.72ms, 1141kinstr; build 280.63ms, 633kinstr)
  crates: 1, mods: 1, decls: 17, fns: 8
Item Collection:     3.20s, 21ginstr
4/8 50% processing: newthread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.70.0/src/lib.rs:2752:10
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by maoe** [comment] 2021-09-08 02:22
I saw a similar issue with our in-house codebase. The error message looked identical apart from the len/index values. FWIW I  was able to work around the issue by downgrading the rust-analyzer vscode extension to v0.2.710. All newer versions seem to suffer from this issue.

**Comment by flodiebold** [comment] 2021-09-08 06:47
Likely a duplicate of #10046

**Comment by lnicola** [comment] 2021-09-10 14:10
Lazy minimization:

```rust
use bitvec::array::BitArray;

fn main() {
    let mut holes = BitArray::default();
    holes.set(0, true);
}
```

**Comment by flodiebold** [comment] 2021-09-10 14:23
Seems like the same case as [mine](https://github.com/rust-analyzer/rust-analyzer/issues/10046#issuecomment-912966855) then.

**Closed** 2021-09-12 09:02 UTC
Labels: A-ty

**Comment by flodiebold** [comment] 2021-09-12 09:14
Should be fixed with the next release.

**Comment by WaffleLapkin** [comment] 2021-09-12 13:10
Thanks!
