### ISSUE TITLE
`Implement Missing Members` doesn't not work correctly with trait defined in `include!("x.rs")`

### ISSUE THREAD

**Issue by zirconium-n** [rust-analyzer/rust-analyzer#10163] opened 2021-09-06 09:09 UTC
I encountered this bug when using grpc with tonic_build. This also occurs on `Expand Macro Recursively` with `serde_closure::Fn!`.

Minimum example:

x.rs
```rust
trait S {
    fn foo() -> i32;
}

```

main.rs
```rust
include!("x.rs");

struct X;
impl S for X {
    fnfoo()->i32 {   // Generated. Spaces are missing
        todo!()
    }
}
```

This bug does not occur if trait is defined in main.rs directly.

**Comment by flodiebold** [comment] 2021-09-06 09:16
Duplicate of #6588

**Closed by flodiebold** 2021-09-06 09:16 UTC
