### ISSUE TITLE
Fix unused import option duplicated

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [rust-analyzer/rust-analyzer#7202] opened 2021-01-07 22:58 UTC
When using the VSCode extension, and adding an unused import, the Quick Fix menu displays two `remove the unused import` options.

Version: v0.2.441

**Comment by flodiebold** [comment] 2021-01-07 23:23
Duplicate of #6851.

**Closed by flodiebold** 2021-01-07 23:23 UTC
