### ISSUE TITLE
Autofill missing structure fields places fields in random places

### ISSUE THREAD

**Issue by StripedMonkey** [rust-analyzer/rust-analyzer#10288] opened 2021-09-19 14:58 UTC
```
RA-Version: rust-analyzer 516eb40ba 2021-09-13 dev
VSCode Ver: v0.2.735
```
I'm not sure the exact reason/conditions but the autofill places the fields inline at the top of the file instead of where it should. 
[example.txt](https://github.com/rust-analyzer/rust-analyzer/files/7192274/example.txt)

This is an example that's not working for me. When you press the button to "fill missing struct fields" I get 
```rust
struct Config {
    server_list: HashMap<u64, S role_id: (), role_requirement: () erver>,
}
```
Up at the top instead of it filling in the correct place. I'm not sure what a smaller example would be, since this is the only instance that I've seen where it doesn't work (it works on filling the "Server" struct) Filling the `Individual` struct places it in the `use serde::{Deserialize, Serialize};` line.

**Comment by Veykril** [comment] 2021-09-19 15:11
I assume you invoked the assist in a macro invocation judging from the example.txt, in which case this is a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4314

**Closed by Veykril** 2021-09-19 15:11 UTC
