### ISSUE TITLE
Unknown type when "use" statement is used

### ISSUE THREAD

**Issue by yay** [rust-analyzer/rust-analyzer#5660] opened 2020-08-03 22:55 UTC
For example (inside a function scope):

![2020-08-03 23 49 13](https://user-images.githubusercontent.com/1799756/89234733-817e0180-d5e4-11ea-9670-2dcb9275a0a4.gif)

**Comment by lnicola** [comment] 2020-08-04 03:28
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1165.

**Closed by lnicola** 2020-08-04 03:28 UTC
