### ISSUE TITLE
'Go to references' doesn't always work

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#6555] opened 2020-11-14 20:13 UTC
Steps to reproduce: Go to https://github.com/rust-lang/rust/blob/98d66340d6e63eda115afc8b0da1d87965881936/src/librustdoc/clean/types.rs#L1528 in VSCode and hit Shift+F12 to go to references.
Expected behavior: Shows a list of usages (at least https://github.com/rust-lang/rust/blob/30e49a9ead550551e879af64ba91a0316da1c422/src/librustdoc/clean/mod.rs#L1907 should show up).
Actual behavior: Hangs forever.

**Comment by bjorn3** [comment] 2020-11-14 20:37
How long did you wait? It took me like 30s before rename definition worked on rustc today. The next times were a lot quicker. If I recall correctly this uses the same information as go to definition and as such should have an equivalent warmup time.

**Comment by jyn514** [comment] 2020-11-14 20:59
I waited 3 minutes just now and it never finished running.

**Comment by jyn514** [comment] 2020-11-14 21:00
It does work for some things, shift+F12 on [`Visibility`](https://github.com/rust-lang/rust/blob/98d66340d6e63eda115afc8b0da1d87965881936/src/librustdoc/clean/types.rs#L1487) works fine.

**Comment by lnicola** [comment] 2020-12-21 07:58
I suppose this is a duplicate of #6568, or the other way around.

**Closed by lnicola** 2020-12-21 07:58 UTC
