### ISSUE TITLE
Not implemented `chalk_solve::clauses::push_auto_trait_impls` causing RA to fail

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#6171] opened 2020-10-08 12:07 UTC
rust-analyzer version: unreleased (e5f252a)

The funny thing about this bug is that it's triggered only in some strange line-dependent context (after line 219 everything from semantic highlighting to completion fails):

![grad-1602158724030](https://user-images.githubusercontent.com/3784017/95456362-6b504100-0999-11eb-8cb0-9e3a6c452765.gif)

```
thread '<unnamed>' panicked at 'not implemented', /home/korvin/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.30.0/src/clauses.rs:60:40
stack backtrace:
   0: std::panicking::begin_panic
   1: chalk_solve::clauses::push_auto_trait_impls
   2: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   3: chalk_solve::clauses::program_clauses_for_goal
   4: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
   5: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   6: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
   7: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
   8: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
   9: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  10: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  11: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  12: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  13: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  14: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  15: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  16: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  17: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  18: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  19: hir_ty::traits::trait_solve_query
  20: salsa::runtime::Runtime::execute_query_implementation
  21: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  22: salsa::derived::slot::Slot<Q,MP>::read
  23: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  24: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  25: <DB as hir_ty::db::HirDatabase>::trait_solve
  26: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  27: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  28: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  29: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  30: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  31: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  32: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  33: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  34: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  35: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  36: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  37: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  38: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  39: hir_ty::infer::infer_query
  40: salsa::runtime::Runtime::execute_query_implementation
  41: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  42: salsa::derived::slot::Slot<Q,MP>::read
  43: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  44: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  45: hir_ty::db::infer_wait
  46: hir::source_analyzer::SourceAnalyzer::new_for_body
  47: hir::semantics::SemanticsImpl::analyze2
  48: hir::semantics::SemanticsImpl::descend_into_macros
  49: ide::hover::hover
  50: std::panicking::try
  51: ide::Analysis::hover
  52: rust_analyzer::handlers::handle_hover
  53: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment] 2020-10-08 12:09
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6134, fixed in the nightly version.

**Closed by lnicola** 2020-10-08 12:09 UTC
Labels: A-ty
