### ISSUE TITLE
Is it possible to add intellisense on toml file?

### ISSUE THREAD

**Issue by dbsxdbsx** [rust-analyzer/rust-analyzer#9705] opened 2021-07-27 02:01 UTC
Currently, the  toml file is treated as a plain text. I hope it could get some highlight on some keywords, also when typing `ctrl+/` in vscode, I hope the line where cursor at could be commented.

**Comment by lnicola** [comment] 2021-07-27 06:35
It's [possible](https://github.com/rust-analyzer/rust-analyzer/issues/3565) and planned, but not being worked on.

In the meanwhile you can try https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml, https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml (it claims to be better, but I don't like the defaults) and https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates.

**Comment by lnicola** [comment] 2021-07-27 06:35
Closing as a duplicate of #3565 to keep things tidy.

**Closed by lnicola** 2021-07-27 06:35 UTC
