### ISSUE TITLE
 if ra-lsp extension is enabled before the vim one, the vim one doesn't work

### ISSUE THREAD

**Issue by guswynn** [rust-analyzer/rust-analyzer#2746] opened 2020-01-04 20:49 UTC
I get "Activating extension 'vscodevim.vim' failed: command 'type' already exists."

This makes it impossible to use both, because I can't control the enable order.
If I enable vim mode, the ra lsp, it works, but then if I restart vscode, it fails with the above message.

see https://github.com/VSCodeVim/Vim/issues/4473

**Comment by bjorn3** [comment] 2020-01-04 20:52
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1831

**Comment by guswynn** [comment] 2020-01-04 20:53
I found that setting rust-analyzer.enableEnhancedTyping to false fixes this. The setting itself says so. Can this be documented more clearly in the install documentation? 

also what does setting this cause me to lose?

**Comment by lnicola** [comment] 2020-01-05 09:11
> I found that setting rust-analyzer.enableEnhancedTyping to false fixes this. The setting itself says so. Can this be documented more clearly in the install documentation?

Can you send a PR to update https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user?

> also what does setting this cause me to lose?

> `rust-analyzer.enableEnhancedTyping`: by default, rust-analyzer intercepts. Enter key to make it easier to continue comments. Note that it may conflict with VIM emulation plugin.

**Closed** 2020-01-06 14:14 UTC
