### ISSUE TITLE
Compiler messages are hard to find in editor hover when documentation is also shown

### ISSUE THREAD

**Issue by rherrmann** [rust-analyzer/rust-analyzer#6525] opened 2020-11-10 21:15 UTC
If multiple diagnostics apply to a cursor position for which a hover tooltip is shown, documentation appears before compiler messages. Not sure how other types of diagnostics (if there are) would mingle in.

To reproduce, hover on a function reference that is also part of a compile error as shown in the screenshot.
<img width="823" alt="Screenshot 2020-11-10 at 21 55 55" src="https://user-images.githubusercontent.com/607182/98733589-0aa19300-23a1-11eb-8fc5-be159cb7bea1.png">

The compiler message is buried at the end of the contents of the editor hover. Is this a known issue that I couldn't find, or would you agree to try to change the order to: compiler messages first, then documentation?

If so, I would volunteer to investigate how to change the order - unless someone who is reading this already knows.

**Comment by bjorn3** [comment] 2020-11-10 22:10
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6070

**Closed by bjorn3** 2020-11-10 22:10 UTC
