### ISSUE TITLE
Misreport of `unresolved import`

### ISSUE THREAD

**Issue by zonyitoo** [rust-analyzer/rust-analyzer#6249] opened 2020-10-16 06:20 UTC
Example code

```rust
use std::os::unix::io::{AsRawFd, RawFd};

fn main() {
    println!("Hello, world!");
}
```

rust-analyzer plugin on vscode reports:

![image](https://user-images.githubusercontent.com/1067951/96219959-7408ce80-0fba-11eb-818f-a7b1aecea9ad.png)

Rust: rustc 1.47.0 (18bf6b4f0 2020-10-07)
OS: x86_64-apple-darwin

rust-analysis is installed by rustup.

**Comment by bjorn3** [comment] 2020-10-16 06:53
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6038

**Closed by bjorn3** 2020-10-16 06:53 UTC
