### ISSUE TITLE
Unknown types in web-sys dependency

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#4150] opened 2020-04-26 05:21 UTC
(I suspect this is a duplicate, but i'm not sure what the root cause is).

I'm trying to use the [web-sys](https://crates.io/crates/web-sys) crate, which is highly generated.

I've enabled both `loadOutDirsFromCheck` and `procMacro.enable`:

<details><summary>.vscode/settings.jon</summary>

```json
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "editor.tokenColorCustomizationsExperimental": {
        "unresolvedReference": "#FF0000"
    }
}
```

</details>

<details><summary>Cargo.toml</summary>

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]
edition = "2018"

[dependencies.web-sys]
version = "0.3"
features = ["Document", "Window"]

```

</details>

Code:

```rust
use web_sys::{Document, Window};

pub fn foo() {
    let win: Window = web_sys::window().unwrap();
    let doc: Document = win.document().unwrap();
}
```
![image](https://user-images.githubusercontent.com/402454/80298125-3a67b100-8757-11ea-8058-d46375aab375.png)

Using RA nightly (fe99a29)

Thanks!

**Comment by flodiebold** [comment] 2020-04-26 09:47
Are you using the weekly build? All these definitions are in `extern "C"` blocks, which we ignored until [a few days ago](https://github.com/rust-analyzer/rust-analyzer/pull/4111). Apart from that, proc macro support is of course still very experimental and web_sys makes very heavy use of proc macros.

**Comment by eminence** [comment] 2020-04-26 15:33
I am using the nightly build (fe99a29).  (Sorry, that was an important detail I should not have omitted)

**Comment by edwin0cheng** [comment] 2020-04-27 05:36
For example, [Here][1] is how `web-sys` implement `Window` type. It seem like there is something we are still not yet implemented in RA :

1. proc-macro for custom-attribues (`#[wasm_bindgen]`), we only support custom-derive now.
2. Extern Type : `extern "C" { pub type Window } 


[1]: https://rustwasm.github.io/wasm-bindgen/api/src/web_sys/features/gen_Window.rs.html#4

**Comment by matklad** [comment] 2020-04-27 13:58
`extern "C` should be handled by https://github.com/rust-analyzer/rust-analyzer/pull/4111. Though, not sure about `extern "C" { pub type Window; }`. Opaque types are unstable?

**Comment by flodiebold** [comment] 2020-04-27 14:08
It probably gets turned into something different by the macro?

**Comment by edwin0cheng** [comment] 2020-04-27 14:13
https://github.com/rust-lang/rust/pull/44295

And we didn't expand it because no custom attr proc-macro support yet. But I doubt if `extern types` are supported in RA, it might be infered properly ?

**Comment by danbrodsky** [comment] 2020-05-28 05:17
Not to hijack but I'm having similar issues with both go-to-definition and completion for the web-sys crate. doing `web_sys::ge[completion here]` correctly shows completions for web-sys functions but doing something like `let canvas = <some web-sys object>; canvas.ge[completion here]` does not. I'm using emacs with lsp and have the following set:
```
        lsp-rust-analyzer-cargo-load-out-dirs-from-check t
        lsp-rust-analyzer-proc-macro-enable t
```

**Comment by crlf0710** [comment] 2020-09-05 02:58
Extern opaque types are supported by chalk now. Hopefully this will help with this issue.

**Comment by eminence** [comment] 2020-09-09 02:05
Cool, that helps a bit!

Using the latest commit (60c8941097f3674ed4b583925603b5ec43833f0c), the `Document` and `Window` types are now resolved, though RA still doesn't know about the methods on them:

![image](https://user-images.githubusercontent.com/402454/92545779-e4d00480-f21e-11ea-8e22-2375435edb4b.png)

**Comment by crlf0710** [comment] 2020-09-16 03:48
I gave adding support for extern opaque types a try in https://github.com/rust-analyzer/rust-analyzer/pull/5993 .

**Comment by crlf0710** [comment] 2020-09-17 07:41
That PR has landed. But that didn't help `web-sys` much. If `web-sys` was using genuine extern opaque type syntax as input to macros (e.g. impl blocks etc) the issue would have been solved. It seems we need to improve proc macro support next. I'll look into what i can do to help.

**Comment by jkelleyrtp** [comment] 2020-11-21 23:41
Is there any movement on this front, or direction contributors could look to have in trying to get this supported? For reference, this the definition of web-sys modules.

```
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = UiEvent , extends = Event , extends = :: js_sys :: Object , js_name = InputEvent , typescript_type = "InputEvent")]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type InputEvent;

    # [wasm_bindgen (structural , method , getter , js_class = "InputEvent" , js_name = isComposing)]
    pub fn is_composing(this: &InputEvent) -> bool;

    #[wasm_bindgen(catch, constructor, js_class = "InputEvent")]
    pub fn new(type_: &str) -> Result<InputEvent, JsValue>;

    #[cfg(feature = "InputEventInit")]
    #[wasm_bindgen(catch, constructor, js_class = "InputEvent")]
    pub fn new_with_event_init_dict(
        type_: &str,
        event_init_dict: &InputEventInit,
    ) -> Result<InputEvent, JsValue>;
}
```

**Comment by lnicola** [comment] 2021-01-22 17:12
Attribute proc macros are tracked in https://github.com/rust-analyzer/rust-analyzer/issues/6029, let's close this for now.

**Closed by lnicola** 2021-01-22 17:12 UTC
Labels: A-macro

**Comment by matklad** [comment] 2021-09-02 12:01
@jonas-schievink do we expand attributes for exten blocks?

```rust
#[wasm_bindgen]
extern "C" {
    pub type Window;
}
```

https://users.rust-lang.org/t/no-autocompletion-with-rust-analyzer-and-wasm-bindgen-web-sys/64301

**Comment by jonas-schievink** [comment] 2021-09-02 12:35
We should

**Comment by jonas-schievink** [comment] 2021-09-02 13:35
Ah, the problem is that turning `rust-analyzer.experimental.procAttrMacros` on will make you run into https://github.com/rust-analyzer/rust-analyzer/issues/8158, and turning it off will also turn it off within `web-sys`, which means that the API doesn't get generated.

**Comment by matklad** [comment] 2021-09-02 13:38
damned if you do, damned if you don't... I am wondering... Can we *just* record two functions with the same name in the def map, one expanded and one not expanded, such that `source2def` returns non-expanded version, but everything which tries to resolve paths gives you the resolved one?

**Comment by matklad** [comment] 2021-09-02 13:42
![image](https://user-images.githubusercontent.com/1711539/131854265-5ab76266-b020-49ff-acef-af83f90e5b85.png)

Something like this I mean.

**Comment by flodiebold** [comment] 2021-09-02 13:44
So `document.x<|>` should work, right?

**Comment by flodiebold** [comment] 2021-09-02 13:57
> damned if you do, damned if you don't... I am wondering... Can we _just_ record two functions with the same name in the def map, one expanded and one not expanded, such that `source2def` returns non-expanded version, but everything which tries to resolve paths gives you the resolved one?

That seems like it would lead to all kinds of other incorrect results?

**Comment by jonas-schievink** [comment] 2021-09-02 14:00
I lied, it's not *just* #8158, but also https://github.com/rust-analyzer/rust-analyzer/issues/9866 that make completion not work here

**Comment by flodiebold** [comment] 2021-09-02 14:05
> I don't think a fully proper fix is possible, as the general case is compile time reflection.

I think a fully proper fix is possible as long as the cursor is in a range of tokens that just get mapped as one continuous range, which I think is what people expect. No-one would reasonably expect completions in `mirror!` ;) IMO we should be able to handle attribute macros the same way we handle macro_rules, i.e. #9866.

**Comment by flodiebold** [comment] 2021-09-02 14:17
> I think 90% proper fix would be to allow proc macro authors to annotate their macros as "this doesn't change item semantics", so that we know that the treatment, suggested above, is fully correct.

I'm not sure we can do this in a useful way? For example, it seems `wasm_bindgen(start)` on a function doesn't change the function, but `wasm_bindgen` on other items has noticeable effects. We could maybe notice that the macro didn't actually change the function though?

**Comment by flodiebold** [comment] 2021-09-02 14:45
... although I guess the problem is that `wasm_bindgen(start)` *doesn't* actually pass through the function when there's a syntax error in it :thinking:

**Comment by jonas-schievink** [comment] 2021-09-02 14:50
Maybe we can just lie to the macro by synthesizing tokens that make the input parse correctly :thinking:

**Comment by flodiebold** [comment] 2021-09-02 14:53
The reason I was wondering is that in this case, the proc macro doesn't need to inspect the body of the function, so it would be fine for it to just parse the header, also for build time and forward compatibility reasons. I don't know if it does that right now though.

> Maybe we can just lie to the macro by synthesizing tokens that make the input parse correctly thinking

Yeah, that's also something I was considering, though it could also lead to other problems. (It's also kind of similar to the hypothetically-expand-with-inserted-token thing we're doing.)

**Comment by flodiebold** [comment] 2022-03-31 13:41
I think the issues discussed here have been mostly fixed.

**Comment by eminence** [comment] 2022-03-31 13:51
I just did a quick test and things seem to be much better!  The `Window` and `Document` types are fully resolved, and tab completion on both the `win` and `doc` variables seems to be working as expected.  This is Very Cool.  Thanks everyone! 🎉
