### ISSUE TITLE
The type hint is different from the actual one

### ISSUE THREAD

**Issue by pf35301** [rust-analyzer/rust-analyzer#7629] opened 2021-02-10 15:57 UTC
```rust:vec3.rs
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vec3<T>
where
    T: Copy + Send + Sync,
{
    pub x: T,
    pub y: T,
    pub z: T,
}

...

impl<T> ops::Sub<Self> for Vec3<T>
where
    T: ops::Sub<Output = T> + Copy + Send + Sync,
{
    type Output = Self;

    fn sub(self, rhs: Self) -> Self {
        Self {
            x: self.x - rhs.x,
            y: self.y - rhs.y,
            z: self.z - rhs.z,
        }
    }
}

...

impl<T> ops::Mul<Self> for Vec3<T>
where
    T: ops::Mul<Output = T> + Copy + Send + Sync,
{
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        Self {
            x: self.x * rhs.x,
            y: self.y * rhs.y,
            z: self.z * rhs.z,
        }
    }
}

...

impl<T> Vec3<T>
where
    T: ops::Add<Output = T> + ops::Mul<Output = T> + Copy + Send + Sync,
{
    pub fn dot(self, rhs: Self) -> T {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
    }

    pub fn sqr_magnitude(self) -> T {
        self.dot(self)
    }
}

...

pub type Vec3f = Vec3<f32>;

```

```rust:lib.rs
    fn refract(in_vec: Vec3f, normal_of_point: Vec3f, in_ior: f32, out_ior: f32) -> Option<Vec3f> {
        let cos1 = in_vec.dot(normal_of_point);
        let in_vech = in_vec - normal_of_point * cos1;

        let out_vech = in_vech * -(in_ior / out_ior);
...
```
![image](https://user-images.githubusercontent.com/18531809/107534290-1ea89b00-6c03-11eb-8d9b-e9cace128237.png)

I expect type hints of `in_vech` and `out_vech` are `Vec3<f32>` but it's `f32`.

**Comment by lnicola** [comment] 2021-02-10 16:00
Probably duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/2454.

**Comment by flodiebold** [comment] 2021-02-10 16:07
Duplicate of #7150. 2454 can probably be closed, actually.

**Closed by flodiebold** 2021-02-10 16:07 UTC
Labels: A-ty, S-unactionable
