### ISSUE TITLE
[feature request] support VSCode's native Testing UI

### ISSUE THREAD

**Issue by findNextStep** [rust-analyzer/rust-analyzer#11600] opened 2022-03-02 03:25 UTC
At present, [VSCode's native Testing UI](https://github.com/microsoft/vscode/issues/107467) has been completed

can we use the testing ui api in ra?

**Comment by flodiebold** [comment] 2022-03-04 13:44
Duplicate of #3601.

**Closed by flodiebold** 2022-03-04 13:44 UTC
