### ISSUE TITLE
Always report error after editing Cargo.toml

### ISSUE THREAD

**Issue by KaoImin** [rust-analyzer/rust-analyzer#8525] opened 2021-04-15 08:16 UTC
First, add a dependency in Cargo.toml. Then:
Error: Progress handler for token rustAnalyzer/indexing already registered

**Comment by SomeoneToIgnore** [comment] 2021-04-15 08:24
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8509

**Closed by SomeoneToIgnore** 2021-04-15 08:24 UTC
