### ISSUE TITLE
rust-analyzer support rustdocflags?

### ISSUE THREAD

**Issue by hamadakafu** [rust-analyzer/rust-analyzer#5469] opened 2020-07-21 07:39 UTC
I'm using rust-analyzer in vs-code.
This is awesome!
I want to use this with `./.cargo/config.toml` like that
```toml
[build]
rustdocflags = [ "--html-in-header", "./.cargo/docs-header.html" ]
```
This html is include nice headers for documents.

Is this supported?

<details>
<summary>Details</summary>

I'm writing mathematical lib and bin, using katex for document.
`./.cargo/docs-header.html` including katex css and javascript link.

write code like that
```rust
/// $a * b + c$
pub struct CalABC<T>{...}
```
then, `cargo doc --open --no-deps` (reference `.cargo/config.toml` -> `./.cargo/docs-header.html`)

<img width="331" alt="スクリーンショット 2020-07-21 16 28 55" src="https://user-images.githubusercontent.com/34128227/88025485-4ce36200-cb6f-11ea-93b1-b1bacba26cd9.png">

I'm expecting vs-code to show like above, but
<img width="322" alt="スクリーンショット 2020-07-21 16 30 55" src="https://user-images.githubusercontent.com/34128227/88025686-9764de80-cb6f-11ea-8096-af10c81fc7a4.png">

I want to see doc formatted by katex...
Is there any idea?

</details>

**Comment by lnicola** [comment] 2020-07-21 07:42
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5321.

**Closed by lnicola** 2020-07-21 07:42 UTC
