### ISSUE TITLE
bug: Can't complete nest use. can't jump to definition

### ISSUE THREAD

**Issue by SolaWing** [rust-analyzer/rust-analyzer#5958] opened 2020-09-07 01:52 UTC
given the follow in file other.rs
```rust
//! other
#[derive(Default, Copy, Clone, Ord, PartialOrd, Eq, PartialEq)]
pub struct Foo {
}

pub trait Tr {
    fn bar(&self);
}

impl Foo {
    fn other() {
        println!("other");
    }
}

impl Tr for Foo {
    fn bar(&self) {
        Self::other();
    }
}

```

and main.rs
```rust
//! main.rs
mod other;
// use other::Tr; // if uncomment this, completion fine, but a.bar() can only jump to trait declaration, can't jump to definition.

/// hello
fn main() {
    use other::Tr;
    let a = other::Foo::default();
    a.bar();
    a.b // <-- no completion tip
}
```

trait is use nest in fn, compile fine but a.b not have completion tip.

if `use other::Tr;` at top, completion fine, but a.bar() can only jump to trait declaration, can't jump to Foo's definition.

**Comment by lnicola** [comment] 2020-09-07 03:58
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1165.

**Closed by lnicola** 2020-09-07 03:58 UTC

**Comment by SolaWing** [comment] 2020-09-07 05:32
@lnicola local import is same as #1165.

another problem, only jump to trait declaration, not Foo's definition, has any solution or relavant issuse?

**Comment by lnicola** [comment] 2020-09-07 05:36
Go to implementation is https://github.com/rust-analyzer/rust-analyzer/issues/4558.
