### ISSUE TITLE
nalgebra unjustified errors for parameter lenghts.

### ISSUE THREAD

**Issue by xero-lib** [rust-analyzer/rust-analyzer#10340] opened 2021-09-24 23:04 UTC
## Errors
![image](https://user-images.githubusercontent.com/54485853/134746790-d63f2d21-03f4-456a-9f2d-57f2ec2014e9.png)
---
## The Vector2 should only have 2 parameters yet for some reason rust analyzer believes it should have 4.
![image](https://user-images.githubusercontent.com/54485853/134746930-e876d30d-5501-41d9-bf73-5f924c850fe1.png)
---
## Autocomplete also suggests many erroneous "new" methods.
![image](https://user-images.githubusercontent.com/54485853/134746959-d23d7564-108a-48c6-b67a-ba6d04897d73.png)

**Comment by xero-lib** [comment] 2021-09-24 23:06
Vector2 should obviously only have one `new` method that takes 2 T parameters.

**Comment by Veykril** [comment] 2021-09-25 00:32
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8654

**Closed by Veykril** 2021-09-25 00:32 UTC
