### ISSUE TITLE
Code is inactive hint on #[cfg(not(test))]

### ISSUE THREAD

**Issue by OleStrohm** [rust-analyzer/rust-analyzer#7529] opened 2021-02-03 04:27 UTC
I have been following the OS tutorial from https://os.phil-opp.com/, and after turning of the standard library and setting up my own panic_handler I ended up with the following code:
```rust
#[cfg(not(test))]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    println!("{}", info);
    loop {}
}

#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    serial_println!("[FAILED]\n");
    serial_println!("Error: {}\n", info);
    exit_qemu(QemuExitCode::Failed);
    loop {}
}
```
the intent is that the first one is active for normal use and the bottom one is only active when running something like `cargo test`. However rust-analyzer is giving me a hint that the first function is inactive code since: `code is inactive due to #[cfg] directives: test is enabled`.

I've checked, and it's definitely running the right panic handler for each version, so I think rust-analyzer is giving me a hint for no reason here.

**Comment by bjorn3** [comment] 2021-02-03 06:03
Rust-analyzer always enables `#[cfg(test)]` and thus disables `#[cfg(not(test))]` to ensure that ide functions work inside tests.

**Comment by lnicola** [comment] 2021-02-03 07:40
Duplicate of #7225 and maybe others.

**Closed by lnicola** 2021-02-03 07:40 UTC
