### ISSUE TITLE
Fail to upgrade language server binary if more than one Rust project is opened on Windows

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#8682] opened 2021-04-28 00:50 UTC
If I open two Rust projects, there will be two running processes of the language server binary. Windows does not allow replacing running process executables, so in order to upgrade the server binary, I have to close all VS Code windows except one.

**Comment by lnicola** [comment] 2021-04-28 08:27
Dupe of #3403 and another one, I think.

**Closed by lnicola** 2021-04-28 08:27 UTC
