### ISSUE TITLE
Panic while closing the tab of a deleted rust file (in VSCode)

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-analyzer/rust-analyzer#7299] opened 2021-01-16 20:07 UTC
The panic happened exactly at the time when I closed the tab of a deleted rust file (deleted with `git rm --force client-common/src/crypto/mod.rs`).

I never touched the config, so everything should be at their defaults.

```
code --version                                                                                                                       256ms  Sat 16 Jan 2021 05:06:07 PM -03
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64

rustc --version --verbose                                                                                                            111ms  Sat 16 Jan 2021 05:05:50 PM -03
rustc 1.51.0-nightly (c97f11af7 2021-01-10)
binary: rustc
commit-hash: c97f11af7bc4a6d3578f6a953be04ab2449a5728
commit-date: 2021-01-10
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly

cargo --version                                                                                                                              Sat 16 Jan 2021 05:05:23 PM -03
cargo 1.51.0-nightly (329895f5b 2021-01-06)

/home/paulg/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version                           Sat 16 Jan 2021 05:05:20 PM -03
rust-analyzer 60c501f
```

```
Panic context:
> request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/paulg/.cargo/git/checkouts/xchacha8blake3siv-6975dc95217c7e64/d276c2b/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 21,
            character: 0,
        },
        end: Position {
            line: 90,
            character: 68,
        },
    },
}

thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::traverse
   3: ide::syntax_highlighting::highlight
   4: ide::Analysis::highlight_range
   5: rust_analyzer::handlers::handle_semantic_tokens_range
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou-playground/client-common/src/crypto/mod.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 68,
            character: 63,
        },
        end: Position {
            line: 68,
            character: 63,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod ::Vec;', crates/syntax/src/ast/make.rs:466:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: syntax::ast::make::name
   3: assists::handlers::generate_function::generate_function
   4: assists::Assist::get
   5: ide::Analysis::assists
   6: rust_analyzer::handlers::handle_code_action
   7: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:31:55 PM] Request textDocument/prepareRename failed.
  Message: No references found at position
  Code: -32603 
Panic context:
> request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou-playground/client-web/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 73,
            character: 0,
        },
        end: Position {
            line: 120,
            character: 0,
        },
    },
}

thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::traverse
   3: ide::syntax_highlighting::highlight
   4: ide::Analysis::highlight_range
   5: rust_analyzer::handlers::handle_semantic_tokens_range
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou-playground/client-web/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 35,
            character: 0,
        },
        end: Position {
            line: 105,
            character: 32,
        },
    },
}

thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::traverse
   3: ide::syntax_highlighting::highlight
   4: ide::Analysis::highlight_range
   5: rust_analyzer::handlers::handle_semantic_tokens_range
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou-playground/client-web/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 35,
            character: 0,
        },
        end: Position {
            line: 105,
            character: 32,
        },
    },
}

thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::traverse
   3: ide::syntax_highlighting::highlight
   4: ide::Analysis::highlight_range
   5: rust_analyzer::handlers::handle_semantic_tokens_range
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/documentHighlight DocumentHighlightParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/home/paulg/Repositories/cachou-playground/client-common/src/core/mod.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 62,
            character: 36,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Bad offset: range 0..3163 offset 5454', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: syntax::algo::ancestors_at_offset
   4: syntax::algo::find_node_at_offset
   5: ide::references::find_all_refs
   6: ide::Analysis::find_all_refs::{{closure}}
   7: std::panic::catch_unwind
   8: ide::Analysis::find_all_refs
   9: rust_analyzer::handlers::handle_document_highlight
  10: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:59:37 PM] Request textDocument/foldingRange failed.
  Message: file not found: /home/paulg/Repositories/cachou-playground/client-common/src/crypto/mod.rs
  Code: -32603 
[Error - 4:59:37 PM] Request textDocument/codeLens failed.
  Message: file not found: /home/paulg/Repositories/cachou-playground/client-common/src/crypto/mod.rs
  Code: -32603
```

**Comment by lnicola** [comment] 2021-01-17 11:17
Related: https://github.com/rust-analyzer/rust-analyzer/issues/7298

**Comment by Veykril** [comment] 2021-02-05 15:53
https://github.com/rust-analyzer/rust-analyzer/pull/7505 should fix this, I unfortunately couldn't reproduce the panic myself intentionally. Therefor I'll close this issue, if you do see this reappearing after the next stable/nightly release feel free to reopen.

**Closed by Veykril** 2021-02-05 15:53 UTC
Labels: S-actionable
