### ISSUE TITLE
wrong expansion on async_trait

### ISSUE THREAD

**Issue by Emilgardis** [rust-analyzer/rust-analyzer#10861] opened 2021-11-25 18:07 UTC
using `rustc 1.58.0-nightly (b426445c6 2021-11-24)` (and stable 1.56.1),  `rust-analyzer 91cb422`

we get the following weird behavior

```rust
//! [dependencies]
//! async-trait = "0.1.51"

#[async_trait::async_trait]
trait Foo {
    type Bar: Clone;
    const TEST: &'static str;
    fn fun1(&self) -> Option<String>;
    fn fun2(&self) -> Option<String> {
        let hello = "Hello";
        println!("{} World", hello);
        self.fun1()
    }
}



pub struct Lol;

impl Foo for Lol {
    type Bar = String;
    const TEST: &'static str = "hello";
    fn fun1(&self) -> Option<String> {
        None
    }
    // || Cursor here, "implement default members" becomes
    // fnfun2(&self)->Option<String>{lethello="Hello";println!("{} World",hello);self.fun1()}
    // no space between tokens
}
```

"implement default members" inside `impl Foo for Lol` becomes 

```rust
fnfun2(&self)->Option<String>{lethello="Hello";println!("{} World",hello);self.fun1()}
```

**Comment by flodiebold** [comment] 2021-11-25 18:11
Duplicate of #6588.

**Closed** 2021-11-25 18:12 UTC
