### ISSUE TITLE
Could rust-analyzer work on github.dev?

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#11634] opened 2022-03-06 14:10 UTC
I imagine it can. There would be 2 things needed though:
- A WASM binary of Rust-Analyzer (which has already been done)
- A rust toolchain needs to ship with it as well.

I do a lot of code reviewing, sometimes on my iPad and having Rust-Analyzer in the browser would be extremely helpful. I acknowledge that this is quite a hard thing to do.

**Comment by Veykril** [comment] 2022-03-06 14:15
See https://github.com/rust-analyzer/rust-analyzer/issues/11244 which talks about that as well, iirc the main problem is that we can't invoke cargo to fetch dependencies and the like making it less useful.

**Comment by Milo123459** [comment] 2022-03-06 14:16
> See #11244 which talks about that as well, iirc the main problem is that we can't invoke cargo to fetch dependencies and the like making it less useful.

Well, that's why I was suggesting shipping a Rust toolchain with it.

Rust analyzer could also expose some toolchain manager commands or something.

**Comment by bjorn3** [comment] 2022-03-06 14:19
Cargo can't work on wasm. It needs the ability to spawn subprocesses (to run rustc and curl) and to make arbitrary (non-http) network requests (to fetch ssh:// and git:// git repos). In addition it needs filesystem access to store a lot of different data. And it needs to share said filesystem with rustc and rust-analyzer. All of which aren't supported for wasm in the browser.

**Comment by lnicola** [comment] 2022-03-06 14:20
That's easier said than done. A `wasm32-wasi` toolchain is around 700 MB, and we'd need that in order to run build scrips and proc macros. We'd also need WASM ports of `cargo`, `rustc` and `rustfmt`.

And this is a dupe of #10612.

**Closed** 2022-03-06 14:38 UTC
