### ISSUE TITLE
The command produced no valid metadata

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-analyzer/rust-analyzer#11336] opened 2022-01-23 18:20 UTC
When VS Code loads and rust-analyzer is loading my workspace, I am shown the following popup:

![2022-01-24_02-02-00-23](https://user-images.githubusercontent.com/17380079/150691589-63b7a064-8bfd-48cb-bc60-570ef4e8b0c1.png)

This happens fairly consistently for me for the https://github.com/hotg-ai/proc-blocks project. 

Here are some minimal instructions for checking out a version I'm seeing issues with (the latest `master`), although I've seen the same issue when checking out commits from a couple months ago.

```console
$ cd /tmp
$ git clone git@github.com:hotg-ai/proc-blocks.git
$ cd proc-blocks 
$ git checkout 441e1e9be  # current master
$ cargo build --quiet
   Compiling proc-macro2 v1.0.36
   ...
   Compiling fft v0.11.1 (/home/consulting/Documents/hotg-ai/proc-blocks/fft)
    Finished dev [unoptimized + debuginfo] target(s) in 14.61s
$ code .
```

<details>
<summary>Rust Analyzer Client output</summary>

```
INFO [1/24/2022, 2:05:24 AM]: Extension version: 0.3.914
INFO [1/24/2022, 2:05:24 AM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: false,
    typeHints: true,
    hideNamedConstructorHints: false
  },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    exprFillDefault: 'todo',
    importGranularity: 'crate',
    importEnforceGranularity: true,
    importPrefix: 'by_crate',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  cache: { warmup: true },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: true,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false,
    loadOutDirsFromCheck: true
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [ '--target-dir', '/tmp/rust-analyzer-target' ],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    snippets: {
      'Arc::new': {
        postfix: 'arc',
        body: 'Arc::new(${receiver})',
        requires: 'std::sync::Arc',
        description: 'Put the expression into an `Arc`',
        scope: 'expr'
      },
      'Rc::new': {
        postfix: 'rc',
        body: 'Rc::new(${receiver})',
        requires: 'std::rc::Rc',
        description: 'Put the expression into an `Rc`',
        scope: 'expr'
      },
      'Box::pin': {
        postfix: 'pinbox',
        body: 'Box::pin(${receiver})',
        requires: 'std::boxed::Box',
        description: 'Put the expression into a pinned `Box`',
        scope: 'expr'
      },
      Ok: {
        postfix: 'ok',
        body: 'Ok(${receiver})',
        description: 'Wrap the expression in a `Result::Ok`',
        scope: 'expr'
      },
      Err: {
        postfix: 'err',
        body: 'Err(${receiver})',
        description: 'Wrap the expression in a `Result::Err`',
        scope: 'expr'
      },
      Some: {
        postfix: 'some',
        body: 'Some(${receiver})',
        description: 'Wrap the expression in an `Option::Some`',
        scope: 'expr'
      }
    },
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [ 'macro-error' ],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: true },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    enumVariantReferences: false,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: false },
  procMacro: { enable: true, server: null, ignored: {} },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } },
  updates: { channel: 'nightly' }
}
INFO [1/24/2022, 2:05:24 AM]: PersistentState: { serverVersion: '0.3.914' }
INFO [1/24/2022, 2:05:24 AM]: Using server binary at /home/consulting/.vscode/extensions/matklad.rust-analyzer-0.3.914/server/rust-analyzer
DEBUG [1/24/2022, 2:05:24 AM]: Checking availability of a binary at /home/consulting/.vscode/extensions/matklad.rust-analyzer-0.3.914/server/rust-analyzer
DEBUG [1/24/2022, 2:05:24 AM]: /home/consulting/.vscode/extensions/matklad.rust-analyzer-0.3.914/server/rust-analyzer --version: {
  status: 0,
  signal: null,
  output: [ null, 'rust-analyzer baa5cd952 2022-01-23 nightly\n', '' ],
  pid: 4080009,
  stdout: 'rust-analyzer baa5cd952 2022-01-23 nightly\n',
  stderr: ''
}
```
</details>

<details>
<summary>Rust Analyzer Language Server output</summary>

```
[ERROR flycheck] Flycheck failed to run the following command: "cargo" "check" "--workspace" "--message-format=json" "--manifest-path" "/home/consulting/Documents/hotg-ai/proc-blocks/Cargo.toml" "--all-targets" "--all-features" "--target-dir" "/tmp/rust-analyzer-target"
```
</details>

I enabled the `rust-analyzer.trace.extension` setting and restarted VS Code, but the *"Rust Analyzer Language Server Trace"* output doesn't seem to contain anything.

---

**rust-analyzer version**: `rust-analyzer version: baa5cd952 2022-01-23 nightly`

**rustc version**:

```
$ rustc --version --verbose
rustc 1.58.0-nightly (bd41e09da 2021-10-18)
binary: rustc
commit-hash: bd41e09da334697c0f993b36685cb599061d9faa
commit-date: 2021-10-18
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

**Comment by lnicola** [comment] 2022-01-23 18:38
I wasn't able to reproduce in ten tries or so. It looks like `cargo check` is actually failing, but I don't know what that would happen.

**Comment by Michael-F-Bryan** [comment] 2022-01-23 20:33
It might be something specific to my setup, then. Do you have any suggestions for troubleshooting this or seeing what `cargo check` actually outputs?

**Comment by jonas-schievink** [comment] 2022-01-24 16:37
The status code 25856 might indicate that Cargo was killed by a signal

**Comment by TornaxO7** [comment] 2022-02-26 20:35
I'm getting the same issue as well, if I try to run `rust-analyzer` on [rust-osdev/bootloader](https://github.com/rust-osdev/bootloader) with `rust-analyzer.cargo.allFeatures = true`.

**Comment by giluis** [comment] 2022-03-11 18:33
I am getting the same issue using using NeoVim's LSP client.
Is there any update on this?

**Comment by flipbit03** [comment] 2022-04-03 17:08
Do you guys have clippy installed and updated? This seemed to fix things for me.

**Comment by latidoremi** [comment] 2022-04-06 10:51
Same issue using vscode on mac
<img width="448" alt="截屏2022-04-06 下午6 50 49" src="https://user-images.githubusercontent.com/49757619/161958946-2dc7aa01-b1a3-4f7f-b05b-9f270dec2a59.png">

rustc --version --verbose
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-apple-darwin
release: 1.59.0
LLVM version: 13.0.0

This error will raise every time I  save project files, any project I mean, even empty projects, it's so annoying that I have to quit using ra for now :(

I've tried reinstalling ra, updating clippy and nothing works

**Comment by Veykril** [comment] 2022-04-06 10:54
What rust-analyzer version are you using? Starting next week's stable release and today's nightly we should show the entire error message given https://github.com/rust-analyzer/rust-analyzer/pull/11891

**Comment by latidoremi** [comment] 2022-04-06 11:02
> What rust-analyzer version are you using? Starting next week's stable release and today's nightly we should show the entire error message given #11891

v0.2.1002
If I switch to pre-release version v0.3.1004, this is what the error looks like
<img width="448" alt="截屏2022-04-06 下午6 59 27" src="https://user-images.githubusercontent.com/49757619/161960474-ff8a6308-47c6-42fd-858b-1f13c426dfbe.png">

**Comment by bjorn3** [comment] 2022-04-06 11:48
It looks like the rust-analyzer.checkOnSave.command preference is set to an empty string. Can you check if this is indeed the case and if so remove the preference?

**Comment by Veykril** [comment] 2022-04-06 12:00
We should probably warn against that (maybe have a general validation thing for the config somehow)

**Comment by latidoremi** [comment] 2022-04-06 14:47
> It looks like the rust-analyzer.checkOnSave.command preference is set to an empty string. Can you check if this is indeed the case and if so remove the preference?

Yes, removing the rust-analyzer.checkOnSave.command preference solves the problem, thanks!!!

**Comment by fitzchivalrik** [comment] 2022-04-09 19:50
I had the same error for the longest time and could not figure out what I did wrong. Using the pre-release version, which adds the error output, I managed to track it down: I had a faulty `rust-analyzer.checkOnSave.extraArgs` setting, I was missing '--' as the first argument:  
Wrong: `"rust-analyzer.checkOnSave.extraArgs": ["-W", "clippy::pedantic"]`  
Correct: `"rust-analyzer.checkOnSave.extraArgs": ["--","-W", "clippy::pedantic"]`

**Comment by Veykril** [comment] 2022-04-09 20:03
I think we can close this now, as the error should now be able to tell what went wrong.

**Closed by Veykril** 2022-04-09 20:03 UTC
Labels: C-support
