### ISSUE TITLE
[VSCode] Request textDocument/semanticTokens/full failed.

### ISSUE THREAD

**Issue by owen-hope** [rust-analyzer/rust-analyzer#5998] opened 2020-09-14 12:24 UTC
Just updated my vscode to the August 1.49v and now I am getting this error show up every time I open a file or try to type in one:

`[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(U64(71)), method: "textDocument/semanticTokens/full", params: Object({"textDocument": Object({"uri": String("file:///Users/ohope/develop/fresnel/fresnel-code/trace/packet-handling-rust-logic/src/parasitic_trace.rs")})}) }
[Error - 8:18:37 AM] Request textDocument/semanticTokens/full failed.
  Message: unknown request
  Code: -32601 `

This is on a mac.

**Comment by lnicola** [comment] 2020-09-14 12:34
That's a mismatch between the Code extension and the LSP binary. Did you build `rust-analyzer` from source? You might have an older version floating around.

**Comment by owen-hope** [comment] 2020-09-14 12:36
@lnicola Nope, I downloaded the extension right from vscode.

**Comment by guzongmin** [comment] 2020-09-15 01:15
Same issue

**Comment by shenshouer** [comment] 2020-09-15 02:21
Same issue

**Comment by hammypants** [comment] 2020-09-15 04:13
Mine is not failing on Windows, but with Sept 14th nightly it has gotten to be _extremely_ slow. On the order of 5-15s per request for `semanticTokens/full` and `codeAction`.

**Comment by kjeremy** [comment] 2020-09-15 18:46
@owen-hope Can you post the extension and server version numbers?

**Comment by fuyumatsuri** [comment] 2020-09-16 22:32
I'm seeing the same thing on windows with current version of the extension (0.2.313, stable channel) and the server binary that was auto downloaded/included.

```
~\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer 
> .\rust-analyzer-windows.exe --version
rust-analyzer ac4b134
```

**Comment by kjeremy** [comment] 2020-09-16 22:39
ac4b134 is the 2020-08-30 release of the `rust-analyzer` binary. The semantic tokens change for both client and server was merged in after that.

**Comment by fuyumatsuri** [comment] 2020-09-16 23:58
It seems in my case, `state.serverVersion` was somehow set to `0.2.313` even though the server binary wasn't actually updated. I forced the extension to download an updated version anyways, and that has fixed it for me.

I'm not really sure how I got in this state, but one "suspicious" thing might be that before updating my vscode from last weeks version, I installed WSL and installed the vs code extension in it. Using the extension under WSL does seem to have a separate globalState than using it under the host windows, so that *shouldnt* be the cause, but you never know.

**Comment by kjeremy** [comment] 2020-09-17 00:10
I think WSL has to be updated separately.

**Comment by owen-hope** [comment] 2020-09-17 15:37
The issue seemed to be resolved when I quit vscode and had a new update for the rust-analyze to v0.2.313

**Comment by kjeremy** [comment] 2020-09-17 18:45
@shenshouer @fuyumatsuri @guzongmin 

Do you still see this?

**Comment by guzongmin** [comment] 2020-09-18 00:30
> @shenshouer @fuyumatsuri @guzongmin
> 
> Do you still see this?
Thanks. It works now.

**Comment by shenshouer** [comment] 2020-09-21 06:05
It worked after I reinstall rust-analyzer

**Closed** 2020-09-21 10:24 UTC

**Comment by Joneyao** [comment] 2022-07-13 06:24
It also worked just restart rust-analyzer.

**Comment by briankung** [comment] 2023-12-29 16:29
I've been getting this error for the past few weeks. I've tried restarting and reinstalling rust analyzer as well as updating VS Code. I'm on a Mac.

<details><summary>Click to expand LSP error</summary>

```
thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.4/src/interned.rs:107:32:
index out of bounds: the len is 143338 but the index is 4294967039
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: salsa::interned::InternedStorage<Q>::lookup_value
   4: <DB as hir_expand::db::ExpandDatabase>::lookup_intern_syntax_context
   5: hir_expand::mod_path::resolve_crate_root
   6: hir_expand::mod_path::convert_path
   7: hir_expand::mod_path::convert_path
   8: hir_expand::mod_path::convert_path
   9: hir_expand::mod_path::convert_path
  10: hir_def::item_tree::lower::Ctx::lower_macro_call
  11: hir_def::item_tree::lower::Ctx::lower_mod_item
  12: hir_def::item_tree::ItemTree::file_item_tree_query
  13: salsa::Cycle::catch
  14: salsa::derived::slot::Slot<Q,MP>::execute
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  17: <DB as hir_def::db::DefDatabase>::file_item_tree
  18: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  19: hir_def::nameres::collector::collect_defs
  20: hir_def::nameres::DefMap::block_def_map_query
  21: salsa::Cycle::catch
  22: salsa::derived::slot::Slot<Q,MP>::execute
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  25: <DB as hir_def::db::DefDatabase>::block_def_map
  26: hir_def::body::lower::ExprCollector::collect_block_
  27: hir_def::body::lower::ExprCollector::maybe_collect_expr
  28: hir_def::body::lower::ExprCollector::collect_stmt
  29: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  30: hir_def::body::lower::ExprCollector::collect_block_
  31: hir_def::body::lower::ExprCollector::maybe_collect_expr
  32: hir_def::body::lower::ExprCollector::collect_stmt
  33: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  34: hir_def::body::lower::ExprCollector::with_label_rib
  35: hir_def::body::lower::ExprCollector::maybe_collect_expr
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  37: <alloc::boxed::Box<[I]> as core::iter::traits::collect::FromIterator<I>>::from_iter
  38: hir_def::body::lower::ExprCollector::maybe_collect_expr
  39: hir_def::body::lower::ExprCollector::collect_block_
  40: hir_def::body::lower::ExprCollector::maybe_collect_expr
  41: hir_def::body::lower::ExprCollector::collect_expr_opt
  42: hir_def::body::lower::lower
  43: hir_def::body::Body::body_with_source_map_query
  44: salsa::Cycle::catch
  45: salsa::derived::slot::Slot<Q,MP>::execute
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  48: hir::DefWithBody::diagnostics
  49: hir::ModuleDef::diagnostics
  50: hir::Module::diagnostics
  51: hir::DefWithBody::diagnostics
  52: hir::Module::diagnostics
  53: ide_diagnostics::diagnostics
  54: std::panicking::try
  55: ide::Analysis::assists_with_fixes
  56: rust_analyzer::handlers::request::handle_code_action
  57: std::panicking::try
  58: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by towry** [comment] 2024-07-14 15:23
Keep getting this error.

**Comment by huseeiin** [comment] 2025-02-20 12:10
i also keep getting it (rarely) but it goes away after restarting vscode
