### ISSUE TITLE
Possible Bug: RA suggests `Global`(nightly) for type thats not needed?. 

### ISSUE THREAD

**Issue by caseykneale** [rust-analyzer/rust-analyzer#9508] opened 2021-07-06 12:01 UTC
I was playing with the serialport crate. I copy pasta'd an example:
```rust
let port = serialport::new("/dev/ttyUSB0", 115_200)
    .timeout(Duration::from_millis(10))
    .open().expect("Failed to open port");
```
I hovered over the type of `port` to use it as a return type in a function and saw:
`mut port: Box<dyn SerialPort, Global>`

When I made that function I was informed about how, std::alloc::Global isn't in stable - it's only in nightly. After a bit of confusion in a rust beginners chatroom someone realized the type:
`mut port: Box<dyn SerialPort>`
is also sufficient. By deleting `Global` the code compiles and runs as expected?

I don't know if this is a bug, but it feels like unexpected behavior. New users(like me) will trace the errors to go install nightly and rely on an unstable feature when they don't have too. It's also in general confusing.

**Comment by lnicola** [comment] 2021-07-06 12:07
This is pretty much #9198.

**Comment by jonas-schievink** [comment] 2021-07-06 13:13
Yeah, closing as a duplicate of #9198

**Closed by jonas-schievink** 2021-07-06 13:13 UTC
