### ISSUE TITLE
Incorrect indication of non-standard name for constants

### ISSUE THREAD

**Issue by khrynczenko** [rust-analyzer/rust-analyzer#6424] opened 2020-10-31 18:24 UTC
Hi,
After performing the latest update from the 2020-10-26 rust-analyzer started indicating that the names of my `const`s are not following the standard which, I believe, is false.
![image](https://user-images.githubusercontent.com/15171153/97786589-e548a400-1bac-11eb-98c4-c2a3963ba587.png)
It shows on all constants in my codebase. I tried some different names and for all of them except one I have the same issue.
This doesn't show for single-letter names.
![image](https://user-images.githubusercontent.com/15171153/97786764-0f4e9600-1bae-11eb-94a3-c7626c3be739.png)

I even have `#![deny(nonstandard_style)]` applied and it does not result in error. If you need any more information, please let me know.

**Comment by lnicola** [comment] 2020-11-01 07:07
Duplicate of https://github.com/rust-analyzer/rust-analyzer/pull/6350, is fixed in nightly and will be available in tomorrow's release.

**Closed by lnicola** 2020-11-01 07:07 UTC
