### ISSUE TITLE
Function-local `use` seems not to work.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#4713] opened 2020-06-02 19:40 UTC
```
mod m {
    pub struct S(pub usize);
}

pub fn f(s: m::S) {
    use m::S;
    let S(_i) = s;
}
```

The type of `_i` is not inferred.

Feel free to change the title of the issue if you think the root cause is something else.

**Comment by bjorn3** [comment] 2020-06-02 19:52
Duplicate of #1165.

**Closed** 2020-06-02 20:03 UTC
