### ISSUE TITLE
Hover tooltip on `Iterator` prints un-rendered markdown noise

### ISSUE THREAD

**Issue by Walther** [rust-analyzer/rust-analyzer#11742] opened 2022-03-17 13:59 UTC
With a function like
```rust
pub fn declaration(
    tokens: &mut Peekable<impl Iterator<Item = Token>>,
) -> Result<Statement, ParseError> { /* */ }
```

when hovering the text `Iterator`, the tooltip seems to get confused:
![image](https://user-images.githubusercontent.com/2943750/158823769-a6a0dea8-d7b7-47b5-bf1c-76afb63f1403.png)

**rust-analyzer version**: 5e8515870 2022-03-14 stable

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

Running VSCode on Windows with the remote extension to a Linux host, in case that matters.

**Comment by jhgg** [comment] 2022-03-18 08:31
dupe of #9926!

**Closed** 2022-03-18 08:36 UTC
