### ISSUE TITLE
Traits exposed by proc_macro are not visibile for IDE completion.

### ISSUE THREAD

**Issue by mehmooda** [rust-analyzer/rust-analyzer#8558] opened 2021-04-17 15:38 UTC
If you have a proc macro attribute which generates a new trait. It doesn't seem to be visible to use in the current crate;

See https://github.com/mehmooda/glib_macro_test/blob/main/muse/src/main.rs

The proc macro attribute defines a MyWidgetExt trait with methods such as `connect_my_signal` and `emit_my_signal`. But they are not visible for auto completion and if you try to write `use MyWidgetExt as Test;` you get unresolved import. Even though cargo check is fine.

**Comment by bjorn3** [comment] 2021-04-17 16:01
Proc macro attributes are not yet implemented. They are planned to be implemented during the current six week sprint though: https://github.com/rust-analyzer/rust-analyzer/issues/8486

**Comment by flodiebold** [comment] 2021-04-17 16:03
Duplicate of #6029

**Closed by flodiebold** 2021-04-17 16:03 UTC
Labels: A-macro
