### ISSUE TITLE
textDocument/formatting takes much longer than cargo fmt

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#1726] opened 2019-08-22 20:56 UTC
I'm using `rust-analyzer` cd243499 with https://github.com/autozimu/LanguageClient-neovim/commit/12e65e7ce62ad769bd01a67063e82e4c01a839d6.

Running `:call LanguageClient_textDocument_formatting()` takes a _really long while_ (upwards of 30 seconds on files from [rav1e](https://github.com/xiph/rav1e), like `src/api/mod.rs`), even though `cargo fmt` completes in half a second.

**Comment by matklad** [comment] 2019-09-06 18:43
That seems pretty strage. For document formatting, we just shell out to rustfmt, so my best guess is that something weird is going on in the environment. I don't have a better advice than to just try to debug this issue.

**Comment by YaLTeR** [comment] 2019-09-06 22:33
How do I go about debugging this?

**Comment by YaLTeR** [comment] 2020-01-06 13:02
I noticed the same behavior in RLS: on some projects formatting via the request just takes a while for some reason. Maybe it's the language client that is to blame here.

**Comment by abbec** [comment] 2021-01-15 19:42
I also get this when the lsp server has just been started. After a while it settles though and becomes instant

**Comment by lnicola** [comment] 2021-01-15 20:34
Maybe it's queued in the event loop?

**Comment by lnicola** [comment] 2021-01-27 18:56
Let's close this as a dupe of #4054 (which is newer, but has more discussion).

**Closed by lnicola** 2021-01-27 18:56 UTC
Labels: E-unknown
