### ISSUE TITLE
 Intellisense failing in latest 2 versions

### ISSUE THREAD

**Issue by Dispersia** [rust-analyzer/rust-analyzer#8699] opened 2021-04-30 18:18 UTC
Upgraded to release 578 two days ago which is when my intellisense first started failing, then release 579 this morning but didn't fix it.

 Every project fails, even just a `cargo new`. Cleared all cargo cache, deleted the executable in AppData and let it redownload, disabled all extra rust-analyzer options. 

```Panic context:
> request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/f%3A/development/test_intelli/src/main.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 372 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 45 }
', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.16.0\src\lib.rs:490:48
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### SPECS:
Windows 10, VSCode insiders.

If any other information is needed let me know, thanks

**Comment by flodiebold** [comment] 2021-04-30 18:45
Duplicate of #8686, should be fixed in the next nightly.

**Closed by flodiebold** 2021-04-30 18:45 UTC
