### ISSUE TITLE
"Implement default members" generates invalid Rust code.

### ISSUE THREAD

**Issue by jonasbb** [rust-analyzer/rust-analyzer#7063] opened 2020-12-28 14:15 UTC
Running "Implement default members" on this impl block leads to invalid Rust code.

```rust
// serde = "=1.0.118"
struct V;
impl serde::de::Visitor for V {
}
```

For me it expands to this code:

<details>
<summary>Full code</summary>

```rust
struct V;
impl serde::de::Visitor for V {
    $0fn visit_bool<E>(self, v: bool) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Bool(v), &serde::de))
    }

    fn visit_i8<E>(self, v: i8) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_i64(v as i64)
    }

    fn visit_i16<E>(self, v: i16) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_i64(v as i64)
    }

    fn visit_i32<E>(self, v: i32) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_i64(v as i64)
    }

    fn visit_i64<E>(self, v: i64) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Signed(v), &serde::de))
    }

    fnvisit_i128<E>(self,v:i128)->Result<Self::Value,E>whereE:serde::de::Error,{let_=v;Err(serde::de::Error::invalid_type(serde::de::Unexpected::Other("i128"), &serde::de))}

    fn visit_u8<E>(self, v: u8) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_u64(v as u64)
    }

    fn visit_u16<E>(self, v: u16) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_u64(v as u64)
    }

    fn visit_u32<E>(self, v: u32) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_u64(v as u64)
    }

    fn visit_u64<E>(self, v: u64) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Unsigned(v), &serde::de))
    }

    fnvisit_u128<E>(self,v:u128)->Result<Self::Value,E>whereE:serde::de::Error,{let_=v;Err(serde::de::Error::invalid_type(serde::de::Unexpected::Other("u128"), &serde::de))}

    fn visit_f32<E>(self, v: f32) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_f64(v as f64)
    }

    fn visit_f64<E>(self, v: f64) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Float(v), &serde::de))
    }

    fn visit_char<E>(self, v: char) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_str(utf8::encode(v).as_str())
    }

    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Str(v), &serde::de))
    }

    fn visit_borrowed_str<E>(self, v: &'de str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_str(v)
    }

    fn visit_string<E>(self, v: String) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_str(&v)
    }

    fn visit_bytes<E>(self, v: &[u8]) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        let _ = v;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Bytes(v), &serde::de))
    }

    fn visit_borrowed_bytes<E>(self, v: &'de [u8]) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_bytes(v)
    }

    fn visit_byte_buf<E>(self, v: Vec<u8>) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        serde::de.visit_bytes(&v)
    }

    fn visit_none<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Option, &serde::de))
    }

    fn visit_some<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Option, &serde::de))
    }

    fn visit_unit<E>(self) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Unit, &serde::de))
    }

    fn visit_newtype_struct<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let _ = deserializer;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::NewtypeStruct, &serde::de))
    }

    fn visit_seq<A>(self, seq: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::SeqAccess<'de>,
    {
        let _ = seq;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Seq, &serde::de))
    }

    fn visit_map<A>(self, map: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::MapAccess<'de>,
    {
        let _ = map;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Map, &serde::de))
    }

    fn visit_enum<A>(self, data: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::EnumAccess<'de>,
    {
        let _ = data;
        Err(serde::de::Error::invalid_type(serde::de::Unexpected::Enum, &serde::de))
    }

    fn __private_visit_untagged_option<D>(self, _: D) -> Result<Self::Value, ()>
    where
        D: serde::Deserializer<'de>,
    {
        Err(())
    }
}
```

</details>

```rust
    fnvisit_i128<E>(self,v:i128)->Result<Self::Value,E>whereE:serde::de::Error,{let_=v;Err(serde::de::Error::invalid_type(serde::de::Unexpected::Other("i128"), &serde::de))}
```

```rust
    fnvisit_u128<E>(self,v:u128)->Result<Self::Value,E>whereE:serde::de::Error,{let_=v;Err(serde::de::Error::invalid_type(serde::de::Unexpected::Other("u128"), &serde::de))}
```

Both functions miss any whitespace between the tokens, thus creating invalid Rust. I suspect this is because both functions are defined inside the `serde_if_integer128!` macro, e.g., [`visit_i128`](https://docs.rs/serde/1.0.118/src/serde/de/mod.rs.html#1347-1359).
The same issue also occurs with the `Deserializer` trait from serde.

This occurs with rust-analyzer version: 2020-12-28 (1d53075). The editor is VS Code version 1.52.1.

**Comment by Veykril** [comment] 2020-12-28 16:29
Duplicate of #2765

**Closed by Veykril** 2020-12-28 16:29 UTC
