### ISSUE TITLE
rust-analyzer crashes when trying to use tokio::spawn async

### ISSUE THREAD

**Issue by misttyat** [rust-analyzer/rust-analyzer#6145] opened 2020-10-06 05:02 UTC
**type: Bug**

**rust-analyzer version**: nightly cb78c40, stable branch has same error.

***Step-By-Step guide*** 
https://asciinema.org/a/gFUmLyfowCRD96ZrFEwsC3GYz

**Reproduce code** 
```rust
#[tokio::main]
pub async fn main() {
  println!("123");
  tokio::spawn(async {
//here ls server crashes 
});
}
```

**Comment by lnicola** [comment] 2020-10-06 11:28
Stack trace:

```
thread '<unnamed>' panicked at 'not implemented', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.30.0/src/clauses.rs:59:36
stack backtrace:
   0: std::panicking::begin_panic
   1: chalk_solve::clauses::push_auto_trait_impls
   2: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   3: chalk_solve::clauses::program_clauses_for_goal
   4: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
   5: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   6: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
   7: hir_ty::traits::trait_solve_query
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  13: <DB as hir_ty::db::HirDatabase>::trait_solve
  14: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  15: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  16: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  17: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  18: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  19: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  20: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  21: hir_ty::infer::infer_query
  22: salsa::runtime::Runtime::execute_query_implementation
  23: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  24: salsa::derived::slot::Slot<Q,MP>::read
  25: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  26: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  27: hir_ty::db::infer_wait
  28: hir_ty::diagnostics::validate_body
  29: hir::code_model::Module::diagnostics
  30: ide::diagnostics::diagnostics
  31: std::panicking::try
  32: ide::Analysis::diagnostics
  33: rust_analyzer::handlers::publish_diagnostics
  34: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  35: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  36: <F as threadpool::FnBox>::call_box
```

Duplicate of #6134, closing.

**Closed by lnicola** 2020-10-06 11:28 UTC
