### ISSUE TITLE
bug: tokio::test no run test buttom in vscode

### ISSUE THREAD

**Issue by gipsyh** [rust-analyzer/rust-analyzer#10857] opened 2021-11-25 12:39 UTC
RA: v0.2.817
![image](https://user-images.githubusercontent.com/42509521/143443067-c4b435e6-d82a-4cef-bd14-d03de1c6c409.png)
![image](https://user-images.githubusercontent.com/42509521/143443147-2e77266d-683b-4a13-9079-871c60ca9651.png)
I remember there was

**Comment by bjorn3** [comment] 2021-11-25 12:41
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10837

**Closed by bjorn3** 2021-11-25 12:41 UTC
