### ISSUE TITLE
`Run Test` and `Debug` execute the code in different working directories

### ISSUE THREAD

**Issue by balintbalazs** [rust-analyzer/rust-analyzer#4705] opened 2020-06-02 10:30 UTC
In certain cases the vscode `Run Test` and `Debug` buttons execute the code in different working directories.

In this example I have a workspace in the `C:\Dev\rust\rust-project` folder, and a crate inside called `metadata`.

For this test in `C:\Dev\rust\rust-project\metadata\lib.rs`:
```rust
#[test]
fn pwd() {
    let working_dir = std::env::current_dir().unwrap();
    println!("{}", working_dir.display());
}
```

when clicking `Run Test` I get the following output:
```
running 1 test
C:\Dev\rust\rust-project\metadata
test tests::pwd ... ok
```

But when clicking the `Debug` option it prints:
```
running 1 test
C:\Dev\rust\rust-project
test tests::pwd ... ok
```

This behavior can be fairly inconvenient when the test code needs to read some files, so it would be great if it would be consistent.

Thanks!

**Comment by matklad** [comment] 2020-06-03 10:32
cc @vsrs 

I think we should always execute the code with cwd set to the worksapce_root.

**Comment by vsrs** [comment] 2020-06-03 10:45
At the moment `runSingle` uses runnable.workspaceRoot and `debugSingle` does not. I'll fix this.

**Comment by vsrs** [comment] 2020-06-03 18:37
Hm, turns out it is not so easy. Both commands correctly set cwd to `runnable.workspaceRoot || '.'`.

So we just see how Cargo works with virtual workspaces:
`cargo test --package metadata --lib -- pwd --exact --nocapture` command spawns 3 processes:

| executable | arguments | cwd |
| - | - |- |
| `~/.cargo/bin/cargo` | `test --package metadata --lib -- pwd --exact --nocapture` | **${workspaceRoot}** |
| `~/.rustup/toolchains/<toolchain>/bin/cargo` | `test --package metadata --lib -- pwd --exact --nocapture` | **${workspaceRoot}** |
|`${workspaceRoot}/target/debug/deps/metadata-34fd8c2a238a9d90`| `pwd --exact --nocapture` | **${workspaceRoot}/metadata** |

So it is Cargo who sets cwd for metadata-34fd8c2a238a9d90. I think the root is here:
https://github.com/rust-lang/cargo/blob/7302186d7beb2b11bf7366c0aa66269313ebe18f/src/cargo/ops/cargo_test.rs#L83

And looks like there is no way to control this behavior and better not to use cwd in tests at all.

`CARGO_MANIFEST_DIR` for the third process is also **${workspaceRoot}\metadata**. Maybe we can add CARGO_WORKSPACE_ROOT_DIR, pointing to the virtual workspace root?  Or even do it upstream in the Cargo.

**Comment by popzxc** [comment] 2020-09-13 13:45
I'm unable to reproduce it. It seems [it was fixed](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_test.rs#L78).

**Comment by sasurau4** [comment] 2021-01-22 12:35
I confirm this issue fixed with the same situation of @balintbalazs . 
```
cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)

rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Closed** 2021-01-22 13:01 UTC
Labels: E-easy, S-actionable

**Comment by gilescope** [comment] 2021-08-10 11:06
I'm getting this issue on vscode/nixos. Personally it seems like the `play` is getting it right and the `debug` is choosing the root dir of the workspace. Ideally it should do the same thing as cargo does.

**Comment by Marko-Vujnovic** [comment] 2022-05-02 11:31
I'm still affected by this. The behavior is exactly the same as described in the OP.
```
# cargo --version
cargo 1.53.0
# rustc --version
rustc 1.53.0 (gentoo)
```

**Comment by NiceneNerd** [comment] 2022-07-14 17:14
I have the same issue as well. Makes relative paths in tests very complicated.

**Comment by johannescpk** [comment] 2022-09-29 10:08
Workaround cargo launch configuration to emulate the debug link with correct cwd that worked for me:

```json
    {
      "type": "lldb",
      "request": "launch",
      "name": "Cargo test test-file-name",
      "cargo": {
        "args": [
          "test",
          "-p",
          "workspace-package-name",
          "--test",
          "test-file-name",
          "--no-run"
        ],
        "filter": { "name": "test-file-name" }
      },
      "program": "${cargo:program}",
      "args": ["--ignored", "--nocapture"],
      "cwd": "${workspaceFolder}/crates/workspace-package-name"
    },
``` 

Needs to be configured per test, so `workspace-package-name` and `test-file-name` need to be adjusted. If you want to run one specific test in the test file, add `args` accordingly.

Resources
- https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#launching-a-new-process
- https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#cargo-support

**Comment by d00z3l** [comment] 2023-05-10 03:42
I have struggled with the same issue, I wanted to use a relative path for a source file for my tests and have it work using run/debug in VS Code and also using `cargo test --all`. My workaround is as follows:

1. Create a local `settings.json` file, i.e. `./.vscode/settings.json`
2. Add the following to the settings file:
```json
{
    "rust-analyzer.runnableEnv": {
        "ENV_ROOT_DIR": "${workspaceFolder}"
    }
}
```
3. Create a test function create the path:
```rust
    pub fn test_data_path() -> String {
        static FILE_PATH : &str = "./tests/my-file-name.csv";
        match std::env::var("ENV_ROOT_DIR") {
            Ok(path) => {
                Path::new(&path).join(FILE_PATH).display().to_string()
            },
            Err(_) => {
                Path::new(&std::env::current_dir().unwrap()).join("../").join(FILE_PATH).display().to_string()
            }
        }
    }
```

`ENV_ROOT_DIR` is used in VS Code and the working directory for `cargo test`

**Comment by tanveerbadar** [comment] 2023-07-13 07:43
Still encountering this issue, the last mentioned work-around doesn't work as the setting isn't recognized by rust-analyzer.

**Comment by kriswuollett** [comment] 2023-07-26 22:55
If test cases are run from same workspace as they are compiled, then for a workaround perhaps using `env!("CARGO_MANIFEST_DIR")` as the relative directory reference point may be a more direct and stable workaround under refactoring crate location conditions.
