### ISSUE TITLE
Wrong mismatched-arg-count on nalgebra Vector and Matrix types.

### ISSUE THREAD

**Issue by dgsantana** [rust-analyzer/rust-analyzer#8895] opened 2021-05-20 14:12 UTC
When writing code with the nalgebra crate, which as lots of type definitions, rust analyzer seems to get mixed up and starts giving mismatched-arg-count for almost all types.

Simple reproducible example.

`
use nalgebra::Vector2;

pub(crate) fn test_vectors() -> Vector2<f32> {
    let my_vector = Vector2::new(2.0, 2.0);
    my_vector
}

#[test]
fn test() {
    let v = test_vectors();
    assert_eq!(v, Vector2::new(2.0, 2.0));
}
`

![image](https://user-images.githubusercontent.com/2750212/118993731-aaa62d80-b97d-11eb-9019-b987002f697a.png)

**Comment by flodiebold** [comment] 2021-05-20 14:15
Duplicate of #8654

**Closed by flodiebold** 2021-05-20 14:15 UTC
