### ISSUE TITLE
Can't work on Ubuntu16.04

### ISSUE THREAD

**Issue by rise0chen** [rust-analyzer/rust-analyzer#11589] opened 2022-03-01 02:03 UTC
![image](https://user-images.githubusercontent.com/12853908/156090806-c0af6d89-9608-4d6e-b37d-ae1521eb8224.png)

**Comment by ihowell** [comment] 2022-03-01 03:16
This also applies to ubuntu 18.x.

**Comment by lnicola** [comment] 2022-03-01 05:22
Yeah, dupe of #11558.

**Closed by lnicola** 2022-03-01 05:22 UTC
