### ISSUE TITLE
index out of bounds in line_index.rs

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#5786] opened 2020-08-17 14:53 UTC
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 7 but the index is 39', crates/ide_db/src/line_index.rs:102:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/library/core/src/panicking.rs:62
   3: ide_db::line_index::LineIndex::offset
   4: rust_analyzer::handlers::handle_code_action
   5: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

rust-analyzer: rust-analyzer@6826dd044a5a08359197b2a006905eb8518494a2
rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16)
vscode 1.49.0-insider bd08768fd310d34cdd4423a53e5f3ca77340fea5

To reproduce:

- Paste the following code into the editor:

```
struct A;

macro_rules! tyypoo {
    () => {
        Bar
    };
}

fn test() {

}
```

- Save the file then delete line 1-7 but **don't** save the file.
- Hovering over `fn test()` should reproduce the panic.

<details>
<summary>Click to see a screencast</summary>

![Peek 2020-08-17 16-51](https://user-images.githubusercontent.com/5961244/90409824-f30c8400-e0a9-11ea-9ec8-424b5f0a22b7.gif)

</details>

**Comment by lnicola** [comment] 2020-08-17 15:17
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4266.

**Closed by lnicola** 2020-08-17 15:17 UTC
