### ISSUE TITLE
Add assist for extracting a selection into a module

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8164] opened 2021-03-23 12:16 UTC
Before:

```rust
fn main() {
    let foo: Foo = bar();
}

$0
struct Foo;

fn bar() -> Foo {
    Foo
}
$0
```

After:

```rust
fn main() {
    let foo: mod_name::Foo = mod_name::bar();
}

mod mod_name {
    struct Foo;

    fn bar() -> Foo {
        Foo
    }
}
```

**Comment by bluss** [comment] 2021-04-12 18:07
I was looking for this, except that the module ends up in a new file. Separate assist?

**Comment by Veykril** [comment] 2021-04-12 18:55
There is already an assist to move an inline declared module into its own file, so having the assist described in this issue together with that existing one would do what you want.

**Comment by Veykril** [comment] 2021-11-27 18:15
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/9591 which has been addressed already

**Closed by Veykril** 2021-11-27 18:15 UTC
Labels: S-actionable, A-assists
