### ISSUE TITLE
Feature - Wrap Type postfix

### ISSUE THREAD

**Issue by theduke** [rust-analyzer/rust-analyzer#9781] opened 2021-08-04 06:29 UTC
Intellij just gained a new postfix snippet for wrapping types with `.wrap`.

Eg: `T.wrap` => `{cursor}<T>`

I've wanted this for a long time in RA.

Additional suggestions:

`T.wrapo` => `Option<T>`
`T.wrapr` => `Result<T, {cursor}>`

**Comment by Veykril** [comment] 2021-08-04 10:10
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4360

**Closed by Veykril** 2021-08-04 10:10 UTC
