### ISSUE TITLE
'importing' a mod inside a funcion don't take effect for intelisense autocompletion or type highlights

### ISSUE THREAD

**Issue by ericpubu** [rust-analyzer/rust-analyzer#5434] opened 2020-07-18 22:18 UTC
Referring to a module with use like `use self::models::Post;` inside a function don't works for the code analizys (it does compile and run)

![Screenshot_20200718_171017](https://user-images.githubusercontent.com/18682359/87862860-2a0c4000-c91a-11ea-8b2c-d9e6493d085f.png)
![Screenshot_20200718_170049](https://user-images.githubusercontent.com/18682359/87862876-663fa080-c91a-11ea-94b2-b4673df55650.png)

It does work if the use sentence is at mod level outside the function.

![Screenshot_20200718_170943](https://user-images.githubusercontent.com/18682359/87862884-722b6280-c91a-11ea-9a3a-d1adc3dd14ee.png)
![Screenshot_20200718_170028](https://user-images.githubusercontent.com/18682359/87862885-78214380-c91a-11ea-884d-3981e9de24b6.png)

Attached some screenshots, happy to provide more info if needed.
Thanks!

**Comment by bjorn3** [comment] 2020-07-19 07:22
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1165

**Closed by bjorn3** 2020-07-19 07:22 UTC
