### ISSUE TITLE
rust-analyzer crashes when used with a file containing the vomit emoji (🤮)

### ISSUE THREAD

**Issue by asg0451** [rust-analyzer/rust-analyzer#7761] opened 2021-02-23 01:26 UTC
rust-analyzer crashes when I enable LSP in a file I'm editing that includes the vomit emoji. Without the emoji it works fine, when I insert it, instant crash.

emacs 27.1, not sure what version of lsp-mode, but it has commit f9e2f51c2cb65709ac2f0d3cc57ef3ffa3a04952
rust-analyzer version 14de9e5

error log:
```
[ERROR rust_analyzer] Unexpected error: expected initialized notification, got Ok(Request(Request { id: RequestId(I32(389)), method: "rust-analyzer/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///home/miles/rust/ra-crash-eg/src/main.rs")})}) }))
expected initialized notification, got Ok(Request(Request { id: RequestId(I32(389)), method: "rust-analyzer/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///home/miles/rust/ra-crash-eg/src/main.rs")})}) }))
[ERROR rust_analyzer] Unexpected error: expected initialized notification, got Ok(Request(Request { id: RequestId(I32(392)), method: "rust-analyzer/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///home/miles/rust/ra-crash-eg/src/main.rs")})}) }))
expected initialized notification, got Ok(Request(Request { id: RequestId(I32(392)), method: "rust-analyzer/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///home/miles/rust/ra-crash-eg/src/main.rs")})}) }))

Process rust-analyzer stderr<2> finished
```

minimal repro:

```rust
fn main() {
    println!("🤮");
}
```

emacs lsp-mode configuration:
```lisp
(use-package lsp-mode
  :after rust-mode
  :config
  (setq lsp-rust-server 'rust-analyzer)
  (setq lsp-completion-provider :capf)

  (setq lsp-rust-analyzer-server-display-inlay-hints t) ;; this might have something to do with it, based on error msg?
  (setq lsp-rust-analyzer-display-parameter-hints t)
  (setq lsp-rust-analyzer-display-chaining-hints t)
  (add-hook 'lsp-mode-hook (lambda ()
                             (when (derived-mode-p 'rust-mode)
                               (lsp-rust-analyzer-inlay-hints-mode 1) ;; sometimes they don't display even with above param.. force the issue
                               )
                             )
            )
  )
  ```

**Comment by asg0451** [comment] 2021-02-23 01:28
don't ask me how i found this out

**Comment by lnicola** [comment] 2021-02-23 05:30
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/2080.

**Closed by lnicola** 2021-02-23 05:30 UTC
