### ISSUE TITLE
No type hint  simplification with enumerate

### ISSUE THREAD

**Issue by fehrnah** [rust-analyzer/rust-analyzer#6561] opened 2020-11-15 20:43 UTC
When using enumerate(), type hints are not correctly simplified

ex:
![enumerate](https://user-images.githubusercontent.com/5240931/99196163-dd7f2700-278a-11eb-96dd-ff03c44f1bf4.PNG)

on line 4, I would expect the hint to be impl Iterator<Item=(usize, &u32)>, same as line 5

**Comment by SomeoneToIgnore** [comment] 2020-11-15 22:14
This is the part, responsible for Iterator implementation checks:

https://github.com/rust-analyzer/rust-analyzer/blob/74c82ca8ce82360f9509ab433263d2f4e872209b/crates/ide/src/inlay_hints.rs#L240-L250

For this particular case, we need to change the logic so that we should stop checking eagerly that a type (`ty`) implements `Iterator`.

Instead, we cover special cases separately, for tuples applying `hint_iterator` to all inner elements instead of the tuple itself.

====

Note that you cannot reuse the snippet from the screenshor easily and it might be simpler to adjust any of the existing tests.
rust-analyzer has no stdlib in unit tests, instead, a minimalistic set of stubs is added to every test that needs it.
Here it's already added and has some iterator stubs, but it lacks the `enumerate` method one, the relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/74c82ca8ce82360f9509ab433263d2f4e872209b/crates/assists/src/utils.rs#L174

**Comment by petr-tik** [comment] 2020-11-19 22:36
Can you please assign this to me? I would like to take a stab at it. 

Thanks for the detailed instructions btw!

**Comment by petr-tik** [comment] 2020-11-19 22:45
> Note that you cannot reuse the snippet from the screenshor easily and it might be simpler to adjust any of the existing tests.
> rust-analyzer has no stdlib in unit tests, instead, a minimalistic set of stubs is added to every test that needs it.
> Here it's already added and has some iterator stubs, but it lacks the `enumerate` method one, the relevant code is here:
> 
> https://github.com/rust-analyzer/rust-analyzer/blob/74c82ca8ce82360f9509ab433263d2f4e872209b/crates/assists/src/utils.rs#L174

Why not use a test like this?

https://github.com/rust-analyzer/rust-analyzer/blob/74c82ca8ce82360f9509ab433263d2f4e872209b/crates/ide/src/inlay_hints.rs#L1227-L1281

**Comment by SomeoneToIgnore** [comment] 2020-11-19 23:13
> Why not use a test like this?

If that works for you, sure.
I've just noted that the exact reproduction is a bit harder that just writing a test.

**Comment by kinnison** [comment] 2021-01-01 00:24
@fehrnah I am unable to reproduce this on current master rust-analyzer.  The inlay hint on the `.enumerate()` is `impl Iterator<Item = (usize, &u32)>` for me.

Indeed it seems that current released rust-analyzer is also behaving correctly for me.

Could you try again to see if this has already been fixed for you?

**Comment by SomeoneToIgnore** [comment] 2021-01-02 21:15
I've rechecked and it works for me too.

Seems like chalk updaate had fixed the type projections handling and that helped?

**Closed by SomeoneToIgnore** 2021-01-02 21:15 UTC
Labels: E-has-instructions, S-actionable, good first issue
