### ISSUE TITLE
Don't suggest function call when function item is expected

### ISSUE THREAD

**Issue by Inky-developer** [rust-analyzer/rust-analyzer#11972] opened 2022-04-12 21:32 UTC
When calling a function that expects a function as parameter, and the completed function has a matching type, don't suggest calling that function. Example of the current behavior:

![output](https://user-images.githubusercontent.com/47245667/163058259-8b4c216c-010d-49e3-a779-7b6119ee0705.gif)

**rust-analyzer version**: rust-analyzer version: 24cf95762 2022-04-11 stable

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: /

**Comment by dbofmmbt** [comment] 2022-04-13 02:57
I was able to reproduce the situation with the following test:

```rust
    #[test]
    fn omit_parens_when_expected_fn_parameter_is_fn() {
        cov_mark::check!(omit_parens_when_expected_fn_parameter_is_fn);

        check_edit(
            "mapper",
            r#"
fn mapper(_: usize) {}

fn main() { [1, 2, 3].iter().map(ma$0) }
"#,
            r#"
fn mapper(_: usize) {}

fn main() { [1, 2, 3].iter().map(mapper$0) }
"#,
        );
    }

```
On `should_add_parens` we check the expected type, but it's coming as `None`. In the function `expected_type_and_name`, the execution goes for the `ArgList` arm, but the `at_token` call returns None. Then it goes all the way to the source_analyzer.rs and `resolve_method_call` returns `None` on the `.method_resolution` call at the end of the function.

I expected it to be a quick fix on the completions crate, but... :sweat_smile: Maybe someone with more knowledge will be able to carry on the troubleshooting.

**Comment by Veykril** [comment] 2022-04-13 08:04
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/3148

**Comment by Veykril** [comment] 2022-04-13 08:04
This is not a quickfix unfortunately, see https://github.com/rust-analyzer/rust-analyzer/issues/8676

**Closed by Veykril** 2022-04-13 08:04 UTC
