### ISSUE TITLE
`use` inside of a function / impl block doesn't highlight imported items

### ISSUE THREAD

**Issue by q2p** [rust-analyzer/rust-analyzer#4581] opened 2020-05-23 06:06 UTC
If you write `use some::module::or::member;` inside of an impl block, or a function block, VSCode won't highlight imported items, won't provide documentation on hover, and won't provide auto-complete suggestions.

**Screenshot:**
![image](https://user-images.githubusercontent.com/11664429/82723017-b5d86600-9cf5-11ea-86d8-5e3d89b72edf.png)

**Example code:**
```rust
pub enum FileExtensions {
	PNG,
	APNG,
	WEBP,
	WEBM,
	MP4,
	M4A,
	JPEG,
	WAVE,
	MP3,
	GIF,
	OGG,
	SWF,
	Torrent,
	MatroskaVideo,
}

impl TryFrom<&str> for FileExtensions {
	type Error = ();
	fn try_from(extension: &str) -> Result<FileExtensions, ()> {
		use FileExtensions::*;
		Ok(match extension {
			"png"     => PNG,
			"apng"    => APNG,
			"webp"    => WEBP,
			"webm"    => WEBM,
			"mp4"     => MP4,
			"m4a"     => M4A,
			"ogg"     => OGG,
			"swf"     => SWF,
			"torrent" => Torrent,
			"jpeg"    => JPEG,
			"jpg"     => JPEG,
			"gif"     => GIF,
			"wav"     => WAVE,
			"wave"    => WAVE,
			"mp3"     => MP3,
			"mkv"     => MatroskaVideo,
			_ => return Err(()),
		})
	}
}
```

**Comment by lnicola** [comment] 2020-05-23 06:13
Duplicate of #1165.

**Closed by lnicola** 2020-05-23 06:13 UTC
