### ISSUE TITLE
Change visibility to pub(crate) assist

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#7079] opened 2020-12-29 13:36 UTC
I have actix-web handler function in separate file:

```
#[get("/sitemap.xml")]
async fn sitemap_xml(state: web::Data<State>) -> actix_web::Result<impl Responder> {
}
```

When I try to call this function somewhere, rust-analyzer allows to call assist which should make this function as pub. The result is:

`$0pub(crate) async fn sitemap_xml(state: web::Data<State>) -> actix_web::Result<impl Responder> {`

So there is wrong `$0` added.

**Comment by lnicola** [comment] 2020-12-29 13:58
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7037

**Closed by lnicola** 2020-12-29 13:58 UTC
