### ISSUE TITLE
Generating a function in another module doesn't work

### ISSUE THREAD

**Issue by fannheyward** [rust-analyzer/rust-analyzer#4551] opened 2020-05-21 10:39 UTC
The new `Add function` code action by `SnippetTextEdit` will fail to generate the function.

For example, there is no `bar` function in foo.rs, `foo::bar();` provides `Add function` action, but will not generate the function after the action fired.

**Comment by lnicola** [comment] 2020-05-21 11:19
It works for me when the module already exists:

```rust
fn main() {
    bar::foo(42);
}

mod bar {
}
```

It also works in the current module:

```
mod bar {
    pub(crate) fn foo(arg: i32) {
        self::baz();
        // or even
        crate::bar::baz();
    }
```

But it doesn't work with `bar::baz` because that's actually `bar::bar::baz`, which doesn't exist.

**Comment by matklad** [comment] 2020-05-23 11:42
cc @TimoFreiberg

**Comment by TimoFreiberg** [comment] 2020-05-23 20:14
I won't be able to look into this for another few days, but I'm planning on doing so

**Comment by fannheyward** [comment] 2020-05-25 09:32
After some tests, I found that `Add function` action in same module with a correct textEdit range, but if the module in a different file, the range is incorrect.

**Comment by TimoFreiberg** [comment] 2020-06-04 20:20
I can't reproduce this issue with current versions, it works properly in nvim using coc-rust-analyzer. I can't try VS Code right now as it's somehow borked on my machine :shrug: 
I'd be very thankful if anyone could try to reproduce the bug using VS Code to see if it's fixed on the latest nightly.

**Comment by fannheyward** [comment] 2020-06-05 00:56
Still not work with RA+VSCode. Yes, `coc-rust-analyzer` works for this, but fails to do selection, I just disable it because the wrong range, will look into this later.

**Comment by TimoFreiberg** [comment] 2020-07-21 17:23
Aw...
https://github.com/rust-analyzer/rust-analyzer/blob/a3ff2751b4cf8625e2874a482fe4d58da3d02891/editors/code/src/snippets.ts#L9
`vscode.window.visibleTextEditors` seems to only include editors whose content is displayed at that moment.
It works when I open the other file in a separate split, but only then.

**Closed** 2020-07-23 12:40 UTC
Labels: E-unknown
