### ISSUE TITLE
Macros emitted by other macros aren't found

### ISSUE THREAD

**Issue by nox** [rust-analyzer/rust-analyzer#8120] opened 2021-03-20 14:11 UTC
```rust
macro_rules! item {
    ($item:item) => { $item }
}

item! {
    macro_rules! indirect_macro { () => {} }
}

indirect_macro!(); // rust-analyzer sees an error here, because it doesn't know of indirect_macro.
```

```json
{
	"resource": "/Users/nox/src/ra-bug/src/lib.rs",
	"owner": "rustc",
	"code": {
		"value": "unresolved-macro-call",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#unresolved-macro-call",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "unresolved-macro-call"
		}
	},
	"severity": 8,
	"message": "unresolved macro call",
	"source": "rust-analyzer",
	"startLineNumber": 9,
	"startColumn": 1,
	"endLineNumber": 9,
	"endColumn": 15
}
```

I don't think this was ever reported, so here we are.

**Comment by jonas-schievink** [comment] 2021-03-20 22:57
This might be because we don't do this correctly during name resolution, not necessarily a problem with the macro expansion engine

**Comment by edwin0cheng** [comment] 2021-03-20 23:01
Yeah, and I remembered we handled this case in our fixed-point loop, so maybe a regression ?

**Comment by edwin0cheng** [comment] 2021-03-20 23:47
Um.. I think I know the problem :

1. In first collecting phase, we collected `item!()` and `indirect_macro!()` macro_calls
2. When expanding `item!()`, we defined a new macro rules `indirect_macro!` in legacy scope.
3. When resolving `indirect_macro`, we only search for module scope. (Because we assumed it cannot be resolved in legacy scope in (1).

But I don't know what's the correct way to fix it ? @jonas-schievink any idea?

**Comment by jonas-schievink** [comment] 2021-03-20 23:56
I think we should expand `item!` *during* collection phase, I believe that's closer to how legacy macros work in rustc anyways. This should always work for legacy macros since they don't need the fixed-point loop.

Not sure how difficult this is to implement, I might look into it later.

**Comment by jonas-schievink** [comment] 2021-03-21 00:46
Turns out this was really easy, unless I missed something https://github.com/rust-analyzer/rust-analyzer/pull/8128

**Closed** 2021-03-21 15:29 UTC
Labels: A-macro, S-actionable
