### ISSUE TITLE
Go to implementations should work on trait functions.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#8537] opened 2021-04-15 20:18 UTC
Feature request: "Go to Implementations" should work on trait functions.

E.g.:

```
trait Tr {
    fn f();
}

struct S;

impl Tr for S {
    fn f() {
        println!("Hello, world!");
    }
}
```

"Go to Implementations" on the trait's `fn f();` should go to the implementation in `S`.

**Comment by DJMcNab** [comment] 2021-04-15 20:25
Probably duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4558

**Comment by umanwizard** [comment] 2021-04-15 20:37
That seems a bit different, if I'm understanding it correctly -- it's about going to the definition of a trait function from the call, rather than going to implementations from inside the trait definition.

**Comment by DJMcNab** [comment] 2021-04-15 21:28
Oh yeah, sorry. That's what I get for trying to triage at a late hour 😅

**Closed** 2021-05-25 13:22 UTC
Labels: A-assists, S-actionable
