### ISSUE TITLE
Does not work for attribute proc macros

### ISSUE THREAD

**Issue by dakyskye** [rust-analyzer/rust-analyzer#6029] opened 2020-09-18 09:34 UTC
rust-analyzer does not work for this file:
```rs
use serenity::{
    client::*,
    framework::standard::{macros::command, Args, CommandResult},
    model::channel::Message,
};

#[command]
fn clear(ctx: &mut Context, msg: &Message, args: Args) -> CommandResult {
    Ok(())
}
```
No intellisense, no completion, nothing works. I assume it's because of `command` macro?

**Comment by lnicola** [comment] 2020-09-18 09:35
Yes, attribute proc macros are not supported.

**Comment by lnicola** [comment] 2020-09-18 09:39
I can't edit the issue title, can you rename it to something like the above?

CC #5412, #2984.

**Comment by flodiebold** [comment] 2020-09-18 09:48
Most features should still work as if the attribute wasn't there though.

**Comment by lnicola** [comment] 2020-09-18 09:51
@dakyskye can you confirm that completions are not working?

![image](https://user-images.githubusercontent.com/308347/93584209-ac15f500-f9ad-11ea-8eee-8ec95a49201c.png)

**Comment by dakyskye** [comment] 2020-09-18 10:32
@lnicola yes ![image](https://user-images.githubusercontent.com/32128756/93587976-c8209300-f9bb-11ea-89bd-29bf6cb7373a.png)

**Comment by lnicola** [comment] 2020-09-18 10:43
Is that Vim? How did you configure `rust-analyzer`?

**Comment by dakyskye** [comment] 2020-09-18 11:13
@lnicola it is NeoVim, yes, with coc.nvim extension. That's the only rust-analyser config I have `"rust-analyzer.serverPath": "rust-analyzer"`

**Comment by lnicola** [comment] 2020-09-18 11:16
Can you run it (from the same terminal) with `rust-analyzer --version`? If you installed from source, it should be under `~/.cargo/bin`, and I'd expect that to be in `PATH`, but it doesn't hurt to check.

**Comment by dakyskye** [comment] 2020-09-18 11:22
Weird enough! My output for it is `rust-analyzer ???????`. I installed it from the Arch packages.

**Comment by dakyskye** [comment] 2020-09-18 11:22
`pacman -S rust-analyzer` outputs `rust-analyzer-20200914-1 is up to date`.

**Comment by lnicola** [comment] 2020-09-18 11:24
Can you try https://github.com/fannheyward/coc-rust-analyzer/ instead? I think the official extension doesn't work too well with `coc.nvim`.

**Comment by dakyskye** [comment] 2020-09-18 11:25
I use `coc-rust-analyzer`, but with custom `rust-analyzer` path.

**Comment by dakyskye** [comment] 2020-09-18 11:29
I have also tried it in VSCode though, the same negative result.

**Comment by lnicola** [comment] 2020-09-18 11:34
Does it work for you (in Code) with a new project?

**Comment by dakyskye** [comment] 2020-09-18 11:38
Nope
![image](https://user-images.githubusercontent.com/32128756/93593346-02426280-f9c5-11ea-815f-0b43f51cbc38.png)

**Comment by lnicola** [comment] 2020-09-18 11:40
Sorry, I meant a new project as `cargo new` produces.

**Comment by dakyskye** [comment] 2020-09-18 11:40
Yes, I did that.

**Comment by matklad** [comment] 2020-10-15 11:11
Can't reproduce, maybe this is fixed in master?

![image](https://user-images.githubusercontent.com/1711539/96115926-fa081500-0ee7-11eb-896e-0c487a44579d.png)

**Comment by dakyskye** [comment] 2020-10-16 08:55
It's weird. I have just tried it in VSCode, Vim and Emacs, works nowhere.

**Comment by dakyskye** [comment] 2020-10-16 08:58
Ah, you said "master". I have latest release installed, let me build RA myself and try again.

**Comment by matklad** [comment] 2020-10-16 09:46
@dakyskye if you run **Rust Analyzer: Status** command, does it list anything as file deps?

![image](https://user-images.githubusercontent.com/1711539/96243574-38173e80-0fa5-11eb-9e42-53869b2f2b37.png)

**Comment by dakyskye** [comment] 2020-10-17 09:40
I accidentally deleted vscode package, and just reinstalled it. Now rust-analyzer works well for me in VSC. Let me try it in Emacs now
![image](https://user-images.githubusercontent.com/32128756/96333978-5bfa8300-107e-11eb-8327-37c8d1a7327c.png)

**Comment by dakyskye** [comment] 2020-10-17 09:52
It started working in VSCode, but still not works in Vim and Emacs.

**Comment by seanybaggins** [comment] 2021-01-07 22:24
I am having a similar issue.

Rust analyzer status
```
workspaces:
54 packages loaded

analysis:
4067 (46mb) files
0 (0b) index symbols
1211 trees, 128 retained
18692 trees, 128 retained (macros)
472mb total


requests:
  783 textDocument/semanticTokens/full/delta2ms
  784 completionItem/resolve              1ms
  785 textDocument/foldingRange           0ms
  786 textDocument/codeLens               0ms
  787 textDocument/codeAction             1ms
  788 textDocument/documentSymbol         0ms
  791 textDocument/codeAction             1ms
* 779 textDocument/documentSymbol         0ms
  781 rust-analyzer/inlayHints            6ms
  782 textDocument/completion             7ms

```

![image](https://user-images.githubusercontent.com/18423154/103951020-2b653b00-50fb-11eb-8ea3-af8cc829dd43.png)

You can find the code with a Dockerfile to reproduce the environment [here](https://github.com/seanybaggins/ipendulum/tree/78cc551ef2c519400981e1375965e47d390a0795/implementation)

**Comment by anirudhb** [comment] 2021-03-03 04:15
Any plans to work on this? Is there anything blocking this?

**Comment by AlaaZorkane** [comment] 2021-03-13 18:39
Similar issue with `wasm_bindgen` :/ (no typings and no type completion)

![image](https://user-images.githubusercontent.com/2952507/111040560-b6ccb680-8433-11eb-9462-a97003e74b5e.png)
![image](https://user-images.githubusercontent.com/2952507/111040561-bdf3c480-8433-11eb-9174-398c9739c771.png)

**Comment by jonas-schievink** [comment] 2021-03-13 21:44
> Any plans to work on this? Is there anything blocking this?

In short, what needs to be done to get this working is:
* Record derive helper attributes, so that they can later be resolved (this is just to avoid false positives from the next step)
* Resolve attributes on items during name resolution (done in #7049, but without the above step)
* Let it bake for a while and fix any false positives that come up
* Change name resolution to not process items until all attached attributes are resolved (this can ignore proc. macro attributes to keep the current behavior)
* When an attribute gets resolved to a proc. macro, expand it like we do for custom derives, but replacing the original item

**Comment by jmg-duarte** [comment] 2021-03-18 12:39
I think this is the best place to put this issue.
I have a macro that adds a field to a `struct`.
For example:
```rust
#[add]
struct S;
```
Gets expanded to:
```rust
struct S { pub field: T }
```
While this compiles without a problem, `rust-analyzer` reports: `no such field`.

**Comment by bjorn3** [comment] 2021-03-18 12:58
Missing autocompletion is just a symptom of the fact that attribute proc macros are currently unimplemented.

**Comment by DanielJoyce** [comment] 2021-04-13 04:05
Yeah, would this explain why mockall_double #[double] macro doesn't work?

**Comment by sanfusu** [comment] 2021-04-17 12:35
Are there any plans to support this feature？

**Comment by abreis** [comment] 2021-04-17 12:36
Yes, it's on the roadmap for the next six weeks: #8486

**Closed** 2021-06-03 16:24 UTC
Labels: A-macro, A-nameres, S-actionable

**Comment by dakyskye** [comment] 2021-06-03 18:46
Oh, finally 🎉 🎉
