### ISSUE TITLE
Trait Bound on un-imported `Hash`  does not provide a `use std::hash::Hash` assist.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#9527] opened 2021-07-07 23:33 UTC
minimal repro:

```rust
struct Foo<K> where K: Hash$0 {
    k: K
}
```

When we try to use quick fix at `$0`, it will not offer to try to import `std::hash::Hash`

![2021-07-07_16-32-22](https://user-images.githubusercontent.com/5489149/124840932-e9e60900-df40-11eb-99e4-9d19daa6c4a4.gif)

I believe this is caused because `Hash` is also a derive macro, but is not included in the stdlib prelude (which is why it works for `Default`, `Clone`, etc...) rustc provides some insight here:

```rust
error[E0404]: expected trait, found derive macro `Hash`
 --> src/main.rs:5:24
  |
5 | struct Foo<K> where K: Hash {
  |                        ^^^^ not a trait
  |
help: consider importing one of these items instead
  |
5 | use core::hash::Hash;
  |
5 | use std::hash::Hash;
  |
  ```

**Comment by Veykril** [comment] 2021-07-08 00:27
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7408

**Closed by Veykril** 2021-07-08 00:27 UTC
