### ISSUE TITLE
Message: Failed to deserialize textDocument/hover: .: missing field `line`; 

### ISSUE THREAD

**Issue by doivosevic** [rust-analyzer/rust-analyzer#9873] opened 2021-08-12 16:02 UTC
I'm getting this output from Rust Analyzer Language Server. I do not have a concrete repro right now as I've just returned from vacay so I'll try and cook something up later.  Everything worked when I stopped working 10 days ago, only thing I did since I came back is updated vscode to latest 1.59.0 from whatever was 2 weeks ago

rust analyzer version: 0.2.702
remote sshing into ubuntu from windows 10 with latest updates
```
Version: 1.59.0 (system setup)
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

```

[Error - 3:49:00 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":27,"character":52},"end":{"line":28,"character":41}}}
  Code: -32602 
[Error - 3:49:17 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":29,"character":35},"end":{"line":29,"character":54}}}
  Code: -32602 
[Error - 3:49:27 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":38,"character":0},"end":{"line":38,"character":0}}}
  Code: -32602 
[Error - 3:50:09 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":38,"character":0},"end":{"line":38,"character":0}}}
  Code: -32602 
[Error - 3:51:10 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":21,"character":0},"end":{"line":21,"character":0}}}
  Code: -32602 
[Error - 3:52:00 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":44,"character":23},"end":{"line":44,"character":45}}}
  Code: -32602 
[Error - 3:52:01 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":44,"character":23},"end":{"line":44,"character":45}}}
  Code: -32602 
[Error - 3:52:05 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/mister/file.rs"},"position":{"start":{"line":44,"character":28},"end":{"line":44,"character":45}}}
  Code: -32602 
```

**Comment by lnicola** [comment] 2021-08-13 04:25
That sounds like a mismatch between the language server and the extension version. Do you have a server path set in the remote Code config?

**Comment by vallentin** [comment] 2021-08-13 10:37
I've had this issue as well for the past 1-2 weeks. I finally figured out a way to reproduce it consistently.

1. Go into any .rs file - even just `cargo new foo` and open `main.rs`
2. Click ANYWHERE with the mouse cursor, so a text cursor is placed
3. Move the mouse cursor away
4. Move the mouse cursor on top (or really close) to the text cursor

This consistently posts the same error message as @doivosevic's to the "Output" panel for me.

GIF:

![GIF 13-08-2021 12-25-09](https://user-images.githubusercontent.com/17464404/129343675-a0061d22-0da8-4fe4-bf46-bb3c7fc2e966.gif)

Here's 3 of the same errors:

```
[Error - 12:17:10 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/vallentin/ra-issue/src/main.rs"},"position":{"start":{"line":1,"character":30},"end":{"line":1,"character":30}}}
  Code: -32602 
[Error - 12:17:20 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/vallentin/ra-issue/src/main.rs"},"position":{"start":{"line":1,"character":9},"end":{"line":1,"character":9}}}
  Code: -32602 
[Error - 12:19:11 PM] Request textDocument/hover failed.
  Message: Failed to deserialize textDocument/hover: .: missing field `line`; {"textDocument":{"uri":"file:///home/vallentin/ra-issue/src/main.rs"},"position":{"start":{"line":3,"character":0},"end":{"line":3,"character":0}}}
  Code: -32602
```

I've tried reinstalling rust-analyzer, and that didn't change anything.

Versions:
- rustc 1.49.0 (e1884a8e3 2020-12-29)
- rust-analyzer version: e5c1c8cf2 2021-07-05 stable
- VSCode - Version: 1.59.0 (user setup), Date: 2021-08-04T23:13:12.822Z, OS: Windows_NT x64 10.0.19043

For what it's worth, I'm using Ubuntu through WSL on Windows.

-----

_On_ the Windows machine itself, I don't have this issue. However, I'm also using Rust 1.54 and can see that I'm also using a different version of rust-analyzer as well.

- rustc 1.54.0 (a178d0322 2021-07-26)
- rust-analyzer version: 5664a2b0b 2021-08-09 stable

Not sure if the version difference is due to the older Rust version, or because it hasn't updated?

**Comment by lnicola** [comment] 2021-08-13 10:39
@vallentin

> rust-analyzer version: e5c1c8c 2021-07-05 stable

Why are you using a `rust-analyzer` version that's a month older than the Code extension?

**Comment by vallentin** [comment] 2021-08-13 10:44
I honestly don't know? When rust-analyzer prompts to download an update, I do so. So I guess it haven't prompted an update for some time? Though I did reinstall the rust-analyzer extension just the other day. I just did it right now as well. Isn't it supposed to check for an update and prompt?

**Comment by lnicola** [comment] 2021-08-13 10:47
The extension should download the corresponding server binary unless another one has been set in `settings.json`. Can you check for the latter (on the remote side) and maybe reinstall the extension? There was a short period of time when the version checking was broken.

**Comment by vallentin** [comment] 2021-08-13 10:54
> unless another one has been set in `settings.json`

I have never specified one manually, and the only thing in my settings are:

```json
"rust-analyzer.cargo.allFeatures": true,
"rust-analyzer.diagnostics.disabled": [
    "unresolved-import",
    "macro-error",
],
```

> maybe reinstall the extension

I just did before :)

When I check the installed extension version, it says `matklad.rust-analyzer@0.2.702`, which is the newest according to VSCode Marketplace.

However, I still haven't gotten any prompt to update rust-analyzer and it still says `rust-analyzer version: e5c1c8cf2 2021-07-05 stable`.

**Comment by flodiebold** [comment] 2021-08-13 10:54
Try deleting the downloaded rust-analyzer binary from the extension.

**Comment by vallentin** [comment] 2021-08-13 11:01
Deleting the rust-analyzer binary and reloading VSCode, then it finally prompted it to download 🎉 

- rust-analyzer version: 5664a2b0b 2021-08-09 stable

_I of course don't know if this is the same problem as @doivosevic._

**Comment by mvanbem** [comment] 2021-08-14 20:48
I also ran into this issue and resolved it by deleting the downloaded rust-analyzer binary.

For anyone else who is confused like I was, the path is documented in the user manual: https://rust-analyzer.github.io/manual.html#vs-code

**Comment by doivosevic** [comment] 2021-08-16 13:58
What worked for me is updating rust-analyzer. Apparently the vscode extension version used was through nix which was using an older version. Now I don't seem to have any problems

**Comment by lnicola** [comment] 2021-08-16 14:03
Let's close this, it was a version mismatch.

**Closed by lnicola** 2021-08-16 14:03 UTC
