### ISSUE TITLE
VSCode: Cannot destructure property `releaseName` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by Progdrasil** [rust-analyzer/rust-analyzer#3347] opened 2020-02-27 14:11 UTC
I just installed the **rust-analyzer** extension on vscode and it was unable to download the binary automatically. it gave me the following error:
> Failed to download language server from rust-analyzer GitHub repository: Cannot destructure property `releaseName` of 'undefined' or 'null'.

My environment:
* manjaro linux
* rust: stable-x86_64-unknown-linux-gnu (default) rustc 1.41.0 (5e1a79984 2020-01-27)
* vscode 1.41.1
* rust-analyzer: 0.1.20200211

**Comment by lnicola** [comment] 2020-02-27 14:12
> rust-analyzer: 0.1.20200211

Did you _just_ install it from the Code Marketplace? This is an old version of the extension. If you update it, the server binary download should work.

This happens because the server binary name has changed.

**Comment by Progdrasil** [comment] 2020-02-27 14:14
yes i _just_ installed it

**Comment by lnicola** [comment] 2020-02-27 14:16
https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer shows it at `0.1.20200224`.

@Veetaha any idea?

**Comment by Progdrasil** [comment] 2020-02-27 14:23
Interesting, when I uninstall the extensions and search for it, it show the right version. However once I install it, it reverts to the version mentioned in the description

**Comment by Veetaha** [comment] 2020-02-27 16:07
@Progdrasil, did you install the extension from source previously?

**Comment by Veetaha** [comment] 2020-02-27 16:23
And do you mind showing the console logs?
`VSCode > Help > Toggle Developer Tools > Console`.

It's interesting to find out how you stumbled upon this. I am pretty sure that the extension has to download only the **matching** version, even an old one.

To fix this problem for you I recommend running (on Ubuntu):
```
rm -rf ${HOME}/.vscode/extensions/matklad.rust-analyzer-0.1.0
rm -rf ${HOME}/.config/Code/User/globalStorage/matklad.rust-analyzer
```
```

**Comment by lnicola** [comment] 2020-02-27 16:24
Could it also be related to the ongoing GitHub issues?

**Comment by not-much-io** [comment] 2020-02-27 18:01
I had the same issue, I can confirm this is as @lnicola said related to the binary name having changes and that updating the vscode plugin fixed the issue for me.

For me since I was hacking on rust-analyzer I installed the plugin from source because it was a command away.

VSCode didn't show me that there was an update for the plugin which might be related to me being on a plugin installed from source before the update where the name was changed.

**Comment by lnicola** [comment] 2020-02-27 18:03
> For me since I was hacking on rust-analyzer I installed the plugin from source because it was a command away.

A command and a preference change away :smiley:. Confusion will ensue otherwise.

**Comment by Veetaha** [comment] 2020-02-27 18:28
Hmmm, I guess I know the root cause. The 02-11 version fetches the latest release, but the latest release contains renamed binary name

**Comment by Veetaha** [comment] 2020-02-27 18:29
Since this is fixed in the new version, we may close this, @matklad ?

**Comment by lnicola** [comment] 2020-02-27 18:39
@Veetaha @Progdrasil said they've installed it from the marketplace.

**Comment by Veetaha** [comment] 2020-02-27 18:57
> Interesting, when I uninstall the extensions and search for it, it show the right version (0.1.20200224). However once I install it, it reverts to the version mentioned in the description (0.1.20200211)

I am pretty sure that the logic introduced in #3162 must ensure that the extension is looking only for a release with the relevant binary name.
Anyway, should have added a double check that the needed binary did is published.

**Comment by Progdrasil** [comment] 2020-02-27 19:00
> @Progdrasil, did you install the extension from source previously?

No i did not

when I install the extension the only log i have regarding rust-analyzer
```console
[Extension Host] 
/home/rene/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/ra_lsp_server-linux --version output: undefined
```
then when i click `Download now` button:
```console
[Extension Host] 
Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/latest

notificationsAlerts.ts:40 
Failed to download language server from rust-analyzer GitHub repository: Cannot destructure property `releaseName` of 'undefined' or 'null'.
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:581
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

notificationsAlerts.ts:40 
Rust Analyzer Language Server is not available. Please, ensure its [proper installation](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code).
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:581
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

[Extension Host] DNS resolution for example.com was successful ["93.184.216.34"]
```

**Comment by Veetaha** [comment] 2020-02-27 19:04
Okay, so you somehow ended up using the `2020-02-11` version (not sure how), because the request it issues goes to for `ra_lsp_server` binary to `rust-analyzer/releases/latest`, whiles the latest release binary is renamed, that's why it crashes.

**Comment by Progdrasil** [comment] 2020-02-27 19:04
> And do you mind showing the console logs?
> `VSCode > Help > Toggle Developer Tools > Console`.
> 
> It's interesting to find out how you stumbled upon this. I am pretty sure that the extension has to download only the **matching** version, even an old one.
> 
> To fix this problem for you I recommend running (on Ubuntu):
> 
> ```
> rm -rf ${HOME}/.vscode/extensions/matklad.rust-analyzer-0.1.0
> rm -rf ${HOME}/.config/Code/User/globalStorage/matklad.rust-analyzer
> ```
> 
> And then reinstalling the extension from the marketplace

As for removing the directories, only the directory under `.vscode` existed. However it does not change the behavior on installation.

**Comment by lnicola** [comment] 2020-02-27 19:05
> As for removing the directories, only the directory under .vscode existed. However it does not change the behavior on installation.

Make that `~/.vscode-oss` and `~/.config/Code\ -\ OSS`.

**Comment by Veetaha** [comment] 2020-02-27 19:08
Please, ensure that `~/.vscode/extensions/` folder contains only one `matklad.rust-analyzer-0.2.20200224` directory, if there are any of 
```
matklad.rust-analyzer-0.2.20200211-dev
matklad.rust-analyzer-0.0.1
```
You should remove them, otherwise you still use the old version of the extension...

**Comment by Progdrasil** [comment] 2020-02-27 19:09
yes, I was refering to the ubuntu directories my actual command is:
```
rm -fr  ~/.vscode-oss/extensions/matklad.rust-analyzer-0.1.20200211     
ls ~/.config/Code\ -\ OSS/User/globalStorage      
                                                                                                                             
    state.vscdb  state.vscdb.backup
```
and the global storage had no matklad directory

**Comment by lnicola** [comment] 2020-02-27 19:10
What if you download the VSIX from the release page?

**Comment by Progdrasil** [comment] 2020-02-27 19:10
> Please, ensure that `~/.vscode/extensions/` folder contains only one `matklad.rust-analyzer-0.2.20200224` directory, if there are any of
> 
> ```
> matklad.rust-analyzer-0.2.20200211-dev
> matklad.rust-analyzer-0.1.20200211  
> matklad.rust-analyzer-0.0.1
> ```
> 
> You should remove them, otherwise you still use the old version of the extension...

```
ls ~/.vscode-oss/extensions | rg matklad
matklad.rust-analyzer-0.1.20200211
```

**Comment by Veetaha** [comment] 2020-02-27 19:13
You might want to click `Uninstall` button in VSCode first and then remove that directory under `~/.vscode-oss/extensions`

**Comment by bjorn3** [comment] 2020-02-27 19:18
Also you should restart vscode before installing again I think.

**Comment by Progdrasil** [comment] 2020-02-27 19:20
> You might want to click `Uninstall` button in VSCode first and then remove that directory under `~/.vscode-oss/extensions`

seeing as there is much confusion here are my steps:

1. install `rust-analyzer` from market place
2. check version, if == 0.1.20200211 then
3. uninstall `rust-analyzer` with button
4. ```bash
rm -fr  ~/.vscode-oss/extensions/matklad.rust-analyzer-0.1.20200211 # Succeeds
 rm -rf~/.config/Code\ -\ OSS/User/globalStorage/matklad.rust-analyzer # Does not exist
```
5. reload vscode window
6. Reinstall `rust-analyzer`
7. goto step 2.


> What if you download the VSIX from the release page?
> 
> Or even from https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer.

after dowing this I get the following console messages
```console
notificationsAlerts.ts:38 
Error
onDidNotificationChange @ notificationsAlerts.ts:38

log.ts:184   
ERR Unable to install extension 'matklad.rust-analyzer' as it is not compatible with VS Code '1.41.1'.: Error: Unable to install extension 'matklad.rust-analyzer' as it is not compatible with VS Code '1.41.1'.
    at file:///usr/lib/code/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:411:762
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by Veetaha** [comment] 2020-02-27 19:21
Yeah, and you need to update the vscode to 1.42 :sweat_smile: (#3139)

**Comment by Progdrasil** [comment] 2020-02-27 19:23
Ah. that version is not in my package manager yet

**Comment by lnicola** [comment] 2020-02-27 19:29
1.42 showed up in Arch on Feb 17, and even so it was two weeks late.

**Comment by Progdrasil** [comment] 2020-02-28 15:44
As of today, 1.42.1 landed in Manjaro. I can confirm the the install works correctly now.

**Closed** 2020-02-28 15:49 UTC
