### ISSUE TITLE
nightly rust yield syntax error

### ISSUE THREAD

**Issue by whaqzhzd** [rust-analyzer/rust-analyzer#6998] opened 2020-12-22 12:42 UTC
I used nightly rust which is not yet stable generators and generator_trait Implementation. Is there any way I can block the error?
```rust
#[cfg(test)]
mod test {
    #![feature(generators, generator_trait)]

    use std::{
        pin::Pin,
        sync::{atomic::AtomicI32, Arc},
    };

    use std::{
        ops::{Generator, GeneratorState},
        sync::atomic::Ordering,
    };

    fn test(count: Arc<AtomicI32>) -> impl Generator<Return = (), Yield = ()> {
        move || {
            loop {
                count.fetch_add(1, Ordering::SeqCst);
                if count.load(Ordering::SeqCst) > 2 {
                    break;
                }
                yield;
            }

            return;
        }
    }

    fn test1(
        count: Arc<AtomicI32>,
    ) -> impl Generator<Return = (), Yield = impl Generator<Return = (), Yield = ()>> {
        move || {
            loop {
                
                let t = test(count.clone());
                // Syntax Error: expected SEMICOLON rust-analyzer
                yield t;
            }
            return;
        }
    }

    pub struct A {
        pub gen: Box<dyn Generator<Return = i32, Yield = i32>>,
    }

    #[test]
    fn testa() {
        let count = Arc::new(AtomicI32::new(0));
        let clone = count.clone();
        let mut a = Box::new(test1(clone));
        let a = &mut a;
    }

    fn firstn(n: u64) -> impl Generator<Yield = u64, Return = ()> {
        move || {
            let mut num = 0;
            while num < n {
                yield num;
                num += 1;
            }
        }
    }

    struct GeneratorIteratorAdapter<G>(Pin<Box<G>>);

    impl<G, E> GeneratorIteratorAdapter<G>
    where
        G: Generator<Return = (), Yield = E>,
        E: Generator<Return = (), Yield = ()>,
    {
        fn new(gen: G) -> Self {
            Self(Box::pin(gen))
        }
    }

    impl<G> Iterator for GeneratorIteratorAdapter<G>
    where
        G: Generator<Return = ()>,
    {
        type Item = G::Yield;

        fn next(&mut self) -> Option<Self::Item> {
            match self.0.as_mut().resume(()) {
                GeneratorState::Yielded(x) => Some(x),
                GeneratorState::Complete(_) => None,
            }
        }
    }

    #[test]
    fn t() {
        let count = Arc::new(AtomicI32::new(0));
        let clone = count.clone();
        let generator_iterator = GeneratorIteratorAdapter::new(test1(clone));

        start_(generator_iterator);
    }

    fn start_(
        generator_iterator: GeneratorIteratorAdapter<
            impl Generator<(), Return = (), Yield = impl Generator<(), Return = (), Yield = ()> + Unpin>,
        >,
    ) {
        for mut i in generator_iterator.into_iter() {
            match Pin::new(&mut i).resume(()) {
                GeneratorState::Yielded(t) => {
                    println!("s");
                }
                _ => break,
            }
        }
    }
}

```

![image](https://user-images.githubusercontent.com/16913061/102889690-0d120500-4496-11eb-89a6-5651999c8040.png)

**Comment by jonas-schievink** [comment] 2020-12-22 13:16
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4309

**Closed by jonas-schievink** 2020-12-22 13:16 UTC
Labels: A-parser, S-actionable
