### ISSUE TITLE
Type inference goes in the wrong direction

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#4618] opened 2020-05-26 11:11 UTC
### To reproduce

1. Open the following program in VSCode:
    ```rust
    // [dependencies]
    // rand = "0.7"

    fn main() {
        use rand::seq::SliceRandom;
        let (x, y) = [(1, 2)].choose(&mut rand::thread_rng()).unwrap();
        let x: i32 = x;
    }
    ```
2. Mouse hover over `x` in `let (x, y) = ...`.

### Expected result

The inferred type should be `&i32`.
Alternatively, if we accept Chalk limitations or [whatever this is](https://github.com/rust-analyzer/rust-analyzer/issues/4619), `{unknown}`.

### Actual result

The inferred type is `i32`.
This makes the error in the next line confusing.

By the way, the inferred type of `y` is `{unknown}`.
Removing the next line turns the inferred type of `x` into `{unknown}` as well.

![image](https://user-images.githubusercontent.com/302938/82894003-955d1580-9f5a-11ea-9cd2-f292910ded90.png)

```
rust-analyzer version: 2020-05-25 (fbb8b88)
```

**Comment by lnicola** [comment] 2020-05-26 11:31
Duplicate of #1165.

![image](https://user-images.githubusercontent.com/308347/82895851-980d3a00-9f5d-11ea-9be7-1c698be152c5.png)

**Closed** 2020-05-26 11:33 UTC

**Comment by flodiebold** [comment] 2020-05-26 11:36
Type inference after type errors is best-effort; we infer `x` as `i32` from the subsequent usage to still give you useful completions.

So yeah, I'd also consider this a duplicate.
