### ISSUE TITLE
Postfix completion panic in macro

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9305] opened 2021-06-17 00:37 UTC
```rs
info!("Downloading «{}» ({})", dest.display().to_string().green(), response.url().as$0.blue());
```

```
thread '<unnamed>' panicked at 'assertion failed: start <= end', /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/text-size-1.1.0/src/range.rs:48:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: ide_completion::completions::postfix::postfix_snippet
   4: ide_completion::completions::postfix::complete_postfix
   5: ide_completion::completions
   6: std::panicking::try
   7: ide::Analysis::completions
   8: rust_analyzer::handlers::handle_completion
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment] 2021-10-03 20:55
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10243

**Closed by Veykril** 2021-10-03 20:55 UTC
Labels: A-completion, S-actionable
