### ISSUE TITLE
Resolve does not see local use declaration in scope

### ISSUE THREAD

**Issue by avrong** [rust-analyzer/rust-analyzer#5995] opened 2020-09-13 09:50 UTC
As a result, no completion is suggested, `go to definition` does not work, etc.

<img width="400" src="https://user-images.githubusercontent.com/6342851/93015042-b22b6080-f5be-11ea-9c0a-29507eaff545.png">

```rust
fn main() {
    use std::collections::HashMap;

    let hashmap = HashMap::<String, String>::new();
}
```

**Comment by lnicola** [comment] 2020-09-13 10:45
Duplicate of #1165.

**Closed by lnicola** 2020-09-13 10:45 UTC
