### ISSUE TITLE
Feature request: Add new arguments assist

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#10361] opened 2021-09-26 18:47 UTC
```Rust
struct TypeA;
struct TypeB;

fn foo(a: TypeA, b: TypeB) {
    sub1(a, b);
    sub2(a, b);
    //   ^ User requests "Add new arguments" assist in parameter list
}

fn sub1(a: TypeA, b: TypeB) {

}

fn sub2() {

}
```

Rust analyzer would change `sub2` to the following:

```Rust
fn sub2(a: TypeA, b: TypeB) {

}
```

This assist would only be available if there are new arguments that can be added at the end of the parameter list of the function signature. For example, if `sub2` already had parameter `a`, only `b` would be added.

**Comment by lnicola** [comment] 2021-09-27 07:53
Duplicate of #6499.

**Closed by lnicola** 2021-09-27 07:53 UTC

**Comment by crumblingstatue** [comment] 2021-09-27 08:09
I don't think this is exactly the same, because this assist would be invoked at the call site, not at the definition site

**Comment by lnicola** [comment] 2021-09-27 08:10
We need to find a good UX, preferably within the LSP limitations. It might be an assist invoked on the caller or callee side, but we won't make two of them. Feel free to post your thoughts in the other issue, though.

**Comment by crumblingstatue** [comment] 2021-09-27 08:15
I don't see the problem with having 2.
For the assist at definition site, the arguments would be provided by the user.
For the assist at the call site, the arguments would be inferred from the call.
They are 2 different assists useful in 2 different contexts.
Can you give a rationale on why we couldn't have 2?
But I'll post these thoughts on the other issue as well.

**Comment by lnicola** [comment] 2021-10-02 09:12
Since they're doing almost the same thing, I think it makes sense to discuss both in the same issue.
