### ISSUE TITLE
Exception when loading the VSCode plugin

### ISSUE THREAD

**Issue by jeluard** [rust-analyzer/rust-analyzer#8057] opened 2021-03-16 16:57 UTC
```
[matklad.rust-analyzer]: 'configuration.property' must be an object
```

It's not clear to me if this prevents part of the plugin to work or not. Is there anything to do to fix that?

**Comment by lnicola** [comment] 2021-03-16 18:06
It's all right, I think. Dupe of #7789.

**Closed by lnicola** 2021-03-16 18:06 UTC

**Comment by jeluard** [comment] 2021-03-26 07:52
With latest plugin version I now get the following:

```js
root ERROR [6192cfe4-b6f9-4328-a493-b51cdd6127fe][matklad.rust-analyzer]: Failed to load 'configuration' contribution. TypeError: Cannot create property 'scope' on boolean 'false'
    at Object.fromPreferenceSchemaProperty (http://localhost:3000/bundle.js:64880:31)
    at PreferenceSchemaProvider.../node_modules/@theia/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.doSetSchema (http://localhost:3000/bundle.js:40527:82)
    at PreferenceSchemaProvider.../node_modules/@theia/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.setSchema (http://localhost:3000/bundle.js:40608:28)
    at http://localhost:3000/48.bundle.js:12206:103
    at pushContribution (http://localhost:3000/48.bundle.js:12197:32)
    at _loop_1 (http://localhost:3000/48.bundle.js:12206:17)
    at PluginContributionHandler.push.../node_modules/@theia/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/48.bundle.js:12211:21)
    at _loop_2 (http://localhost:3000/48.bundle.js:1344:63)
    at HostedPluginSupport.push.../node_modules/@theia/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadContributions (http://localhost:3000/48.bundle.js:1365:17)
    at HostedPluginSupport.<anonymous> (http://localhost:3000/48.bundle.js:1211:52)
```

Is it worth opening a new issue @lnicola ?

**Comment by lnicola** [comment] 2021-03-26 07:58
No, it's the same issue as #7789. Last time I tried, the extension still worked despite the error. Does it actually fail to load for you now?

**Comment by jeluard** [comment] 2021-03-26 08:10
I am trying to load it in https://theia-ide.org/ and it fails.
I am unclear if this error plays a role in it or not.

**Comment by lnicola** [comment] 2021-03-26 08:17
Can you try to edit the `package.json` and remove those lines?

**Comment by jeluard** [comment] 2021-03-26 08:40
I can confirm that cleaning up the `package.json` removes the error message. Still the extension doesn't work.

I can see another error message:

```js
root ERROR [hosted-plugin: 49778] Activating extension 'rust-analyzer' failed: TypeError: Class extends value undefined is not a constructor or null
    at /Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:12905:63
    at createCommonjsModule (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:66:9)
    at Object.<anonymous> (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:11119:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.module._load (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:67:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

Does that ring a bell @lnicola ?

**Comment by lnicola** [comment] 2021-03-26 08:42
No, not really. I suppose it's hard to tell what's `extension/out/src/main.js:12905`.

**Comment by jeluard** [comment] 2021-03-26 08:48
This line: 

```js
class LSPCancellationError extends vscode__default['default'].CancellationError {
```

**Comment by lnicola** [comment] 2021-03-26 08:50
It means that `vscode__default['default'].CancellationError` doesn't exist.

**Comment by jeluard** [comment] 2021-03-26 09:11
DO you know by any chance starting when `rust-analyzer` started depending on it?

**Comment by lnicola** [comment] 2021-03-26 09:14
I'm not sure, might have been https://github.com/rust-analyzer/rust-analyzer/pull/7701 or earlier.

**Comment by jeluard** [comment] 2021-03-26 09:25
Thanks for the help!

**Comment by jeluard** [comment] 2021-03-26 10:30
BTW, it works ok-ish with older versions (like 489).

Except for files with heavy macro usage:

![Capture d’écran 2021-03-26 à 11 28 20](https://user-images.githubusercontent.com/359723/112618593-93880b00-8e26-11eb-8126-d1055dca8724.png)

Then there is this weird `<<MISSING COMMAND>>` message. What could trigger this?

**Comment by Veykril** [comment] 2021-03-26 11:08
That's due to us sending annotations for files that aren't being indexed by RA, so when those get resolved we don't actually send commands back causing this inline Error. This has been fixed in recent versions.

**Comment by jeluard** [comment] 2021-03-26 13:33
@Veykril Should it be fixed in `0.2.521` ?

**Comment by lnicola** [comment] 2021-03-26 13:36
I think it was fixed in https://github.com/rust-analyzer/rust-analyzer/pull/8015, which went into `0.2.529`.

**Comment by jeluard** [comment] 2021-03-26 14:11
Indeed, I don't have the missing command with latest nightly 👍  
But I don't have any completion or code navigation either in those macros. Can't spot any obvious error message. I guess I need to dig some more :)

**Comment by lnicola** [comment] 2021-03-26 14:14
Note that proc macro attributes aren't supported at all (i.e. they're ignored), but some features should still work in there IIRC.

**Comment by Veykril** [comment] 2021-03-26 14:15
Ye that's because those files are most likely not in the module tree for RA so it doesn't really do anything in those files, though you should be getting a warning or error from RA telling you it's not indexed on nightly then 🤔

**Comment by jeluard** [comment] 2021-03-26 14:28
Oh my bad I thought they were supported now?

I can see checking with VScode that the only difference is that theia doesn't grey out the file with the warning message.
How is that done BTW? Probably something not yet supported by theia.

**Comment by jeluard** [comment] 2021-03-26 14:30
Hmm just to be sure: the non-inclusion is related to the proc macro usage? Or something else?

**Comment by Veykril** [comment] 2021-03-26 14:32
It shouldn't be, given they are unsupported the source there should act like the attribute isnt there at all. The non inclusion should only happen if the file is not included into the project via `mod` statements. Is the entire file unincluded or just the annotated module in your screenshot?

**Comment by jeluard** [comment] 2021-03-26 14:36
The whole file is not included.

It's a standalone lib.rs file used as example. The whole thing is annotated. See this [example](https://github.com/paritytech/ink/blob/master/examples/erc20/lib.rs)

**Comment by Veykril** [comment] 2021-03-26 14:45
I think we don't support examples at all yet? I am not too into how project structure loading works. Though adding an example to the workspace in a test repo makes it load for me, so I think this line in your Cargo.toml might be causing this https://github.com/paritytech/ink/blob/master/Cargo.toml#L16

**Comment by jeluard** [comment] 2021-03-26 14:56
Indeed, removing that bit and messing with `members` include the file. Thanks!
