### ISSUE TITLE
`unresolved import - rust-analyzer (unresolved-import)` for Derivative

### ISSUE THREAD

**Issue by doivosevic** [rust-analyzer/rust-analyzer#7641] opened 2021-02-11 15:24 UTC
Apologies is this is a duplicate but I didn't find any.
I cannot get rust-analyzer to resolve the Derivative import

I'm on ubuntu latest stable and Windows 10 latest. Latest rust-analyzer stable available in latest stable vscode.

Example code: 

```
extern crate derivative;

use derivative::Derivative;

#[derive(Derivative)]
#[derivative(Debug)]
struct Manual {
    config: String,
}

pub fn main() {
}

```

Zip of the project:
[alerting.zip](https://github.com/rust-analyzer/rust-analyzer/files/5966383/alerting.zip)

The code compiles via cargo but the error is in vscode.
Please tell me if you need more info. This seems very reproducible.

**Comment by jonas-schievink** [comment] 2021-02-11 15:50
duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7459

**Closed by jonas-schievink** 2021-02-11 15:50 UTC
