### ISSUE TITLE
ra_lsp_server uses all available RAM when editing cargo-script script

### ISSUE THREAD

**Issue by pzmarzly** [rust-analyzer/rust-analyzer#397] opened 2019-01-01 01:23 UTC
I am unable to reproduce this bug, but I had vscode in background with cargo-script script opened, when I noticed I was slowly running out of RAM. I opened KSysGuard and noticed ra_lsp_server using 4.5GB and usage rising at about 50MB/s. I killed vscode, that did not stop ra_lsp_server, then I killed it too.

The scripts had `.rs` extension, there was no `Cargo.toml` anywhere. The script basically looked like this:

```rust
#!/usr/bin/env run-cargo-script
//! ```cargo
//! [package]
//! edition = "2018"
//!
//! [dependencies]
//! duct = "0.11"
//! ```
use duct::cmd;

fn main() {
    // some code using only stdlib functions
}
```

I don't know if this bug is related to cargo-script scripts, but if so, then ignoring shebang line will probably help.

**Comment by pzmarzly** [comment] 2019-01-01 01:39
In case it is not caused by cargo-script scripts, maybe a separate thread in ra_lsp_server could monitor its RAM usage and kill the server if it exceeds e.g. 1GB (this number should be based on monitored RAM usage on e.g. stdlib, ripgrep and some projects using gtk-rs). It's nicer to have the server stop itself than trying to kill it while fighting with HDD memory swapping later on.

**Comment by DJMcNab** [comment] 2019-01-01 11:48
I don't think we use the shebang for anything, so it shouldn't be an issue directly in run-cargo-script. I would postulate that this issue lies in our use of cargo metadata, given that there probably isn't a Cargo.toml in this directory. However that's just a guess, and looking at the code I don't see how that could happen.

**Comment by matklad** [comment] 2019-01-01 12:45
In general, rust-analyzer is pretty ram-hungry at the moment: 1 GB is required to work with rust-analyzer itself, rust-lang/rust need 4 GBs. This is definitely excessive and something to tackle, it just hasn't been a priority yet. Will open issue describing memory usage challenges.

**Comment by matklad** [comment] 2019-01-01 12:49
This specific case defenitelly looks like a bug though: opening a single file should not cause a huge memory usage. My guess is that we somehow process much more than a single file, perhaps the contents of `~/.cargo` or something like this. I wouldn't have capacity to investigate this issue in the nearest future but, if someone wants to take a look,  here's how we deterine the "project directory" (which contains half of the stuff we want to index):

https://github.com/rust-analyzer/rust-analyzer/blob/5a866a772c863ba7e3ec8bad353c1b6997a7a62a/crates/ra_lsp_server/src/main.rs#L44-L47

And here's how we determine the set of dependent crates (other half to index):

https://github.com/rust-analyzer/rust-analyzer/blob/5a866a772c863ba7e3ec8bad353c1b6997a7a62a/crates/ra_lsp_server/src/main_loop.rs#L65-L74

**Comment by matklad** [comment] 2019-02-18 15:39
Closing: I wasn't able to reproduce and we've significantly improved memory usage in the meantime.

**Closed by matklad** 2019-02-18 15:39 UTC

**Comment by pzmarzly** [comment] 2019-04-06 20:27
Sadly, I ran into it again, this time sacrificing few minutes to take a screenshot (swapping is slow). It happened in "normal" multi-crate (cargo workspace) project (30KLOC, 220 dependencies). I was working for few hours, ra_lsp_server using about 1.6GB of RAM the whole time. Then, suddenly, it took all of it.

Alt+SysRq+R -> Alt+SysRq+F made the system unfreeze for few seconds as it killed web browser, but ra_lsp_server quickly (<10 seconds) took over newly freed gigabytes of memory. Repeating Alt+SysRq+F helped.

Version 990e74ba7c77485f914434ac6f09a40d1364634d

While the bug still happens out of nowhere, the I/O stats show that it is loading crazy amounts of files.

Right now I'm running this code in background as a workaround: `watch -n 1 "ps aux --sort pmem | tail -1 | grep ra_lsp_server | cut -d' ' -f8 | awk '\$1>3000000' | awk '{system(\"pkill ra_lsp_server\")}'"` (it kills ra_lsp_server if the usage goes over 3GB)

![Screenshot from 2019-04-06 21-48-58](https://user-images.githubusercontent.com/8074163/55674539-5089a180-58b6-11e9-8cbf-c4fff2904cbf.png)
