### ISSUE TITLE
Show module on hover

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3208] opened 2020-02-17 23:48 UTC
Sometimes I wonder where things come from and it would be nice to show the module that eg a struct or function comes from on hover.

**Comment by memoryruins** [comment] 2020-03-09 10:18
Is this a duplicate of #1064 ?

**Comment by matklad** [comment] 2020-03-09 10:20
yup, closed by  #3519

**Closed by matklad** 2020-03-09 10:20 UTC
