### ISSUE TITLE
impl AsRef<str> is shown as {unknown} in signature help

### ISSUE THREAD

**Issue by wandercn** [rust-analyzer/rust-analyzer#11222] opened 2022-01-07 09:05 UTC
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

`rust-analyzer 8e9ccbf97 2022-01-03 stable`

**rustc version**: (eg. output of `rustc -V`)

`rustc 1.57.0 (f1edd0429 2021-11-29)`

```rust

pub fn Compare(a: impl AsRef<str>, b: impl AsRef<str>) -> int {
    if a.as_ref() == b.as_ref() {
        return 0;
    }
    if a.as_ref() < b.as_ref() {
        return -1;
    }
    1
}

fn main() {


    Compare(#output
}

```
#output
```
fn Compare(a: {unknown}, b: {unknown}) 
```

**Comment by flodiebold** [comment] 2022-01-07 09:14
Duplicate of #10432.

**Closed by flodiebold** 2022-01-07 09:14 UTC
