### ISSUE TITLE
Formatting unterminated double quote string leads to panic and weird backtrace. 

### ISSUE THREAD

**Issue by Lighty0410** [rust-analyzer/rust-analyzer#3226] opened 2020-02-18 23:40 UTC
This code led to panic and weird backtrace on formatting. Moreover only once. I'm not able to reproduce the same backtrace again (only an error for now) for some reason despite the fact that all indentations are the same.   

vscode 1.42, ubuntu 18.04. 

Code: 
```
use std::fmt::Debug;
 
#[derive(Debug)]
struct TRef<'a, T: 'a> {
    t_num: &'a T,
}
 
struct NoDebug();
 
fn print_t_ref<'a, T>(t: &'a T)
where
   T: Debug + 'a,
{
    println!("this is a generic num: {:?}", t);
}
 
fn main() {
    let generic_ref = TRef { t_num: &32i32 };
    print_t_ref(&k");
}
```
Backtrace:
https://gist.github.com/Lighty0410/fd82d582b30764aa80922fe6e21cdf0d

**Comment by Veetaha** [comment] 2020-02-19 07:09
Big thanks for the repro.

Here is a better stacktrace:

<details>

<summary>Klick me</summary>

```
[ERROR rust_analyzer::main_loop] overly long loop turn: 116.293478ms
thread '<unnamed>' panicked at 'Fail to convert given literal Literal {
    text: "\");\n}\n",
    id: TokenId(
        73,
    ),
}', crates/ra_mbe/src/subtree_source.rs:137:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  13: ra_mbe::subtree_source::convert_literal::{{closure}}
  14: core::option::Option<T>::unwrap_or_else
  15: ra_mbe::subtree_source::convert_literal
  16: ra_mbe::subtree_source::convert_leaf
  17: ra_mbe::subtree_source::SubtreeTokenSource::get
  18: ra_mbe::subtree_source::SubtreeTokenSource::mk_token
  19: <ra_mbe::subtree_source::SubtreeTokenSource as ra_parser::TokenSource>::lookahead_nth
  20: ra_parser::parser::Parser::at_composite3
  21: ra_parser::parser::Parser::nth_at
  22: ra_parser::parser::Parser::at
  23: ra_parser::grammar::expressions::lhs
  24: ra_parser::grammar::expressions::expr_bp
  25: ra_parser::grammar::expressions::lhs
  26: ra_parser::grammar::expressions::expr_bp
  27: ra_parser::grammar::expressions::expr
  28: ra_parser::grammar::expressions::expr_with_attrs
  29: ra_parser::grammar::expressions::arg_list
  30: ra_parser::grammar::expressions::call_expr
  31: ra_parser::grammar::expressions::postfix_expr
  32: ra_parser::grammar::expressions::lhs
  33: ra_parser::grammar::expressions::expr_bp
  34: ra_parser::grammar::expressions::expr_stmt
  35: ra_parser::grammar::expressions::stmt
  36: ra_parser::grammar::expressions::expr_block_contents
  37: ra_parser::grammar::error_block
  38: ra_parser::grammar::items::adt::record_field_def_list
  39: ra_parser::grammar::items::adt::struct_or_union
  40: ra_parser::grammar::items::adt::struct_def
  41: ra_parser::grammar::items::items_without_modifiers
  42: ra_parser::grammar::items::maybe_item
  43: ra_parser::grammar::items::item_or_macro
  44: ra_parser::grammar::items::mod_contents
  45: ra_parser::grammar::fragments::macro_items
  46: core::ops::function::FnOnce::call_once
  47: ra_parser::parse_from_tokens
  48: ra_parser::parse_fragment
  49: ra_mbe::syntax_bridge::token_tree_to_syntax_node
  50: ra_hir_expand::builtin_derive::parse_adt
  51: ra_hir_expand::builtin_derive::expand_simple_derive
  52: ra_hir_expand::builtin_derive::debug_expand
  53: ra_hir_expand::builtin_derive::BuiltinDeriveExpander::expand
  54: ra_hir_expand::db::TokenExpander::expand
  55: ra_hir_expand::db::macro_expand
  56: <ra_hir_expand::db::MacroExpandQuery as salsa::plumbing::QueryFunction<DB>>::execute
  57: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
  58: salsa::runtime::Runtime<DB>::execute_query_implementation
  59: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  60: <salsa::derived::slot::Slot<DB,Q,MP> as salsa::dependency::DatabaseSlot<DB>>::maybe_changed_since
  61: salsa::dependency::Dependency<DB>::maybe_changed_since
  62: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value::{{closure}}
  63: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  64: core::iter::traits::iterator::Iterator::find::check::{{closure}}
  65: core::iter::traits::iterator::Iterator::try_fold
  66: core::iter::traits::iterator::Iterator::find
  67: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
  68: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value
  69: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  70: <salsa::derived::slot::Slot<DB,Q,MP> as salsa::dependency::DatabaseSlot<DB>>::maybe_changed_since
  71: salsa::dependency::Dependency<DB>::maybe_changed_since
  72: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value::{{closure}}
  73: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  74: core::iter::traits::iterator::Iterator::find::check::{{closure}}
  75: core::iter::traits::iterator::Iterator::try_fold
  76: core::iter::traits::iterator::Iterator::find
  77: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
  78: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value
  79: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  80: <salsa::derived::slot::Slot<DB,Q,MP> as salsa::dependency::DatabaseSlot<DB>>::maybe_changed_since
  81: salsa::dependency::Dependency<DB>::maybe_changed_since
  82: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value::{{closure}}
  83: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  84: core::iter::traits::iterator::Iterator::find::check::{{closure}}
  85: core::iter::traits::iterator::Iterator::try_fold
  86: core::iter::traits::iterator::Iterator::find
  87: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
  88: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value
  89: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  90: salsa::derived::slot::Slot<DB,Q,MP>::read
  91: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  92: salsa::QueryTable<DB,Q>::try_get
  93: salsa::QueryTable<DB,Q>::get
  94: <T as ra_hir_def::db::DefDatabase>::raw_items
  95: ra_hir_def::nameres::collector::DefCollector<DB>::collect_macro_expansion
  96: ra_hir_def::nameres::collector::DefCollector<DB>::resolve_macros
  97: ra_hir_def::nameres::collector::DefCollector<DB>::collect
  98: ra_hir_def::nameres::collector::collect_defs
  99: ra_hir_def::nameres::CrateDefMap::compute_crate_def_map_query
 100: <ra_hir_def::db::ComputeCrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
 101: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
 102: salsa::runtime::Runtime<DB>::execute_query_implementation
 103: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
 104: salsa::derived::slot::Slot<DB,Q,MP>::read
 105: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
````

</details>

**Comment by Veetaha** [comment] 2020-02-19 07:40
I know what the issue is. Recently in #2911 we started collecting errors from the tokenizer. Now the function that panics doesn't expect to get `None` in case of an erroneous token (i.e. unclosed string literal). I'll provide a fix for this, thanks!

**Closed** 2020-02-22 11:25 UTC
