### ISSUE TITLE
Merge import double comma

### ISSUE THREAD

**Issue by floatingmountain** [rust-analyzer/rust-analyzer#3832] opened 2020-04-03 09:27 UTC
Hey, I think I found a bug using merge imports. 
_Example:_
```
use hyper::service::make_service_fn;
use hyper::{
    StatusCode,
};
```
Merge imports on **line 2**.
```
use hyper::{
    StatusCode,
, service::make_service_fn};
```
There should only be one comma.
Correct behaviour on Merge imports on line 1 though.
vscode rust-analyzer version 0.2.108

**Comment by matklad** [comment] 2020-04-03 09:59
I think this should be fixed around here: https://github.com/rust-analyzer/rust-analyzer/blob/77462bba621b0e85f3f04bbcebd2a065a875ac02/crates/ra_assists/src/handlers/merge_imports.rs#L76

**Comment by dnamsons** [comment] 2020-04-04 12:06
Hey, I'd love to give this issue a shot!

**Comment by IceSentry** [comment] 2020-04-13 00:09
Has this been fixed? I was unable to reproduce it in a test.

The following test currently passes, but I expected it to fail based on the issue description.

```rust
    fn test_double_comma() {
        check_assist(
            merge_imports,
            r"
			use hyper::<|>service::make_service_fn;
			use hyper::{
			    StatusCode,
			};
			",
            r"
			use hyper::<|>{service::make_service_fn, 
			    StatusCode,
			};
			",
        )
    }
```

I can still make a PR with it if you want since it isn't currently covered in a test

**Comment by IceSentry** [comment] 2020-04-13 00:13
Disregard that, I missed the "on line 2 part". My updated test does fail. I'll try to make work on it then.

**Closed** 2020-04-13 18:11 UTC
Labels: E-easy, E-mentor, good first issue
