### ISSUE TITLE
Types completely off in async/await code

### ISSUE THREAD

**Issue by Follpvosten** [rust-analyzer/rust-analyzer#1791] opened 2019-09-08 11:25 UTC
Full example, reproducible on the latest nightly:

```rust
async fn do_stuff() -> usize {
    1
}

#[allow(unused_must_use, unused_variables)]
fn main() {
    async {
        // Type shown is usize, should be `impl Future<Output = usize>`
        let future = do_stuff();
        // Type shown is i32, should be `impl Future<Output = i32>`
        let future = async { 1 };
        // Type shown is {unknown}, should be usize
        let value = do_stuff().await;
        // Type shown is {unknown}, should be i32
        let value = async { 1 }.await;
    };
}
```
![image](https://user-images.githubusercontent.com/22855787/64487527-af6f9000-d233-11e9-98d5-85be5c729380.png)
Also, when I hover over the `do_stuff` call, the function's signature is shown without the `async`.  
All this happens for both free-standing functions and methods in impls, as well as async blocks.

**Comment by flodiebold** [comment] 2019-09-08 13:46
Yeah, I think we don't handle `async fn` yet (we do handle `await` though, so it should work with things that return explicit futures). We should either lower the function to an `-> impl Future` function during HIR lowering (so [here](https://github.com/rust-analyzer/rust-analyzer/blob/07e3976f426aaab93bfd3056374ec6ed32ffb255/crates/ra_hir/src/code_model.rs#L577)), or just store that it is an async function and handle it when creating the type signature ([here](https://github.com/rust-analyzer/rust-analyzer/blob/07e3976f426aaab93bfd3056374ec6ed32ffb255/crates/ra_hir/src/ty/lower.rs#L497)). The first approach would be closer to what rustc does, but could bring additional complications :thinking:

**Comment by Follpvosten** [comment] 2019-09-08 13:52
I've just tried `await`, but with this code:

```rust
use std::future::Future;

fn do_something_async() -> impl Future<Output=usize> {
    async { 1 }
}

#[allow(unused_must_use, unused_variables)]
fn main() {
    async {
        let value = do_something_async().await;
    };
}
```
the type of `value` is still shown as `{unknown}`. Is that expected, did I get something wrong? Of course, without the `await`, it shows the right type now.

**Comment by flodiebold** [comment] 2019-09-08 14:47
Well, `impl Future` doesn't yet work because we're missing support for `impl Trait` in Chalk, so that's another, separate problem :slightly_smiling_face:

**Comment by flodiebold** [comment] 2019-12-26 12:18
All of these except async blocks work now.

**Comment by jhgg** [comment] 2020-04-15 02:36
Is there any momentum on this? Types are not able to be inferred across an `.await` yet :(

**Comment by edwin0cheng** [comment] 2020-04-15 05:05
> Types are not able to be inferred across an .await yet :(

@jhgg is it async block ? do you have any  reproducible test case ?

**Comment by SomeoneToIgnore** [comment] 2020-04-15 10:29
I believe, @jhgg had meant any non-trivial `.await` invocatio, here's a small example:
```rust
// add `tokio = { version = "0.2", features = ["full"] }` dependency into Cargo.toml
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let five = get_five().await?;
    Ok(())
}

async fn get_five() -> Result<u32, Box<dyn std::error::Error>> {
    Ok(5)
}
```
<img width="493" alt="image" src="https://user-images.githubusercontent.com/2690773/79327352-fab1f580-7f1c-11ea-9681-e5d9ddd5b65b.png">


If I understand the issue correctly, that is caused by the https://github.com/rust-analyzer/rust-analyzer/issues/2603 due to the fact that the async method invocation type is `impl Future<Output = whatever>`

**Comment by flodiebold** [comment] 2020-04-15 11:17
Yes, likely some combination of #2603 and missing support for return position impl trait. There's a lot happening in Chalk though, so we're pretty close to fixing both!

**Comment by flodiebold** [comment] 2020-04-17 16:26
Actually, I don't think we have an implementation for async blocks yet: #4018

**Comment by bjeanes** [comment] 2020-05-04 04:07
I am also seeing this, when working with `reqwest` gem, which is async by default.

![image](https://user-images.githubusercontent.com/2560/80935510-4c5cea00-8e10-11ea-9d48-071c361b8f22.png)

We can see that after the `.send()` line, it picks up `impl Future<Output = Result<Response, Error>>`. However, after the `.await?` line, information is lost:

![image](https://user-images.githubusercontent.com/2560/80935561-80380f80-8e10-11ea-8c76-257ace933666.png)

**Comment by sluongng** [comment] 2020-05-12 17:25
Im also stuck with https://github.com/sluongng/git-trace-analysis/blob/9599050c28d0bcaad2b146c4cce9909f8d24e7dc/src/main.rs#L29 where async-std is not really supported well by Rust-analyzer.

Would appreciate if this issue is prioritized because await syntax is just getting more and more popular.

**Comment by DanielJoyce** [comment] 2020-05-29 17:48
I'm getting spurious warnings now that other functions should be made async when they don't need to be.

**Comment by lnicola** [comment] 2020-06-05 17:11
Two of the test cases in the first comment work now. The other two, the `async` blocks still don't.

**Comment by oxalica** [comment] 2020-09-07 13:41
Seems all examples above works now except the type of async block, which has a stand-alone issue #4018
I think this issue can be closed.

**Comment by jonas-schievink** [comment] 2020-10-13 14:42
Even async blocks work now, so closing

**Closed by jonas-schievink** 2020-10-13 14:42 UTC
Labels: A-ty
