### ISSUE TITLE
not support #[tokio::test] 

### ISSUE THREAD

**Issue by xiaoquanju** [rust-analyzer/rust-analyzer#10856] opened 2021-11-25 07:06 UTC
when i update rust-analyzer from 0.2.792 to 0.2.826 
#[tokio::test]  can not support now (can not click debug/run button)
please retain this feature ,i like it. thks

**Comment by Emilgardis** [comment] 2021-11-25 10:45
duplicate of #10837

**Closed** 2021-11-25 10:46 UTC
