### ISSUE TITLE
Using js_sys::Reflect causes "This operation is unsafe"

### ISSUE THREAD

**Issue by strowk** [rust-analyzer/rust-analyzer#6658] opened 2020-11-28 09:49 UTC
I am using js_sys::Reflect to access js objects from rust (from webassembly). Rustc compiles that fine, but `Reflect::get` or `Reflect::set` in IDE all show "This operation is unsafe and requires an unsafe function or block" from rust-analyzer

**Comment by bjorn3** [comment] 2020-11-28 10:21
js-sys uses a proc macro from wasm-bindgen. At https://github.com/rustwasm/wasm-bindgen/blob/83cc988cbfa9ced7be419a3429cbd99c74b1fec1/crates/js-sys/src/lib.rs#L2759 there is an `extern "C"` block annotated with `#[wasm_bindgen]`. This proc macro rewrites the extern block such that every function declaration within it becomes a safe function definition containing glue code. Rust-analyzer doesn't enable proc macro support by default. You can enable it using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by bjorn3** [comment] 2020-11-28 10:23
Looks like attribute proc macros are not yet supported by rust-analyzer anyway: https://github.com/rust-analyzer/rust-analyzer/blob/59c4975b54066417d22ab4ae028f53e1ee1e847d/crates/proc_macro_api/src/lib.rs#L103-L104

**Comment by flodiebold** [comment] 2020-11-28 10:40
Duplicate of #5412.

**Closed by flodiebold** 2020-11-28 10:40 UTC
