### ISSUE TITLE
Nightly extension seems to hang when loading metadata

### ISSUE THREAD

**Issue by bnjbvr** [rust-analyzer/rust-analyzer#8528] opened 2021-04-15 13:11 UTC
Hi! I'm on Windows 10, using VSCode 1.55.2, with Rust-analyzer nightly (according to the RA version command). As a sidenote, I didn't think I explicitly chose nightly when installing the addon from the available vscode extensions, is that the default?
Anyhow I'm trying to build a large Rust binary, and it seems the rust-analyzer binary keeps getting stuck loading metadata of random dependencies, and not even large ones (e.g. libm, . It seems most dependencies' metadata is loaded right away, but at some point it gets stuck on one randomly. In this case, there's no noticeable CPU activity or disk activity.

On the other hand, full builds in a bash CLI window works perfectly fine, so that seems to be an issue in rust-analyzer.

Please let me know if I can help debug this with logs!

**Comment by bjorn3** [comment] 2021-04-15 13:33
It being reported as nightly was a bug that has been fixed two days ago: https://github.com/rust-analyzer/rust-analyzer/issues/8239.

**Comment by BlackHoleFox** [comment] 2021-04-17 05:59
I am seeing this bug on the Nightly version of the extension, so perhaps there is more to it. It basically chooses at random which crate it wants to freeze up on.

As of sending this, its been spinning here for 7 minutes, holding a `Cargo.lock` file lock for the entire time D:
![image](https://user-images.githubusercontent.com/20936452/115103480-d0bc5600-9f17-11eb-830b-6b70331109ab.png)

Version: 0.3.560-nightly
OS: Windows 10

<details>
  <summary>Heres my client startup logs if they help at all:</summary>

```
INFO [4/17/2021, 12:51:34 AM]: Extension version: 0.3.560-nightly
INFO [4/17/2021, 12:51:34 AM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'nightly', askBeforeDownload: true },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importMergeBehavior: 'full',
    importPrefix: 'plain',
    importGroup: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: true,
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false,
    loadOutDirsFromCheck: true
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'clippy',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: false },
    autoimport: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [ 'incorrect-ident-case' ],
    warningsAsHint: [],
    warningsAsInfo: []
  },
  files: { watcher: 'client', excludeDirs: [] },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    run: true,
    linksInHover: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false
  },
  linkedProjects: [],
  lruCapacity: 256,
  notifications: { cargoTomlNotFound: true }, // Dunno why it says this, Im in a valid project.
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: { extraArgs: [], overrideCommand: null }
}
INFO [4/17/2021, 12:51:34 AM]: PersistentState: {
  lastCheck: 1618629240813,
  releaseId: 41574990,
  serverVersion: '0.3.560-nightly'
}
INFO [4/17/2021, 12:51:34 AM]: Using server binary at c:\Users\User\AppData\Roaming\Code - Insiders\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc.exe
```
</details>

**Comment by jonas-schievink** [comment] 2021-04-19 12:05
We will probably need a code base that reproduces this problem in order to fix it

**Comment by ChayimFriedman2** [comment] 2021-04-19 13:02
To me it occured in the codebase of rust-analyzer itself (checked only yesterday, so I'm not sure if it's still there).

**Comment by BlackHoleFox** [comment] 2021-04-19 14:06
I'm able to consistently reproduce the issue in [a GearBot repository](https://github.com/gearbot/GearBot-2).

**Comment by jonas-schievink** [comment] 2021-04-19 14:10
Hmm, I can't reproduce it on Linux with the GearBot repo, and the rust-analyzer repo also works fine for me

**Comment by lnicola** [comment] 2021-04-19 14:11
@ChayimFriedman2 are you also using Windows?

**Comment by ChayimFriedman2** [comment] 2021-04-19 14:30
Yes.

**Comment by BinChengZhao** [comment] 2021-04-19 14:53
I am in the same situation:.

OS: win10
rustc: stable-x86_64-pc-windows-msvc


Always blocking at 'Loading: metadata *'

**Comment by joshmossas** [comment] 2021-04-19 14:53
I'm experience the same issue with Windows 10, VSCode, and rust-analyzer v0.2.563. I just spins for forever and it seems to get stuck on a different crate each time.

![image](https://user-images.githubusercontent.com/31548851/115255193-a32c0400-a0f3-11eb-82cd-1a913c29c0f6.png)

This is a brand new project. I just ran `cargo new my-project` and then added `bevy v0.5` as a dependency.

I've gotten around this by doing the following:
- disable rust-analyzer extension
- run `cargo build`
- reenable rust-analyzer and now it loads up fine

However when I add a new dependency I have to repeat the process.

**Comment by lnicola** [comment] 2021-04-19 15:17
Looks like this is Windows only and is related to our `RUSTC_WRAPPER` shenanigans. Our wrapper process closes, but its parent `cargo` hangs for some reason:

![image](https://user-images.githubusercontent.com/308347/115260564-8c110480-a13b-11eb-904b-5bcf46c18703.png)

**Comment by stanciuadrian** [comment] 2021-04-19 15:34
Mine is stuck here too:

![image](https://user-images.githubusercontent.com/2334569/115262926-a51ab500-a13d-11eb-8146-fc04288e6c78.png)

with the environment:

![image](https://user-images.githubusercontent.com/2334569/115263077-c8ddfb00-a13d-11eb-9db5-4954d938220b.png)

If I run `cargo check --workspace --message-format=json --manifest-path Cargo.toml --all-targets`, the process ends successfully.

**Comment by lnicola** [comment] 2021-04-19 15:35
I suspected `cargo` pipelining might play a part here, but setting `CARGO_BUILD_PIPELINING` to `false` does nothing.

**Comment by stanciuadrian** [comment] 2021-04-19 15:37
`cargo` seems stuck in some `git` functionality:

![image](https://user-images.githubusercontent.com/2334569/115263611-3be77180-a13e-11eb-9e66-0e517560a57b.png)

**Comment by jonas-schievink** [comment] 2021-04-19 15:37
What happens if you disable `rust-analyzer.cargo.useRustcWrapperForBuildScripts`? Does that fix it?

**Comment by lnicola** [comment] 2021-04-19 15:41
It still hangs 😱 

![image](https://user-images.githubusercontent.com/308347/115264207-c4661200-a13e-11eb-9862-9939bcd539db.png)

No `RUSTC_WRAPPER` set:

![image](https://user-images.githubusercontent.com/308347/115264273-d2b42e00-a13e-11eb-8981-cda4df616513.png)

**Comment by stanciuadrian** [comment] 2021-04-19 15:42
@jonas-schievink  For me it loaded some metadata but got stuck at `"Loading: metadata base_db"`.
Same call stack for cargo.exe as above.

**Comment by bjorn3** [comment] 2021-04-19 16:12
Just a guess, but would closing stdin/stdout/stderr in the wrapper or replacing the wrapper process with rustc using the windows equivalent of `exec` help?

**Comment by lnicola** [comment] 2021-04-19 17:22
I think the problem is around https://github.com/rust-analyzer/rust-analyzer/blob/186c5c47cbfde4ae9d81dc67450c958cb6aece2c/crates/project_model/src/build_data.rs#L179. We previously changed https://github.com/rust-analyzer/rust-analyzer/blob/186c5c47cbfde4ae9d81dc67450c958cb6aece2c/crates/project_model/src/build_data.rs#L172 from `.stderr(Stdio::null())` to `.stderr(Stdio::piped())` in https://github.com/rust-analyzer/rust-analyzer/pull/8375/files#diff-1ad3a8ef11808c99ff307253865b291a412098a6f475a4ddd8152faf60cbe9f1R156.

So now we're getting output from `cargo` on `stderr` (it's not only errors, but also the "compiling foo" messages printed on console). Normally, the `wait_with_output` [here](https://github.com/rust-analyzer/rust-analyzer/blob/186c5c47cbfde4ae9d81dc67450c958cb6aece2c/crates/project_model/src/build_data.rs#L247) would drain both `stdout` and `stderr`, but we're stuck in the `for` loop above.

One solution might be to spawn a thread that runs the `for` loop -- or the `wait_with_output`, or just drains `stderr` by itself. This shouldn't affect the current logic, since the `stdout` was `take`n above, so there's no conflict between `wait_with_output` and the `for` loop.

**Comment by lnicola** [comment] 2021-04-21 06:14
There was a hotfix release put out yesterday which included #8600 which should have fixed this, but there's a report in #8414 that it didn't. If you're affected by this, can you please retest? The fixed version identifies itself as `rust-analyzer 2021-04-19-1-gd906b7ad8` or needs to include https://github.com/rust-analyzer/rust-analyzer/commit/ad131049c4cd1302af1a5616ff83d0e1f0cadea2 if built from source.

As we found out, it seems easier to reproduce if you load the project after a `cargo clean`.

**Comment by stanciuadrian** [comment] 2021-04-21 10:46
All 3 approaches (thread / crossbeam / iocomp) worked for me on Windows.

`rust-analyzer 2021-04-19-1-gd906b7ad8` is also fine.

**Comment by matklad** [comment] 2021-04-22 12:57
#8414 seems resolved: https://github.com/rust-analyzer/rust-analyzer/issues/8414#issuecomment-824466501

Can we close both issues?

**Comment by matklad** [comment] 2021-04-22 13:01
Note that there was a process failure here, where we could've fixed redgression before release, but didn't. We've added a new issue template to make it easier for nightly users to visibly report release-blocking issues: https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/ISSUE_TEMPLATE/critical_nightly_regression.md

Big :heart: for all our nightly users!

@bnjbvr stable is default, are you sure you don't have some pre-existing setting sets rust-analzyer's channel to nightly?

**Comment by bnjbvr** [comment] 2021-04-22 18:35
Thanks a bunch :star2: 

> @bnjbvr stable is default, are you sure you don't have some pre-existing setting sets rust-analzyer's channel to nightly?

I don't think so. For what it's worth I cloned a repository that had some checked-in `.vscode` with the recommended VSCode extension, and I just accepted to install it. No clues what happened then, and that work on windows has (fortunately!) wrapped up.

**Closed** 2021-04-24 10:06 UTC
Labels: Broken Window, E-has-instructions, S-actionable, fun
