### ISSUE TITLE
Show struct fields on hover

### ISSUE THREAD

**Issue by aryan9600** [rust-analyzer/rust-analyzer#9125] opened 2021-06-03 10:50 UTC
Right now hovering on a struct, only shows the name and the doc comments for the same. 
![image](https://user-images.githubusercontent.com/43110940/120632983-398b6d80-c487-11eb-99b7-b75ddb026f4b.png)
It'd be helpful to also show the fields defined for the struct, something similar to [gopls](https://github.com/golang/tools/blob/master/gopls/README.md), the language server for GoLang.
![image](https://user-images.githubusercontent.com/43110940/120633128-6770b200-c487-11eb-92f3-1519133f6ac4.png)

**Comment by arzg** [comment] 2021-07-12 12:37
I already get this in VS Code when I hover while holding <kbd>cmd</kbd>. Is this a VS Code feature layered on top of LSP, or a proper part of the LSP itself?

**Comment by Veykril** [comment] 2021-07-13 11:46
That's a vscode thing to my knowledge, which unfortunately doesn't always work that well(and I'm pretty sure that's just vscode's implementation being buggy cause our ranges are correct) as it sometimes doesn't show the whole thing.

**Comment by Veykril** [comment] 2021-11-22 17:14
Duplicate of #3197

**Closed by Veykril** 2021-11-22 17:14 UTC
Labels: S-actionable
