### ISSUE TITLE
rust-analyzer takes too much time to load a project

### ISSUE THREAD

**Issue by tomruk** [rust-analyzer/rust-analyzer#9271] opened 2021-06-14 16:20 UTC
I'm using rust-analyzer version **2021-06-14 stable** with Visual Studio Code. I have rust-analyzer plugin installed (the default official rust plugin is not installed).

When i open a project with Visual Studio Code, rust-analyzer takes too much time to initialize. Especially if the project is big and has a lot of dependencies it takes approximately 1 minute for intellisense to be enabled.

These 2 steps take the most time:
- Fetching metadata
- Indexing

I like rust-analyzer. It is a great LFS but i wish there was a cache or something because whenever i open a project i wait for a minute (sometimes a few minutes) for the intellisense.

**Comment by flodiebold** [comment] 2021-06-14 16:25
Duplicate of #1650 / #4712, unless you have a specific project where indexing takes abnormally long.

**Closed by flodiebold** 2021-06-14 16:25 UTC

**Comment by lnicola** [comment] 2021-06-14 16:29
Also, "fetching metadata" means it's updating the cargo registry, which can take quite a while but is usually called by cargo itself.

**Comment by tomruk** [comment] 2021-06-17 08:51
Sorry for duplicate issue. I'm new to Rust and i want to write an API server. But web frameworks (warp, rocket, gotham, actix) have a lot of dependencies. Try creating a simple web server with one of these frameworks and you'll see that rust-analyzer takes more than 30 seconds to initialize.

Indexing takes too much time.

![Screenshot from 2021-06-17 11-45-08](https://user-images.githubusercontent.com/41700170/122363661-cb07de80-cf61-11eb-864f-16d4787f3511.png)

Is it a problem related to my system? Or is it common for rust-analyzer to take too much time to index such a large set of dependencies?

Also **fetching metadata** take a while too. Does it fetch data from a server? Is this related to my internet connection?

**Comment by lnicola** [comment] 2021-06-17 08:56
We need to run `cargo metadata` when loading the project, which can cause `cargo` to update its crate index (presumably if it's the first time you're compiling a project, or if the project is using a crate version that's not available locally). This is a `git clone`, but I've seen it take a couple of minutes.

We also run `cargo check` for diagnostics, proc  macros and build scripts. You can disable all of these, but they happen in the background. "Indexing" is rust-analyzer itself.
