### ISSUE TITLE
"Bad offset" crash

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#4058] opened 2020-04-20 15:18 UTC
I switched to the "nightly" channel in order to get better backtraces, but it doesn't seem to have helped:

```
thread '<unnamed>' panicked at 'Bad offset: range [0; 6211) offset 6502', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rowan-0.9.1\src\cursor.rs:449:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
```

**Comment by Diggsey** [comment] 2020-04-20 15:19
![image](https://user-images.githubusercontent.com/451321/79768485-c2e2ed80-8322-11ea-9d0d-e9fa8bd017c0.png)

**Comment by Veetaha** [comment] 2020-04-21 23:41
[Related discussion](https://www.coursera.org/programs/igor-sikorsky-kyiv-polytechnic-institute-on-coursera-1uynq?organization=c4c-igor-sikorsky-kyiv-polytechnic-institute&utm_campaign=programId%3ADIqEsmyWEeqnfhJfLYb_Fw%3Bday%3A1585166400000%3Binvitation&utm_medium=email&utm_source=other&webToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnZpdGF0aW9uSWQiOiJ3MW9XUzFmalRPcVNMMlE5Qm53ZW5BIiwiZW1haWwiOiJnZXJ6b2gxQGdtYWlsLmNvbSIsIm5hbWUiOiJLcnl2ZW5rbyBWaXRhbGlpIElob3JvdnljaCIsImV4cCI6IjkyMjMzNzIwMzY4NTQ3NzU4MDciLCJqdGkiOiJ3MW9XUzFmalRPcVNMMlE5Qm53ZW5BIn0.5Db75GIZwdLXU1j_Wi8eWGFlupdtbfQ9X4TPyra4dP0)

**Comment by lnicola** [comment] 2020-04-22 06:34
@Veetaha wrong link?

**Comment by Veetaha** [comment] 2020-04-22 08:55
Fixed

**Comment by jonas-schievink** [comment] 2020-05-07 21:12
Here's a symbolized backtrace in case that's useful:

```
thread '<unnamed>' panicked at 'Bad offset: range 0..19413 offset 68268', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: rowan::cursor::SyntaxNode::token_at_offset
  14: ra_syntax::algo::ancestors_at_offset
  15: ra_syntax::algo::find_node_at_offset
  16: ra_ide::references::find_all_refs
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  19: ra_ide::Analysis::find_all_refs
  20: rust_analyzer::main_loop::handlers::handle_document_highlight
  21: <F as threadpool::FnBox>::call_box
```

**Comment by jonas-schievink** [comment] 2020-10-22 17:23
Another one with what looks like a different cause:

```
thread '<unnamed>' panicked at 'Bad offset: range 0..20468 offset 21175', /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::references::rename::rename_with_semantics
   4: <hir_ty::diagnostics::IncorrectCase as ide::diagnostics::fixes::DiagnosticWithFix>::fix
   5: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   6: hir_expand::diagnostics::DiagnosticSink::_push
   7: hir_ty::diagnostics::decl_check::DeclValidator::validate_item
   8: hir_ty::diagnostics::validate_module_item
   9: hir::code_model::ModuleDef::diagnostics
  10: hir::code_model::Module::diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: std::panicking::try
  14: ide::Analysis::diagnostics
  15: rust_analyzer::handlers::publish_diagnostics
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jonas-schievink** [comment] 2020-12-09 17:21
Another one, found while running `rust-analyzer diagnostics .` on r-a itself:

```
thread 'main' panicked at 'Bad offset: range 0..6056 offset 6113', /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::references::rename::rename_with_semantics
   4: <hir_ty::diagnostics::IncorrectCase as ide::diagnostics::fixes::DiagnosticWithFix>::fix
   5: ide::diagnostics::warning_with_fix
   6: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   7: hir_expand::diagnostics::DiagnosticSink::_push
   8: hir_ty::diagnostics::decl_check::DeclValidator::validate_item
   9: hir_ty::diagnostics::validate_module_item
  10: hir::code_model::ModuleDef::diagnostics
  11: hir::code_model::Module::diagnostics
  12: hir::code_model::Module::diagnostics
  13: ide::diagnostics::diagnostics
  14: std::panicking::try
  15: ide::Analysis::diagnostics
  16: rust_analyzer::cli::diagnostics::diagnostics
  17: rust_analyzer::main
```

**Comment by lnicola** [comment] 2020-12-09 17:27
This one at least seems actionable, I can reproduce it. Do we misadjust offsets while computing an edit?

**Comment by jonas-schievink** [comment] 2020-12-10 13:24
Looks like we have separate issues here. I've fixed the bug in the incorrect-case diagnostic in #6796.

**Comment by lnicola** [comment] 2021-01-22 18:20
@Diggsey are you still seeing this?

**Comment by lnicola** [comment] 2021-04-08 10:36
No update here, I don't think we've seen it lately, and `rowan` has changed substantially in the meanwhile, so let's close this.

**Closed by lnicola** 2021-04-08 10:36 UTC
Labels: S-unactionable
