### ISSUE TITLE
VS Code extension does not recognize dependencies added to cargo.toml via external tools like `cargo add`

### ISSUE THREAD

**Issue by grandopener** [rust-analyzer/rust-analyzer#7634] opened 2021-02-10 22:05 UTC
I couldn't find anyone else complaining about this so I assume I must be doing something wrong here (again), but any time I add a new dependency to a project, I have to restart rust-analyzer for it to recognize the new one.

Minimal repro: simply start with a hello world project (`cargo new hello`), then add any dependency (toml, rand, whatever) to cargo.toml, then do `cargo build` to make sure it's downloaded, then try to add a valid `use::...` statement to the `main.rs` file.

Rust analyzer tells me it's an unresolved import, and if I check `Rust Analyzer: Status` the new dependency is not listed in the `deps` section.  Running `cargo check` manually from the terminal verifies that the import is, in fact, valid.  (Cargo check does warn about it being unused, which is expected.)  If I `Rust Analyzer: Restart Server`, the `use::...` statement is immediately recognized as valid, and the library appears in the `deps` section of the status report.

Edit: This happens when editing cargo.toml external to VS Code, for example when using a utility like `cargo-add`.  It does not happen when manually editing and saving cargo.toml.

Using:
macOS Big Sur: 11.2.1
VS Code: 1.53.1
RA extension: 0.2.481
RA version (automatically installed by extension): 2021-02-08 (336909b)

**Comment by memoryruins** [comment] 2021-02-10 22:55
In a new project using the same version of vscode/ra/extension (except on w10), I added regex to deps, saved `Cargo.toml`, and it automatically begins to check for me then show completions without manual builds/checks.

Do you have the following enabled in your settings?
```
"rust-analyzer.cargo.autoreload": true
```
![image](https://user-images.githubusercontent.com/6868531/107583021-534b3100-6bc8-11eb-8b3c-b6bc5a224e45.png)

It should be enabled by default, but maybe it was disabled somehow.

**Comment by grandopener** [comment] 2021-02-11 01:17
That setting is enabled, but it gave me an idea that helped me track down some more info.  If I manually edit `cargo.toml`, things work as you've described / as expected.  However, coming from node/npm and python/pip previously, I've gotten in the habit of using `cargo add` (via https://github.com/killercup/cargo-edit) because it just matches my existing workflow / muscle memory.  Unfortunately, this does not trigger the project reload.  Without looking at the code, my current guess is that the extension must be watching events for an in-editor `cargo.toml` window to be saved, whereas a file watch might be more appropriate.

**Comment by flodiebold** [comment] 2021-02-11 09:59
Duplicate of #5333.

**Closed by flodiebold** 2021-02-11 09:59 UTC
