### ISSUE TITLE
Failed to correctly analyze parameters in rust core::x86 with SSE.

### ISSUE THREAD

**Issue by alpnn** [rust-analyzer/rust-analyzer#11032] opened 2021-12-16 06:49 UTC
The function type analysis fails when trying to run SSE instructions.

For example, _mm_slli_si128 actually takes 2 params but rust-analyzer reports that only 1 needed. Additionally, it will report an error if I put indeed 2 params here.

```rust
use std::arch::x86_64::*;

fn main() {
    unsafe {
        let a = _mm_setzero_si128();
        let b = _mm_slli_si128(a, 8);
    }
}
```

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: db2a7087b 2021-12-13 stable

**rustc version**: (eg. output of `rustc -V`)
rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by jonas-schievink** [comment] 2021-12-17 13:57
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10009

**Closed by jonas-schievink** 2021-12-17 13:57 UTC
