### ISSUE TITLE
Code completion list (sometimes?) contains base64 coded data collected from the source file

### ISSUE THREAD

**Issue by bugadani** [rust-analyzer/rust-analyzer#7825] opened 2021-03-01 13:16 UTC
Sometimes, if I'm typing code to call a method on a non-imported type, either RA or VSCode brainfarts like this:
![image](https://user-images.githubusercontent.com/977627/109501626-263bc100-7a98-11eb-8847-23584b49c7ff.png)

Looks like this happens reliably enough for methods that start with "n" or "w".

**Comment by lnicola** [comment] 2021-03-01 13:19
Can you extract a smaller test case from your project? It might be specific to some of your dependencies.

**Comment by lnicola** [comment] 2021-03-01 13:20
Also, what happens if you select that completion?

**Comment by bugadani** [comment] 2021-03-01 13:20
> Also, what happens if you select that completion?

It just pastes the base64 string like `Foobar::eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9`

**Comment by lnicola** [comment] 2021-03-01 13:21
Does it auto-import anything? Does hover work on it?

**Comment by lnicola** [comment] 2021-03-01 13:24
That looks like a JWT:

![image](https://user-images.githubusercontent.com/308347/109502871-3a84bb80-7aa2-11eb-8dc1-8fd29fbf9fb3.png)

**Comment by bugadani** [comment] 2021-03-01 13:24
Actually, the string itself is present in one of my doc comments in the file I'm working in. Could this be a suggestion offered by VS Code?

**Comment by bugadani** [comment] 2021-03-01 13:27
Minimal repro:

``````rust
//! ```json
//! "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
//! ```

fn main() {
    Foo::n
}
``````

**Comment by lnicola** [comment] 2021-03-01 13:27
Dunno, I still can't reproduce it. You can enable LSP logging with `rust-analyzer.trace.server`: `verbose`. Maybe we time out returning the suggestions and Code uses the words it find in the file? `net` and `ny` also don't look like they're supposed to be there.

**Comment by lnicola** [comment] 2021-03-01 13:28
```
[Trace - 15:27:36] Received response 'textDocument/completion - (352)' in 0ms.
Result: {
    "isIncomplete": true,
    "items": []
}
```

I wonder if `isIncomplete` matters in this case.

**Comment by bugadani** [comment] 2021-03-01 13:31
I also see

```
[Trace - 14:30:45] Received response 'textDocument/completion - (25)' in 1ms.
Result: {
    "isIncomplete": true,
    "items": []
}
```

**Comment by lnicola** [comment] 2021-03-01 13:35
Yeah, that must be a Code heuristic (to show a completion list when there's no response from the LSP). You can ask why we don't resolve `User` in your case, but there's not much we can do about the random JWTs.

**Comment by bugadani** [comment] 2021-03-01 13:37
> You can ask why we don't resolve User in your case,

It's not imported right now.

> there's not much we can do about the random JWTs.

Thanks for investigating :)

**Comment by lnicola** [comment] 2021-03-01 13:38
Yeah, let's close this, I guess.

**Closed by lnicola** 2021-03-01 13:38 UTC
Labels: A-vscode, S-unactionable

**Comment by kjeremy** [comment] 2021-03-01 13:40
I feel like the JWT might be a bug in vscode-languageclient?

**Comment by bugadani** [comment] 2021-03-01 13:41
The summary of this issue, as far as I understand is: when the type I'm calling a method is not resolved, the completion list contains all the words from the current file. The JWT is just the "random" string I noticed.

**Comment by kjeremy** [comment] 2021-03-01 13:46
Ah thank you.

**Comment by lnicola** [comment] 2021-03-01 13:54
And that's because we don't return any completions and Code falls back to its default behavior.
