### ISSUE TITLE
Incorrect autocomplete and hover for certain types

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#5706] opened 2020-08-11 00:29 UTC
The [`uefi::Status`](https://docs.rs/uefi/0.5.0/uefi/struct.Status.html) struct renders without any spaces in autocomplete, and on hover renders without any spaces in `Status`

<details>
<summary>Autocomplete</summary>

![Screenshot_20200810_201402](https://user-images.githubusercontent.com/5275194/89843300-37e26900-db46-11ea-9c8c-fa9d81ff5418.png)

</details>

<details>
<summary>Hover</summary>

![Screenshot_20200810_201417](https://user-images.githubusercontent.com/5275194/89843311-3e70e080-db46-11ea-8397-9b3753bf3f87.png)

</details>

<details>
<summary>And for comparison, how it "should* render</summary>

![Screenshot_20200810_201723](https://user-images.githubusercontent.com/5275194/89843393-87c13000-db46-11ea-906f-ca8aacd3e9e9.png)

</details>

Note that [`Status` is macro generated](https://docs.rs/uefi/0.5.0/src/uefi/result/status.rs.html#17), possibly relevant. I was unable to come up with a minimal reproduction of this problem, so it may be because of macros?

----

rust-analyzer commit b050937c1071e68a4ade69375f1f17b703cafb02
VSCode Version: 1.47.3

**Comment by lnicola** [comment] 2020-08-11 06:27
Duplicate of #2765.

**Closed by lnicola** 2020-08-11 06:27 UTC
