### ISSUE TITLE
Documentation popovers don't use the usual syntax sugar for Fn* traits

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#9870] opened 2021-08-12 12:11 UTC
Similar to #3012, but this time I noticed it in the documentation popover in VSCodium:

![Screenshot_2021-08-12_140951](https://user-images.githubusercontent.com/951129/129194494-b4c3d41a-cb87-4f3c-bc2f-c335a7226ffc.png)

**Comment by Veykril** [comment] 2021-08-12 13:11
Duplicate of #8157

**Closed by Veykril** 2021-08-12 13:11 UTC
