### ISSUE TITLE
Type not inferred to `&T` for `.borrow()` on an `impl Borrow<T>`

### ISSUE THREAD

**Issue by rben01** [rust-analyzer/rust-analyzer#11346] opened 2022-01-26 17:16 UTC
**rust-analyzer version**: `17afa2e77 2022-01-24 stable`
**rustc version**: `rustc 1.58.1 (db9d1b20b 2022-01-20)`

Bug: if `s` implements `Borrow<T>`, then RA does not infer that the type of `s.borrow()` is `&T`.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/766670/151212809-9e3abd80-8563-485b-a549-682ea0f161c1.png">

**Comment by jonas-schievink** [comment] 2022-01-26 18:14
This might be a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5514

**Closed** 2022-01-26 18:16 UTC
