### ISSUE TITLE
Fill match arms should use Self when available

### ISSUE THREAD

**Issue by lbrande** [rust-analyzer/rust-analyzer#8859] opened 2021-05-16 21:47 UTC
When you use the "fill match arms"-fix in VSCode the `Enum` variants should use `Self::` instead of `TypeName::` when available.

**Comment by Veykril** [comment] 2021-05-16 22:14
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6404

**Closed by Veykril** 2021-05-16 22:14 UTC
