### ISSUE TITLE
Auto-completion suggest private module

### ISSUE THREAD

**Issue by julianlalu** [rust-analyzer/rust-analyzer#2830] opened 2020-01-13 21:24 UTC
Rust-analyzer auto completion suggest private module.
Example:
- Files tree of MyLib is simple : lib.rs and private_submodule.rs are sibling.
- lib.rs contains `mod private_submodule;`
In the integration tests of MyLib:
```rust
extern crate MyLib;
[test]
fn visibility() {
    MyLib::private_submodule // This should not be suggested
}```

**Comment by lnicola** [comment] 2020-11-01 17:41
Duplicate of #824.

**Closed by lnicola** 2020-11-01 17:41 UTC
