### ISSUE TITLE
Right type is recognized but a wrong type is shown from returns on ops

### ISSUE THREAD

**Issue by SarthakSingh31** [rust-analyzer/rust-analyzer#7447] opened 2021-01-26 11:47 UTC
```rust
use std::ops::Mul;

struct TestType(pub f32);

impl Mul<f32> for TestType {
    type Output = TestType;

    fn mul(self, rhs: f32) -> Self::Output {
        TestType(self.0 * rhs)
    }
}

impl Mul<TestType> for f32 {
    type Output = TestType;

    fn mul(self, rhs: TestType) -> Self::Output {
        TestType(self * rhs.0)
    }
}

fn main() {
    let b = TestType(1.0) * 2.0; // Shows up as f64
    let c = 2.0 * TestType(1.0); // Shows up as TestType

    match (b, c) {
        (TestType(_), TestType(_)) =>
            println!("`b` and 'c' are both instances of TestType"),
        // Shows warning here that this is unreachable
        _ => println!("`b` and 'c' are not instances of TestType")
    }
}
```
The above code shows this:
![Screenshot from 2021-01-26 03-44-36](https://user-images.githubusercontent.com/35749450/105841165-0d1b8e00-5f89-11eb-9c08-d27408fbd83b.png)

rust-analyzer version e8c8039

**Comment by flodiebold** [comment] 2021-01-26 11:52
Duplicate of #7150.

**Closed by flodiebold** 2021-01-26 11:52 UTC
