### ISSUE TITLE
Latest release 0.2.563 hangs in VS Code

### ISSUE THREAD

**Issue by evaera** [rust-analyzer/rust-analyzer#8594] opened 2021-04-20 05:20 UTC
After upgrading to the latest release for VS Code (0.2.563), rust-analyzer never finishes initializing. It gets stuck on this step: 
![image](https://user-images.githubusercontent.com/2489210/115336197-b3cc9080-a16c-11eb-81b7-53e773d3fb97.png)

It just says it's loading forever and never does anything. Note: The crate that it gets stuck on isn't consistent. 

My rustc version is 1.51.0 and this happens even after a `cargo clean`. It happens even after a reload or restart of rust-analyzer. 

Downgrading to the previous release (0.2.554) fixes this problem, and oddly enough, after letting it initialize once on that version, switching back to latest (0.2.563) now works. But if I cargo clean, it will no longer work until I let it initialize at least once on the previous version. 

A new rust project with these dependencies in Cargo.toml is enough to reproduce this issue. Repro dependencies (I couldn't narrow them down any further than this):

```
egui = "0.11.0"
egui_wgpu_backend = "0.6.0"
egui_winit_platform = "0.6.0"
rapier3d = "0.8.0"
wgpu = "0.7.1"
env_logger = "0.8.3"
futures = "0.3.5"
hecs = "0.3.2"
gltf = "0.15.2"
```

<details>
<summary>Full dependencies list (in case you can't repro with my narrowed down version for some reason)</summary>

```
egui = "0.11.0"
egui_wgpu_backend = "0.6.0"
egui_winit_platform = "0.6.0"
rapier3d = "0.8.0"
wgpu = "0.7.1"
cgmath = { version = "0.18.0", features = ["serde", "mint"] }
nalgebra = { version = "0.26.1", features = ["convert-mint"] }
anyhow = "1.0.31"
anymap = "0.12.1"
argh = "0.1.3"
async-trait = "0.1.42"
bytemuck = { version = "1.4.1", features = ["derive"] }
crossbeam-channel = "0.5.0"
env_logger = "0.8.3"
futures = "0.3.5"
gltf = "0.15.2"
hecs = "0.3.2"
image = { version = "0.23.4", features = ["png"] }
lazy_static = "1.4.0"
log = "0.4.8"
mint = "0.5.5"
parking_lot = "0.11.0"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
take_mut = "0.2.2"
tokio = { version = "1.2.0", features = ["rt", "rt-multi-thread"] }
typed-arena = "2.0.1"
winit = "0.24.0"
```

</details>

<details><summary>rust-analyzer status</summary>
workspaces:
193 packages loaded

analysis:
4655 (50mb) files
0 (0b) index symbols
2604 trees, 128 retained
39313 trees, 128 retained (macros)
0b total

counts:
all counts are zero

requests:
   68 textDocument/documentHighlight      0ms
   69 textDocument/semanticTokens/full    0ms
   70 textDocument/foldingRange           0ms
   71 textDocument/codeLens               0ms
   72 textDocument/codeLens               0ms
   73 textDocument/codeAction             0ms
   75 textDocument/codeLens               0ms
   76 textDocument/codeLens               0ms
*  66 rust-analyzer/inlayHints            0ms
   67 textDocument/documentSymbol         0ms</details>

**Comment by lnicola** [comment] 2021-04-20 05:29
Duplicate of #8528

**Comment by bjorn3** [comment] 2021-04-20 05:29
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8528

**Closed** 2021-04-20 05:29 UTC
