### ISSUE TITLE
Errors highlighting (underscoring) don't work in lib files

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-analyzer/rust-analyzer#10141] opened 2021-09-03 21:24 UTC
VSCode v.1.60.0.
RA doesn't highlight errors neither on live edit nor on save. in lib files only.

Reproduce with follow project structure:

main.rs:
```
fn main() {
    let _s = "abc";
}
```
Cargo.toml:
```
[package]
name = "test"

[dependencies]
ares = { version = "0", path = "ares" }
```
ares\src\lib.rs:
```
pub enum Err {
    ToDo,
}
```

ares\Cargo.toml:
```
[lib]
name = "ares"
```

When I edit main.rs than every error is highlighted (underscored) in editor well on the fly.
But when I edit lib.rs - no highlight works on the fly, nor on save file.

Some investigation brings that last RA version with correct work is 0.2.678.
So I forced to use RA 0.2.678 and can't use further versions.

**Comment by jonas-schievink** [comment] 2021-09-03 23:07
I'm guessing this was caused by https://github.com/rust-analyzer/rust-analyzer/pull/9801 and we treat path dependencies as part of the "library", which means you can fix it by using a Cargo workspace. We should probably treat path dependencies as workspace roots (https://github.com/rust-analyzer/rust-analyzer/issues/9070).

**Comment by DustinByfuglien** [comment] 2021-09-04 10:09
> you can fix it by using a Cargo workspace
Thanks a lot. It works.

**Comment by lnicola** [comment] 2021-09-06 12:50
Let's close as a duplicate of #9070.

**Closed by lnicola** 2021-09-06 12:50 UTC
