### ISSUE TITLE
fn() -> GAT causes Request textDocument/semanticTokens/full to fail

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#11939] opened 2022-04-08 20:03 UTC
```rust
pub struct InlineStorage {}

pub struct InlineStorageHandle<T: ?Sized> {}

pub unsafe trait Storage {
    type Handle<T: ?Sized>;
    fn create<T: ?Sized>() -> Self::Handle<T>;
}

unsafe impl Storage for InlineStorage {
    type Handle<T: ?Sized> = InlineStorageHandle<T>;
}
```

**rust-analyzer version**: rust-analyzer version: bc5692075 2022-04-08 nightly

**rustc version**: rustc 1.61.0-nightly (76d770ac2 2022-04-02)

**relevant settings**:

```
{
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.experimental.procAttrMacros": true,
    "rust-analyzer.cargo.allFeatures": true,
}
```

**Comment by CAD97** [comment] 2022-04-08 20:04
```
Panic context:
> 
version: bc5692075 2022-04-08 nightly
request: textDocument/semanticTokens/full SemanticTokensParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/d%3A/repos/cad97/storage/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir_ty\src\utils.rs:308:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:48
   3: hir_ty::utils::Generics::find_param
   4: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   7: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   8: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   9: hir_ty::lower::TyLoweringContext::lower_ty_ext
  10: hir_ty::lower::ty_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: salsa::QueryTable<Q>::get
  15: <DB as hir_ty::db::HirDatabase>::ty
  16: hir_ty::chalk_db::associated_ty_value_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: salsa::derived::slot::Slot<Q,MP>::read
  20: salsa::QueryTable<Q>::get
  21: <DB as hir_ty::db::HirDatabase>::associated_ty_value
  22: chalk_solve::clauses::program_clauses_that_could_match
  23: chalk_solve::clauses::program_clauses_that_could_match
  24: chalk_recursive::solve::SolveIteration::solve_iteration
  25: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  26: chalk_recursive::fulfill::Fulfill<I,Solver>::push_goal
  27: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  28: chalk_recursive::solve::SolveIteration::solve_iteration
  29: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  30: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  31: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: salsa::QueryTable<Q>::get
  36: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  37: hir_ty::db::trait_solve_wait
  38: <DB as hir_ty::db::HirDatabase>::trait_solve
  39: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  40: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  41: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty
  42: hir_ty::infer::InferenceContext::make_ty_with_mode
  43: hir_ty::infer::infer_query
  44: salsa::runtime::Runtime::execute_query_implementation
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: salsa::QueryTable<Q>::get
  48: <DB as hir_ty::db::HirDatabase>::infer_query
  49: hir_ty::db::infer_wait
  50: hir::source_analyzer::SourceAnalyzer::new_for_body
  51: hir::semantics::SemanticsImpl::analyze_impl
  52: ide_db::defs::NameRefClass::classify
  53: ide::syntax_highlighting::highlight::name_like
  54: ide::syntax_highlighting::highlight
  55: salsa::Cancelled::catch
  56: ide::Analysis::highlight
  57: rust_analyzer::handlers::handle_semantic_tokens_full
  58: std::panicking::try
  59: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:03:48 PM] Request textDocument/semanticTokens/full failed.
  Message: server panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

**Comment by CAD97** [comment] 2022-04-08 20:21
Note: workspace settings of

```
{
    "rust-analyzer.highlighting.strings": false,
    "rust-analyzer.highlightRelated.breakPoints": false,
    "rust-analyzer.highlightRelated.exitPoints": false,
    "rust-analyzer.highlightRelated.references": false,
    "rust-analyzer.highlightRelated.yieldPoints": false
}
```

appear to not impact the issue.

**Comment by Veykril** [comment] 2022-04-08 20:23
Setting
```json
    "editor.semanticHighlighting.enabled": false,
```
might make your session usable again for the time being.

**Comment by CAD97** [comment] 2022-04-08 20:23
Ah, found it just as you did 😄

**Comment by CAD97** [comment] 2022-04-08 20:40
I got a normal request textDocument/documentHighlight to fail as well with playing around in the minimization:

<details><summary>Log</summary>

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir_ty\src\utils.rs:308:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:48
   3: hir_ty::utils::Generics::find_param
   4: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   7: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   8: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   9: hir_ty::lower::TyLoweringContext::lower_ty_ext
  10: hir_ty::lower::ty_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: salsa::QueryTable<Q>::get
  15: <DB as hir_ty::db::HirDatabase>::ty
  16: hir_ty::chalk_db::associated_ty_value_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: salsa::derived::slot::Slot<Q,MP>::read
  20: salsa::QueryTable<Q>::get
  21: <DB as hir_ty::db::HirDatabase>::associated_ty_value
  22: chalk_solve::clauses::program_clauses_that_could_match
  23: chalk_solve::clauses::program_clauses_that_could_match
  24: chalk_recursive::solve::SolveIteration::solve_iteration
  25: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  26: chalk_recursive::fulfill::Fulfill<I,Solver>::push_goal
  27: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  28: chalk_recursive::solve::SolveIteration::solve_iteration
  29: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  30: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  31: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: salsa::QueryTable<Q>::get
  36: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  37: hir_ty::db::trait_solve_wait
  38: <DB as hir_ty::db::HirDatabase>::trait_solve
  39: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  40: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  41: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty
  42: hir_ty::infer::InferenceContext::make_ty_with_mode
  43: hir_ty::infer::infer_query
  44: salsa::runtime::Runtime::execute_query_implementation
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: salsa::QueryTable<Q>::get
  48: <DB as hir_ty::db::HirDatabase>::infer_query
  49: hir_ty::db::infer_wait
  50: hir::source_analyzer::SourceAnalyzer::new_for_body
  51: hir::semantics::SemanticsImpl::analyze_impl
  52: ide_db::defs::NameRefClass::classify
  53: ide_db::search::FindUsages::search
  54: ide_db::search::FindUsages::all
  55: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  56: <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend
  57: ide::highlight_related::highlight_related
  58: std::panicking::try
  59: ide::Analysis::highlight_related
  60: rust_analyzer::handlers::handle_document_highlight
  61: std::panicking::try
  62: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:36:45 PM] Request textDocument/documentHighlight failed.
  Message: server panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: bc5692075 2022-04-08 nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/d%3A/repos/cad97/playground/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 13,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 11,
                        character: 4,
                    },
                    end: Position {
                        line: 11,
                        character: 46,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rustc",
                ),
                message: "associated function in `impl` without body",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    cannot_be_a_base: false,
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/d%3A/repos/cad97/playground/src/lib.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 11,
                                        character: 45,
                                    },
                                    end: Position {
                                        line: 11,
                                        character: 46,
                                    },
                                },
                            },
                            message: "provide a definition for the function: ` { <body> }`",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 11,
                        character: 45,
                    },
                    end: Position {
                        line: 11,
                        character: 46,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rustc",
                ),
                message: "provide a definition for the function: ` { <body> }`",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    cannot_be_a_base: false,
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/d%3A/repos/cad97/playground/src/lib.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 11,
                                        character: 4,
                                    },
                                    end: Position {
                                        line: 11,
                                        character: 46,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 5,
                        character: 4,
                    },
                    end: Position {
                        line: 5,
                        character: 27,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0658",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            cannot_be_a_base: false,
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0658",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "generic associated types are unstable\nsee issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information\nadd `#![feature(generic_associated_types)]` to the crate attributes to enable",
                related_information: None,
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 10,
                        character: 4,
                    },
                    end: Position {
                        line: 10,
                        character: 52,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0658",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            cannot_be_a_base: false,
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0658",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "generic associated types are unstable\nsee issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information\nadd `#![feature(generic_associated_types)]` to the crate attributes to enable",
                related_information: None,
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 2,
                        character: 31,
                    },
                    end: Position {
                        line: 2,
                        character: 32,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0392",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            cannot_be_a_base: false,
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0392",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "parameter `T` is never used\nconsider removing `T`, referring to it in a field, or using a marker such as `std::marker::PhantomData`",
                related_information: None,
                tags: None,
                data: None,
            },
        ],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}
```

</summary>

It's not an every keystroke thing like the semantic highlight diff though at least, so it's still usable enough.

**Comment by Veykril** [comment] 2022-04-08 21:01
Ye anything trying to do trait solving for your given code will panic, semantic highlighting is just the worst offender for it as it runs type resolution on the entire document on every char entered.

**Comment by flodiebold** [comment] 2022-04-08 21:47
Probably duplicate of #11923 / #11921. I guess we don't need three copies of this, so let's close this one.

**Closed by flodiebold** 2022-04-08 21:47 UTC
Labels: A-ty, C-bug
