### ISSUE TITLE
Autocomplete not working in macro calls

### ISSUE THREAD

**Issue by KyrietS** [rust-analyzer/rust-analyzer#8227] opened 2021-03-28 18:15 UTC
Code completion doesn't work in macro calls, e.g. `println!`, `assert!`, `write!` etc.

Example code:

```rust
struct Foo {
    bar: i32
}

fn main() {
    let foo = Foo {
        bar: 123
    };
    println!("{}", foo.bar);  // there is no code completion when you type "foo."
}
```

![image](https://user-images.githubusercontent.com/19170699/112762333-68a4df00-8fff-11eb-9e57-6d9ec470b85b.png)

When you type first letter "b" then it starts to work:

![image](https://user-images.githubusercontent.com/19170699/112762347-7eb29f80-8fff-11eb-9892-7eadee155f94.png)

Same problem with other macros like assert!():

![image](https://user-images.githubusercontent.com/19170699/112762375-9c800480-8fff-11eb-9480-d72f070d64e7.png)

And again, it works when you type first letter:

![image](https://user-images.githubusercontent.com/19170699/112762417-e0730980-8fff-11eb-924c-eaacb2fddc89.png)

This bug is very annoying because you can't see any member of **any type**. The only workaround to see all members is to type dot "." outside the macro:

![image](https://user-images.githubusercontent.com/19170699/112762516-52e3e980-9000-11eb-90f8-761e19cd660a.png)

**Rust version**: `rustc 1.50.0 (cb75ad5db 2021-02-10)`
**Cargo version**: `cargo 1.50.0 (f04e7fab7 2021-02-04)`
**rust-analyzer version**: `v0.2.529`

**Comment by flodiebold** [comment] 2021-03-28 18:18
Duplicate of #8158, see there for an explanation.

**Closed by flodiebold** 2021-03-28 18:18 UTC

**Comment by KyrietS** [comment] 2021-03-28 18:21
Sorry! I have no idea how I missed this issue. I searched for duplicates before submitting this issue I swear 😅
