### ISSUE TITLE
Show full method signature

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#8019] opened 2021-03-14 20:45 UTC
![image](https://user-images.githubusercontent.com/5961244/111083434-ec45d280-850d-11eb-8b8f-da0b08101c8d.png)

```rust
fn main() {
    use tokio::runtime::Builder;

    let runtime = Builder::new_multi_thread()
        .enable_all()
        .build()
        .unwrap();

    runtime.<|>;
}
```

We should show parameter information here. Imo not showing any parameter information here in auto-completion context is not useful at all (Hovering works, but it disrupts the workflow).

I am not exactly sure but this used to show the full signature.

**Comment by Veykril** [comment] 2021-03-14 20:59
This is already being addressed in https://github.com/rust-analyzer/rust-analyzer/pull/7900, duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7842

**Closed by Veykril** 2021-03-14 20:59 UTC

**Comment by cynecx** [comment] 2021-03-14 21:02
I haven't even bothered with searching for PRs. Only for issues. Sorry about that.

**Comment by Veykril** [comment] 2021-03-14 21:04
No problem
