### ISSUE TITLE
ra_lsp_server thread '<unnamed>' panicked at 'internal error cycle detected'

### ISSUE THREAD

**Issue by alex179ohm** [rust-analyzer/rust-analyzer#2892] opened 2020-01-22 10:03 UTC
full output:
```
thread '<unnamed>' panicked at 'Internal error, cycle detected:

__SalsaDatabaseKey { kind: DefDatabaseStorage(compute_crate_def_map(CrateId(167))) }
', <::std::macros::panic macros>:5:6
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: ra_hir_def::db::crate_def_map
  14: ra_hir_def::nameres::collector::collect_defs
  15: ra_hir_def::nameres::CrateDefMap::compute_crate_def_map_query
  16: salsa::runtime::Runtime<DB>::execute_query_implementation
  17: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<DB,Q,MP>::read
  19: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  20: ra_hir_def::db::crate_def_map
  21: ra_hir_def::nameres::collector::collect_defs
  22: ra_hir_def::nameres::CrateDefMap::compute_crate_def_map_query
  23: salsa::runtime::Runtime<DB>::execute_query_implementation
  24: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  25: salsa::derived::slot::Slot<DB,Q,MP>::read
  26: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  27: ra_hir_def::db::crate_def_map
  28: ra_hir::source_binder::SourceBinder<DB>::to_module_def
  29: ra_hir::source_binder::SourceBinder<DB>::find_container
  30: <T as ra_hir::source_binder::ToId>::to_id
  31: ra_hir::source_binder::SourceBinder<DB>::find_container
  32: ra_hir::source_binder::SourceBinder<DB>::analyze
  33: <once_cell::unsync::Lazy<T,F> as core::ops::deref::Deref>::deref
  34: ra_ide::inlay_hints::inlay_hints
  35: std::panicking::try::do_call
  36: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  37: ra_db::CheckCanceled::catch_canceled
  38: ra_ide::Analysis::inlay_hints
  39: ra_lsp_server::main_loop::handlers::handle_inlay_hints
  40: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
branch: master
toolchain: nightly-x86_64-unknown-linux-gnu
rustc: rustc 1.42.0-nightly (689fca01c 2020-01-17)

**Comment by flodiebold** [comment] 2020-01-24 19:42
Hmm. This looks like there's a crate with a dependency on itself, but I think we check for that? Could you post the output of `cargo metadata` for the workspace, or provide a reproduction?

**Comment by alex179ohm** [comment] 2020-01-27 10:09
Tank you for your response! following your hint, I started investigating to find a suitable reproduction for the panics and it sorted out that the problem was putting the crate on `dev-dependencies` in order to have a bunch of examples in the examples directory which points to the crate himself:
reproduction:
```bash
$ ls tst-crate
examples/
        tst_example.rs
src/
      lib.rs
Cargo.toml
```
where Cargo.toml is:
```toml
[package]
name = "tst-crate"
version = "0.1.0"
authors = ["Alessandro Cresto Miseroglio <alex179ohm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tst-crate = { path = "./" }
```
allowing tst_example.rs to use the crate like this:
```rust
use tst_crate::something;
fn main() {
     something();
}
```
and run examples without the needs of a different crate for each of them, simply typing:
```bash
$ cargo run --example tst_example
```

**Comment by lnicola** [comment] 2020-01-27 10:55
While panicking isn't a great way to handle this, you don't actually need that line under `dev-dependencies` because the examples already depend on the crate. More so, it would also apply to the crate itself, which isn't what you want.

**Comment by matklad** [comment] 2020-01-28 15:49
@alex179ohm I can't reproduce the error with the minized example you've provided. If you can give an example project where this panic happens, that would be very helpful, as we indeed should protect against cyclic deps between crates.

**Comment by alex179ohm** [comment] 2020-02-11 15:19
@matklad sorry for the late, the example in question is the following crate:
https://github.com/alex179ohm/nsq-rust/tree/consumer
just change the Cargo.toml with the following:
```
[package]
name = "nsq-rust"
version = "0.1.0"
authors = ["Alessandro Cresto Miseroglio <alex179ohm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.4.0"
async-tls = "0.6.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hostname = "0.2"
byteorder = "1.3.2"
bytes = "0.5.3"
log = "0.4.8"
rustls = "0.16"

[dev-dependencies]
femme = "1.3.0"
nsq-rust = { path = "./" }
```
and the rust-analyzer crash.
btw, the example I've posted in the previous comment seems working as expected to me too, I wrongly supposed that just adding the same crate to the dev-dependencies should crashing rust-analyzer, but seems not the case. sorry :)

**Comment by lnicola** [comment] 2021-01-25 17:40
@alex179ohm  the linked repo is now gone, do you think you could check if this still happens and maybe prepare a test case?

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it).

**Comment by jonas-schievink** [comment] 2021-05-13 13:45
No update, so closing

**Closed by jonas-schievink** 2021-05-13 13:45 UTC
Labels: S-actionable

**Comment by lnicola** [comment] 2021-05-13 13:50
The repo seems to be back now (?). It doesn't build, but we don't seem to panic, only:

    [ERROR project_model::workspace] cyclic deps: nsq_rust(CrateId(303)) -> nsq_rust(CrateId(303))
