### ISSUE TITLE
Import code action missing if derive macro with same name as trait already imported

### ISSUE THREAD

**Issue by daboross** [rust-analyzer/rust-analyzer#7670] opened 2021-02-14 00:15 UTC
If nothing's imported with a given name, rust-analyzer will give a code action to suggest importing it. But if there's something (just of the wrong type) the action isn't there. At least in cases where it's clearly the wrong type of thing, I think rust-analyzer should still suggest importing.

For example, see this code:

```rust
pub fn thing<T>()
where
    T: Display + Debug,
{
}
```

`Display` gives code actions "Import Display" and "Qualify Display". However, `Debug` gives "no code actions available".

Relatedly, `cargo check` reports different errors for each of these - but also suggests importing for both:

```
$ cargo check
    Checking asdftest v0.1.0 (/home/daboross/asdftest)
error[E0405]: cannot find trait `Display` in this scope
 --> src/lib.rs:3:8
  |
3 |     T: Display + Debug,
  |        ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use core::fmt::Display;
  |
1 | use std::fmt::Display;
  |

error[E0404]: expected trait, found derive macro `Debug`
 --> src/lib.rs:3:18
  |
3 |     T: Display + Debug,
  |                  ^^^^^ not a trait
  |
help: consider importing one of these items instead
  |
1 | use core::fmt::Debug;
  |
1 | use std::fmt::Debug;
  |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0404, E0405.
For more information about an error, try `rustc --explain E0404`.
error: could not compile `asdftest`

To learn more, run the command again with --verbose.
```

Using rust-analyzer version 2021-02-08 installed via the VS Code Marketplace.

**Comment by Veykril** [comment] 2021-02-14 00:44
Duplicate of #7408

**Closed by Veykril** 2021-02-14 00:44 UTC
