### ISSUE TITLE
Renaming import alias renames the original import

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#6554] opened 2020-11-14 19:35 UTC
```rust
pub mod test {
    pub struct OriginalStruct;
}

use test::OriginalStruct as RenamedStruct<|>;

fn main() {
    let renamed = RenamedStruct;
}
```

I place the caret at `RenamedStruct` in the `use test::OriginalStruct as RenamedStruct` line and attempt to use a different name instead of `RenamedStruct`. 
Expected: only two places with `RenamedStruct` are changed:

```rust
pub mod test {
    pub struct OriginalStruct;
}

use test::OriginalStruct as RenamedAgainStruct;

fn main() {
    let renamed = RenamedAgainStruct;
}
```

actulal: the `OriginalStruct` name gets changed:

```rust
pub mod test {
    pub struct RenamedAgainStruct;
}

use test::RenamedAgainStruct as RenamedStruct;

fn main() {
    let renamed = RenamedStruct;
}
```

**Comment by flodiebold** [comment] 2020-12-21 21:39
Duplicate of #5671.

**Closed by flodiebold** 2020-12-21 21:39 UTC
Labels: A-assists, S-actionable
