### ISSUE TITLE
Function trait objects output is not normalized

### ISSUE THREAD

**Issue by smmalis37** [rust-analyzer/rust-analyzer#5057] opened 2020-06-25 11:54 UTC
~~Normally when I use the ? operator, type inference is able to correctly see through it and mark variables with the Ok type of the Result. This seems to fall apart when used on a ref to a function trait object:~~
![image](https://user-images.githubusercontent.com/4054472/85715131-f7b34e00-b69f-11ea-8834-7beb4182864d.png)

I would expect the type of r to be u8.

**Comment by lnicola** [comment] 2020-06-25 12:00
Duplicate of #4281?

**Comment by flodiebold** [comment] 2020-06-25 12:01
I assume the problem is simply inferring the result of `f()`, nothing related to the ? operator. It was mentioned in #4958, but I don't think we have a bug for it yet.

**Comment by smmalis37** [comment] 2020-06-25 12:08
Ah, yeah this happens without ?. I was confused because I have other code that correctly normalizes Fn output, but what I didn't realize that that's on a generic over Fn, not a trait object. This seems to be something specific to trait object Fns.

**Comment by smmalis37** [comment] 2020-06-29 22:32
This might have just been fixed? https://github.com/rust-analyzer/rust-analyzer/pull/4982/files#diff-2166f1133a31a1444822c765c18b9115L1760

**Comment by cynecx** [comment] 2020-06-30 01:03
@smmalis37 Nope. I just checked, afaics it's still "broken".

**Comment by flodiebold** [comment] 2020-07-10 16:21
It seems that's a bug in Chalk: rust-lang/chalk#567.

**Closed** 2020-07-12 20:31 UTC
Labels: A-ty
