### ISSUE TITLE
Renaming trait method name should also change method name in impls and method call (VS Code)

### ISSUE THREAD

**Issue by KSXGitHub** [rust-analyzer/rust-analyzer#4201] opened 2020-04-29 03:31 UTC
Given this code:

```rust
trait MyTrait {
  fn my_func(&self);
}

struct MyStruct;
impl MyTrait for MyStruct {
  fn my_func(&self) {
    println!("hello");
  }
}

fn main() {
  MyStruct.my_func();
}
```

Now, if I move the text caret to `my_func` in trait declaration, press F2, and rename it to `new_name`, I expect `my_func` in trait impl for MyStruct and main function to be changed to `new_name` as well, but it didn't.

**Comment by lnicola** [comment] 2020-12-21 09:43
Duplicate of #2977

**Closed by lnicola** 2020-12-21 09:43 UTC
Labels: E-hard, fun
