### ISSUE TITLE
Error detecting variable type

### ISSUE THREAD

**Issue by shootingsyh** [rust-analyzer/rust-analyzer#5542] opened 2020-07-27 02:29 UTC
Sorry I didn't get a clear repro here.
Here is the file containing the problem: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=073305de6384df0e7ba6e11bdf798189 at line 80.

Or you may download git project at https://github.com/shootingsyh/rxstream, and open vs code with rust plugin and rust-analyser setup. See file with_latest_from.rs. 

queued_source is a pin project field, and should be of type Option. When calling the Option::take function, rust-analyser think it is a stream and expect it to have one argument.

**Comment by lnicola** [comment] 2020-07-27 08:32
> is a pin project field

We don't support proc macros other than custom derives.

**Comment by shootingsyh** [comment] 2020-07-27 15:34
It causes an explicit syntax error in the IDE. If proc macro is not supported, should we mark it just as unknown and not issuing an error?

发自我的iPhone

**Comment by lnicola** [comment] 2020-07-27 15:37
It's not a syntax error, but rather a false positive in a "wrong argument count" check. The check can be disabled in the latest release using the `rust-analyzer.diagnostics.enableExperimental` setting.

**Comment by flodiebold** [comment] 2020-12-21 21:59
Closing this as a duplicate of #6029 since it's caused by an unexpanded proc macro attribute.

**Closed by flodiebold** 2020-12-21 21:59 UTC
