### ISSUE TITLE
ref (&) completion is broken for fiels

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8090] opened 2021-03-18 15:59 UTC
![image](https://user-images.githubusercontent.com/1711539/111656958-0dfbce00-881c-11eb-9495-9fbf76441d0e.png)

![image](https://user-images.githubusercontent.com/1711539/111656984-148a4580-881c-11eb-92a0-d7f3d9566722.png)

:disappointed:

**Comment by flodiebold** [comment] 2021-03-18 16:06
Duplicate of #8058.

**Closed by flodiebold** 2021-03-18 16:06 UTC
Labels: A-completion, S-actionable

**Comment by JoshMcguigan** [comment] 2021-03-22 00:45
Just noting I've implemented a potential workaround for this in #8142.
