### ISSUE TITLE
Struct autocomplete inside macro doesn't work

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#9296] opened 2021-06-15 20:11 UTC
I'm using stable versions:

* rust-analyzer v0.2.637
* Rust v1.52.1
* VSCode v1.57.0
* Windows 10 x64

Autocomplete works normally, except inside macros. In the example below, when **inside** de macro, the <kbd>.</kbd> key brings nothing. With <kbd>Ctrl</kbd> + <kbd>Space</kbd>, the structs members also won't show:

![printscreen](https://user-images.githubusercontent.com/1283868/122116657-3df74500-cdfc-11eb-9afe-f26914acb7dd.gif)

This is the minimal reproducible code:

```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

macro_rules! say {
	($n:expr) => {
		println!("{}", $n);
	};
}

struct Foo {
	num: i32,
	other: i32,
}

fn main() {

	let ff = Foo { num: 123, other: 456 };

	say!(ff.num);
}

```

**Comment by lnicola** [comment] 2021-06-15 20:12
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8158.

**Closed by lnicola** 2021-06-15 20:12 UTC
