### ISSUE TITLE
No highlighting and type interference for localy used enum variants.

### ISSUE THREAD

**Issue by addrianyy** [rust-analyzer/rust-analyzer#5540] opened 2020-07-26 12:47 UTC
```rust
enum TestEnum {
    VariantA,
}
```
Given this enum, when VariantA is used in global scope then highlighting and type interference work correctly:
![image](https://user-images.githubusercontent.com/60794154/88479339-acb28200-cf4e-11ea-9d6d-60e02390b392.png)
However if it's used in function scope it doesn't work correctly:
![image](https://user-images.githubusercontent.com/60794154/88479336-a3c1b080-cf4e-11ea-8c82-2bf6fe1bce6f.png)

**Comment by flodiebold** [comment] 2020-07-26 12:52
Duplicate of #1165.

**Closed by flodiebold** 2020-07-26 12:52 UTC
