### ISSUE TITLE
RA misdetects structopt field access as iterator

### ISSUE THREAD

**Issue by birkenfeld** [rust-analyzer/rust-analyzer#6675] opened 2020-11-30 08:52 UTC
With the following snippet (rust-analyzer cadf0e9, structopt 0.3.20, nightly rust):

```
use structopt::StructOpt;

#[derive(StructOpt, Default)]
struct Options {
    arg: Option<String>
}

fn main() {
    let mut opts = Options::from_args();
    let _arg = opts.arg.take().unwrap();
}
```

the `take()` call produces the error "expected 1 argument", and doc hints show the iterator method.  Also the type of `opts` is not known even though `StructOpt::from_args` should be visible.

**Comment by bjorn3** [comment] 2020-11-30 09:27
`StructOpt` is a proc-macro derive. Proc-macro support is disabled by default. You can enable it using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by birkenfeld** [comment] 2020-11-30 10:22
Thanks for the hint!  With the options set it works as expected.  However I have two questions:

* Even without proc-macro support, should RA not assume an `impl StructOpt for Options`?  This would be enough to know the signature of `from_args`.

* Why is, without any additional info, `take()` inferred to be an iterator method? That's a pretty hit-and-miss assumption.

**Comment by lnicola** [comment] 2020-11-30 11:13
> Even without proc-macro support, should RA not assume an impl StructOpt for Options? This would be enough to know the signature of from_args.

I proposed that at some point, but `derive` isn't required to output a trait impl, so I'd rather see proc macros work better than a heuristic like this.

> Why is, without any additional info, take() inferred to be an iterator method? That's a pretty hit-and-miss assumption.

I think it's an artifact of the way type inference works. The type on the left is unknown and `Iterator::take` is in scope (due to being imported by the prelude), so that's what you get.

**Comment by birkenfeld** [comment] 2020-11-30 14:23
> I proposed that at some point, but derive isn't required to output a trait impl, so I'd rather see proc macros work better than a heuristic like this.

I know, but it's a pretty good heuristic, as heuristics go. Deriving an impl is literally what the syntax means, and also what the user expects. I don't know the plans for the proc-macro support, so maybe it's moot, but in the meantime it should be useful.

> I think it's an artifact of the way type inference works. The type on the left is unknown and Iterator::take is in scope (due to being imported by the prelude), so that's what you get.

This isn't what rustc does, though, so it's also a kind of heuristic. But a worse one...

**Comment by lnicola** [comment] 2020-11-30 14:31
The plan is to enable them by default: #6448.

**Comment by flodiebold** [comment] 2020-11-30 15:13
> This isn't what rustc does, though, so it's also a kind of heuristic. But a worse one...

rustc doesn't need to provide completions for code containing errors.

What we shouldn't do though is emit diagnostics in these situations. It's just not trivial to correctly track.

**Comment by lnicola** [comment] 2020-12-20 15:04
This works pretty much as designed, closing for now.

**Closed by lnicola** 2020-12-20 15:04 UTC
Labels: A-ty
