### ISSUE TITLE
error parsing macro

### ISSUE THREAD

**Issue by sehz** [rust-analyzer/rust-analyzer#7343] opened 2021-01-19 00:56 UTC
When I am file with following lines, VS Code extension can't parse it:
```
select! {

                _ = listener.listen() => {
                    // this should be full sync
                    let changes = listener.sync_changes().await;
                    trace!("{} received changes: {:#?}",S::LABEL,changes);

                    Ok(search(self.store().read().await))
                },
                _ = &mut timer => {
                    debug!(
                        SPEC = S::LABEL,
                        Timeout = *MAX_WAIT_TIME,
                        "store look up timeout expired");
                    return Err(IoError::new(
                        ErrorKind::TimedOut,
                        format!("timed out searching metadata {} failed due to timeout: {} ms",S::LABEL,*MAX_WAIT_TIME),
                    ))
                }

            }
```

Interesting part is that in other places, `select!` macro works fine.

Steps to reproduce:
* clone repo: https://github.com/infinyon/fluvio.git
* Open file: `fluvio/src/client/sync/mod.rs`.

You should see above lines marked as error.  This used to work some months back

**Comment by lnicola** [comment] 2021-01-19 08:22
https://github.com/infinyon/fluvio/blob/master/src/client/src/sync/mod.rs#L107

Duplicate of #1165.

**Closed by lnicola** 2021-01-19 08:22 UTC
Labels: A-macro, S-actionable
