### ISSUE TITLE
Type inference fails on FromIterator trait using basic range.

### ISSUE THREAD

**Issue by cameron-rowe** [rust-analyzer/rust-analyzer#4132] opened 2020-04-25 00:19 UTC
The type inference of FromIterator seems to fail, even though the type of range is correctly deduced.

```rust
use std::iter::FromIterator;
fn main() {
    let v = Vec::from_iter(0..10);
    println!("v: {:?}", v);
}
```
![image](https://user-images.githubusercontent.com/3857514/80266173-71529f80-864f-11ea-9850-6e49de155a75.png)

Explicitly stating the type of the range seems to fix the issue.
```rust
use std::iter::FromIterator;
fn main() {
    let v = Vec::from_iter(0i32..10);
    println!("v: {:?}", v);
}
```
![image](https://user-images.githubusercontent.com/3857514/80266241-b1198700-864f-11ea-81fb-88e255fbf965.png)

**Comment by flodiebold** [comment] 2020-04-25 09:21
Duplicate of #4072, I think.

**Closed by flodiebold** 2020-04-25 09:21 UTC
Labels: A-ty
