### ISSUE TITLE
Unresolved references with syntax errors

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6219] opened 2020-10-13 18:55 UTC
I might be wrong, but I feel we should be able to resolve `open` here:

![image](https://user-images.githubusercontent.com/308347/95903359-b5249700-0d9e-11eb-8afb-5db9069b9a10.png)

(note the missing `>` in the return type).

We resolve `File` just fine.

**Comment by matklad** [comment] 2020-10-14 13:00
What happens here is that the whole `{}` block gets treated as a `const` parameter: `Result<(), 92>`. So, the issue is that we don't really support bodies of const arguments..

**Comment by ruabmbua** [comment] 2020-10-17 12:36
IDE can be hard ^^.

**Comment by Veykril** [comment] 2021-10-30 13:27
Closing in favor of https://github.com/rust-analyzer/rust-analyzer/issues/8655

**Closed by Veykril** 2021-10-30 13:27 UTC
Labels: E-hard, S-unactionable
