### ISSUE TITLE
Wrong error report when macro in macro

### ISSUE THREAD

**Issue by NichtsVonChaos** [rust-analyzer/rust-analyzer#7039] opened 2020-12-25 18:15 UTC
Write some code like:
```rust
use serde_json::json;

fn main() {
    let a = 1;
    let b = json!(format!("{}", a));
}
````
Obviously it can be compiled successfully.
But RA will report:
```
could not resolve macro `$crate::format`
```

**Comment by bjorn3** [comment] 2020-12-25 19:02
Duplicate of #6788

**Closed by bjorn3** 2020-12-25 19:02 UTC
