### ISSUE TITLE
Nalgebra false error

### ISSUE THREAD

**Issue by vctibor** [rust-analyzer/rust-analyzer#9843] opened 2021-08-10 12:42 UTC
Trying out nalgebra crate, many functions are reported as error, but running `cargo run` from command line works.

Cargo.toml:
```
[package]
name = "rnn2"
version = "0.1.0"
edition = "2018"

[dependencies]
nalgebra = "0.29"
```

main.rs:
```
use nalgebra::DMatrix;

fn main() {
    let mut result: DMatrix<f32> = DMatrix::zeros(2, 3);
}
```

`DMatrix::zeros(2, 3)` is reported as error with `expected 0 arguments, found 2` but actually the function exists and is correct, as confirmed by running compiler from terminal.

rust analyzer version: v0.2.702
VS Code version: 1.59
rustup version: 1.24.3

**Comment by Veykril** [comment] 2021-08-10 12:45
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5441

**Closed by Veykril** 2021-08-10 12:45 UTC
