### ISSUE TITLE
Rust analyzer cannot activate because bootstrap error

### ISSUE THREAD

**Issue by HaNaK0** [rust-analyzer/rust-analyzer#8958] opened 2021-05-24 08:50 UTC
Rust analyzer fails to initilize due to an error

Repro: Open a rust project in visual studio code with rust-analyzer installed, 

Error: ERROR [2021-05-24 10:44:23]: Bootstrap error [Error: ENOENT: no such file or directory, mkdir 'C:\C:\Users\Hampus\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\C:\\Users\\Hampus\\AppData\\Roaming\\Code\\User\\globalStorage\\matklad.rust-analyzer'
}

Workaround: Install an older version of rust-analyzer

**Comment by lnicola** [comment] 2021-05-24 08:51
Duplicate of #8956.

**Closed by lnicola** 2021-05-24 08:51 UTC
