### ISSUE TITLE
Mismatched arg count with complicated type aliases from ncollide3d library

### ISSUE THREAD

**Issue by WilliamVenner** [rust-analyzer/rust-analyzer#9923] opened 2021-08-16 15:33 UTC
Hi, I'm using the [ncollide3d] library and rust analyzer is giving me `mismatched-arg-count`:

![image](https://user-images.githubusercontent.com/14863743/129589542-78d67f59-d81d-4403-a94c-2478b39fe2dc.png)

`cargo check` runs fine.

![image](https://user-images.githubusercontent.com/14863743/129589582-3fd6a035-cc0f-49c9-9a02-04ccc16ced94.png)

![image](https://user-images.githubusercontent.com/14863743/129589600-4cae8bbc-b759-4425-8754-1d0c505f0d14.png)

![image](https://user-images.githubusercontent.com/14863743/129589623-ef162ec6-5039-41f1-aa08-a4ad401b0308.png)

rust analyzer incorrectly infers the `new` function as coming from Point1, but it's Point3

**Comment by lnicola** [comment] 2021-08-16 15:35
Duplicate of #8654.

**Closed by lnicola** 2021-08-16 15:35 UTC
