### ISSUE TITLE
Rust-analyzer or VS code error

### ISSUE THREAD

**Issue by dickytamara** [rust-analyzer/rust-analyzer#7458] opened 2021-01-27 00:49 UTC
I have code like this

```Rust
pub const fn test(a: i32, b: i32) -> [i32; 2] { [a, b] }

const LOOKUPVALUE: &'static [[i32;2]; 4] = &[
    test(0x0fab272b, 0x0fab272b), test(0x7e1d93ea, 0x7e1d93ea),
    test(0x0fab272b, 0x7e1d93ea), test(0x7e1d93ea, 0x0fab272b),
];

fn main() {
    //
    LOOKUPVALUE.iter().for_each(|x| println!("{:?}", x))

}
```

Vs-code 
![Screenshot from 2021-01-27 06-53-23](https://user-images.githubusercontent.com/10103969/105926059-d5d5db80-6073-11eb-999b-a37cf660a7ef.png)

please look at variable that printed on const LOOKUPVALUE "a:" and "b:"

**Comment by bjorn3** [comment] 2021-01-27 07:35
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7434

**Comment by flodiebold** [comment] 2021-01-27 10:31
I don't think this is related to #7434.

The issue is a bit unclear, but I think what @dickytamara is referring to is that the parameter hints `a:` and `b:` only show up in some of the calls. My guess is that our heuristics are a bit too eager there; notice that the arguments where the hints are hidden end in `a` resp. `b`.

**Comment by dickytamara** [comment] 2021-01-27 13:01
here another example, like @flodiebold says heruistic more resonable for now 
![Screenshot from 2021-01-27 17-05-23](https://user-images.githubusercontent.com/10103969/105994401-2aac3d00-60da-11eb-9f96-c258c20a78ec.png)

**Comment by Veykril** [comment] 2021-01-27 13:18
The problem is that we check if the expression has the argument name as a prefix or postfix and since your hexadecimal numbers have a trailing `a` or `b` the parameter hints disappear respectively. We shouldn't just check every expression like that but only some of them, mainly field access, paths and method_calls I guess?

**Comment by dickytamara** [comment] 2021-01-27 13:31
yes @Veykril , hints disappear when we have same postfix. i found this when editing large set of predefined table value.

**Closed** 2021-01-27 14:55 UTC
Labels: S-actionable
