### ISSUE TITLE
overwhelming amount of diagnostics with a `use something::{` at top of file

### ISSUE THREAD

**Issue by tspiteri** [rust-analyzer/rust-analyzer#4457] opened 2020-05-14 17:19 UTC
For example
1. Open rust-analyzer/crates/ra_hir_def/src/nameres.rs.
2. Insert a new line before the first use statement.
3. Type `use core::ops::{`.

rust-analyzer sends a textDocument/publishDiagnostics notification with an overwhelming 1821 diagnostics.

I see two issues here:
1. I think there should be zero or one errors in this specific case of an open use statement.
2. I think rust-analyzer should cap the amount of diagnostics in order not to trigger error thresholds that disable checkers (or in order not to make the editor crawl if no thresholds are present in the editor).

(Observed with emacs lsp-mode + flycheck and rust-analyzer version `eb892d7`.)

**Comment by bjorn3** [comment] 2020-05-14 17:23
Duplicate of #1329.

**Comment by tspiteri** [comment] 2020-05-15 10:03
@lnicola In the report I mentioned two things:
1. About the use statement itself, which is a duplicate.
2. That rust-analyzer should cap the amount of diagnostics, which is not a duplicate.

Should I open a new issue focused just on capping? Or is that simply considered as not-a-bug? (I'm fine with either decision, it's just that I'm not sure if this was considered.)

**Comment by lnicola** [comment] 2020-05-15 10:37
I guess we can repurpose this one for capping the amount of diagnostics. I don't have a strong opinion on whether it's a bug or not. I _believe_ we don't have such arbitrary limitations in rust-analyzer, but we'll need to add some for e.g. macro expansion.

**Comment by matklad** [comment] 2020-07-12 00:24
we added diagnostics cap recenty

**Closed by matklad** 2020-07-12 00:24 UTC
