### ISSUE TITLE
Code completion for async_std doesn't work

### ISSUE THREAD

**Issue by EddieIvan01** [rust-analyzer/rust-analyzer#6211] opened 2020-10-13 07:04 UTC
I'm using vscode with RA extension, it couldn't complete code for `async_std::net::TcpStream.[read/write]`

```rust
use async_std::{
    prelude::*,
    net::{TcpListener, TcpStream},
};

// ...

let mut s = TcpStream::connect("1.1.1.1:80").await.unwrap();
s.wr    // no hint for write
s.re    // no hint for read
```

**Comment by EddieIvan01** [comment] 2020-10-13 07:11
![](https://i.loli.net/2020/10/13/tAEP8Ou9KcWZqo1.png)
![](https://i.loli.net/2020/10/13/bGRsXln9DZpwt3V.png)

**Comment by flodiebold** [comment] 2020-10-13 09:02
Might be related to #4243.

**Comment by lnicola** [comment] 2020-10-14 14:02
This seems to end up again in `extension_trait!`, used for the definition of `Read`. Closing as a duplicate of #4243.

**Closed by lnicola** 2020-10-14 14:02 UTC
Labels: A-completion, A-ty, E-unknown, S-unactionable
