### ISSUE TITLE
Use statements in functions not working

### ISSUE THREAD

**Issue by Nashenas88** [rust-analyzer/rust-analyzer#5204] opened 2020-07-03 13:21 UTC
The program below shows `io::ErrorKind::Other` as unresolved. Moving the `use std::io;` line to outside of the function fixes the resolution.

```rust
fn f() {
    use std::io;
    let _ = io::ErrorKind::Other;
}
```

**Comment by lnicola** [comment] 2020-07-03 13:22
Duplicate of #1165.

**Closed by lnicola** 2020-07-03 13:22 UTC
