### ISSUE TITLE
VSCode: failed to parse macro invocation following update to latest version of rust analyzer

### ISSUE THREAD

**Issue by alanhkarp** [rust-analyzer/rust-analyzer#6756] opened 2020-12-08 00:50 UTC
I closed my VSCode project because the rust analyzer was crashing every few minutes. When I opened my project again, I was told to install the latest version of the analyzer, which I did. The next thing I know, I've got a gazillion "failed to parse macro invocation" error messages in my Problems pane. They aren't real errors, because my project compiles and runs just fine.  Many of them point to a line using the json! macro.  Others point to the first line, first character of a file.  One of them is ```could not resolve macro `crate::format_args```.  These errors are only reported on 3 files of the many that use the json! macro.

**Comment by chanks** [comment] 2020-12-08 04:51
I encountered this too, on 0.2.408. Rolled back to 0.2.400, which doesn't have the issue.

(If anyone else needs to, you can do this via Extensions icon -> choose rust-analyzer -> Manage (gear icon) -> Install Another Version)

**Comment by lnicola** [comment] 2020-12-08 05:47
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6740.

You can find there instructions to disable the warning, and it's likely fixed in the latest nightly build.

**Closed by lnicola** 2020-12-08 05:47 UTC
