### ISSUE TITLE
server panicked: assertion failed: check_disjoint_and_sort(indels)

### ISSUE THREAD

**Issue by vi** [rust-analyzer/rust-analyzer#11811] opened 2022-03-24 17:54 UTC
`Refactor: extract module` failed with a panic.

**rust-analyzer version**: `rust-analyzer version: b8e1d09b9 2022-03-24 nightly` (also reproducible in older version)

**rustc version**: `rustc 1.60.0-nightly (0c292c966 2022-02-08)`

```
Panic context:
> 
version: b8e1d09b9 2022-03-24 nightly
request: codeAction/resolve CodeAction {
    title: "Extract Module",
    group: None,
    kind: Some(
        CodeActionKind(
            "refactor.extract",
        ),
    ),
    edit: None,
    is_preferred: None,
    data: Some(
        CodeActionData {
            code_action_params: CodeActionParams {
                text_document: TextDocumentIdentifier {
                    uri: Url {
                        scheme: "file",
                        cannot_be_a_base: false,
                        username: "",
                        password: None,
                        host: None,
                        port: None,
                        path: "/mnt/bkel/vi/code/syn-file-expand/src/lib.rs",
                        query: None,
                        fragment: None,
                    },
                },
                range: Range {
                    start: Position {
                        line: 106,
                        character: 0,
                    },
                    end: Position {
                        line: 272,
                        character: 1,
                    },
                },
                context: CodeActionContext {
                    diagnostics: [],
                    only: Some(
                        [
                            CodeActionKind(
                                "refactor",
                            ),
                        ],
                    ),
                },
                work_done_progress_params: WorkDoneProgressParams {
                    work_done_token: None,
                },
                partial_result_params: PartialResultParams {
                    partial_result_token: None,
                },
            },
            id: "extract_module:RefactorExtract:1",
        },
    ),
}

thread '<unnamed>' panicked at 'assertion failed: check_disjoint_and_sort(indels)', crates/text_edit/src/lib.rs:191:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: text_edit::assert_disjoint_or_equal
   4: ide_assists::assist_context::Assists::add::{{closure}}
   5: ide_assists::assist_context::Assists::add_impl
   6: ide_assists::handlers::extract_module::extract_module
   7: ide_assists::assists
   8: std::panicking::try
   9: ide::Analysis::assists_with_fixes
  10: rust_analyzer::handlers::handle_code_action_resolve
  11: std::panicking::try
  12: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

While trying to extract [`expand_impl` function](https://github.com/vi/syn-file-expand/blob/1c7615b4ba5c6cff3b7338a436cfb410a94f7549/src/lib.rs#L107).

**Comment by lnicola** [comment] 2022-03-24 18:09
Dupe of #11766?

**Closed** 2022-03-24 18:09 UTC
