### ISSUE TITLE
Autocomplete for deref doesn't work for structs defined inside a function

### ISSUE THREAD

**Issue by cbrewster** [rust-analyzer/rust-analyzer#5269] opened 2020-07-08 17:42 UTC
Example:
```rust
use std::rc::Rc;

fn main() {
    struct Foo {
        a: i32,
        b: String,
    }

    let foo = Rc::new(Foo {
        a: 1,
        b: "Hello!".into(),
    });

    foo.<|>
}
```
Expected:
The autocomplete at `foo.<|>` should show options for fields `a` and `b`.

Actual:
The autocomplete options do not include any of the fields from `Foo`.

**Comment by flodiebold** [comment] 2020-07-08 17:51
Duplicate of #1559, I don't think this has anything to do with the deref.

**Closed by flodiebold** 2020-07-08 17:51 UTC
