### ISSUE TITLE
Creating new examples while rust-analyzer is running

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#3768] opened 2020-03-30 01:11 UTC
To reproduce:

`cargo new` a new project, and open it in VSCode.  

Create a new "examples" folder, and create a new foo.rs example.

Fill out the file with `fn main() {}`

On top of the main function you'll see a "Run" link to click.  If you click it, the terminal will say:

```
> Executing task: cargo run -- <

error: a bin target must be available for `cargo run`
The terminal process terminated with exit code: 101
```

If you then use the "Rust Analyzer: Restart Server" action, then the "Run" link does the correct thing (`> Executing task: cargo run --package foo --example foo -- <`)

(Running RA aaa6961)

**Comment by lnicola** [comment] 2020-03-30 06:32
Duplicate of #3715 and #1968.

`rust-analyzer` doesn't handle adding new binaries or dependencies to a workspace. We can probably close this for now, since it's a known issue covered by the others.

**Closed by lnicola** 2020-03-30 06:32 UTC
