### ISSUE TITLE
RA asking for new Github Auth Token?

### ISSUE THREAD

**Issue by Xunjin** [rust-analyzer/rust-analyzer#9289] opened 2021-06-15 10:22 UTC
This morning, received this message from VSCode trying to update to the latest nightly.

![image](https://user-images.githubusercontent.com/31026338/122036725-44f56780-cdaa-11eb-8ad3-4b8a5a285412.png)

Do I really need to give a token to RA? If so why?

Sorry bothering with this question :P

**Comment by bjorn3** [comment] 2021-06-15 10:25
Github sometimes rate limits the downloads. For this reason the option to enter a github auth token was added to get a much higher rate limit. In this case it isn't a rate limit though. Your problem is a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/9284.

**Comment by Xunjin** [comment] 2021-06-15 10:26
In this obvious way deleted all targets at "matklad.rust-analyzer" folder and re download again.

**Closed by bjorn3** 2021-06-15 10:25 UTC
