### ISSUE TITLE
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`   left: `2`,  right: `1`', crates/ra_hir_ty/src/lower.rs:349:5

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#2705] opened 2019-12-31 14:34 UTC
Just saw this in the output window:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', crates/ra_hir_ty/src/lower.rs:349:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: std::panicking::begin_panic_fmt
   8: ra_hir_ty::lower::substs_from_path_segment
   9: ra_hir_ty::lower::<impl ra_hir_ty::TraitRef>::from_resolved_path
  10: ra_hir_ty::lower::<impl ra_hir_ty::TraitRef>::from_path
  11: ra_hir_ty::lower::<impl ra_hir_ty::GenericPredicate>::from_type_bound
  12: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_hir_ty::infer::infer_query
  15: salsa::runtime::Runtime<DB>::execute_query_implementation
  16: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<DB,Q,MP>::read
  18: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  19: ra_hir::source_binder::SourceAnalyzer::new
  20: <once_cell::unsync::Lazy<T,F> as core::ops::deref::Deref>::deref
  21: ra_ide::inlay_hints::get_inlay_hints
  22: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
  26: ra_db::CheckCanceled::catch_canceled
  27: ra_ide::Analysis::inlay_hints
  28: ra_lsp_server::main_loop::handlers::handle_inlay_hints
  29: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pyrotechnick** [comment] 2020-01-03 07:00
I'm also experiencing this.

###  Repro
1. Install latest stable (1.41.1) `Visual Studio Code.app` via `brew cask`
2. Clone `rust-analyzer` and install server and extension via `cargo xtask install`
2. Open relatively large rust project; waiting for the entire workspace to "check"
3. Save any rust file reachable from /Cargo.toml

### Env

```sh
$ rustup show
...
stable-x86_64-apple-darwin (default)
rustc 1.40.0 (73528e339 2019-12-16)
```

```sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
...
```

```sh
$ code --version
1.41.1
```

```sh
$ code --list-extensions
matklad.ra-lsp
```

```sh
$ git -C ~/rust-analyzer rev-parse HEAD
4516c4c1447942a8f01b59a71dcf5abfa2c5e37a
```

**Comment by kiljacken** [comment] 2020-01-03 11:12
Could one of you attempt to get a minimal case that reproduces the issue? It helps debugging a lot.

**Comment by kiljacken** [comment] 2020-01-03 13:23
Okay, so @pyrotechnick and I have gotten it down to the following:
```
use async_std::prelude::*;
use legion::prelude::*;

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Translation(usize);

fn main() {
  let query = <Read<Translation>>::query();
}
```

It seems to be an issue resolving the `Read<T>` struct from legion vs the `Read` trait from async-std. Investigating further.

**Comment by kiljacken** [comment] 2020-01-03 13:34
Repro without external dependencies:
```
use prelude_a::*;
use prelude_b::*;

pub struct Foo;

fn main() {
  let query = <Bar<Foo>>::query();
}

mod prelude_a {
  pub use inner::Bar;

  mod inner {
    pub struct Bar<T>(T);

    impl<T> Bar<T> {
      pub fn query() -> usize {
        0
      }
    }
  }
}

mod prelude_b {
  pub trait Bar {}
}
```
Seems to be related to how we resolve ambiguities (or maybe don't) compared to how rustc does.

**Comment by flodiebold** [comment] 2020-01-03 13:43
Actually it's much simpler, it's an off-by-one error in handling extraneous type arguments for traits:
```rust
trait Trait {}
fn test() {
    <Trait<u32>>::foo()
}
```
Will fix.

**Comment by flodiebold** [comment] 2020-01-03 13:47
(Of course there's probably another issue with `Read` resolving to the wrong thing in the original code.)

**Closed** 2020-01-03 14:09 UTC

**Comment by kiljacken** [comment] 2020-01-03 15:05
Ahh, the remaning issue is just that we don't handle `#[cfg(std)]` properly. Will open an issue if there isn't one already (which there very likely may be)
