### ISSUE TITLE
Unknown type in regex captures index

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#5121] opened 2020-06-29 06:46 UTC
<img width="444" alt="Screenshot 2020-06-29 at 09 46 33" src="https://user-images.githubusercontent.com/24208746/85981778-6e788000-b9ed-11ea-9189-9f63a06e7a04.png">

**Comment by lnicola** [comment] 2020-06-29 06:57
Probably duplicate of #2534.

**Comment by flodiebold** [comment] 2020-06-29 11:33
If it works with `1usize`, it's a duplicate.

**Closed** 2020-06-29 13:59 UTC
