### ISSUE TITLE
Feature Request: Generate documentation stubs for enums, functions and structs

### ISSUE THREAD

**Issue by djthegr8** [rust-analyzer/rust-analyzer#9695] opened 2021-07-26 06:51 UTC
It would help people easily write docstrings for their code if this is added to the quick actions. If there's no disagreement over whether this should be added, I could send up a PR for this...

**Comment by lnicola** [comment] 2021-07-26 07:01
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4767.

**Closed by lnicola** 2021-07-26 07:01 UTC
