### ISSUE TITLE
Find references does't work on `self`

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7316] opened 2021-01-18 07:42 UTC
```rust
struct Foo {}

impl Foo {
    fn bar(self, x: i32) {
        self;
        x;
        x;
    }
}
```

See also https://github.com/rust-analyzer/rust-analyzer/issues/4912#issuecomment-648439029.

**Comment by Veykril** [comment] 2021-01-18 08:50
This does seem to work for me though? 🤔 
![image](https://user-images.githubusercontent.com/3757771/104892532-95d77000-5972-11eb-93e5-d14cd587bba0.png)

**Comment by lnicola** [comment] 2021-01-18 08:53
![image](https://user-images.githubusercontent.com/308347/104892874-5cefc900-597b-11eb-846f-6d5185a9f070.png)

**Comment by Veykril** [comment] 2021-01-18 08:58
Ah okay, it doesn't work on current master, my build was a bit older cause of the update issue we had this week I guess, looks like I broke this somehow, surprised that the test for it still passes though 😅 will take a look then

**Comment by Veykril** [comment] 2021-01-18 09:00
Oh I already see my mistake(and why the test doesn't check this). 👍

**Comment by Veykril** [comment] 2021-01-18 09:26
Ah wait I just realized this will fix itself once https://github.com/rust-analyzer/rust-analyzer/pull/7291 gets merged 😄 

In short the problem is the `self` in the function signature isn't being recognized as a `Name` yet and hence it looks like there is nothing there. The PR changes that.

**Closed** 2021-01-18 17:33 UTC
Labels: S-actionable
