### ISSUE TITLE
Trait bound `impl Into` not able to infer return type.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#9729] opened 2021-07-30 09:46 UTC
In both these examples, the type of `y` is unable to be inferred by rust-analyzer:

```rust
fn a(x: impl Into<String>) {
    let y = x.into();
    y.to_ascii_lowercase();
}

fn b<T>(x: T)
where
    T: Into<String>,
{
    let y = x.into();
    y.to_ascii_lowercase();
}
```

However, interestingly enough, if the following is defined in the file (to shadow built in `Into`) it works:
```rust
pub trait Into<T>: Sized {
    fn into(self) -> T;
}
```

On: rust-analyzer version: 8232804d3 2021-07-30 nightly & rustc 1.53.0 (53cb7b09b 2021-06-17)

![2021-07-30_02-47-48](https://user-images.githubusercontent.com/5489149/127635380-5e423af8-d686-4d74-a7c6-e7c174d3b15f.gif)

**Comment by flodiebold** [comment] 2021-07-30 09:49
Duplicate of #5514.

**Closed by flodiebold** 2021-07-30 09:49 UTC
