### ISSUE TITLE
 Called `Option::unwrap()` on a `None` value, warning in simple hello world Rocket app

### ISSUE THREAD

**Issue by joemooney** [rust-analyzer/rust-analyzer#10570] opened 2021-10-18 01:16 UTC
This compiles and runs fine but there is a rust-analyzer warning present in 2.776 and 2.768 but not in 2.760 and earlier versions of rust-analyzer.

```
 ::::::::::::::
Cargo.toml
::::::::::::::
[package]
name = "foobar"
version = "0.0.1"
edition = "2018"

[dependencies]
rocket = "0.4"
::::::::::::::
src/main.rs
::::::::::::::
#![feature(decl_macro, proc_macro_hygiene)]
#[macro_use]
extern crate rocket;

#[get("/hello")]
fn status() -> String {
    format!("rust-analyzer No warnings in this function")
}

// Compiles fine but rust-analyzer highlights function with:
// called `Option::unwrap()` on a `None` value

#[get("/foobar/<_a>")]
fn foobar(_a: bool) -> String {
    format!("rust-analyzer Warnings in this function")
}

fn main() {
    rocket::ignite()
        .mount("/", routes![status, foobar])
        .launch();
}
```

**Comment by ripxorip** [comment] 2021-11-12 18:06
This is happening to me as well using rust-analyzer 2021-11-08 on arch

**Comment by lnicola** [comment] 2021-11-12 18:13
Possibly a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/10710.

**Comment by MiroFurtado** [comment] 2021-11-30 00:57
This is still occurring on latest nightly release.

**Comment by Tamschi** [comment] 2021-12-25 17:44
Here's a smaller reproduction that builds on stable Rust 1.57.0:

```toml
[package]
name = "macro-test"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
# Needed because `unquote`'s syn dependency isn't set up correctly. It's hopefully not relevant.
proc_macro = true

[dependencies]
proc-macro2 = "1.0.34"
quote = "1.0.10"
syn = "1.0.83"
unquote = "0.0.6"
```

```rust
use quote::quote;
use syn::parse::ParseStream;
use unquote::unquote;

#[allow(dead_code)]
fn parse(input: ParseStream) -> syn::Result<()> {
    unquote!(input, a); // <--
    Ok(())
}
```

Settings (not minimal):

```json
{
    "rust-analyzer.cargo-watch.command": "clippy",
    "rust-analyzer.rainbowHighlightingOn": true,
    "rust-analyzer.procMacro.enabled": true,
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.experimental.procAttrMacros": true,
    "rust-analyzer.cargo.allFeatures": true,
    "rust-analyzer.checkOnSave.extraArgs": [
        "--locked"
    ],
    "rust-analyzer.updates.channel": "nightly"
}
```

- - -

`cargo expand`:

```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
use quote::quote;
use syn::parse::ParseStream;
use unquote::unquote;
#[allow(dead_code)]
fn parse(input: ParseStream) -> syn::Result<()> {
    let input = input;
    let mut prev_span = input.cursor().span();
    if input.call(<syn::Ident as syn::ext::IdentExt>::parse_any)?
        != syn::parse::Parser::parse2(<syn::Ident as syn::ext::IdentExt>::parse_any, {
            let mut _s = ::quote::__private::TokenStream::new();
            ::quote::__private::push_ident(&mut _s, "a");
            _s
        })
        .unwrap()
    {
        return Err(syn::Error::new(input.cursor().span(), "Expected `a`"));
    };
    Ok(())
}
const _: () = {
    extern crate proc_macro;
    #[rustc_proc_macro_decls]
    #[allow(deprecated)]
    static _DECLS: &[proc_macro::bridge::client::ProcMacro] = &[];
};
```

- - -

Error:

```json
[{
	"resource": "/C:/Users/Tamme/Documents/Projekte/macro-test/src/lib.rs",
	"owner": "rustc",
	"code": {
		"value": "macro-error",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#macro-error",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "macro-error"
		}
	},
	"severity": 8,
	"message": "called `Option::unwrap()` on a `None` value",
	"source": "rust-analyzer",
	"startLineNumber": 7,
	"startColumn": 5,
	"endLineNumber": 7,
	"endColumn": 23
}]
```

- - -

Rust Analyzer Client output (abbreviated):
```
INFO [25.12.2021, 18:38:34]: Extension version: 0.3.875
INFO [25.12.2021, 18:38:34]: Using configuration {
  […]
}
INFO [25.12.2021, 18:38:34]: PersistentState: { serverVersion: '0.3.875' }
INFO [25.12.2021, 18:38:34]: Using server binary at c:\Users\Tamme\.vscode\extensions\matklad.rust-analyzer-0.3.875\server\rust-analyzer.exe
```

Rust Analyzer Language Server Trace appears to be empty.

**Comment by oren0e** [comment] 2021-12-28 12:49
Hi, I am having this same issue with rocket. I use `rustc 1.56.0-nightly (0035d9dce 2021-08-16)` with coc-rust-analyzer  0.57.0

**Comment by lnicola** [comment] 2021-12-28 13:00
@MiroFurtado, @Tamschi, @oren0e see https://github.com/rust-analyzer/rust-analyzer/issues/10710#issuecomment-962559112.

**Comment by Tamschi** [comment] 2021-12-28 13:15
> @MiroFurtado, @Tamschi, @oren0e see [#10710 (comment)](https://github.com/rust-analyzer/rust-analyzer/issues/10710#issuecomment-962559112).
> 
> Updating to a newer version of Rocket might fix it.

I'm not using Rocket and I'm on stable, so that's not the issue/fix for me, unfortunately.

**Comment by Tamschi** [comment] 2021-12-28 13:23
(A separate comment since @lnicola already saw the previous reply.)

Should I open a separate issue?
It looks like my problem is likely unrelated then, if this error message can be caused by not implemented endpoints generally.

**Comment by oren0e** [comment] 2021-12-29 10:05
> @MiroFurtado, @Tamschi, @oren0e see [#10710 (comment)](https://github.com/rust-analyzer/rust-analyzer/issues/10710#issuecomment-962559112).
> 
> Updating to a newer version of Rocket might fix it.

Unfortunately I can't use the rc version of rocket for various stability and dependency issues, so that fix is not for me either. Any chance to work it out in rust-analyzer itself?

**Comment by SIGUSR97** [comment] 2022-01-11 16:02
this also occurred to me with [realworld-rust-rocket](https://github.com/TatriX/realworld-rust-rocket). Any updates?

**Comment by nbittich** [comment] 2022-02-19 11:43
Same Here.
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.60.0-nightly (09cb29c64 2022-02-15)

**Closed** 2022-03-23 11:31 UTC
Labels: A-macro, S-actionable, Broken Window, C-bug

**Comment by jonas-schievink** [comment] 2022-03-23 11:34
I hope https://github.com/rust-analyzer/rust-analyzer/pull/11797 has properly fixed this. If not, please leave a comment.

**Comment by oren0e** [comment] 2022-03-23 16:10
Not for me. I still have
```
macro-error: called Option::unwrap() on a None value
```
error in my vim (I use coc.nvim with rust-analyzer) on each one of my endpoints with rocket

**Comment by jonas-schievink** [comment] 2022-03-23 21:00
Presumably because of the same issue as https://github.com/rust-analyzer/rust-analyzer/issues/10772#issuecomment-1076533915

**Comment by jonas-schievink** [comment] 2022-03-24 11:45
@oren0e If you're still using the same nightly version as in https://github.com/rust-analyzer/rust-analyzer/issues/10570#issuecomment-1002088217, it is quite outdated. We can't reasonably support outdated nightly versions.
