### ISSUE TITLE
none-determinism when analyzing types

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#2277] opened 2019-11-16 13:53 UTC
while running `ra_cli  analysis-stats .` on the RA repo itself, I noticed that unknown types/mismatches are not always deterministic:

first run:
````
Expressions of unknown type: 5404 (5%)
Expressions of partially unknown type: 3275 (3%)
Type mismatches: 3852
````
second run:
````
Expressions of unknown type: 5401 (5%)
Expressions of partially unknown type: 3278 (3%)
Type mismatches: 3845
````

ra @ 5d9bce6e88626ec5f36b562803686c848fdf7b66

**Comment by lnicola** [comment] 2019-11-16 13:55
Duplicate of #1552.

**Closed** 2019-11-16 13:57 UTC
