### ISSUE TITLE
Incorrect completion for clippy lints in #[allow()]

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#8369] opened 2021-04-06 11:14 UTC
If I type `#[allow(clippy::susp|)]` and then hit one of the completion options, the tool lint is completed as `clippy::clippy::suspicious_operation_groupings`, that is, with a double `clippy::` prefix.

Current RA nightly and stable rustc.

**Comment by djc** [comment] 2021-04-06 11:26
Also, not sure if this is worth filing a separate issue for, but recovery from early-stage parse errors seems to work well for an unfinished `#[allow`, but as soon as I type an opening parenthesis (`#[allow(`), this leads to the rest of the file being broken. It feels like it ought to be possible to be better there.

**Comment by Veykril** [comment] 2021-04-06 11:39
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7144

**Comment by Veykril** [comment] 2021-04-06 11:40
I dont think we can improve recovery there because as soon as the `(` is typed the parser expects a token tree, which means it spans the entire file I imagine?

**Closed by Veykril** 2021-04-06 11:39 UTC
Labels: A-completion, S-actionable

**Comment by djc** [comment] 2021-04-06 11:51
Ah, I guess that makes sense about the token trees, though I still wonder if it could be slightly smarter. For example, maybe it should recover if the first token is a keyword -- particularly a keyword that introduces an item (`pub`, `struct`, `enum`), or maybe a block (`if`, `for`).

**Comment by Veykril** [comment] 2021-04-06 12:48
I don't think that's possible. The parser can't know that the attribute is unclosed and that the keyword is supposed to start an Item as it doesn't do that kinda lookahead, it might just be part of the token tree. @matklad probably knows better if we can do some tricks here though.

**Comment by djc** [comment] 2021-04-06 12:58
I agree that it might be part of the token tree, but the point is that it seems unlikely -- as I understand it, recovery is all about heuristics.

**Comment by matklad** [comment] 2021-04-06 13:02
recovery became a mess after we added support for macros, see https://github.com/rust-analyzer/rust-analyzer/pull/4680#issuecomment-641346748 for the current state. Straightening this up is on the mid-term roadmap for me personally.
