### ISSUE TITLE
Closing "A request has failed." notification opens output panel

### ISSUE THREAD

**Issue by nyanpasu64** [rust-analyzer/rust-analyzer#10407] opened 2021-09-30 22:05 UTC
In the VS Code plugin, if I close the "A request has failed." with the close button, or it gets automatically closed by a second identical message, it opens the output panel automatically. I expect it to only happen when I press the "Go to output" button.

As to how I'm getting so many crashes that it's becoming a nuisance... well, #10386.

I'm on VS Code plugin version v0.3.763.

**Comment by lnicola** [comment] 2021-10-01 16:48
Probably a duplicate of https://github.com/microsoft/vscode-languageserver-node/issues/786.

**Comment by lnicola** [comment] 2021-10-01 16:49
e

**Comment by nyanpasu64** [comment] 2021-10-01 23:01
How is this a duplicate? That bug was filed in a *different* repository (and this repository doesn't seem to be a fork of it, and I'm not sure if and how the rust-analyzer extension depends on it), was resolved 2.5 months ago, and the bug is still present in the rust-analyzer extension. When will it be fixed here?

**Comment by bjorn3** [comment] 2021-10-02 04:35
> and this repository doesn't seem to be a fork of that, and I'm not sure if and how the rust-analyzer extension depends on it

The vscode extension uses vscode-languageserver-node to communicate with the rust-analyzer language server. Vscode doesn't have an LSP implementation itself. All vscode LSP based extensions need to use this package.

https://github.com/rust-analyzer/rust-analyzer/blob/237ea0d34dced3444486931f68e87cd07f52b6a8/editors/code/package.json#L41

> was resolved 2.5 months ago, and the bug is still present in the rust-analyzer extension.

Maybe updating the dependency version will work? Updating could be non-trivial though. We are currently using 7.1.0-next.5. The main branch on which it should be fixed is 8.0.0-next.2: https://github.com/microsoft/vscode-languageserver-node/blob/10b56de150ad67c3c330da8e2df53ebf2cf347c4/client/package.json#L4

**Comment by lnicola** [comment] 2021-10-02 04:40
Yeah, sorry about it. The bug was in the Code LSP client, but I missed the new release (I had the page in an open tab). Filed #10421 for it.

**Closed** 2021-10-02 16:51 UTC

**Comment by nyanpasu64** [comment] 2021-10-03 03:40
Thanks for the fix!
