### ISSUE TITLE
Code: Postfix completions don't replace typed text

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2558] opened 2019-12-14 06:23 UTC
If you type `1.db` and press Enter, you'll get `dbdbg!(1)`, as opposed to `1.cl` where you get `1.clamp()`.

**Comment by matklad** [comment] 2019-12-14 09:58
I can't reproduce this issue, but I believe *something* has changed recently. I get a similar append/replace confusion for usual completion. I *think* this might be a client-side issue: I remmeber reading something about this in release-notes

**Comment by lnicola** [comment] 2019-12-14 10:10
I'm using Code 1.41. Are you saying that postfix/macro completions work fine, but the usual ones exhibit the problem I mentioned?

**Comment by matklad** [comment] 2019-12-14 10:12
Yes. And I am on 1.40

**Comment by SomeoneToIgnore** [comment] 2019-12-17 20:17
I've stumbled onto the same problem, using RA `ff8f805` and VS Code 1.41, reproduces on 2 different machines with macOs and Linux.
Looks like it persists after RA server reinstalls also.

For instance, in reproduces for me on this line: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/source_binder.rs#L224 when I try to add a new one after the `ty` with `ty.dbg` and press tab.

**Comment by matklad** [comment] 2019-12-17 21:22
Could you check with 1.40?

**Comment by SomeoneToIgnore** [comment] 2019-12-17 21:39
Cannot reproduce with that version indeed.
Sounds like a fun upstream investigation and more workarounds to add awaits :)

**Comment by matklad** [comment] 2019-12-17 21:48
Yeah, just verified that it's broken with 1.41 but "works" with 1.40. Works in quotes, because we do have specific work-arounds for this: https://github.com/rust-analyzer/rust-analyzer/blob/ee93fac7767d36ee91d5a0029bb58023765c72d5/crates/ra_lsp_server/src/conv.rs#L102-L114

Our policy is to support only the latest VS Code, so we should refactor the work-around so that it works with new code

**Comment by SomeoneToIgnore** [comment] 2019-12-17 23:48
I've gazed at the debug prints a bit and it seems that we should adjust a different place: in that method, both `self.source_range.end` and `atom_edit.delete.end` are now not covering the postfix that we've entered (`db` from `ty.db<|>` case, for instance).

The code snippet you've linked seem to do its job well, it just does not know that the ranges are odd and have no way of knowing that.
Neither it is able to know what prefix we've entered to trigger the completion, so I think the place that processes this prefix should be adjusted.

**Comment by SomeoneToIgnore** [comment] 2019-12-17 23:58
I also have a theory on the upstream issue that may cause this: recently I've noticed a very annoying behavior in VS Code that's easy to reproduce:
1. Assign a shortcut to the `Rerun last task` aciton in VS Code. 
2. Open/create a small Rust project with a task (tests or main method) that you can run
3. Run the task once so you can trigger it with the rerun last task shortcut
4. Enter some jibberish sequence in the code and *quickly* trigger the last task rerun right afterwards

Old VS Code always shows a compiler error message with the latest changes.

New VS Code has some sort of a lag that shows an error message for the previous state:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/2690773/71043913-c67a2400-2138-11ea-92d8-736dd16daf0d.png">

If you instead wait for a few seconds before triggering a rerun, VS Code (or RA?) will pick the correct editor state.

Postfix completion bug seems to be related, since RA seem to observe an outdated editor state, the one without the postfix entered.
Alas, waiting does not help with the postfix issues, so it might be something else, but this theory seems like a good starting point for invesstigations anyway.

**Comment by matklad** [comment] 2019-12-18 11:09
>Postfix completion bug seems to be related, since RA seem to observe an outdated editor state, the one without the postfix entered.

Wow, that would be really bad! Could you check if this is indeed the case? I somewhat doubt that this is the reason though: syncing state is kinda important, and I trust VS Code devs to not mess it up :)

**Comment by SomeoneToIgnore** [comment] 2019-12-18 11:32
I am not entirely sure if the postfix bug and the sync issue are related, but double checked the sync issue on my Linux and mac with freshmost RA and it is indeed works as described in https://github.com/rust-analyzer/rust-analyzer/issues/2558#issuecomment-566803280

Here's the video that shows what I'm talking about: https://www.dropbox.com/s/k9yjg29x6p3mqti/vs_code_sync_bug.mov

I really want it to be some kind of local isssue with my settings, but it does not look like it.
Could you double check it yourself?

**Comment by SomeoneToIgnore** [comment] 2019-12-19 20:18
Guess what: 14.1.1 had adressed the postfix completion issue.

The task rerun issue is still a thing though, so now we know that they are not related.

**Comment by SomeoneToIgnore** [comment] 2019-12-19 21:42
> The task rerun issue is still a thing though, so now we know that they are not related after all.

I've checked it on a non-RA project and it's also affected.
I'll create an upstream issue after the https://github.com/microsoft/vscode/issues/87440 ends.

And since the OP issue is fixed, I think we should close this ticket.

**Comment by lnicola** [comment] 2019-12-19 21:52
Sure. I didn't test 1.41.1 (it's not out yet for me), but it's probably working now. Thanks!

**Closed** 2019-12-19 21:57 UTC

**Comment by SomeoneToIgnore** [comment] 2019-12-20 21:35
>  I'll create an upstream issue after the microsoft/vscode#87440 ends.

And during the issue creation, I've checked, as suggested, with the VS Code developer preview and it seems like both issues are fixed there.
So we just have to wait for more VS Code updates, great.
