### ISSUE TITLE
Hover in vec![] quickly disappears

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3135] opened 2020-02-14 14:06 UTC
If I hover on the `None` below the hover window pops up and immediately closed. vscode 1.42.1
```rust
pub fn foo() -> Vec<Option<i32>> {
    vec![No<|>ne]
}
```

**Comment by 0xd4d** [comment] 2020-02-14 21:46
https://github.com/rust-analyzer/rust-analyzer/issues/3000

**Comment by KamranMackey** [comment] 2020-02-17 14:26
This severely needs to be fixed. It's *really* annoying.

**Comment by KamranMackey** [comment] 2020-02-17 14:27
I'm experiencing the same thing, and honestly it's kind of annoying and distracting. This is imho a pretty major issue and should be looked into being fixed soon.

**Comment by kiljacken** [comment] 2020-02-17 14:30
@KamranMackey Please don't bump issues with a "me too", you have to remember that you are notifying quite a lot of people when you comment, so if you just want to acknowledge the issue please use the reaction buttons instead.

If it's that important to you, you're also more than welcome to dig into the code and help solve the issue :+1:

**Comment by edwin0cheng** [comment] 2020-02-17 14:39
My wild guess is that the resolved hover `text_range` is mapping to a `MacroFile` `FileId`, but we do not remap it to the original file. But I remember I did fix this similar bug. Maybe a regression...

**Comment by KamranMackey** [comment] 2020-02-18 16:57
Sorry to be a bother by bumping the issue again, but this isn't of the me too bumping variety. Just wanted to add onto the issue. It appears that when hovering, it appears to disappear for a lot of macros, not just `vec!`. Even custom macros appear to exhibit the issue of the hover preview quickly disappearing in VS Code, at least from my testing.

**Comment by KamranMackey** [comment] 2020-02-19 13:08
Commit b80426 did not fix the issue. The flicker on hover is still happening in VS Code with `vec!`'s and other macros. And I just updated Rust Analyzer to the latest commit so I know I merged the fix into my local build.

**Comment by edwin0cheng** [comment] 2020-02-19 13:12
I did try that fixed the flicking issue in mentioned in my machine (e.g. `match_ast` macro in RA source code) 

Are you set the `rust-analyzer.serverPath: rust-analyzer` to prevent to use the market place one?

**Comment by KamranMackey** [comment] 2020-02-19 13:14
@edwin0cheng Yup, my server path is set to rust-analyzer as it told me to do after I had finished compiling.

**Comment by edwin0cheng** [comment] 2020-02-19 13:15
Do you have any reduced test case I can test with ?

**Comment by KamranMackey** [comment] 2020-02-19 13:20
Sure.

```rust
vec![
  ("Artist", artist, true),
  ("Mastered for iTunes", &mastered_for_itunes, true),
  ("Release Date", release_date, true),
  ("Genres", genres, true),
  ("Record Label", record_label, true),
  ("Tracks", track_count, true)
  ("Mastered for iTunes", &mastered_for_itunes, true),
  ("Release Date", release_date, true),
  ("Genres", genres, true),
  ("Record Label", record_label, true),
  ("Tracks", track_count, true),
]);
```

This is in my production code, it's inside of a function that accepts a `vec!`. The variables names won't exist so I think just using generic String variables should work.

**Comment by edwin0cheng** [comment] 2020-02-19 13:30
![test_hover](https://user-images.githubusercontent.com/11014119/74838695-fe7f2c80-535e-11ea-80ad-c36065bb2716.gif)

**Comment by KamranMackey** [comment] 2020-02-19 13:34
That's not the case for me, the hover fails to work and still immediately disappears. The vec! was also in a function. And I'm on Visual Studio Code Insiders, version 1.43.0 on the `win64` platform.

**Comment by edwin0cheng** [comment] 2020-02-19 14:03
I don't know what happened exactly, but maybe because VSCode is somehow still using the old binary. 

Maybe you could try to uninstall the plugin and delete the binary from ~/.vscode/extensions from marketplace (If it is previously installed), and reinstall it from source.

**Comment by KamranMackey** [comment] 2020-02-19 14:07
@edwin0cheng I just did a clean reinstall of the extension, and nope. No dice. :(

**Comment by lnicola** [comment] 2020-02-19 21:10
Can you also make sure that the extension is no longer present on disk?

**Comment by KamranMackey** [comment] 2020-02-20 02:26
> Can you also make sure that the extension is no longer present on disk?

It wasn't present on disk as I completely removed the extension from the code insiders folder. I don't know what might be causing the bug but if it isn't happening on macOS, it might be a Windows specific quirk that might need more looking into.

**Comment by bjorn3** [comment] 2020-02-20 08:38
I believe `globalStoragePath`, where the language server is stored, is different from the extension dir.

**Comment by edwin0cheng** [comment] 2020-02-21 10:49
@KamranMackey,  since #3247 was merged, would you mind to use that "Show RA Version" command to confirm which RA you are using ?

**Comment by Veetaha** [comment] 2020-02-21 14:39
Better input would be the console log output (our logging infra is under development #3250....). Might I ask you, please, to open command palette with <kbd>Ctrl+Shift+P</kbd>, write `Toggle Developer Tools` and press enter to open the Developer Tools, then open Console tab and send its contents here?

**Comment by KamranMackey** [comment] 2020-02-21 16:50
@edwin0cheng @Veetaha Sure, I'll do both:

```
rust-analyzer version : rust-analyzer e3037c2
```

[Log File](https://github.com/rust-analyzer/rust-analyzer/files/4237098/-1582303742626.log)

**Comment by SomeoneToIgnore** [comment] 2020-02-22 20:36
Hm, for me the `vec!` [example](https://github.com/rust-analyzer/rust-analyzer/issues/3135#issuecomment-588225383) displays the offset hovers and `match_ast!` macro contents from `inlay_hints.rs` in RA codebase shows quickly disappearing pop-up.

`rust-analyzer version : rust-analyzer e91375c` (the freshmost currently), macOs, VSCodium

Ping me here or on Zulip if I can help with the issue somehow.

**Comment by lnicola** [comment] 2020-02-22 20:41
I see this myself. It attaches the hover hints to the variable definition sites:

![image](https://user-images.githubusercontent.com/308347/75098911-62565f00-55c4-11ea-99c7-a187d8b6521b.png)

**Comment by edwin0cheng** [comment] 2020-02-23 01:43
Thanks @lnicola for typing the code out, it actually helps me to understand what happened.

Note that the following code works: (Would like to confirm by others)

```rust
fn main() {
    let artist = "";
    let mastered_for_itunes = "";
    let release_date = "";
    let genres = "";
    let record_label = "";
    let track_count = "";

    let _ = vec![
        ("Artist", artist, true),
        ("Mastered for iTunes", &mastered_for_itunes, true),
        ("Release Date", release_date, true),
        ("Genres", genres, true),
        ("Record Label", record_label, true),
        ("Tracks", track_count, true)    /// No trailing comma
    ];
}
```

It is because `vec!` is defined as :
```rust
macro_rules! vec {
    ($elem:expr; $n:expr) => (
        $crate::vec::from_elem($elem, $n)
    );
    ($($x:expr),*) => (
        <[_]>::into_vec(box [$($x),*])
    );
    ($($x:expr,)*) => ($crate::vec![$($x),*])
}
```

***With*** trailing comma, it is a recursive macro, and as  I said in this [comment](https://github.com/rust-analyzer/rust-analyzer/issues/3000#issuecomment-589968324), we didn't support recursive macro on `original_range` yet.

**Comment by lnicola** [comment] 2020-02-23 08:16
> Would like to confirm by others

It does, mostly. One strange thing is the tooltip I get when hovering over `"Mastered for iTunes"`, see below. There's no tooltip for the other strings.

![image](https://user-images.githubusercontent.com/308347/75106438-564eb980-5625-11ea-99d7-5b5405e5ab14.png)

**Comment by kjeremy** [comment] 2020-02-25 16:42
This also happens in `assert_eq_text!`

**Comment by edwin0cheng** [comment] 2020-02-26 04:41
@lnicola #3314 should fix the recursive macro bug. however,

> It does, mostly. One strange thing is the tooltip I get when hovering over "Mastered for iTunes", see below. There's no tooltip for the other strings.

This bug is so strange... If I change it to: 
```
fn main() {
    let artist = "";
    let mastered_for_itunes = "";
    let release_date = "";
    let genres = "";
    let record_label = "";
    let track_count = "";

    let _ = vec![
        ("Artist", artist, true),
        ("Mastered for iTunes", mastered_for_itunes, true),   // <- removed `&` here.
        ("Release Date", release_date, true),
        ("Genres", genres, true),
        ("Record Label", record_label, true),
        ("Tracks", track_count, true),
    ];
}
```

The tooltip do not show in this case. Um...

**Comment by lnicola** [comment] 2020-02-26 13:51
This works fine for me, including the string hover issue I mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/3135#issuecomment-590038654.

**Comment by tommyshem** [comment] 2020-02-26 20:28
I was looking into this problem as I am new to rust and the hover flashes up and then goes away.

You have to have more than one page of code to see this problem as it looks like the range sent back is wrong. So if you have a test example then it will show up as normal but in the wrong place but if you have more code then it show up as a flash hover. 

Tag code below on any project with more than a full page on 'vscode'.

```rust
 fn updater(){
        let art = "testing";
        let _ = vec![("test",art,true),];
    }
```

If you hover over 'art' in the vec! code you get his trace from vscode. 
The return type is right but the range is wrong.

Note the line number and character of the sent request to the response message.

```json
[Trace - 20:09:35] Sending request 'textDocument/hover - (706)'.
Params: {
    "textDocument": {
        "uri": "file:///home/tommy/External/git-workspaces/github/rust-analyzer/crates/ra_ide/src/hover.rs"
    },
    "position": {
        "line": 821,
        "character": 30
    }
}


[Trace - 20:09:35] Received response 'textDocument/hover - (706)' in 3ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```rust\n&str\n```"
    },
    "range": {
        "end": {
            "character": 24,
            "line": 0
        },
        "start": {
            "character": 21,
            "line": 0
        }
    }
}
```
 
I hope this helps to narrow down the fault. I have been looking into the code base but it is a bit to advanced for me to find where it gets the range from.

**Comment by edwin0cheng** [comment] 2020-02-27 00:56
@tommyshem Thanks for the comment. I think It should be fixed by #3325, would you mind to test it again ?

**Comment by tommyshem** [comment] 2020-02-27 23:25
@edwin0cheng I have tested with the fix and I can confirm that it is working now.  

Thank you for fixing it.

**Comment by KamranMackey** [comment] 2020-02-27 23:28
Working over here too! Thank you so much for fixing this. :)

**Comment by edwin0cheng** [comment] 2020-02-28 00:47
I will close this for now, Feel free to reopen it if needed.

**Closed by edwin0cheng** 2020-02-28 00:47 UTC
Labels: A-vscode
