### ISSUE TITLE
unresolved macro call

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#8477] opened 2021-04-12 11:34 UTC
VS code plugin version: 0.2.554

Seems like #6716 is still present.

![image](https://user-images.githubusercontent.com/22871609/114388142-ee548d00-9bb0-11eb-8e13-84e7e77a6c83.png)

And the previous workaround is not working anymore:

```
"rust-analyzer.diagnostics.disabled": [
  "macro-error"
]
```

**Comment by lnicola** [comment] 2021-04-12 11:36
That's `unresolved-macro-call`.

**Comment by jonas-schievink** [comment] 2021-04-12 11:42
duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6835

**Closed by jonas-schievink** 2021-04-12 11:42 UTC
Labels: A-macro
