### ISSUE TITLE
When auto-importing the trait for `.deref()`, RA chooses `lazy_static::__Deref` over `std::ops::Deref`

### ISSUE THREAD

**Issue by rben01** [rust-analyzer/rust-analyzer#10882] opened 2021-11-29 04:40 UTC
Description: when RA suggests `.deref()` and picks a trait to auto-import to bring `deref()` into scope, it chooses `lazy_static::__Deref` instead of the more common `std::ops::Deref` or `core::ops::Deref`. My Cargo.toml contains `lazy_static = "1.4.0"` under `[dependencies]`.

VSCode screenshot:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/766670/143809678-0d82b22b-4f72-43e0-ad23-a3dbf5cf5084.png">

Code to reproduce is below. The issue also occurs if `rc::Rc` is replaced with `cell::RefCell` (and `.borrow()` added to obtain a `Ref`), but I'm not sure about what happens with other `Deref` implementors.

```rust
use std::rc::Rc;

struct A {
	r: Rc<String>,
}

fn f() {
	let a = A {
		r: Rc::new("s".to_owned()),
	};
	let s = a.r.der|      // Cursor to the right of `der`
	//             ┌──────────────────────────────────────────┐
	//             │³ deref() (use lazy_static::__Deref)      │
	//             │³ deref_mut() (use std::ops::DerefMut)    │
	//             └──────────────────────────────────────────┘
}
```

RA correctly suggests `.deref()` as an autocomplete for `der`, but chooses to auto-import the necessary trait from `lazy_static::__Deref`, instead of `std::ops::Deref` or `core::ops::Deref`, which seem like more reasonable choices. (It correctly offers to import `.deref_mut()` from `std::ops::DerefMut`.) In the attached screenshot, pressing `<TAB>` will insert `use lazy_static::__Deref` near the top of the file.

Similarly, if you write out `deref()` without importing anything, the fix-it for the error offers to import or qualify with `lazy_static::_Deref` (same underlying issue, I assume).

**Comment by Veykril** [comment] 2021-11-29 11:05
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/9197

**Closed by Veykril** 2021-11-29 11:05 UTC
