### ISSUE TITLE
Could not resolve macro 'ufmt::uwriteln`

### ISSUE THREAD

**Issue by nbigaouette** [rust-analyzer/rust-analyzer#7674] opened 2021-02-14 15:30 UTC
First, thanks a lot for rust-analyzer!!

I am exploring rust on an Arduino Uno (avr-atmega328p target) but rust-analyzer can not resolve the `ufmt::uwriteln` macro:

![Capture d’écran, le 2021-02-14 à 10 23 31](https://user-images.githubusercontent.com/112988/107880827-4b80da80-6eaf-11eb-8be1-ad0fe31e3a66.png)

My code is available at https://github.com/nbigaouette/robot-car/tree/343b89bc397dc99761de583d744ebe8d47dfd135/rust
Note that I do have [this as settings](https://github.com/nbigaouette/robot-car/blob/343b89bc397dc99761de583d744ebe8d47dfd135/.vscode/settings.json#L14-L21):
```
    "rust-analyzer.checkOnSave.allTargets": false,
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "avr-atmega328p.json"
    ],
```

My guess is that I might be missing a config option or that r-a is confused by the options I have...

Thank you!

**Comment by bjorn3** [comment] 2021-02-14 15:40
`ufmt` uses proc-macro-hack, which uses attribute proc macros. These aren't yet supported.

Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6029

**Closed** 2021-02-14 17:30 UTC
