### ISSUE TITLE
feature: Snippet completions

### ISSUE THREAD

**Issue by yaahc** [rust-analyzer/rust-analyzer#1705] opened 2019-08-19 20:04 UTC
currently, rls supports presenting completions for associated functions as snippets where you can jump through the various args.

![Screenshot from 2019-08-19 12-05-11](https://user-images.githubusercontent.com/1993852/63295482-9c475100-c281-11e9-8eca-025123943968.png)
![Screenshot from 2019-08-19 12-05-22](https://user-images.githubusercontent.com/1993852/63295486-9e111480-c281-11e9-80a1-8f81bf22a425.png)

rust-analyzer does not yet have this feature. Instead it will insert a pair of parens, and place the cursor between them if the function has 1 or more args, and after if the function has no args.

![Screenshot from 2019-08-19 12-06-22](https://user-images.githubusercontent.com/1993852/63295518-b6812f00-c281-11e9-81c7-7ea1ffee8f03.png)
![Screenshot from 2019-08-19 12-06-32](https://user-images.githubusercontent.com/1993852/63295525-b7b25c00-c281-11e9-8271-3b4c5431005c.png)

We should add support for snippets and do our best to at least support all the features that rls does with snippets and function completions.

**Comment by yaahc** [comment] 2019-08-19 20:05
More comments from @matklad on zulip

I can't give a super-thorogh mentoring instructions right now, but (besides dec docs in the repo) what you want to look at are:

* [entry point for completion](https://github.com/rust-analyzer/rust-analyzer/blob/c7d37e424f1e04f87982233f97e1e9385191b7f1/crates/ra_lsp_server/src/main_loop/handlers.rs#L340-L377)
* [code that translates internal completion items to lsp](https://github.com/rust-analyzer/rust-analyzer/blob/c7d37e424f1e04f87982233f97e1e9385191b7f1/crates/ra_lsp_server/src/conv.rs#L92-L139)
* [code that inserts parens](https://github.com/rust-analyzer/rust-analyzer/blob/c7d37e424f1e04f87982233f97e1e9385191b7f1/crates/ra_ide_api/src/completion/presentation.rs#L120-L130)

**Comment by matklad** [comment] 2019-08-22 11:45
@yaahc see https://github.com/rust-analyzer/rust-analyzer/pull/1715 which implements feature flags. In particular, `"completion.insertion.add-call-parenthesis"` controls "auto insert ()" behavior.

**Comment by bstaletic** [comment] 2019-12-09 21:42
Hello, I'm a maintainer of a client that doesn't support snippets. Currently rust-analyzer doesn't work because it always returns snippets on completion. I wanted to try `completion.insertion.add-call-parenthesis` and pretend that rust-analyzer isn't completing snippets, just to see how it works.

Sending `{"completion.insertion.add-call-parenthesis":false}` in `initializationOptions` didn't work, the `()` still got inserted. So how is this option supposed to be used?

**Comment by matklad** [comment] 2019-12-10 10:59
@bstaletic at the moment, rust-analyzer doesn't support non-snippet based completion. Strictly speaking, this is a violation of the LSP protocol, which requires to consult the corresponding client capability before sending completion. However, at the moment we deliberately target "the latest" version of the protocol (more discussion [here](https://github.com/rust-analyzer/rust-analyzer/issues/144#issuecomment-471856896)). I've opened https://github.com/rust-analyzer/rust-analyzer/issues/2518 to add proper support here.

What `completion.insertion.add-call-parenthesis` feature does is removing a specific snippet some users find annoying, it does not disable all snippets. However, looking at the code, it seems like it should fall back to plain completion in this snippet. 

I think the problem is that you need to nest `insertion` into `featureFlags` key. See sublime example here: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/README.md#sublime-text-3. I would argue that this `featureFlags` nesting makes sense from the implementation point of view, but, UI-wise, you are not the first person confused with it... We should remove this nesting on the surface some day.

**Comment by bstaletic** [comment] 2019-12-10 11:33
@matklad Thanks for opening #2518, I did leave my thoughts regarding snippets there.

**Comment by iTZAvishay** [comment] 2020-02-29 23:10
I guess no one wants to implement this yet; I'll bite the bullet and attempt to implement this as my first issue, anything I should know?

**Comment by matklad** [comment] 2020-02-29 23:12
I believe https://github.com/rust-analyzer/rust-analyzer/issues/1705#issuecomment-522732758 still lists the most relevant things.

**Comment by iTZAvishay** [comment] 2020-02-29 23:23
I see, thank you.

**Comment by kjeremy** [comment] 2020-03-03 19:49
See snippet syntax here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion

**Comment by justinas** [comment] 2020-04-15 12:03
Having https://github.com/rust-analyzer/rust-analyzer/pull/3432 merged, what is left to fully support snippets?

**Comment by Ten0** [comment] 2020-04-21 10:49
Hmm I beleive RLS supports a `derive` snippet and other things of the same kind, which would be useful to add as well :)

**Comment by matklad** [comment] 2020-04-22 08:40
Yeah, I belive the original issue is fixed. For code snippets, which is a different feature from completion, my general stance is that they are often (but not always) a work-around for a missing feature in and IDE. 

For derive specifically, see https://github.com/rust-analyzer/rust-analyzer/pull/4015

**Closed by matklad** 2020-04-22 08:40 UTC
Labels: A-completion
