### ISSUE TITLE
Failed inference of types from typenum::consts::*

### ISSUE THREAD

**Issue by dfoxfranke** [rust-analyzer/rust-analyzer#6247] opened 2020-10-15 22:37 UTC
If I call `sha2::Sha256::digest()`, rust-analyzer infers a return type of `GenericArray<u8, {unknown}>`. The unknown parameter ought to be `typenum::consts::U64`. If you take a look at the source of the `typenum` crate, it ceases to be surprising that this is broken: `consts.rs` doesn't appear anywhere in the source tree; it's wholly generated by `main/build.rs`. I've enabled the "Load Out Dirs From Check" and "Proc Macro: Enable" options hoping that these would allow rust-analyzer to cope with such situations, but it seems not.

**Comment by lnicola** [comment] 2020-10-16 09:35
Duplicate of #4991?

**Comment by dfoxfranke** [comment] 2020-10-16 14:36
Could be. #4991 might be related to this bug, to #5003, or both; I'm not sure. It's plausibly related to this one because of the constraints `D::BlockSize: ArrayLength<u8>` and `D::DigestSize: ArrayLength<u8>` on the `impl<D> NewMac for Hmac<D>`. `Sha256::BlockSize` and `Sha256::DigestSize` are both defined using symbols from `typenum::consts`.

**Comment by dfoxfranke** [comment] 2020-10-16 14:44
n.b, I can't wait for `const_generics` and `const_evaluatable_checked` to stabilize so that we can take the `typenum` and `generic_array` crates out behind the shed.

**Comment by flodiebold** [comment] 2020-12-21 14:43
Works for me on master (but in a way that might make you wish it wouldn't):

![2020-12-21-154302_940x117_scrot](https://user-images.githubusercontent.com/906069/102788631-3ef66f00-43a3-11eb-8435-9890337d4bdb.png)

**Closed** 2020-12-22 15:07 UTC
Labels: A-ty
