### ISSUE TITLE
No diagnostics on startup with rust-analyzer compiled from master (~2 days ago)

### ISSUE THREAD

**Issue by bstaletic** [rust-analyzer/rust-analyzer#8538] opened 2021-04-15 23:15 UTC
With the latest rust-analyzer available through rustup, diagnostics work as expected, but compiling master, I had some problems.

Specifically, https://github.com/rust-analyzer/rust-analyzer/commit/10a243ea55565a0dd1de52f8f802c3e3a7bfef54 is the commit I've compiled and with it, `textDocument/publishDiagnostics` is always empty on startup.

Test file:

```rust
fn main() {
    let captured_val = "a captured value".to_string();
    let closure_parameter = "a parameter value".to_string();

    let mut ct = ClosureTest {
        cls: |closure_parameter| &captured_val,
    };
    println!("{}", (ct.cls)(&closure_parameter));
}

struct ClosureTest<T>
where
    T: FnMut(&str) -> &str,
{
    cls: T,
}
```

Steps to reproduce:

1. Open the `src/main.rs` with the above contents.
2. RA reports `ok` status
3. My fans spin up while RA indexes the project.
4. No diagnostics highlighting happens and `publishDiagnostics` is `[]` in the log.
5. Force write to the file.
6. Correct diagnostics arrive instantly.

Log of exchanged messages before writing the file:

```
2021-04-16 01:07:35,862 - DEBUG - TX: Sending message: b'Content-Length: 1332\r\n\r\n{"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"experimental":{"serverStatusNotification":true,"statusNotification":true},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true}}},"initializationOptions":{},"processId":5630,"rootPath":"/home/bstaletic/work/test/r","rootUri":"file:///home/bstaletic/work/test/r"}}'
2021-04-16 01:07:35,864 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"selectionRangeProvider":true,"hoverProvider":true,"completionProvider":{"triggerCharacters":[":",".","\'"]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite"],"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">","{"]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"workspace":{"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.rs","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}},"callHierarchyProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","enumMember","typeParameter","function","method","property","macro","variable","parameter","angle","arithmetic","attribute","bitwise","boolean","brace","bracket","builtinType","characterLiteral","colon","comma","comparision","constParameter","dot","escapeSequence","formatSpecifier","generic","label","lifetime","logical","operator","parenthesis","punctuation","selfKeyword","semicolon","typeAlias","union","unresolvedReference"],"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","consuming","unsafe","attribute","trait","callable","intraDocLink"]},"range":true,"full":{"delta":true}},"experimental":{"joinLines":true,"ssr":true,"onEnter":true,"parentModule":true,"runnables":{"kinds":["cargo"]}}},"serverInfo":{"name":"rust-analyzer","version":""}}}'
2021-04-16 01:07:35,865 - DEBUG - TX: Sending notification: b'Content-Length: 52\r\n\r\n{"jsonrpc":"2.0","method":"initialized","params":{}}'
2021-04-16 01:07:35,865 - DEBUG - TX: Sending notification: b'Content-Length: 86\r\n\r\n{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}'
2021-04-16 01:07:35,865 - DEBUG - TX: Sending notification: b'Content-Length: 536\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"rust","text":"fn main() {\\n    let captured_val = \\"a captured value\\".to_string();\\n    let closure_parameter = \\"a parameter value\\".to_string();\\n\\n    let mut ct = ClosureTest {\\n        cls: |closure_parameter| &captured_val,\\n    };\\n    println!(\\"{}\\", (ct.cls)(&closure_parameter));\\n}\\n\\nstruct ClosureTest<T>\\nwhere\\n    T: FnMut(&str) -> &str,\\n{\\n    cls: T,\\n}\\n","uri":"file:///home/bstaletic/work/test/r/src/main.rs","version":1}}}'
2021-04-16 01:07:35,872 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":0,"method":"workspace/configuration","params":{"items":[{"section":"rust-analyzer"}]}}'
2021-04-16 01:07:35,872 - DEBUG - TX: Sending response: b'Content-Length: 40\r\n\r\n{"id":0,"jsonrpc":"2.0","result":[null]}'
2021-04-16 01:07:35,872 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"experimental/serverStatus","params":{"health":"ok","quiescent":false,"message":null}}'
2021-04-16 01:07:36,038 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":1,"method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/home/bstaletic/work/test/r/**/*.rs"}]}}]}}'
2021-04-16 01:07:36,041 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":1,"jsonrpc":"2.0","result":null}'
2021-04-16 01:07:36,102 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":2,"method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/home/bstaletic/work/test/r/**/*.rs"}]}}]}}'
2021-04-16 01:07:36,105 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":2,"jsonrpc":"2.0","result":null}'
2021-04-16 01:07:36,122 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":3,"method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/home/bstaletic/work/test/r/**/*.rs"}]}}]}}'
2021-04-16 01:07:36,124 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":3,"jsonrpc":"2.0","result":null}'
2021-04-16 01:07:36,142 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"experimental/serverStatus","params":{"health":"ok","quiescent":true,"message":null}}'
2021-04-16 01:07:40,340 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[],"version":1}}'
```

After the above, writing the file results in:

```
2021-04-16 01:08:16,466 - DEBUG - TX: Sending notification: b'Content-Length: 144\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","version":1}}}'
2021-04-16 01:08:16,572 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[{"range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}},"severity":2,"code":"unused_variables","source":"rustc","message":"unused variable: `closure_parameter`\\n`#[warn(unused_variables)]` on by default","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}}},"message":"if this is intentional, prefix it with an underscore"}],"tags":[1]},{"range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}},"severity":4,"code":"unused_variables","source":"rustc","message":"if this is intentional, prefix it with an underscore","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}}},"message":"original diagnostic"}]}],"version":1}}'
2021-04-16 01:08:16,576 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","diagnostics":[{"range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}},"severity":2,"code":"unused_variables","source":"rustc","message":"unused variable: `closure_parameter`\\n`#[warn(unused_variables)]` on by default","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}}},"message":"if this is intentional, prefix it with an underscore"}],"tags":[1]},{"range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}},"severity":4,"code":"unused_variables","source":"rustc","message":"if this is intentional, prefix it with an underscore","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":14},"end":{"line":5,"character":31}}},"message":"original diagnostic"}]},{"range":{"start":{"line":5,"character":34},"end":{"line":5,"character":46}},"severity":1,"code":"E0597","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0597"},"source":"rustc","message":"`captured_val` does not live long enough\\nborrowed value does not live long enough","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":1}}},"message":"`captured_val` dropped here while still borrowed"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":13},"end":{"line":5,"character":32}}},"message":"value captured here"},{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":33},"end":{"line":5,"character":46}}},"message":"returning this value requires that `captured_val` is borrowed for `\'static`"}]},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":1}},"severity":4,"code":"E0597","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0597"},"source":"rustc","message":"`captured_val` dropped here while still borrowed","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":34},"end":{"line":5,"character":46}}},"message":"original diagnostic"}]},{"range":{"start":{"line":5,"character":13},"end":{"line":5,"character":32}},"severity":4,"code":"E0597","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0597"},"source":"rustc","message":"value captured here","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":34},"end":{"line":5,"character":46}}},"message":"original diagnostic"}]},{"range":{"start":{"line":5,"character":33},"end":{"line":5,"character":46}},"severity":4,"code":"E0597","codeDescription":{"href":"https://doc.rust-lang.org/error-index.html#E0597"},"source":"rustc","message":"returning this value requires that `captured_val` is borrowed for `\'static`","relatedInformation":[{"location":{"uri":"file:///home/bstaletic/work/test/r/src/main.rs","range":{"start":{"line":5,"character":34},"end":{"line":5,"character":46}}},"message":"original diagnostic"}]}],"version":1}}'
```

**Comment by theli-ua** [comment] 2021-04-16 22:09
Same behaviour in VSCode, no diags on provided repro unless I force save.

**Comment by matklad** [comment] 2021-04-27 11:42
Failed to repro "no diagnostics on startap". Successfully reproduced "no diagnostics after open/close/open". The following bit of code is responsible for that:

https://github.com/rust-analyzer/rust-analyzer/blob/6cd669e8809d9e19b2169d04b99f33258848b814/crates/rust-analyzer/src/main_loop.rs#L638-L648

**Comment by Veykril** [comment] 2021-12-14 12:22
The linked source has been change some time ago due to other problems which also addresses the mentioned issue here I think, closing in that case.

**Closed by Veykril** 2021-12-14 12:22 UTC
Labels: E-unknown, S-actionable
