### ISSUE TITLE
Macros duplicate

### ISSUE THREAD

**Issue by Zenthae** [rust-analyzer/rust-analyzer#7081] opened 2020-12-29 17:35 UTC
vscode `1.52.1`
rust-analyzer `every version`
i get duplicate of macros in the completion panel, it's not the case for all of them but a big part.
i tried while disabling all extension and still got the same issue.

![zEYkPlPtZJ](https://user-images.githubusercontent.com/32647899/103303120-7ef1cd80-4a05-11eb-84e0-b3a52c3afb6b.gif)
![lEGZRqq0Fo](https://user-images.githubusercontent.com/32647899/103303130-81542780-4a05-11eb-9a83-b3e5b00b1fe9.gif)

**Comment by AdnoC** [comment] 2020-12-31 19:08
Looking into this. What I've found so far is that `completions::unqualified_path::complete_unqualified_path` is adding macros twice. This is due to `hir_def::resolver::Resolver::process_all_names` passing the name to the closure twice.

Thats as far as I've been able to go. Will try to fix, but if I can't and this is still open in a week at least there will be a starting place for someone else.

**Comment by AdnoC** [comment] 2020-12-31 20:17
After more investigation: The `concat` definition is present in both the legacy macros scope and the prelude scope.

**Comment by Zenthae** [comment] 2020-12-31 21:23
i don't know if the problem is linked but something else is broken, when telling vscode to fill missing match arms it's messing up things, first it's displaying the error twice, second it's adding some weird pattern,
![3G3SdsycDS](https://user-images.githubusercontent.com/32647899/103426042-d1beb700-4bb6-11eb-8ec4-09ac3095c859.gif)

**Comment by lnicola** [comment] 2020-12-31 21:35
@Zenthae that's already fixed in nightly, if you also update the Code extension.

**Comment by Zenthae** [comment] 2020-12-31 21:38
it mean i must use rust nightly to fix this ?, and there is no update for the extension since 3 day ago

**Comment by lnicola** [comment] 2020-12-31 21:40
No, this nightly: https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly. Or you can wait until the Monday release.

**Comment by Zenthae** [comment] 2020-12-31 21:44
thanks, it indeed fixed this issue, by the way there is still a duplicate of `option.rs(blabla): not covered`

**Comment by AdnoC** [comment] 2020-12-31 21:58
I'd take a look at the duplicate Option diagnostic, but I can't reproduce. I use vim rather than vscode though.

**Closed** 2021-01-14 10:12 UTC
Labels: A-completion, S-actionable
