### ISSUE TITLE
Suggestions directly after `self.` in macro args aren't useful

### ISSUE THREAD

**Issue by danielzfranklin** [rust-analyzer/rust-analyzer#8869] opened 2021-05-18 13:07 UTC
Given this project

```rust
pub struct Foo {
    member: bool,
}

impl Foo {
    fn frob(&self) {
        format!("{}", /* HERE */);
    }
}

fn main() {}
```

If I type `self.` in place of `/* HERE */` I see this

![Screenshot from 2021-05-18 14-00-25](https://user-images.githubusercontent.com/10361846/118656093-18b5ed80-b7e2-11eb-9f92-7a500a2ce2d4.png)

(scrolling down only shows similar suggestions such as `unsafe` and `use`.)

If I then type `m` I see the member suggested

![Screenshot from 2021-05-18 14-00-54](https://user-images.githubusercontent.com/10361846/118656241-413de780-b7e2-11eb-81ff-4ebae834a962.png)

Expected behavior:

The same thing is suggested for a macro argument as for a function generic over any T

**Comment by Veykril** [comment] 2021-05-18 13:19
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8158

**Closed by Veykril** 2021-05-18 13:19 UTC
