### ISSUE TITLE
Better Renaming for Trait Members

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#4649] opened 2020-05-28 22:15 UTC
Hello! This is a **suggestion, not a bug report**

Currently, the RA doesn't have complete support for trait renaming. Specifically, if I rename a trait method (within the trait itself), we will only rename instances where a trait object is used (I believe), but will instantly run into trouble, as our own implementation of that trait will not have their methods renamed.

I believe that our own implementations should also get renamed -- additionally, I think if I rename a method which is from an implementation of a trait, and I own the trait, we should also rename that method on the trait. That may be harder to implement.

Thank you all for all your hard work!

**Comment by lnicola** [comment] 2020-05-29 04:40
Sounds like a duplicate of #4201 if I'm not missing something.

**Closed by lnicola** 2020-05-29 04:40 UTC
