### ISSUE TITLE
[f9d20b674 2021-07-06 nvim-lsp] proc macro server crashed

### ISSUE THREAD

**Issue by Hakukano** [rust-analyzer/rust-analyzer#9511] opened 2021-07-06 15:08 UTC
## Versions
* rustc: 1.55.0-nightly (406d4a9cc 2021-06-21)
* rust-analyzer: f9d20b674 2021-07-06 dev
* nvim: v0.5.0-dev+1428-g997a9c879
* serde: 1.0.126

## Minimal Code
```
#[derive(Deserialize)]
pub struct Query {
    id: u64,
}
```

## lsp.lua
I am using the default settings given by [nvim-lsp](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rust_analyzer).

## lsp.log
```
[ ERROR ] 2021-07-06T10:49:15-0400 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "rust-analyzer" "stderr"        
'[ERROR proc_macro_api::process] proc macro server crashed, server process state: Ok(Some(ExitStatus(ExitStatus(139)))), server request error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }\n'
```

**Comment by flodiebold** [comment] 2021-07-06 15:31
Duplicate of #8925.

**Closed by flodiebold** 2021-07-06 15:31 UTC
