### ISSUE TITLE
calling macro with pattern `pat1 | pat2` fails with `leftover tokens`

### ISSUE THREAD

**Issue by y21** [rust-analyzer/rust-analyzer#11488] opened 2022-02-17 08:57 UTC
If a macro with a pattern argument is called with something like `1 | 2` as pattern, RA thinks this is invalid.

```rs
macro_rules! test {
    ($x:pat) => {};
}

fn main() {
    test!(1 | 2);
}
```

![image](https://user-images.githubusercontent.com/30553356/154438514-a572357a-154a-424f-ba11-342d87fa6976.png)

**rust-analyzer version**: 02904e99a 2022-02-14 stable

**rustc version**: rustc 1.60.0-nightly (75d9a0ae2 2022-02-16)

**Comment by Veykril** [comment] 2022-02-17 09:42
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/11368

**Closed by Veykril** 2022-02-17 09:42 UTC
Labels: A-macro, S-actionable, C-bug
