### ISSUE TITLE
Wrong type deduction

### ISSUE THREAD

**Issue by almindor** [rust-analyzer/rust-analyzer#5444] opened 2020-07-20 04:06 UTC
The following code causes Rust Analyzer to "deduce" the type of `*obj` to be a form of `Iterator` instead of the `Object` type and shows the error `Expected 1 argument, found 0` on line 35 by the `.position()` method call. Hovering over the error in the editor (VSCode) is pointing to `core::iter::traits::iterator::Iterator`.

The code compiles fine `legion = "0.2.4"` is required as a dependency.

```rust
use legion::prelude::*;

#[derive(Clone, Default, Copy, Debug, PartialEq)]
struct Position {
    x: f32,
    y: f32,
}

#[derive(Clone, Default, Copy, Debug, PartialEq)]
struct Object {
    pos: Position,
}

impl Object {
    pub fn position(&self) -> Position {
        self.pos
    }
}

fn main() {
    // Create a world to store our entities
    let universe = Universe::new();
    let mut world = universe.create_world();

    // Create entities with `Position` and `Velocity` data
    world.insert((), std::iter::once((Object::default(),)));

    // Create a query which finds all `Position` and `Velocity` components
    let query = <Read<Object>>::query();

    // Iterate through all entities that match the query in the world
    for obj in query.iter(&mut world) {
        use std::ops::Deref;

        let pos = obj.deref().position(); // RA error here
        println!("P: {:?}", pos);
    }
}
```

**Comment by bjorn3** [comment] 2020-07-20 06:55
This uses an `use` inside a function. This is not yet supported: https://github.com/rust-analyzer/rust-analyzer/issues/1165

**Comment by flodiebold** [comment] 2020-07-20 09:23
Yeah, duplicate of #1165 + #5419.

**Closed by flodiebold** 2020-07-20 09:23 UTC
Labels: A-ty

**Comment by almindor** [comment] 2020-07-20 15:38
Nothing to do with `use` see newly edited example.
