### ISSUE TITLE
Implement Missing Members command creates garbage for traits with attribute macros

### ISSUE THREAD

**Issue by Alexandcoats** [rust-analyzer/rust-analyzer#9539] opened 2021-07-09 12:58 UTC
When the `Rust-analyzer > Experimental: Proc Attr Macros` `Expand attribute macros` setting is enabled, using the `Implement Missing Members` command for a trait decorated with the `async_trait` macro generates unusable code.

```rust
struct TestStruct;

#[async_trait]
trait Test {
    type Associated;

    async fn test_fn(&mut self, data: &Option<u32>) -> Result<(), String>;
}

// This is the generated code
impl Test for TestStruct {
    typeAssociated;

    fntest_fn< 'life0, 'life1, 'async_trait>(& 'life0mutself,data: & 'life1Option<u32>)-> core::pin::Pin<Box<dyncore::future::Future<Output=Result<(),String> > + core::marker::Send+ 'async_trait> >where'life0: 'async_trait, 'life1: 'async_trait,Self: 'async_trait {
        todo!()
    }
}
```

**Comment by flodiebold** [comment] 2021-07-09 15:17
Duplicate of #6588

**Closed by flodiebold** 2021-07-09 15:17 UTC
