### ISSUE TITLE
Missing spaces when using "Implement missing members" operation on impl block

### ISSUE THREAD

**Issue by fasterthanlime** [rust-analyzer/rust-analyzer#4879] opened 2020-06-14 17:12 UTC
With rust-analyzer version 2020-06-08 (d696776)

Input code:

```rust
use serde::de::{self};

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("custom error: {0}")]
    Custom(String),
}

impl de::Error for Error {
}
```

In vscode, place the cursor on `impl`, Ctrl+comma, choose "Implement missing members", and the inserted code it this:

```rust
    fncustom<T>(msg:T)->SelfwhereT:std::fmt::Display {
        todo!()
    }
```

Looks like it's missing a few spaces :)

**Comment by bjorn3** [comment] 2020-06-15 08:34
Duplicate of #4665

**Closed by bjorn3** 2020-06-15 08:34 UTC

**Comment by fasterthanlime** [comment] 2020-06-15 08:55
Ah, thanks! I had found #4665 before, wasn't sure it was related.
