### ISSUE TITLE
[Regression] type-mismatch on expanded macro

### ISSUE THREAD

**Issue by BlackDex** [rust-analyzer/rust-analyzer#11816] opened 2022-03-25 13:03 UTC
**rust-analyzer version**:
**Broken since:**
 - v0.3.987 - rust-analyzer version: c2ea37892 2022-03-23 nightly

**Working in:**
 - v0.3.986 - rust-analyzer version: 754d8687f 2022-03-22 nightly (Except it contains #11781)

**rustc version**: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**relevant settings**: All default except for features which have `sqlite,postgresql,mysql` configured.

**codebase**: https://github.com/dani-garcia/vaultwarden (Branch: main)

Getting the following errors:
**utils.rs:**
`expected Pin<Box<dyn Future<Output = ()> + Send, Global>>, found Pin<Box<impl Future<Output = ()>, Global>>`

**admin.rs:**
`expected Pin<Box<dyn Future<Output = Outcome<Referer, (Status, ()), ()>> + Send, Global>>, found Pin<Box<impl Future<Output = Outcome<Referer, (Status, ()), ()>>, Global>>`

**Original code (admin.rs#L89):**
```rust
struct Referer(Option<String>);
#[rocket::async_trait]
impl<'r> FromRequest<'r> for Referer {
    type Error = ();

    async fn from_request(request: &'r Request<'_>) -> request::Outcome<Self, Self::Error> {
        Outcome::Success(Referer(request.headers().get_one("Referer").map(str::to_string)))
    }
}
```

**Looking at the expanded code it does seem to be in there:**
```rust
::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = request::Outcome<Self, Self::Error>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
```

Maybe linked to: https://github.com/rust-lang/rust/issues/95267 ?

**Comment by Veykril** [comment] 2022-03-25 13:18
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/11815

**Closed by Veykril** 2022-03-25 13:18 UTC

**Comment by BlackDex** [comment] 2022-03-25 13:28
Sorry for the noise.

**Comment by Veykril** [comment] 2022-03-25 13:37
No worries
