### ISSUE TITLE
Newest rust analyzer crashes

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [rust-analyzer/rust-analyzer#6986] opened 2020-12-21 17:26 UTC
![image](https://user-images.githubusercontent.com/33642056/102804365-4a37a380-437f-11eb-9170-3c57ed2eefcc.png)

**Comment by lnicola** [comment] 2020-12-21 17:28
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6979.

**Closed by lnicola** 2020-12-21 17:28 UTC
