### ISSUE TITLE
Inline type hints do not play well with inline variable fix

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3008] opened 2020-02-04 07:08 UTC
```
commit 918547dbe9a2907401102eba491ac25cebe1404d
Merge: b090ee5a6 a3e5663ae
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Mon Feb 3 22:51:17 2020 +0000

    Merge #2911
```

Suppose we have a code snippet like this:

![image](https://user-images.githubusercontent.com/3784017/73721366-a0dfc300-4756-11ea-8ede-2d0d84b7c70c.png)

We would like to inline the `pointer_type` variable, so we apply `inline variable` fix:

![image](https://user-images.githubusercontent.com/3784017/73721494-fa47f200-4756-11ea-882d-b3239f5a8815.png)

Suddenly, the whole code looks like a mess:
![image](https://user-images.githubusercontent.com/3784017/73721579-2a8f9080-4757-11ea-99c9-3b6d26534844.png)

Please note that `undo` command does _not_ restore the view. However, actual edit buffer seems to be unaffected, so this is probably a rendering issue. If I switch to another tab and go back, the code is redrawn correctly.

**Comment by 0x7CFE** [comment] 2020-02-06 06:55
It seems that this issue is not tied to particular edit being applied. For example, "flip comma" fix breaks the code in the same manner.

**Comment by Veetaha** [comment] 2020-02-16 17:55
@0x7CFE, thank you for the report! #3173 should've fixed the issue.
cc @matklad

**Comment by 0x7CFE** [comment] 2020-02-17 12:55
@Veetaha, seem to be working now. Awesome, thanks! :heart:

**Comment by 0x7CFE** [comment] 2020-02-28 12:37
@Veetaha, I've just found another bug that seems to be related.

Suppose, we added some function to an existing file:
![image](https://user-images.githubusercontent.com/3784017/75549023-4427ad80-5a61-11ea-9167-3b2e8403b38f.png)

Note the inlay type hint on line 7. If we'd then decide to revert the whole chunk using the revert icon
![image](https://user-images.githubusercontent.com/3784017/75548904-e6936100-5a60-11ea-9d35-6b1835720d96.png)

then we may end up with a situation like this: 
![image](https://user-images.githubusercontent.com/3784017/75549096-6e796b00-5a61-11ea-8732-47a320da08f4.png)

If that is a different bug, I will file another report. Revision 3e25b17cfd0bd9bbd741ca6cf16ab39089910a74.

**Comment by Veetaha** [comment] 2020-02-28 13:34
@0x7CFE, thanks for the report, I don't think there is a big need for another issue, I'll look into this today!
Just to be cut the dumb case, would you mind running `Rust Analyzer: Show RA Version` command to make sure that the commit hash indeed is https://github.com/rust-analyzer/rust-analyzer/commit/3e25b17cfd0bd9bbd741ca6cf16ab39089910a74

**Comment by 0x7CFE** [comment] 2020-02-28 14:16
![image](https://user-images.githubusercontent.com/3784017/75555813-8d7ef980-5a6f-11ea-9a48-578afb987aeb.png)

**Comment by Veetaha** [comment] 2020-02-28 19:26
I know what's the problem. The issue is that the preview that you open is considered a separate text editor, but it points to the same document and this conflicts with our current implementation where we rely on the invariant that one rust source code file can be opened maximum in one text editor.
Thank you for the pointer, I'll try to fix this
![bug_report](https://user-images.githubusercontent.com/36276403/75580769-00d53b00-5a71-11ea-8e4b-01aa124fcd74.gif)

**Comment by Veetaha** [comment] 2020-02-28 19:36
I also think that vscode has a memory leak here. Once you close that vsc preview, it is not removed from the array of visible text editors, it is left hanging there and you can get out of memory if you open and close it millions of times... I'll report this bug to vscode guys...

**Comment by 0x7CFE** [comment] 2020-02-29 07:31
I reopen the issue to keep tracking

**Closed** 2020-03-07 12:50 UTC
