### ISSUE TITLE
AllFeatures not working in workspace

### ISSUE THREAD

**Issue by LucioFranco** [rust-analyzer/rust-analyzer#3897] opened 2020-04-08 19:08 UTC
I have tried 216 and 217 to compile the https://github.com/tower-rs/tower workspace with the all-features command but nothing seems to work even if I set things manually. This same version seems to work in code bases that contain a mixed workspace and crate in the root `Cargo.toml` but seems to fail in tower where we have the root crate external of the root `Cargo.toml`.

**Comment by JoshMcguigan** [comment] 2020-04-08 22:32
Hi @LucioFranco, can you share the version of rust-analyzer you are using (`rust-analyzer --version`) as well as what specifically you are seeing as an issue? I've cloned the repo and at least basic navigation through the tower project seems to be working for me.

**Comment by LucioFranco** [comment] 2020-04-08 22:36
I tried the 04-06 version but my issue was with things that are feature flagged like `tower/src/util/service_fn.rs`, I couldn't get compiler errors to come through. It may be my fault and I can retry tomorrow :)

**Comment by JoshMcguigan** [comment] 2020-04-09 01:56
So I'm not too familiar with this part of the code base, but I did some testing and it seems the all features boolean setting doesn't do it, but `"rust-analyzer.checkOnSave.extraArgs": ["--all-features"]` works for me. Note if you aren't on a recent nightly the setting might be named slightly differently, as the setting names changed recently.

**Comment by matklad** [comment] 2020-04-09 08:04
>So I'm not too familiar with this part of the code base, but I did some testing and it seems the all features boolean setting doesn't do

I think I know the problem. We call cargo for two different purposes, for `cargo metadata` and for `cargo check`. The `--all-features` boolean flag only affects the former. We should have a better UX here somehow.

**Comment by matklad** [comment] 2020-04-09 08:08
Marking it as hard, as, although the impl shouldn't be *that* hard (just trace the flow of `CargoConfig` and `FlycheckConfig` structs), the user-visible feature-flags design seems like a hard-problem. Some constraits:

* I think users should be able to independencly fully override both check and metadata commands
* setting common features (like --all-features or --all-targets) should not require overriding the whole command
* (the hardest bit) it would be resonable to somehow share the features by default
* (hard bit) ideally, we should avoid duplicating cargo's CLI in our config structure, and capitalize on user's existing knowlege of cargo fields. Like, ideally we should have code-completion for `--all-features` in the `extraArgs` field, instead of a separate toogle, or even magit-style interafece. Which we obviously can't express in the LSP at all.

**Comment by LucioFranco** [comment] 2020-04-13 20:56
@JoshMcguigan sweet! that extra args command does help!

**Comment by jhpratt** [comment] 2020-04-27 19:20
@matklad I'm going to go out on a limb and say this is the same reason the `rust-analyzer.cargo.features` doesn't appear to do anything?

**Comment by matklad** [comment] 2020-04-29 10:22
@jhpratt that depens on what do you expect it to do. It certainly affects `cfg` resolution within rust-analyzer, and the set of crates we process.

**Comment by jhpratt** [comment] 2020-04-30 02:45
@matklad Doesn't seem to work for me then. For time-rs/time, activating the `serde` and `rand` features doesn't do anything noticeable.

I should probably file another issue for this? I can provide any details that may be necessary to reproduce things.

**Comment by matklad** [comment] 2020-04-30 10:57
@jhpratt yes do. Though, for serde I suspect the answer is "we can't handle serde yet" (though I am not sure about this, @edwin0cheng, what's the status of serde support with respect to proc-macro). 

For `rand`, I don't think there should be any observable differences? The impls are for distributions, not for types in `rand`, so there shoudln't be any new completions or something like that.

**Comment by edwin0cheng** [comment] 2020-04-30 11:12
For `serde-derive`, We expanded `serde` custom derive macro properly. However, in the expanded code, they use `try!` which we can't parse it correctly in our parser (`try` is a keyword in 2018 edition).

**Comment by matklad** [comment] 2020-04-30 12:19
@edwin0cheng arg, try is annoying, I've submitted https://github.com/rust-analyzer/rust-analyzer/pull/4221 as hopefully a good-enough work-around in practice.

**Comment by jhpratt** [comment] 2020-04-30 21:04
Hmm…even removing the `serde` feature doesn't do it for me. It's not a big deal, since I don't touch the serde or rand code frequently, but it's something worth noting.

Is this something you're able to reproduce, at least? Aside from switching to use `clippy` instead of `check`, I'm pretty much using the default settings for rust-analyzer.

**Comment by Walther** [comment] 2020-07-08 02:53
Thank you for the great project! ❤

Adding a comment / anecdote from user experience perspective. I was working on separating some things in a project under optional features. When working on that, my editor stopped showing tooltips _and even errors_ related to things that were behind a feature gate.

This is fairly confusing; the editor continues to syntax highlight but suddenly you don't have information on correctness. This could also have poor discoverability: only reason I found this issue was because I knew rust-analyzer is work-in-progress (no judgement meant!) and suspected maybe there could be a bug here, related to the `--features`.

Luckily, enabling the setting `  "rust-analyzer.cargo.allFeatures": true` brought the tooltips and errors back. I'm personally wondering could this become a default?

(Arguably, a similar confusion can exist even when running `cargo check` manually - if some of your modules are behind a feature gate, `cargo` won't check those unless you specify `cargo check --features`. I'd say that also is fairly confusing, and might warrant discussion elsewhere 💭)

**Comment by lnicola** [comment] 2020-07-08 06:34
@Walther 

`rust-analyzer.checkOnSave.allFeatures` was disabled in https://github.com/rust-analyzer/rust-analyzer/pull/4711 because a lot of people were working on projects with incompatible features (e.g. game engine backends) or that had a `nightly` feature. See also the discussion in https://github.com/rust-analyzer/rust-analyzer/pull/4704.

`rust-analyzer.cargo.allFeatures` was disabled in the same PR to keep things consistent, although it's less bad to have it always enabled.

**Comment by lnicola** [comment] 2021-01-27 17:12
We now have:

```
  // Activate all available features.
  "rust-analyzer.cargo.allFeatures": false,

  // Check with all features (will be passed as `--all-features`). Defaults to `rust-analyzer.cargo.allFeatures`.
  "rust-analyzer.checkOnSave.allFeatures": null
```

@LucioFranco, @jhpratt would you mind testing if these work for you?

**Comment by jhpratt** [comment] 2021-01-27 18:53
I'm fairly certain I've been using the flag on-and-off for quite a while now, just off the top of my head.

**Comment by lnicola** [comment] 2021-01-27 18:54
Let's close this and hope for the best, then :-).

**Closed by lnicola** 2021-01-27 18:54 UTC
Labels: E-hard, S-unactionable

**Comment by LucioFranco** [comment] 2021-01-28 21:57
I have not run into this issue in a while! So I think what ever was fixed like a few months ago works now! Thanks for the help!
