### ISSUE TITLE
Enum variant rename should rename all usages

### ISSUE THREAD

**Issue by montekki** [rust-analyzer/rust-analyzer#4237] opened 2020-05-01 08:38 UTC
```rust
mod foo {
    pub enum Bar {
        Baz<|>,
    }
}

fn func(f: foo::Bar) {
    match f {
        foo::Bar::Baz => {}
    }
}

```

renaming to `Foo` currently gives

```rust
mod foo {
    pub enum Bar {
        Foo,
    }
}

fn func(f: foo::Bar) {
    match f {
        foo::Bar::Baz => {}
    }
}
```
while the usage of `foo::Bar::Baz` remains unchanged.

**Comment by matklad** [comment] 2020-05-01 20:24
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/ra_ide_db/src/search.rs#L178

**Comment by bnjjj** [comment] 2020-05-02 20:09
I will try to resolve this one in the next days :)

**Comment by bnjjj** [comment] 2020-05-03 11:26
Ok after investing it seems than it comes from the `search_scope` which is not good because it's limited to the current file. For example I can't reproduce this bug when I declare the mod and the enum in the same file, even if the enum is in a different module. Then here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide_db/src/search.rs#L126 we are looking to find a good search scope. But as the visibility of an `EnumVariant` is always None because it's different than for Struct field. So even if the Enum is public the visibility in search scope is `None`. And when I try to force this visibility to Public it's not enough because the `reverse_dependencies` method try to find deps but find nothing for this enum variant. I think the fix should be to detect if we have a enum variant and if we are in this case we looks for the parent node which are the `Enum` and then try to find search scope with this `Enum` instead of with Enum variant data.  What do you think @matklad ?

**Comment by matklad** [comment] 2020-05-04 08:21
Yeah, I belive this is dupe of https://github.com/rust-analyzer/rust-analyzer/issues/4188#issuecomment-620584791

**Closed** 2020-05-07 16:38 UTC
Labels: E-has-instructions, E-unknown
