### ISSUE TITLE
Type inference failure under eta conversion

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4981] opened 2020-06-22 07:46 UTC
Non-minimized example from RA:

```rust
let _x = comment.syntax().next_token().and_then(|x| ast::Whitespace::cast(x));
// _x is Option<Whitespace>
let _x = comment.syntax().next_token().and_then(ast::Whitespace::cast);
// _x is Option<{unknown}>
```

Might be a duplicate of an existing issue. Possibly related to `Self` used in the return type of a trait method.

**Comment by lnicola** [comment] 2020-06-22 07:54
CC #4281.

**Comment by flodiebold** [comment] 2020-06-22 08:11
Yeah, it's a duplicate of that.

**Closed by flodiebold** 2020-06-22 08:11 UTC
Labels: A-ty
