### ISSUE TITLE
std::thread::sleep doesn't show in autocomplete during typing (needs press alt+. for autoimport)

### ISSUE THREAD

**Issue by asv7c2** [rust-analyzer/rust-analyzer#11290] opened 2022-01-15 08:48 UTC
**rust-analyzer version**: 844c152fd 2022-01-15 nightly

**rustc version**: 1.58.0 (02072b482 2022-01-11)

**VSCode version**: 1.63.2

Just type sleep and std::thread::sleep doesn't show in autocomplete.

**Comment by Veykril** [comment] 2022-01-15 09:09
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10112

Basically the problem is that we currently limit the number of generated imports when typing for performance reasons and sleep is unfortunately getting kicked out by that due to the sheer amount of simd imports from std.

**Closed by Veykril** 2022-01-15 09:09 UTC
