### ISSUE TITLE
record struct defined in function is invisible to type inference

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#5462] opened 2020-07-20 18:41 UTC
```Rust
fn main() {
    struct My {
        field: i32
    }

    let v = [My { field: 0 }];
}
```

![image](https://user-images.githubusercontent.com/1521976/87973640-1f43dd80-cac9-11ea-80b7-c6cf6d1fe456.png)

If we move the definition of `My` above main, or make `My` a tuple or unit struct, type inference works.

`rust-analyzer version: 2020-07-20 (c9c518e)`

**Comment by lnicola** [comment] 2020-07-20 18:43
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1559.

**Closed by lnicola** 2020-07-20 18:43 UTC
