### ISSUE TITLE
"Unresolved macro `html!`"

### ISSUE THREAD

**Issue by teymour-aldridge** [rust-analyzer/rust-analyzer#7221] opened 2021-01-09 18:05 UTC
- Cargo.toml
```
[package]
name = "something"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew="0.17.3"
```

* main.rs
```
use yew::prelude::*;
fn something() -> Html {
  html! {<p>{"Hello world"}</p>}
}
fn main() {}
```

Which results in an error saying "unresolved import"

<img width="497" alt="Screenshot 2021-01-09 at 18 05 19" src="https://user-images.githubusercontent.com/42674621/104105342-3e1b7380-52a5-11eb-8248-f0f921c30784.png">

**Comment by bjorn3** [comment] 2021-01-09 18:08
You need to enable proc-macro support using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by harmic** [comment] 2021-01-14 00:11
I am getting the same error but for the [futures_util::select](https://docs.rs/futures-util/0.3.10/futures_util/macro.select.html) macro.

![image](https://user-images.githubusercontent.com/8588043/104526278-1a19b280-5656-11eb-8846-9c3c62795b71.png)

I tried enabling proc-macro support, but the error persists.

rust-analyzer 60c501f

Note: I am using VS Code Remote, and the VM I am working towards is Centos 7. As a result I have to install rust-analyzer manually. I used the [instructions in the manual](https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary), checking out the the '2021-01-11' tag.

**Comment by edwin0cheng** [comment] 2021-01-14 00:42
@harmic it is different problem, `futures_util::select` used `proc_macro_hack` which is an attr proc macro which is not yet implemented in RA. (see #6835)

**Comment by harmic** [comment] 2021-01-14 01:29
Thanks @edwin0cheng, you are correct.

**Comment by lnicola** [comment] 2021-01-17 06:13
@teymour-aldridge is it working with the settings above?

**Comment by teymour-aldridge** [comment] 2021-01-22 09:33
Sorry for taking a while to get back.
For some reason the problem persists even with procedural macro support enabled.
<img width="1030" alt="Screenshot 2021-01-22 at 09 32 16" src="https://user-images.githubusercontent.com/42674621/105473200-b9612a00-5c94-11eb-883d-a32bdd282fc0.png">

**Comment by edwin0cheng** [comment] 2021-01-22 09:39
Have you enabled *both* settings: 
```
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by teymour-aldridge** [comment] 2021-01-22 09:41
Yup
<img width="975" alt="Screenshot 2021-01-22 at 09 41 47" src="https://user-images.githubusercontent.com/42674621/105474296-0db8d980-5c96-11eb-8ac2-761bea589793.png">

**Comment by flodiebold** [comment] 2021-01-22 09:48
The `html` macro actually also uses `proc_macro_hack`, as far as I can see.

**Comment by teymour-aldridge** [comment] 2021-01-22 09:52
`proc_macro_hack` was removed with Rust 1.45.0

See this commit: https://github.com/yewstack/yew/commit/a8f16673321c1922196889af1170591cea835749

**Comment by flodiebold** [comment] 2021-01-22 09:57
I just did `cargo add yew` and got a version with proc macro hack, so I'd assume this isn't released yet.

**Comment by edwin0cheng** [comment] 2021-01-22 09:57
> proc_macro_hack was removed with Rust 1.45.0
> See this commit: yewstack/yew@a8f1667

But you are using `yew="0.17.3"`, it used proc-macro-hack

https://github.com/yewstack/yew/blob/f7b52bfc562b1964a409ca4fa804f98b0bdfc384/yew-macro/src/lib.rs#L106-L110

**Comment by teymour-aldridge** [comment] 2021-01-22 09:59
Sorry, you're right – this hasn't been released yet.

**Comment by teymour-aldridge** [comment] 2021-01-22 10:08
I think this is a regression because it used to work.

**Comment by lnicola** [comment] 2021-01-22 10:12
It didn't work before, but the diagnostic is new. You can disable it with `"rust-analyzer.diagnostics.disabled": ["unresolved-proc-macro"]`.

**Comment by teymour-aldridge** [comment] 2021-01-22 10:13
Ah – cheers!

**Comment by lnicola** [comment] 2021-01-22 10:17
Let's close this as a dupe of #6029.

**Closed by lnicola** 2021-01-22 10:17 UTC
Labels: A-macro, S-unactionable
