### ISSUE TITLE
`Self::Variant` patterns are not resolved correctly

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4789] opened 2020-06-07 22:58 UTC
```rust
enum Enum {
    Variant,
}

impl Enum {
    fn f(self) {
        match self {
            Enum::Variant => {}
        }
    }

    fn g(self) {
        match self {
            Self::Variant => {}
        }
    }
}
```

In `f`, everything works correctly. In `g`, `Variant` is not recognized correctly and does not show up in completions after `Self::`.

(I'm kind of assuming that this is a known bug, but I couldn't find an issue about it, so I'm opening this to track it)

**Comment by flodiebold** [comment] 2020-06-08 08:21
They should be resolved, I think I fixed that recently; but it's possible that `Self::` completion and syntax highlighting need additional fixes. I think there was another issue about this, which I can't find right now.

**Comment by BGluth** [comment] 2020-06-09 21:56
Is this a good issue for someone new to this project to take a look at? If it is, I don't mind trying to do a fix.

**Comment by matklad** [comment] 2020-06-09 22:06
@BGluth should be! It needs some digging around (as the root cause is not completely known), but the actual fix shouldn't be too hard. I'd start with writing a small goto definition or syntax highlighitng test, and then tracing where we loose the knowledge.

**Comment by BGluth** [comment] 2020-06-09 23:05
Sweet! I'll give it a go.

**Comment by BGluth** [comment] 2020-06-13 18:55
I'm just taking a bit of time getting familiar with the project, so I've just spent the last several days placing traces everywhere. :)

```rust
enum Foo {
    Bar,
}

impl Foo {
    fn baz(self) {
        match self {
            Self::Bar<|> => {}
        }
    }
}
```

From what I can tell (and this could be wrong), the problem seems to be based around `Self` resolving to the `impl` block whenever it's used within one. The problem is that we actually need to be looking in the enum definition to find the enum variant. So stuff like `Self` alone is fine because it resolves to the entire impl block and `Self::baz` (if `baz` is a func in the impl block) is also good.

I've also spent a descent amount of time looking at how similar things involving `Self` get resolved. Like just `Self` by itself:

```rust
struct Foo;
impl Foo {
    pub fn new() -> Self {
        Self<|> {}
    }
}
```

ends up getting resolved in [`resolve_hir_path`](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir/src/source_analyzer.rs#L402-L448), while `Self::baz`:


```rust
enum Foo {
    Bar,
}

impl Foo {
    fn baz(self) {
        match self {
            Self::Bar => {}
        }
    }

    fn after_baz() {
        Self::baz<|>;
    }
}
```

doesn't resort to calling `resolve_hir_path` and is resolved a bit earlier [here](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir/src/source_analyzer.rs#L214-L219).

I also noticed something somewhat odd when it tries to resolve `Self::Bar` (from the first block above). When [`analyze2`](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir/src/semantics.rs#L311-L331) calls [`find_container`](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir/src/semantics/source_to_def.rs#L157-L205), it ends up returning this (`ChildContainer`):
```
DefWithBodyId(
    FunctionId(
        FunctionId(
            0,
        ),
    ),
)
```

before it tries (and fails) to resolve it in `resolve_hir_path`. Should this be resolving to a `FunctionId`? What function is it resolving to?

At this point, I'm not really sure where (or how) to do a fix. I think it's probably possible to resolve this without going into `resolve_hir_path`, but I'm no sure where. If it ends up being best to resolve it in `resolve_hir_path`, we could do a check to see if we're dealing with an enum variant whenever we match against `Scope::ImplDefScope` and the path has more than 1 segments. This feels somewhat hacky though, and I suspect there's a better place.

I'll keep poking at this. If anyone has any insights let me know.

**Comment by flodiebold** [comment] 2020-06-13 22:14
You're right that `resolve_hir_path` can't resolve this. Things like `Self::Variant` are only fully resolved during type inference, in [`resolve_variant`](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir_ty/src/infer.rs#L419) or in [`resolve_assoc_item`](https://github.com/rust-analyzer/rust-analyzer/blob/246c66a7f7fd3f85d7d6e47a36f17bafb0ccb08a/crates/ra_hir_ty/src/infer/path.rs#L107), depending on whether it's a record literal / pattern, a tuple struct pattern, or a value. So to get these resolutions, we need to check the inference result similar to what's happening at the beginning of `resolve_path` already. The resolution should be in `assoc_resolutions` resp. `variant_resolutions`.

**Comment by BGluth** [comment] 2020-06-14 19:11
You're right. It's resolving the enum variant in `variant_resolutions`.

I feel like `resolve_path` is a pretty natural place to check `variant_resolutions` (since we first perform a bunch of checks if `name_ref` is a function/field/etc. before resorting to `resolve_path`). We could just have `resolve_path` check `variant_resolutions` as well.

**Closed** 2020-06-22 14:45 UTC
Labels: A-completion
