### ISSUE TITLE
hover goto issues

### ISSUE THREAD

**Issue by ikreva** [rust-analyzer/rust-analyzer#5691] opened 2020-08-08 17:59 UTC
My English is weak. so I upload a picture
![i1](https://user-images.githubusercontent.com/69108874/89716931-cf7b7680-d9e3-11ea-8e3f-ae396531be32.gif)

**Comment by bjorn3** [comment] 2020-08-08 18:07
Duplicate of #5546

**Closed by bjorn3** 2020-08-08 18:07 UTC
