### ISSUE TITLE
Request codeLens/resolve failed

### ISSUE THREAD

**Issue by suhr** [rust-analyzer/rust-analyzer#1893] opened 2019-09-21 16:59 UTC
RA extension spams the following error:

```
[Error - 19:58:42] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/main.js:154:15)
	at closeHandler (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.constructor.writable.on (/home/suhr/.vscode/extensions/matklad.ra-lsp-0.0.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

**Comment by kiljacken** [comment] 2020-01-09 18:43
@suhr Are you still having this issue on master?

**Comment by suhr** [comment] 2020-01-09 22:07
Yes. Specifically, I have this issue when I add a dir with a rust project into non-rust workspace and then navigate a rust file.

There are also extra messages:

> rust-analyzer failed to load workspace: can't find Cargo.toml at /home/suhr/Projects/tox/tox-ksy
> workspace loaded, 149 rust packages

**Comment by kiljacken** [comment] 2020-01-10 07:55
In that case, this is a duplicate of #1798, would you mind closing this one and checking that one out? Thanks. :)

**Closed** 2020-01-10 07:58 UTC
