### ISSUE TITLE
.to_owned shows unknown type

### ISSUE THREAD

**Issue by kanekv** [rust-analyzer/rust-analyzer#1961] opened 2019-10-06 02:56 UTC
`let s = "test".to_owned()` - shows `unknown` type.

**Comment by ice1000** [comment] 2019-10-08 13:19
Maybe it's relevant to `trait`'s `Self` type:

```rust
pub trait ToOwned {
    type Owned: Borrow<Self>;
    fn to_owned(&self) -> Self::Owned;
}
```

**Comment by matklad** [comment] 2019-10-08 13:49
A good first step here would be to write a reproduciable test-case, using our own versions of `Borrow` and `ToOwned`, to `ty/tests.rs`

**Comment by flodiebold** [comment] 2019-10-08 14:03
I _think_ the problem lies with actually normalizing the projection in Chalk, because of https://github.com/rust-lang/chalk/issues/234. There are sadly still lots of cases where associated types don't work because of this. I might be wrong though, and the problem might be somewhere before that.

**Comment by flodiebold** [comment] 2020-04-17 15:50
This should be fixed in master.

**Closed by flodiebold** 2020-04-17 15:50 UTC
Labels: A-ty, E-unknown
