### ISSUE TITLE
RA populates all available RAM (huge memory leak)

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4698] opened 2020-06-01 22:57 UTC
[Reported in zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Memory.20usage)

Reproduction: open [this file](https://github.com/cloudflare/lol-html/blob/344063e669731f8151a4b506d85f3fa4cc0fbd8a/src/rewriter/mod.rs#L533) in vscode and you should see how the number of trees increases and your RAM with swap are used more and more
![image](https://user-images.githubusercontent.com/36276403/83462660-6ec83e80-a474-11ea-8af2-ad01ff2fc72c.png)

**Comment by JasmineCA** [comment] 2020-06-10 09:05
Same issue with plugin rust-ide in Atom, using rust-analyzer

**Comment by gagbo** [comment] 2020-09-27 14:26
I could _not_ repro with Emacs, using brotzeit/rustic@781a2914d (might tweak init options) + joaotavora/eglot@61b71ea769 (actual client) on bcdedbb3d5

**Comment by coder543** [comment] 2020-12-15 19:54
Just going to mention that I’ve seen Rust Analyzer using 40GB of memory on a Mac that only has 32GB of memory... this has happened several times in the few days since I installed RA, so I’ve now given up on RA and will be returning to RLS. I hope to try RA again someday.

**Comment by bjorn3** [comment] 2020-12-15 19:56
What project is that on?

**Comment by coder543** [comment] 2020-12-15 20:26
It’s a proprietary project, sorry. I wish I could give more detail. Between this issue and #4923, it seems there are already multiple test cases to reproduce a memory leak of some kind, and indications that something is happening beyond just my machine.

I’m unsure whether I was experiencing one of these, or a different one, but something weird is going on. RLS only uses about 1GB of memory, for comparison, although RLS isn’t working perfectly for me either.

**Comment by bjorn3** [comment] 2020-12-15 20:28
What does the "rust analyzer: report memory (clears database)" command show?

**Comment by lnicola** [comment] 2020-12-19 08:42
I tested on https://github.com/cloudflare/lol-html, the LSP process is using about 552 MB RAM and the proc macro server crashes.

<details>

```
Per-query memory usage:
   173mb ItemTreeQuery
    29mb CrateDefMapQueryQuery
    23mb FileTextQuery (purge)
    20mb MacroArgTextQuery
    17mb ImplDataQuery
    14mb ParseQuery
     9mb MacroDefQuery
     8mb GenericParamsQuery
     7mb AttrsQuery
     6mb InternEagerExpansionQuery
     4mb ParseMacroExpansionQuery (purge)
     4mb GenericParamsQuery (purge)
     4mb ImplSelfTyQuery (purge)
     4mb MacroExpandQuery (purge)
     4mb ImplTraitQuery (purge)
  3872kb FunctionDataQuery
  3872kb InternMacroQuery (purge)
  3845kb AstIdMapQuery (purge)
  3762kb AstIdMapQuery
  3666kb ItemTreeQuery (purge)
  3662kb InternFunctionQuery
  3564kb ImplTraitQuery
  3502kb ImplDataQuery (purge)
  3392kb InternFunctionQuery (purge)
  3335kb MacroArgTextQuery (purge)
  3189kb InternMacroQuery
  2635kb AttrsQuery (purge)
  2208kb CrateGraphQuery (purge)
  2033kb ImplDataQuery (deps)
  1810kb ImplTraitQuery (deps)
  1698kb ImplSelfTyQuery (deps)
  1649kb TraitImplsInCrateQuery
  1619kb InternImplQuery
  1568kb InternImplQuery (purge)
  1389kb TraitImplsInDepsQuery
  1321kb ParseMacroExpansionQuery (deps)
  1138kb GenericParamsQuery (deps)
  1078kb MacroExpandQuery (deps)
   900kb MacroArgTextQuery (deps)
   838kb ItemTreeQuery (deps)
   799kb SourceRootQuery (purge)
   785kb ParseMacroExpansionQuery
   657kb TyQuery (purge)
   623kb GenericDefaultsQuery (purge)
   619kb CrateDefMapQueryQuery (deps)
   591kb AstIdMapQuery (deps)
   516kb InternTypeAliasQuery
   500kb TraitSolveQuery (purge)
   492kb ImplDatumQuery
   435kb AttrsQuery (deps)
   424kb InternTypeAliasQuery (purge)
   398kb MacroExpandQuery
   388kb InternEagerExpansionQuery (purge)
   387kb InternConstQuery
   372kb BodyQuery
   360kb InternConstQuery (purge)
   353kb InferQueryQuery
   308kb EnumDataQuery
   307kb TraitImplsInCrateQuery (deps)
   258kb ParseQuery (purge)
   254kb FileSourceRootQuery (purge)
   250kb GenericPredicatesQuery (purge)
   206kb GenericDefaultsQuery
   203kb InternStructQuery
   199kb ImplDatumQuery (purge)
   196kb InternStructQuery (purge)
   172kb TyQuery
   160kb GenericDefaultsQuery (deps)
   143kb ImplSelfTyQuery
   138kb MacroDefQuery (purge)
   136kb TypeAliasDataQuery
   135kb BodyWithSourceMapQuery
   104kb FunctionDataQuery (purge)
   100kb TyQuery (deps)
    95kb TraitSolveQuery (deps)
    88kb GenericPredicatesQuery
    87kb ImplDatumQuery (deps)
    72kb CrateLangItemsQuery (deps)
    67kb InferQueryQuery (deps)
    66kb InherentImplsInCrateQuery (deps)
    66kb GenericPredicatesQuery (deps)
    62kb CrateDefMapQueryQuery (purge)
    61kb StructDataQuery
    49kb ParseQuery (deps)
    49kb InternEnumQuery (purge)
    49kb InternTraitQuery (purge)
    44kb ExprScopesQuery
    44kb TypeAliasDataQuery (purge)
    42kb InternTraitQuery
    41kb InternEnumQuery
    34kb AssociatedTyValueQuery
    33kb InherentImplsInCrateQuery
    28kb GenericPredicatesForParamQuery (purge)
    28kb FunctionDataQuery (deps)
    26kb FnDefDatumQuery
    25kb InternStaticQuery
    24kb CallableItemSignatureQuery
    24kb InternStaticQuery (purge)
    24kb GenericPredicatesForParamQuery
    23kb ValueTyQuery (purge)
    23kb MacroDefQuery (deps)
    22kb TraitImplsInCrateQuery (purge)
    22kb EnumDataQuery (purge)
    21kb TraitSolveQuery
    21kb FieldTypesQuery
    18kb TraitDataQuery
    14kb CallableItemSignatureQuery (purge)
    14kb AssociatedTyValueQuery (purge)
    14kb StaticDataQuery
    11kb TypeAliasDataQuery (deps)
     9kb StructDatumQuery
     9kb ValueTyQuery
     9kb TraitDatumQuery
     9kb GenericPredicatesForParamQuery (deps)
     9kb LineIndexQuery
     7kb TraitDataQuery (purge)
     7kb StructDatumQuery (purge)
     7kb CallableItemSignatureQuery (deps)
     7kb StaticDataQuery (purge)
     7kb BodyWithSourceMapQuery (purge)
     7kb BodyQuery (purge)
     6kb InferQueryQuery (purge)
     6kb ExprScopesQuery (purge)
     6kb ValueTyQuery (deps)
     6kb BodyWithSourceMapQuery (deps)
     6kb EnumDataQuery (deps)
     5kb TraitDatumQuery (purge)
     5kb FnDefDatumQuery (purge)
     5kb AssociatedTyValueQuery (deps)
     5kb LangItemQuery (purge)
     5kb TraitDataQuery (deps)
     4kb CrateLangItemsQuery
     4kb AssociatedTyDataQuery
   4080b StructDataQuery (purge)
   3520b InternCallableDefQuery (purge)
   3088b SourceRootCratesQuery (deps)
   2656b FieldTypesQuery (purge)
   2192b FnDefDatumQuery (deps)
   2080b StaticDataQuery (deps)
   1984b TraitDatumQuery (deps)
   1952b AssociatedTyDataQuery (purge)
   1904b FieldTypesQuery (deps)
   1744b StructDatumQuery (deps)
   1664b InternTypeParamIdQuery (purge)
   1568b LibraryRootsQuery (purge)
   1424b InternClosureQuery (purge)
   1264b BodyQuery (deps)
   1216b ExprScopesQuery (deps)
   1200b StructDataQuery (deps)
   1104b AssociatedTyDataQuery (deps)
    992b TraitImplsInDepsQuery (deps)
    864b LangItemQuery (deps)
    800b InherentImplsInCrateQuery (purge)
    688b ConstDataQuery
    528b ConstDataQuery (purge)
    528b CrateLangItemsQuery (purge)
    528b LineIndexQuery (purge)
    304b LocalRootsQuery (purge)
    272b SourceRootCratesQuery (purge)
    272b TraitImplsInDepsQuery (purge)
    240b InternUnionQuery (purge)
    160b ConstDataQuery (deps)
    160b InternUnionQuery
    128b SourceRootCratesQuery
      0b CrateGraphQuery
      0b CrateGraphQuery (deps)
      0b FileTextQuery
      0b FileTextQuery (deps)
      0b FileSourceRootQuery
      0b FileSourceRootQuery (deps)
      0b SourceRootQuery
      0b SourceRootQuery (deps)
      0b UnionDataQuery
      0b UnionDataQuery (deps)
      0b UnionDataQuery (purge)
      0b LangItemQuery
      0b ImportMapQuery
      0b ImportMapQuery (deps)
      0b ImportMapQuery (purge)
      0b AssociatedTyDataQuery
      0b AssociatedTyDataQuery (deps)
      0b AssociatedTyDataQuery (purge)
      0b ReturnTypeImplTraitsQuery
      0b ReturnTypeImplTraitsQuery (deps)
      0b ReturnTypeImplTraitsQuery (purge)
      0b InternCallableDefQuery
      0b InternCallableDefQuery (deps)
      0b InternTypeParamIdQuery
      0b InternTypeParamIdQuery (deps)
      0b InternImplTraitIdQuery
      0b InternImplTraitIdQuery (deps)
      0b InternImplTraitIdQuery (purge)
      0b InternClosureQuery
      0b InternClosureQuery (deps)
      0b FileSymbolsQuery
      0b FileSymbolsQuery (deps)
      0b FileSymbolsQuery (purge)
      0b LibrarySymbolsQuery
      0b LibrarySymbolsQuery (deps)
      0b LibrarySymbolsQuery (purge)
      0b LocalRootsQuery
      0b LocalRootsQuery (deps)
      0b LibraryRootsQuery
      0b LibraryRootsQuery (deps)
      0b LineIndexQuery (deps)
      0b InternMacroQuery (deps)
      0b InternEagerExpansionQuery (deps)
      0b InternFunctionQuery (deps)
      0b InternStructQuery (deps)
      0b InternUnionQuery (deps)
      0b InternEnumQuery (deps)
      0b InternConstQuery (deps)
      0b InternStaticQuery (deps)
      0b InternTraitQuery (deps)
      0b InternTypeAliasQuery (deps)
      0b InternImplQuery (deps)
      0b InternTypeParamIdQuery
      0b InternTypeParamIdQuery (deps)
      0b InternTypeParamIdQuery (purge)
```
</details>

**Comment by lnicola** [comment] 2020-12-19 09:00
Actually, it gets stuck in `chalk` with `rust-analyzer analysis-stats --memory-usage --with-deps -o de::next .`

@flodiebold should we try to print the crate name there? I have no idea what `de::next` is.

**Comment by lnicola** [comment] 2021-12-14 16:42
Surprisingly, this seems to work now, but on `HEAD` and on `e0758b948ad6920883803c739df4412b3141d54a` (a commit from November 2020):

```text
# e0758b948ad6920883803c739df4412b3141d54a
Database loaded:     557.43ms, 243minstr, 72mb (metadata 395.33ms, 13minstr, 286kb; build 94.74ms, 74minstr, 72kb)
  crates: 5, mods: 107, decls: 998, fns: 692
Item Collection:     4.86s, 50ginstr, 249mb
  exprs: 34651, ??ty: 124 (0%), ?ty: 89 (0%), !ty: 2                                                             
Inference:           3.91s, 32ginstr, 137mb
Total:               8.77s, 83ginstr, 387mb

# 2772fd0e9feb4a820bfc0cb460e9441b0d0c205d
Database loaded:     572.80ms, 233minstr, 85mb (metadata 406.26ms, 17minstr, 383kb; build 85.44ms, 10minstr, 36kb)
  crates: 5, mods: 107, decls: 1008, fns: 700
Item Collection:     5.98s, 59ginstr, 289mb
  exprs: 34940, ??ty: 124 (0%), ?ty: 89 (0%), !ty: 2                                                             
Inference:           4.05s, 35ginstr, 157mb
Total:               10.03s, 95ginstr, 447mb
```

`rust-analyzer analysis-stats --memory-usage --with-deps -o de::next .` works too. So let's close this for now.

**Closed by lnicola** 2021-12-14 16:42 UTC
Labels: S-unactionable, A-perf
