### ISSUE TITLE
Failed to deserialize InitializeParams: missing field `prepareSupportDefaultBehavior`

### ISSUE THREAD

**Issue by runiq** [rust-analyzer/rust-analyzer#6997] opened 2020-12-22 11:03 UTC
With 5e2935e ([release 2020-12-21](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-12-21)) and neovim's builtin LSP client.

**Comment by lnicola** [comment] 2020-12-22 11:47
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6979.

You should stay on the older release until neovim's LSP client gets updated or we work around this.

**Closed by lnicola** 2020-12-22 11:47 UTC

**Comment by runiq** [comment] 2020-12-22 14:02
Ah, thanks! The different field name threw me off.
