### ISSUE TITLE
Autocomplate showing duplicate functions/macros

### ISSUE THREAD

**Issue by muniategui** [rust-analyzer/rust-analyzer#8301] opened 2021-04-02 21:22 UTC
First of all say that i'm totally new to rust (just installed Rust, VSC and was doing the hello world example and reading the rust docs) so it might be due to my lack of knowladge that I missconfigured something.

![imagen](https://user-images.githubusercontent.com/14365006/113455183-4b5e7f00-940a-11eb-87a0-d832571f5120.png)

As it can be seen in the imagen when autocomplate appaars or is forced with ctrl+space, functions are duplicated (println! can be seen 2 times one under another and even a 3rd time at the bottom but wihtout ()). The same can be seen with print!.

I don't know if its because they are macros, something misconfigured or bug.

I'm uisng rust-analyzer and i have also installed rust (rls) but its disabled so it shouldn't be a problem. 

If i disable analyzer and enable rls it displays only 1 time the functions.

**Comment by lnicola** [comment] 2021-04-03 05:16
This sounds a lot like https://github.com/rust-analyzer/rust-analyzer/issues/7081. It might have regressed at one point.

**Comment by SomeoneToIgnore** [comment] 2021-04-03 07:20
Hm, for me a sample hello world project works as intended (I've checked this both on the latest stable and nightly releases on RA):

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2690773/113471432-dec49e00-9464-11eb-8420-2a8e524add0e.png">

Do you use the latest RA version? You can run "Show RA version" command to get that.
Unfortunately, the versions displayed there are somewhat messed up, so don't be surprised to see something odd in the output.

If you use the latest version and it is still the case, could you provide more details to reproduce the issue? The complete project will help.

**Comment by muniategui** [comment] 2021-04-03 10:32
![imagen](https://user-images.githubusercontent.com/14365006/113475706-877bf900-9477-11eb-8993-04bdc6e61644.png)
The vscode version is 1.55
Plugin downloaded from the integrated vscode plugin shop, version of the plugin v0.2.538


My plugin list (enabled) is: C/C++ 1.2.2, CodeLLDB 1.6.1, GitLens 11.3.0, Remote -WSL 0.56.6, rust-analyzer 0.2.538

The only extrange thing i did during the installation of rust was setting the CARGO_HOME to another disk location and RUST_UP to other location as well: D:\rustinstllation\.cargo and D:\rustinstllation\.rustup

The PATH looks like D:\rustinstallation\.cargo\bin

If i remember properly i did not change any settings of the plugin itself.

**Comment by SomeoneToIgnore** [comment] 2021-04-03 10:57
Yes, that's the latest version you have.

Thanks for more details about the macro invocation, I can confirm that happens to me too.
Interestingly, there seems to be difference with how we treat stdlib items (including macros) and custom macros in completion:

<img width="736" alt="no_macro" src="https://user-images.githubusercontent.com/2690773/113476350-b6986780-9483-11eb-8236-3a710fe30b12.png">

stdlib items get duplicated here even after a custom macro is used:

<img width="725" alt="std_macro" src="https://user-images.githubusercontent.com/2690773/113476367-cc0d9180-9483-11eb-9fcf-bc634caf853b.png">

but custom macro is not duplicated at all, same works for other crates:

<img width="820" alt="same_macro" src="https://user-images.githubusercontent.com/2690773/113476361-c44ded00-9483-11eb-8237-0ddc3b94d9b3.png">

**Comment by Veykril** [comment] 2021-04-03 11:01
I believe this got fixed with https://github.com/rust-analyzer/rust-analyzer/pull/8297? I can't reproduce it on today's nightly

**Comment by SomeoneToIgnore** [comment] 2021-04-03 11:16
Hm, this means that nightly have issues with self updating for me 😞 

Just checked the locally built from source (that emitted this weird version too btw: `rust-analyzer version: 2021-03-29-113-g8289b9621`, the date is odd and the has does not exist) and it works indeed.

So this will be automatically fixed with the tomorrow stable release and should be in the nightly release already.

**Closed by SomeoneToIgnore** 2021-04-03 11:16 UTC
Labels: A-completion, S-actionable

**Comment by SomeoneToIgnore** [comment] 2021-04-03 11:18
@muniategui we close the issues if it's fixed in `master` so that's what I'll do now, please feel free to reopen if the issue persists after tomorrow's release.

**Comment by Veykril** [comment] 2021-04-03 11:20
Ye the rust-analyzer version command still doesn't seem to work properly, https://github.com/rust-analyzer/rust-analyzer/issues/8239

**Comment by muniategui** [comment] 2021-04-03 13:37
However I was on the stable update channel (extension settings>Rust-analyzer>Updates:Channel) not on the nightly one despites version tellingme i was in nighlty. If i'm not mistaken i should pick nightly in order to check if the bug is corrected tomorrow right?
