### ISSUE TITLE
Incorrect current directory set between Run Test and Debug test in VSCode

### ISSUE THREAD

**Issue by selvavm** [rust-analyzer/rust-analyzer#8251] opened 2021-03-30 04:00 UTC
I have a workspace setup and inside it I have different libraries. Something like below,
```
 my_app
    |_ lib_a
          |_ src
          |_ tests
                |_ testcase.rs
    |_ lib_b
          |_ src
          |_ tests
  ```

When I click on the Run Test in my `testcase.rs`, the current working directory is considered as `C:\user\selva\my_app\lib_a` and when I click on Debug in my `testcase.rs`, the current working directory is considered as `C:\user\selva\my_app\`. 

Is there a possibility to fix this?

**Comment by flodiebold** [comment] 2021-03-30 08:32
Duplicate of #6422.

**Closed by flodiebold** 2021-03-30 08:32 UTC
