### ISSUE TITLE
Autocomplete fails on Vec after custom allocators support was added

### ISSUE THREAD

**Issue by andylizi** [rust-analyzer/rust-analyzer#6668] opened 2020-11-29 08:17 UTC
### Description
Autocomplete fails to show any result under specific circumstances:

![demo](https://user-images.githubusercontent.com/12008103/100536707-525b6200-325d-11eb-8171-b9c9771ce83c.gif)

This problem only seems to happen on rust nightly. It consistently disappears after `rustup default stable` and restarting the RA server. The [`bytes` crate](https://github.com/tokio-rs/bytes) doesn't seems to have anything cfg'ed on nightly. Functions in other traits (e.g. `std::io::Read`) seems to work fine.

### Environment
* RA: `2020-11-23` (cadf0e9)
* VSCode: `1.51.1`
* Rust: `1.50.0-nightly (1c389ffef 2020-11-24)`

### Minimal reproducible example
1. Switch to `nightly` toolchain
2. Add `bytes = "0.6"` to dependencies
3. Add `use bytes::{BytesMut, buf::Buf};`
4. Write `let buf = BytesMut::new();`
5. Try to complete on `buf.<|>`

~~(Verified to be reproducible in Windows Sandbox using a fresh install of Rust, VSCode, and RA without changing any settings)~~

~~This is *maybe* related to #6612, but I'm not sure because a) it doesn't complete no matter what I do or how long I wait; and b) it somehow only appears in *Rust* nightly.~~

Edit: see https://github.com/rust-analyzer/rust-analyzer/issues/6668#issuecomment-735501557

**Comment by bjorn3** [comment] 2020-11-29 08:34
If you write `let a = Vec::new()` does it show the type of `a` in an inlay hint like it does for `buf` in the gif when you use nightly rustc?

**Comment by andylizi** [comment] 2020-11-29 08:36
Yeah, it shows `Vec<{unknown}>` in inlay hint and autocompletion on `a` works fine.

**Comment by andylizi** [comment] 2020-11-29 08:43
Actually no, autocomplete fails to give any result on `a`, just like `buf`.

But other types, like `str` `String` `File` `Rc` and even `VecDeque` works. I'm not sure what's the pattern here...

**Comment by SomeoneToIgnore** [comment] 2020-11-29 23:22
The symptoms are familiar to https://github.com/rust-analyzer/rust-analyzer/issues/6672 

> The last working version for me is `nightly-2020-10-26-x86_64-unknown-linux-gnu - rustc 1.49.0-nightly (4760b8fb8 2020-10-25)`

so maybe nightly after all.

**Comment by andylizi** [comment] 2020-11-30 01:53
For me the latest working version is `da3846948 2020-11-21` and it fails on `a0d664bae 2020-11-22`, so it shouldn't be the same issue? The only major [difference between them](https://github.com/rust-lang/rust/compare/da3846948...a0d664bae) appears to be rust-lang/rust#78461.

Oh! I see. `BytesMut` derefs to `Vec<u8>`, so that's why most of the other types don't have the same issue.
```rust
use std::ops::Deref;

fn main() {
    let test = Test { vec: vec![] };
    test.<|>        // Fails to complete
}

struct Test {
    vec: Vec<u8>
}

impl Deref for Test {
    type Target = Vec<u8>;

    fn deref(&self) -> &Self::Target {
        &self.vec
    }
}
```

**Comment by jonas-schievink** [comment] 2020-11-30 12:20
```rust
fn f() {
    let mut v = Vec::new();
    v.<|>
}
```

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir_ty/src/lib.rs:1007:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:62
   3: <hir_ty::Ty as hir_ty::TypeWalk>::walk_mut_binders
   4: <hir_ty::Ty as hir_ty::TypeWalk>::walk_mut_binders
   5: hir_ty::method_resolution::is_valid_candidate
   6: hir_ty::method_resolution::iterate_inherent_methods
   7: hir_ty::method_resolution::iterate_method_candidates_by_receiver
   8: hir_ty::method_resolution::iterate_method_candidates_impl
   9: hir::code_model::Type::iterate_method_candidates
  10: completion::completions::dot::complete_dot
  11: completion::completions
  12: std::panicking::try
  13: ide::Analysis::completions
  14: rust_analyzer::handlers::handle_completion
  15: <F as threadpool::FnBox>::call_box
```

Looks like we aren't accounting for default type parameters somewhere.

**Comment by jonas-schievink** [comment] 2020-11-30 12:55
Self-contained repro (minus `Deref`):

```rust
use core::ops;

pub struct Vec<T, A = ()> {
}

impl<T> Vec<T> {
    pub const fn new() -> Self {
    }
}

impl<T, A> Vec<T, A> {
    pub fn push(&mut self, value: T) {
    }
}

impl<T, A> ops::Deref for Vec<T, A> {
    type Target = [T];

    fn deref(&self) -> &[T] {
    }
}
```

and then again

```rust
fn f() {
    let mut v = Vec::new();
    v.<|>
}
```

**Comment by flodiebold** [comment] 2020-11-30 13:36
Hmm. I fear that might be our slightly hacky [Deref handling](https://github.com/rust-analyzer/rust-analyzer/blob/13025ae2a121be8320a6ec40ad3519df5640c927/crates/hir_ty/src/autoderef.rs#L98-L129)...

**Comment by flodiebold** [comment] 2020-12-04 16:41
@jonas-schievink I can't reproduce the problem with your repro, with current RA and rustc 1.48 :thinking:

**Comment by jonas-schievink** [comment] 2020-12-04 16:44
You need nightly Rust, custom allocator support for `Vec` is still nightly-only

**Comment by flodiebold** [comment] 2020-12-04 16:46
But why would your self-contained repro depend on custom allocator support in `Vec`?

**Comment by flodiebold** [comment] 2020-12-04 16:49
You're right though, it reproduces with nightly :thinking:

**Comment by flodiebold** [comment] 2020-12-04 17:14
```rust

struct Slice<T> {}
struct Box<T, A> {}
struct Vec<T, A> {}

impl<T> Slice<T> {
    pub fn into_vec<A>(self: Box<Self, A>) -> Vec<T, A> { }
}

fn main() {
    let foo: Slice<u32>;
    foo.
}
```
reproduces the problem on stable. I'm pretty sure the problem is the second type parameter on the `Box`.

**Comment by flodiebold** [comment] 2020-12-04 19:00
Should be fixed on master now.

**Closed by flodiebold** 2020-12-04 19:00 UTC
Labels: A-ty, S-actionable
