### ISSUE TITLE
Feature request:  Format output from expended macro.

### ISSUE THREAD

**Issue by nurmohammed840** [rust-analyzer/rust-analyzer#11748] opened 2022-03-18 09:09 UTC
I heavily use  [Expand Macro Recursively](https://rust-analyzer.github.io/manual.html#expand-macro-recursively) feature, to debug macro.

Most of the time the output is gibberish, Code is not well formatted. Is there any way to get formatted output ?

Although Rust has build in  formatting tool ([rust-fmt](https://github.com/rust-lang/rustfmt))

**Comment by flodiebold** [comment] 2022-03-18 09:34
Duplicate of #10548.

**Closed by flodiebold** 2022-03-18 09:34 UTC
Labels: S-actionable, C-feature, A-ide
