### ISSUE TITLE
Type inference works with slicing only 4/5 times

### ISSUE THREAD

**Issue by smmalis37** [rust-analyzer/rust-analyzer#5055] opened 2020-06-25 11:36 UTC
![image](https://user-images.githubusercontent.com/4054472/85712713-722e9e80-b69d-11ea-838b-f8d5c34f4834.png)

These are the first lines in the function. The signature of decode_ascii85 is `fn decode_ascii85(input: &[u8]) -> impl Iterator<Item = u8> + '_`

**Comment by lnicola** [comment] 2020-06-25 11:38
It might infer some of them based on usage. Does anything change if you comment out the rest of the code?

**Comment by smmalis37** [comment] 2020-06-25 11:39
Good catch, they all become &{unknown} in that case. Shouldn't the type be known without later information though?

**Comment by flodiebold** [comment] 2020-06-25 11:39
Yeah, it's a duplicate of #2534.

**Closed by flodiebold** 2020-06-25 11:39 UTC
