### ISSUE TITLE
Rust analyzer stop working when the vim/vscode idles for a long time

### ISSUE THREAD

**Issue by YYTVicky** [rust-analyzer/rust-analyzer#4324] opened 2020-05-05 16:45 UTC
Hi,

Currently, I use RA in a large project. Due to a long time waiting for the initialization (include the definition jumping), I prefer not to close vim/vscode. But recently I found that the RA will stop working if vim/vscode idle for a long time. 

The RA is nightly build version.

**Comment by bjorn3** [comment] 2020-05-05 17:09
Is the rust-analyzer process still running?

**Comment by w93163red** [comment] 2020-05-05 17:59
I don’t think so, since the status line shows nothing.

bjorn3 <notifications@github.com>于2020年5月5日 周二13:10写道：

**Comment by bjorn3** [comment] 2020-05-05 19:53
Can you try `ps aux | grep rust-analyzer`?

**Comment by w93163red** [comment] 2020-05-08 00:56
> Can you try `ps aux | grep rust-analyzer`?

![image](https://user-images.githubusercontent.com/7308728/81358714-4469a800-90a5-11ea-91f3-ee5d5758a866.png)
I think it related to this setting.

**Comment by matklad** [comment] 2020-07-12 00:32
Haven't seen this myself, not sure how to reproduce, closing as unactionable.

**Closed by matklad** 2020-07-12 00:32 UTC
