### ISSUE TITLE
"Bootstrap Error" rust-analyzer requires glibc >= 2.28 in latest build.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#11558] opened 2022-02-26 03:00 UTC
rust-analyzer no longer will run on Ubuntu 18.04( which bundles [glibc 2.27](https://launchpad.net/ubuntu/+source/glibc/2.27-3ubuntu1)), and other distros which have a glibc older than 2.27.

this issue manifests as a "Bootstrap Error" notably, the extension output will log something along the lines of:

```
ERROR [2/28/2022, 8:46:56 AM]: Bootstrap error [Error: Failed to execute /home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
```

when running the binary, we get the following error: 

```
/home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer)
/home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer)
```

current workarounds are mentioned in this comment: https://github.com/rust-analyzer/rust-analyzer/issues/11558#issuecomment-1054802255

**Comment by bjorn3** [comment] 2022-02-26 06:41
You can use the rust-analyzer from rustup if you need to run it on a system with an older glibc version. The change breaking 18.04 support was probably https://github.com/rust-analyzer/rust-analyzer/pull/10672 which updated the builder from ubuntu 18.04 to 20.04.

**Comment by jhgg** [comment] 2022-02-27 01:33
This is somewhat problematic for us, because our remote development environment for our company is ubuntu 18.04 at current, which means the rust-analyzer extension will suddenly break in a weird way (the error message isn't that clear about lacking glibc, I had to actually go and execute the bundled r-a binary directly.)

I wonder how many people will run into this issue when this change hits the main release.

**Comment by bjorn3** [comment] 2022-02-27 06:19
Musl's memory allocator is slower. It may also affect memory usage (positive or negative).

**Comment by bjorn3** [comment] 2022-02-27 06:20
In addition using musl would make it impossible to load proc macros compiled for glibc. (which is the default)

**Comment by jhgg** [comment] 2022-02-27 08:27
Hmm, is there any viable path forward to restore 18.04 support?

**Comment by bjorn3** [comment] 2022-02-27 08:34
Using the rust-analyzer-preview component from rustup is the easiest way. This one is built to support the exact same glibc versions as rustc.

**Comment by jhgg** [comment] 2022-02-27 08:44
Is that one regularly updated with each week's r-a release?

**Comment by bjorn3** [comment] 2022-02-27 09:03
Yes, it get updated every week: https://github.com/rust-lang/rust/pulls?q=is%3Apr+%3Aup%3A+rust-analyzer+is%3Amerged+-label%3Arollup I agree that it is less user friendly.

**Comment by jhgg** [comment] 2022-02-27 09:36
Would it be possible to just replicate what rustc is doing to compile rust-analyzer here? That way we can maintain same support as the rustup component?

**Comment by iamwwc** [comment] 2022-02-28 07:45
> We could try to roll back our CI to 18.04, but in general we don't have the same infrastructure as rust-lang/rust and we can't offer the same variety of builds. That's why it's available in `rustup`.

How I can use RA from rustup? what should I do

**Comment by iamwwc** [comment] 2022-02-28 07:48
Bootstrap error [Error: Failed to execute /root/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version

```
$ /root/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
> /root/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /root/.vscode-server/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer)
```

**Comment by lnicola** [comment] 2022-02-28 07:50
```bash
$ rustup toolchain install nightly --component rust-analyzer-preview
```

Then set `rust-analyzer.server.path` to `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer`.

**Comment by Matthias247** [comment] 2022-02-28 21:22
> Musl's memory allocator is slower. It may also affect memory usage (positive or negative).

This could be somewhat mitigated by using a custom allocator - e.g. either setting jemalloc or mimalloc via `LD_LIBRARY_PATH` or as a global allocator in Rust.

I definitely recommend to publish by default an extension which works with older glib versions - because far more distributions than just Ubuntu 18 haven't caught up and will run into issues. Whether that's best achieved using an older Ubuntu builder again or by moving to musl and bundling more dependencies is up to the team :)

**Comment by rimutaka** [comment] 2022-02-28 23:19
## Summary of a workaround

* the last working build: 0.2.948
* the first broken build: 0.2.956

### Option 1 - downgrade

1.Open the extension page in VS Code
2. Click on [V] next to Uninstall button
3. Select  0.2.948 and reload

#### Notes
You will be perpetually stuck on that version.

### Option 2 - use pre-prelease via rustup

1. Install _rust-analyzer-preview_ by running `rustup toolchain install nightly --component rust-analyzer-preview`
2. Go to VSCode settings and search for `rust-analyzer.server.path`. You should see something along these lines
![image](https://user-images.githubusercontent.com/5926028/156072582-06172d16-c01a-4b3e-9f3c-add70d623a30.png)
3. Click on `Edit in settings.json` and add `"rust-analyzer.server.path": "~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer"`
5. Reload VSCode

#### Notes
You will have to update the extension manually with `rustup update`
* Even if _rust-analyzer_ is built using _nightly_ you can still use _stable_ as your default channel
* Component availability: https://rust-lang.github.io/rustup-components-history/

**Comment by dpypin** [comment] 2022-03-01 01:30
Workaround Option 1 is not working for me. When I try to downgrade to 0.2.948 I get the following error in VSCode:

"Can't install 'matklad.rust-analyzer' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2)."

**Comment by sunjay** [comment] 2022-03-01 02:49
Getting the same error as @dpypin for Option 1. When I try Option 2, I don't actually see any `rust-analyzer.server.path` option. If I put it in manually in settings.json, vscode just says that it is unused. Does that setting work for when the extension is installed remotely over SSH? I followed the `rustup` step on my remote server, so everything should be installed correctly.

**Comment by sejr** [comment] 2022-03-01 05:08
Is there any way to get one of the previous builds to work with VS Code 1.64.2? This has kinda derailed me in an environment where I can’t use rustup.

**Comment by lnicola** [comment] 2022-03-01 05:22
@sejr you can download one from https://github.com/rust-analyzer/rust-analyzer/releases, `chmod +x` it, then set `rust-analyzer.server.path`.

**Comment by lnicola** [comment] 2022-03-01 05:49
This was probably caused by https://github.com/rust-lang/rust/pull/90846. We're pulling in `statx`, at least:

```
    97: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND statx@GLIBC_2.28 (17)
 66653: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND statx@@GLIBC_2.28
   124: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND [...]@GLIBC_2.29 (21)
```

**Comment by dominikwerder** [comment] 2022-03-01 08:49
Unfortunately it's broken on redhat 8 as well:

```
~ % /home/werder_d/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
/home/werder_d/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/werder_d/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer)
```

**Comment by dominikwerder** [comment] 2022-03-01 09:08
Replacing the rust-analyzer binary which is used by vscode by an older binary and disabling automatic extension updates in vscode solves this for me for the time being.

**Closed** 2022-03-01 18:38 UTC

**Comment by sunjay** [comment] 2022-03-01 18:42
Thanks for reverting the change that was causing this! Any idea when the fix will get released into vscode?

**Comment by bjorn3** [comment] 2022-03-01 18:44
Next monday.

**Comment by jhgg** [comment] 2022-03-01 19:08
Can't we just release a new version now to fix everyone with a broken binary more expeditiously?

**Comment by lnicola** [comment] 2022-03-01 19:25
A new nightly will be out in 6 hours or so.

**Comment by opensas** [comment] 2022-03-05 14:05
> Next monday.

so next monday (2022-03-14) with just reintalling the extension everything should work out of the box on 18.04. right?

**Comment by lnicola** [comment] 2022-03-05 14:07
It should update automatically, so you don't have to reinstall it. But in the meanwhile you can test a pre-release version by clicking on this button:

![image](https://user-images.githubusercontent.com/308347/156886810-fca9422d-337e-4f10-84de-754e7269a21d.png)

(the pre-release versions are generally quite stable)

**Comment by opensas** [comment] 2022-03-05 14:10
I just went to the second option of [this thread](https://github.com/rust-analyzer/rust-analyzer/issues/11558#issuecomment-1054802255) and it seems to be working fine.

**Comment by lnicola** [comment] 2022-03-05 14:11
Yeah, just keep in mind that it won't update automatically and the Code extension and server binary might become mismatched.

**Comment by xflcx1991** [comment] 2022-03-06 13:08
> It should update automatically, so you don't have to reinstall it. But in the meanwhile you can test a pre-release version by clicking on this button:
> 
> ![image](https://user-images.githubusercontent.com/308347/156886810-fca9422d-337e-4f10-84de-754e7269a21d.png)
> 
> (the pre-release versions are generally quite stable)

Done!It seems to working on Ubuntu 18.04 now.But my pre-release version is v0.3.962.

**Comment by lnicola** [comment] 2022-03-06 13:09
Stable versions are 0.2.X, preview versions are 0.3.Y and source builds are 0.4.0.

**Comment by iamwwc** [comment] 2022-03-07 08:06
v0.3.963 not working in debian 9

```
Debian GLIBC 2.24-11+deb9u4

Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

**Comment by lnicola** [comment] 2022-03-07 08:08
The GLIBC version in Debian 9 is too old, you'll have to use `rustup` as described above.

**Comment by jotingen** [comment] 2022-03-09 15:53
For Option 2, note that when searching for rust-analyzer.server.path you need to be in the remote tab of settings.

**Comment by yurymik** [comment] 2022-08-22 23:35
This issue seems to reappear in the most recent release:

```
~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1170-linux-x64/server/rust-analyzer --version
rust-analyzer 0.3.1170-standalone (b6d59f2bb 2022-08-14)

~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer --version
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found

objdump -T ~/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer | grep "GLIBC_2.29"
0000000000000000  w   DF *UND*  0000000000000000  GLIBC_2.29  posix_spawn_file_actions_addchdir_np
```

This is on Debian 10.12 that has GLIBC 2.28:

```
~$ cat /etc/issue
Debian GNU/Linux 10 \n \l

$ cat /etc/debian_version
10.12

$ readlink -f /lib/x86_64-linux-gnu/libc.so.6
/usr/lib/x86_64-linux-gnu/libc-2.28.so
```

**Comment by lnicola** [comment] 2022-08-23 03:08
@yurymik see #13081.

**Comment by ponchofiesta** [comment] 2022-09-10 13:37
glibc 2.28 not supported by latest versions anymore.
Last working version with glibc 2.28 is v0.3.1170

**Comment by zybmajia1** [comment] 2022-09-22 07:13
why the vscode can not select the version ? downward compatibility is correct。 give up the rust instead of C++。terrible rule.

**Comment by lnicola** [comment] 2022-09-22 07:15
Since two weeks ago the binaries are built again on Ubuntu 18.04. VS Code different know anything about GLIBC version requirements.

**Comment by zybmajia1** [comment] 2022-10-13 07:22
> Since two weeks ago the binaries are built again on Ubuntu 18.04. VS Code different know anything about GLIBC version requirements.

If our company use Rust,there are issues:
1.We programe closed type , connect WWW is not allowed. So config enviroment without WWW is impossible.
2.We use linux(run) + windows(vscode & rust-analyzer+Remote - SSH+CodeLLDB) 。 So weekly update is impossible.
Is there offline solution?

**Comment by wellingfine** [comment] 2023-01-31 08:57
Not found "rust-analyzer.server.path" in v0.4.1387
first install by rustup， then mv to vscode's path：
```shell
rustup toolchain install nightly --component rust-analyzer-preview
mv /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1387-linux-x64/server/rust-analyzer
```

**Comment by manmartgarc** [comment] 2023-08-25 16:46
Looks like the issue should be reopened, still having the exact same issue and the current instructions to edit our VSCode settings are no longer up to date with the extensions' configuration schema.

**Comment by lnicola** [comment] 2023-08-25 17:07
@manmartgarc which distro are you on? I remember some Ubuntu version upgraded to a newer GLIBC a while ago.

**Comment by manmartgarc** [comment] 2023-08-25 17:17
> @manmartgarc which distro are you on? I remember some Ubuntu version upgraded to a newer GLIBC a while ago.

Using AL2

**Comment by lnicola** [comment] 2023-08-25 17:27
I suggest building from source for now. The config key is still `rust-analyzer.server.path`.

**Comment by people-can-fly** [comment] 2023-09-28 20:26
It works for me in `AL2`
- First make sure the extension is installed.
- install the nightly version `rustup toolchain install nightly --component rust-analyzer-preview`
- Note on the previous comment mentioned path of the bin could be different. For my case it was under `ASDF`
- add `"rust-analyzer.server.path": "/home/ec2-user/.asdf/installs/rust/1.69.0/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer",` to the remote settings.

**Comment by NoobZang** [comment] 2024-04-21 05:50
`git clone https://github.com/rust-analyzer/rust-analyzer`
then `cargo build --release`
`cp target/release/rust-analyzer ~/.vscode-server/extensions/rust-lang.rust-analyzer-*version-number*-linux-x64/server/rust-analyzer`

**Comment by NEU-Apollo** [comment] 2025-03-22 13:47
https://github.com/rust-lang/rust-analyzer/issues/11558#issuecomment-1054802255

I use CentOS 7, and Option 2 works for me.

First, I install `rust-analyzer` using `rustup`:

```
rustup component add rust-analyzer
```

Then, I can find `rust-analyzer` in the following path:  
`$HOME/.rustup/toolchains/nightly-2023-07-06-x86_64-unknown-linux-gnu/bin/rust-analyzer`.

Next, follow the instructions in Option 2 from the issue link and add the following to your `settings.json` in VSCode (note: `$HOME` needs to be replaced with your own home path):

```
"rust-analyzer.server.path": "$HOME/.rustup/toolchains/nightly-2023-07-06-x86_64-unknown-linux-gnu/bin/rust-analyzer"
```
