### ISSUE TITLE
rust-analyzer doesn't work fully for rust files which not in src folder

### ISSUE THREAD

**Issue by BruceChen2017** [rust-analyzer/rust-analyzer#8009] opened 2021-03-14 08:14 UTC
For example, you open git repo [rustlings](https://github.com/rust-lang/rustlings). Then in the rustings/src directory, rust-analyzer works well. But in rustlings/exercises/some_topic/some_rust_file, rust-analyzer does not work except  that it gives syntax error message  if you have. I also test official rust extension independently, rls works in rustlings/exercises/some_topic/some_rust_file.   

Note: When using rust-analyzer, I have disabled official rust extension.

**Comment by flodiebold** [comment] 2021-03-14 12:54
This is a problem with the rustlings project structure, which does some special things that don't work with IDEs. See https://github.com/rust-lang/rustlings/issues/443. On RA side, this is mostly a duplicate of #6388, which would make most features work in the exercise files.

**Closed by flodiebold** 2021-03-14 12:54 UTC

**Comment by jackos** [comment] 2022-01-09 06:48
A fix specifically for rustlings: https://gist.github.com/jackos/7332fa8ab0b67a87f382fd566696f412

**Comment by flodiebold** [comment] 2022-01-10 22:33
@jackos great! Maybe rustlings could generate this file automatically? :thinking:

**Comment by jackos** [comment] 2022-01-12 05:00
@flodiebold I opened a pull request to do that: https://github.com/rust-lang/rustlings/pull/911

**Comment by jackos** [comment] 2022-01-13 13:15
@flodiebold also I add this crate: https://crates.io/crates/rustlings-fix

Just go into `rustlings` folder and do:

```
cargo install rustlings-fix
rustlings-fix
```

And it'll generate the file
