### ISSUE TITLE
Unable to do any definition lookups inside impl defined inside function

### ISSUE THREAD

**Issue by jgarvin** [rust-analyzer/rust-analyzer#5382] opened 2020-07-14 19:27 UTC
In the main.rs below, you can't lookup anything inside the `test()` definition inside the `impl`. `get`, `self`, `unwrap` etc. all can't be found. rustc has no issue compiling it though.

```
#![allow(dead_code)]

use std::collections::HashMap;

trait Test {
    fn test(&self) -> i32;
}

fn foo() -> () {
    struct Foo {
        h: HashMap<i32, i32>
    }
    impl Test for Foo {
        fn test(&self) -> i32
        {
            return *self.h.get(&3).unwrap();
        }
    }
}

fn main() {
    println!("Hello, world!");
}

```

```
$ ~/opt/bin/rust-analyzer --version
rust-analyzer 5ca7cd9
```

**Comment by lnicola** [comment] 2020-07-14 19:43
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1559.

**Closed by lnicola** 2020-07-14 19:43 UTC
