### ISSUE TITLE
No completion in function-local impl blocks

### ISSUE THREAD

**Issue by bk138** [rust-analyzer/rust-analyzer#7979] opened 2021-03-12 09:20 UTC
Completion of struct members inside an impl block inside a function does not work.

![Bildschirmfoto von 2021-03-12 10-10-01](https://user-images.githubusercontent.com/80450/110918168-184d3200-831b-11eb-858e-e70a3259288e.png)

It also _does not_ work if the struct definition is moved out of main(). Completes fine if both definition and impl block are outside main. This feels kinda related to #4438 and maybe even is a dupe of that one, so feel free to mark as such. Then again, it might have a different cause so reporting that here nonetheless.

Environment: 
* rust-analyzer d54e115
* GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-02-09, modified by Debian
* lsp-mode-20210311.814

**Comment by jonas-schievink** [comment] 2021-03-12 15:40
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7633

**Closed by jonas-schievink** 2021-03-12 15:40 UTC
