### ISSUE TITLE
Registering progress handler for token rustAnalyzer/startup failed.

### ISSUE THREAD

**Issue by segalll** [rust-analyzer/rust-analyzer#8632] opened 2021-04-23 02:47 UTC
I'm on Arch Linux using the oss version of vscode.

When I open a rust project in vscode, I get an error from rust-analyzer.

Error: Progress handler for token rustAnalyzer/Indexing already registered
	at Object.onProgress (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:5384:23)
	at LanguageClient.onProgress (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:13071:45)
	at new ProgressPart (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:11050:41)
	at createHandler (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:14415:34)
	at handleRequest (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:4917:41)
	at processMessageQueue (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:4781:17)
	at Immediate._onImmediate (/home/segal/.vscode-oss/extensions/matklad.rust-analyzer-0.2.563/out/src/main.js:4771:13)
	at processImmediate (internal/timers.js:456:21)

It was working before, but now it suddenly doesn't. I can run cargo check and cargo run with no issues outside of vscode. I've tried uninstalling and reinstalling the rust-analyzer extension, but it still fails. The only other extensions I have are Better TOML and a color theme. I am not using the vscode rust plugin. I know this issue has come up in the past, but it has always been supposedly solved and closed.

**Comment by jonas-schievink** [comment] 2021-04-23 12:46
This should be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8606, can you check with the latest nightly release?

**Comment by lnicola** [comment] 2021-04-23 12:52
I don't think Arch packaged https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-04-20.

**Comment by segalll** [comment] 2021-04-23 21:45
This is using the vscode plugin, which afaik manages its own rust-analyzer instance separate from anything installed on the system (I could be wrong though). Installing the 2021-04-20 release's vscode plugin (v0.2.565) gave me the same issue as before, as did the nightly release's vscode plugin (v0.3.568-nightly)

**Comment by lnicola** [comment] 2021-04-24 05:31
My bad, sorry, the fix isn't included in that release, but nightly should work though.

**Comment by segalll** [comment] 2021-04-24 21:17
Using the nightly version, I booted up my computer and opened vscode, and there was no issue with rust-analyzer. I then closed vscode and opened it again, but then the issue was back.

**Comment by jonas-schievink** [comment] 2021-04-24 21:18
Is this for `rustAnalyzer/Indexing` or `rustAnalyzer/startup`? The title disagrees with the issue description here

**Comment by segalll** [comment] 2021-04-24 22:07
This is for `rustAnalyzer/Indexing`. I open my rust project with vscode, and rust analyzer begins trying to index, and then the issue arises. The issue does not happen if it is my first time opening vscode and indexing my rust project since I last restarted my computer.

**Comment by matklad** [comment] 2021-04-26 18:02
Reproduced locally. The problem seems to be that we run several indexing processes in parallel. Feels like we should put an OpQueue here?

https://github.com/matklad/rust-analyzer/blob/f06e4b8e74bc2cec1fec4075f64b9909356c2bd3/crates/rust-analyzer/src/op_queue.rs#L4-L8

@jonas-schievink would you like to take a look at it? I wonder how to you feel about the `OpQueue` thing -- it's something I've coded up on the spot, not sure if this abstracion really makes sense.

**Comment by jonas-schievink** [comment] 2021-04-28 00:08
I haven't managed to reproduce this so far, but I'm happy to take a look if I manage to reproduce it

**Comment by matklad** [comment] 2021-04-28 08:19
Oh, right, this happens most reliably when you type in Cargo.toml with auto-save enabled

**Comment by alekspickle** [comment] 2021-04-28 10:31
Getting this error right about the time this issue opened. Maybe it is related with newer release somewhere?
Using only `matklad.rust-analyzer` vscode extension.

**Comment by jonas-schievink** [comment] 2021-04-28 12:42
> Oh, right, this happens most reliably when you type in Cargo.toml with auto-save enabled

Hmm, I still can't reproduce by doing that. I'm using r-a built from a recent git commit.

**Comment by Bobo1239** [comment] 2021-04-29 15:13
Did some digging and believe to have found the issue:
During cache priming we still reach [this line](https://github.com/rust-analyzer/rust-analyzer/blob/80bee14e14f67f02746befff77a8a4bbfd3e5849/crates/rust-analyzer/src/main_loop.rs#L421) in the main loop which in turn starts a new cache priming task [here](https://github.com/rust-analyzer/rust-analyzer/blob/80bee14e14f67f02746befff77a8a4bbfd3e5849/crates/rust-analyzer/src/main_loop.rs#L718) while the first one is still running.

Now the question is what is misbehaving here. My first instinct was that [`is_quiescent()`](https://github.com/matklad/rust-analyzer/blob/f06e4b8e74bc2cec1fec4075f64b9909356c2bd3/crates/rust-analyzer/src/reload.rs#L32) shouldn't return true during cache priming and indeed if I (as an experiment) add a new `priming_cache: bool` variable to `GlobalState` and check for that in `is_quiescent()` the error doesn't happen anymore. Don't really know the context of `is_quiescent()` though so this may not really make sense architecturally.

If you can tell me what a proper solution should look like I'd be happy to send a PR with the fix.

**Comment by matklad** [comment] 2021-04-29 15:19
@Bobo1239 the right soln is to add `OpQueue` around priming. It is correct that we consider state quiescent even while cache priming (the ground state is correct, so, if you ask a query, you'll get a correct and consistent result, but you might wait for some time for it to be computed). The issue here is that we schedule more than one priming op concurrently. That dosen't make sense, there should be at most on in flight at any point in time. The `OpQueue` struct ensures this serialization.

**Closed** 2021-05-02 18:41 UTC
Labels: Broken Window, S-actionable
