### ISSUE TITLE
Debug-test runs in a different working directory than run-test

### ISSUE THREAD

**Issue by georgewfraser** [rust-analyzer/rust-analyzer#6661] opened 2020-11-28 16:21 UTC
When I run a test, the test process runs with `std::env::current_dir()` equal to the directory the test file is in.

When I debug a test, the test process runs in the root directory of the project. 

Either is fine, but it would be nice if it were consistent.

**Comment by simonvandel** [comment] 2020-12-26 21:52
AFAICT this is a duplicate of #4705

**Closed** 2021-01-01 14:51 UTC
Labels: S-actionable
