### ISSUE TITLE
could not resolve macro `$crate::format`

### ISSUE THREAD

**Issue by adder46** [rust-analyzer/rust-analyzer#6773] opened 2020-12-09 08:32 UTC
Rust analyzer complains about using `format!` directly [here](https://github.com/adder46/hstr-rs/blob/master/src/app.rs#L45) with the error: 

`could not resolve macro `$crate::format`rust-analyzermacro-error
`
However, the program compiles with no problems.

Referring to `format!` as `std::format!` resolves the issue.

**Comment by lnicola** [comment] 2020-12-09 08:36
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6716.

This is fixed on `master` and available in the nightly builds.

![image](https://user-images.githubusercontent.com/308347/101605071-6dbb2f80-3a0a-11eb-8771-37c8c9995892.png)

**Closed by lnicola** 2020-12-09 08:36 UTC
