### ISSUE TITLE
Completion doesn't use local `use`s.

### ISSUE THREAD

**Issue by red75prime** [rust-analyzer/rust-analyzer#4752] opened 2020-06-05 08:44 UTC
`use`s in code blocks are not taken into account for completion.

```
mod foo {
    pub enum Foo {
        Variant1,
        Variant2,
    }
}

fn main() {
    use foo::Foo;
    // Completion for `Foo::` doesn't suggest anything relevant
}
```

Expected result for completion:
![image](https://user-images.githubusercontent.com/10704684/83855336-5afd3080-a731-11ea-98b9-8b8fb2a8515e.png)

Actual result for completion:
![image](https://user-images.githubusercontent.com/10704684/83855323-5769a980-a731-11ea-8fa0-10e0c40b7030.png)

**Comment by lnicola** [comment] 2020-06-05 08:56
Local imports are not supported, duplicate of #1165.

**Closed by lnicola** 2020-06-05 08:56 UTC
