### ISSUE TITLE
Macro call inside macro parameter is not parsed correctly if used in another macro parameter

### ISSUE THREAD

**Issue by c410-f3r** [rust-analyzer/rust-analyzer#10757] opened 2021-11-12 23:58 UTC
Feel free to close this issue if there is duplication elsewhere.

![Capture d’écran de 2021-11-12 20-53-04](https://user-images.githubusercontent.com/17877264/141596585-b95043a1-c1aa-47fd-8278-3998fad9f855.png)

Does not trigger if `concat!` is removed. Compiles fine using Rustc.

**Comment by jonas-schievink** [comment] 2021-12-10 13:32
Caused by https://github.com/rust-analyzer/rust-analyzer/pull/10623, `concat!` is now passed `("PEEK A BOO")` including parentheses, which it doesn't handle (and neither does rustc's implementation)

**Comment by jonas-schievink** [comment] 2021-12-10 13:32
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10721, actually

**Closed by jonas-schievink** 2021-12-10 13:32 UTC
Labels: A-macro, C-bug
