### ISSUE TITLE
Wrong import error when importing trait created by proc-macro

### ISSUE THREAD

**Issue by SrTobi** [rust-analyzer/rust-analyzer#8219] opened 2021-03-27 20:57 UTC
Version: v0.2.529

Imports are marked red when importing traits created by proc-macro. In this case by the  [extend crate](https://github.com/davidpdrsn/extend). Note that the method that is called on that trait is resolved correctly.

`cargo run` runs fine.

I uploaded a test repo: https://github.com/SrTobi/rust-anlyzer-extend-bug

![image](https://user-images.githubusercontent.com/4148534/112734519-924dff80-8f46-11eb-9e8f-fd99aac5b708.png)

I also tried to play around with settings, but was not able to get it running. Maybe I did something wrong? (`loadOutDirsFromCheck` gets suggested a lot, but when I tried to add it to the settings, vscode told me that it is not an option).
![image](https://user-images.githubusercontent.com/4148534/112734640-4fd8f280-8f47-11eb-83b1-64aa56fbe368.png)

**Comment by flodiebold** [comment] 2021-03-27 23:10
Duplicate of #6029, attribute proc macros aren't supported yet.

**Closed by flodiebold** 2021-03-27 23:10 UTC
