### ISSUE TITLE
Syntax error on `<&str>::SOMETHING`

### ISSUE THREAD

**Issue by zeenix** [rust-analyzer/rust-analyzer#3659] opened 2020-03-19 19:47 UTC
While this is valid code that rustc has no issues with, rust-analyzer thinks it's invalid syntax on line 12: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0307cad4b9afa2ff5fa3197d35429a73

**Comment by matklad** [comment] 2020-03-20 07:23
I don't seem able to reproduce this, what is the error exactly?

![image](https://user-images.githubusercontent.com/1711539/77143614-03c9b700-6a84-11ea-973f-9dc956962fc8.png)

**Comment by zeenix** [comment] 2020-03-20 10:26
Right, sorry i should have tested my sample code before submitting. Seems it's only an issue if i use it as a pattern in `match`:

```rust
    let c = 'x';
    match c {
        <&str>::SIGNATURE_CHAR => {
            println!("{}", <&str>::SIGNATURE_CHAR);
        }
        _ => (),
    }
```

The error is `Syntax Error: expected pattern` on the `&` token.

**Comment by zeenix** [comment] 2020-03-20 10:29
Updated playground code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc20513f8d88420d3a0700885083e2cc

**Comment by zeenix** [comment] 2020-04-28 11:06
ping? would this be a hard one to solve?

**Comment by edwin0cheng** [comment] 2020-04-28 14:26
The relevant code is : 

https://github.com/rust-analyzer/rust-analyzer/blob/a8e032820f14cad3630299a1ae16c62dcf59f358/crates/ra_parser/src/grammar/patterns.rs#L79-L106

**Comment by zeenix** [comment] 2020-06-09 11:23
I know devs have higher priority tasks so this is not a complaint but I was wondering if this could be prioritised with some bribe from me? :) I-e I promise to contribute 30 euros (on top of existing 10 euros/month) on pencollective.com if someone fixes this issue.

**Comment by matklad** [comment] 2020-06-09 11:48
@zeenix would be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/4815 :0)

Thank you for your financial contributions!

**Closed** 2020-06-09 11:53 UTC
Labels: E-has-instructions, E-medium

**Comment by zeenix** [comment] 2020-06-09 11:57
@matklad wow, that was super quick. :) With this instant success of my idea, it might be worth to add a contribution request/link in issues if people want to prioritise their favourite issues. :) Just a suggestion.

Many thanks again!

**Comment by matklad** [comment] 2020-06-09 12:04
Yup, I'll think about this...

I am not 100% on board with idea of issue bounties, because:

* it might be hard to estimate the efforts required to fix the issue (this one was a happy case, where I basically needed to just remove two words).
* I think it's important that overall priorities are determined by the project developers, and not the users, as the developers have more context. 

Basically, i don't want to create mismatched expectations situation

**Comment by zeenix** [comment] 2020-06-09 12:11
Understood and I agree. :)
