### ISSUE TITLE
Code completion doesn't show accessible methods

### ISSUE THREAD

**Issue by 0xd4d** [rust-analyzer/rust-analyzer#3059] opened 2020-02-08 16:57 UTC
Version: 3e1d97790be166f8735607c552a94a28ab9b09b8

`S3::m1` and `S3::m2` aren't shown in the completion list in `f2()`

```rust
pub struct S3;
impl S3 {
	pub fn m1(&self) {}
	pub fn m2(&mut self) {}
}
mod mod1 {
	use super::S3;
	fn f1(s3: &S3) {
		s3.m1();
	}
	mod mod2 {
		// doesn't work:
		use super::super::S3;
		// Uncoment and it works:
		// use super::S3;
		// Uncoment and it works:
		// use crate::S3;
		fn f2(s3: &S3) {
			s3.m1();
			// The completion list doesn't show `m1()` and `m2()` after typing `s3.m`
			s3.m
		}
	}
}
```

**Comment by bjorn3** [comment] 2020-02-08 16:58
This is a duplicate of #2377.

**Closed by bjorn3** 2020-02-08 16:58 UTC
