### ISSUE TITLE
Make it easier to import a trait "shadowed" by a derive macro

### ISSUE THREAD

**Issue by kpreid** [rust-analyzer/rust-analyzer#11138] opened 2021-12-28 22:14 UTC
1. Write `&dyn Debug`.
2. Get compiler error [E0404](https://doc.rust-lang.org/error-index.html#E0404) "not a trait", because the standard library prelude contains the derive macro named `Debug` but not the trait named `Debug`.
3. Ask rust-analyzer to assist.

Right now, no assists are available. It would be nice if instead it offered to add `use std::fmt::Debug;`. The compiler does provide a suggestion: "consider importing one of these items instead: `use serde::__private::fmt::Debug;`, `use std::fmt::Debug;`, `use core::fmt::Debug;`" but evidently this doesn't translate into rust-analyzer assists.

**Comment by Veykril** [comment] 2021-12-29 01:20
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7408

**Closed by Veykril** 2021-12-29 01:20 UTC
