### ISSUE TITLE
auto completion broken when typing in a macro call 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#9044] opened 2021-05-29 06:15 UTC
## Description
auto completion broken when typing in a macro call, compare to a function call;
## Expected
auto completion work same as typing in a function call

https://user-images.githubusercontent.com/17974631/120060087-3a3b9280-c088-11eb-83a2-beafe871c9a9.mp4

**Comment by Veykril** [comment] 2021-05-29 10:20
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8158

**Comment by Veykril** [comment] 2021-05-29 10:21
Basically `Foo::` isn't valid input for the macro so it fails to expand which makes us unable to show completions atm

**Closed by Veykril** 2021-05-29 10:20 UTC
