### ISSUE TITLE
deref does not populate methods for structs defined in function bodies

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10763] opened 2021-11-14 10:27 UTC
Consider this code:

When A is defined outside of `main()`, `will_show_in_autocomplete` will show when trying to autocomplete at `$0`

```rust
struct A {}

impl A {
    fn will_show_in_autocomplete(&self) {}
}

fn main() {
    struct B(A);

    impl std::ops::Deref for B {
        type Target = A;

        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }

    let b = B(A {});

    b.$0();
}
```

However, when moved into `main()`, like so, `wont_show_in_autocomplete` will not show up in the auto-complete at position `$0`. 

```rust
fn main() {
    struct A {}

    impl A {
        fn wont_show_in_autocomplete(&self) {}
    }

    struct B(A);

    impl std::ops::Deref for B {
        type Target = A;

        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }

    let b = B(A {});

    b.$0();
}
```

**Comment by flodiebold** [comment] 2021-11-14 11:55
Probably a duplicate of #10676. Can you check with current nightly / a build that includes b2bce38bb44f46b9a68b7f98b03000f099cef4f8?

**Comment by jhgg** [comment] 2021-11-14 13:59
Yes still repros with current nightly.

**Comment by flodiebold** [comment] 2022-03-31 16:25
Works for me now.

**Closed by flodiebold** 2022-03-31 16:25 UTC
Labels: A-ty
