### ISSUE TITLE
git hash is gone from --version?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#8049] opened 2021-03-16 11:09 UTC
I'm on  `nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.52.0-nightly (107896c32 2021-03-15)`
````
$ rust-analyzer --version
rust-analyzer 2021-03-15
````
didn't it show a git hash in previous versions or do I remember that wrong...?

**Comment by lnicola** [comment] 2021-03-16 11:13
Duplicate of #8043

**Comment by lnicola** [comment] 2021-03-16 11:14
Actually no, this isn't a duplicate. Did you build from source?

**Closed by lnicola** 2021-03-16 11:13 UTC

**Comment by matthiaskrgr** [comment] 2021-03-16 11:15
Yeah I just wondered:
"changelog fix fix version display in release artifacts"
I'm using rust-analyzer that dis distributed as rustc-nightly component, and I didn't think that some RA-ci-fixes would fix that... :sweat_smile:

**Comment by lnicola** [comment] 2021-03-16 11:17
We now use `git describe --tags` for the version string. For tagged releases, this will be the tag name, without any hash.

**Comment by lnicola** [comment] 2021-03-16 11:18
That comes from https://github.com/rust-analyzer/rust-analyzer/issues/7854.

**Comment by matthiaskrgr** [comment] 2021-03-16 11:22
`git describe --tags` in the rustc repo submodule only says `2021-03-15` :thinking:

**Comment by lnicola** [comment] 2021-03-16 11:23
And that's what it says in the rust-analyzer repo as well.

**Comment by lnicola** [comment] 2021-03-16 11:25
You can see what commit a tag corresponds to in the GitHub UI or by running `git show 2021-03-15`.

**Comment by matthiaskrgr** [comment] 2021-03-16 11:26
Ah so is that intended to only show the tag now (since the tag just corresponds to a commit, I guess we don't need the commit anyway..?)

**Comment by lnicola** [comment] 2021-03-16 11:28
Yes. Of course, tags are mutable, but I don't think it's really a problem here.
