### ISSUE TITLE
lint autocompletions don't account for existing prefix

### ISSUE THREAD

**Issue by lopopolo** [rust-analyzer/rust-analyzer#9725] opened 2021-07-29 18:49 UTC
<img width="1422" alt="Screen Shot 2021-07-29 at 11 48 59 AM" src="https://user-images.githubusercontent.com/860434/127549216-04e0e289-c261-4252-89cd-007d198d0b1a.png">
<img width="1422" alt="Screen Shot 2021-07-29 at 11 49 03 AM" src="https://user-images.githubusercontent.com/860434/127549243-28dce4f3-f025-4aba-99a5-8ca4eb14b292.png">

**Comment by Veykril** [comment] 2021-07-29 19:58
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7144

**Closed by Veykril** 2021-07-29 19:58 UTC
