### ISSUE TITLE
Add integrated completion benchmark

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8517] opened 2021-04-14 16:44 UTC
Like https://github.com/rust-analyzer/rust-analyzer/blob/e6728a8cd39f9111dcdd654c7c65e99e5a2f1190/crates/rust-analyzer/src/benchmarks.rs#L22

cc https://github.com/rust-analyzer/rust-analyzer/pull/8515#issuecomment-819661571

**Comment by SomeoneToIgnore** [comment] 2021-04-14 17:25
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6633 ?

**Comment by matklad** [comment] 2021-04-14 17:39
Not really. Simple integrated benchmark is a broken window, but I'd love to see something fancier with generated code for #6633

**Comment by lnicola** [comment] 2021-05-05 19:28
I guess we can close this now?

**Closed** 2021-05-05 19:48 UTC
Labels: Broken Window
