### ISSUE TITLE
No type data available for code areas dealing with inlined / scope-defined structs

### ISSUE THREAD

**Issue by avkonst** [rust-analyzer/rust-analyzer#6460] opened 2020-11-04 06:41 UTC
I am not sure if it is a duplicate or not, but I could not find related issue. Here is the screenshot with hover showing `{unknown}` when struct is defined in scope of a function:
![image](https://user-images.githubusercontent.com/3971413/98077650-813c1d80-1ed5-11eb-99fb-2f43a351beb6.png)

When struct definition is moved out of the function scope, types are recognized correctly:
![image](https://user-images.githubusercontent.com/3971413/98077758-ae88cb80-1ed5-11eb-951d-92d4f0956345.png)

**Comment by lnicola** [comment] 2020-11-04 06:47
Duplicate of #1559

**Closed by lnicola** 2020-11-04 06:47 UTC
