### ISSUE TITLE
No autocomplete for salsa generated methods

### ISSUE THREAD

**Issue by artempyanykh** [rust-analyzer/rust-analyzer#7976] opened 2021-03-11 16:27 UTC
RA version: 2021-03-08 (proc macros enabled)
Editor: VSCode 1.54.1
rustc version: 1.50.0
Platform: Windows
salsa: 0.16.0

Snippet:
```rust
// mod facts;
use salsa;

use crate::{
  ...
};

#[salsa::query_group(FactsStorage)]
pub trait Facts: salsa::Database {
    #[salsa::input]
    fn tracked_notes(&self, key: ()) -> NoteIndex;
    ...
}

#[salsa::database(FactsStorage)]
#[derive(Default)]
pub struct FactsDB {
    storage: salsa::Storage<Self>,
}

impl salsa::Database for FactsDB {}
```

````rust
// mod index.rs;
use crate::{self, Facts};

pub struct Index {
  facts:: facts::FactsDB
}

impl Index {
  pub fn foo(&mut self) {
        let idx = self.facts.tracked_notes(());
        self.facts.set_tracked_notes((), idx);
  }
}
````

The latter compiles just fine, but there's no autocomplete for any of the autogenerated method `tracked_notes/set_tracked_notes`.

Is it expected? Or perhaps I'm doing something wrong? I see RA uses salsa quite a bit, so assumed both should play nicely together.

**Comment by lnicola** [comment] 2021-03-11 16:34
IIRC even if you enable proc macros, `salsa` doesn't work in `rust-analyzer` itself. I don't think we know why, but anyway, using `salsa` in the implementation doesn't guarantee that we support it well.

**Comment by Veykril** [comment] 2021-03-11 16:41
Isn't this just a case of us not supporting attribute macros yet?

**Comment by lnicola** [comment] 2021-03-11 16:41
Ah, right.

**Comment by flodiebold** [comment] 2021-03-11 17:38
Indeed, so let's close this as a duplicate of #6029.

**Closed by flodiebold** 2021-03-11 17:38 UTC
Labels: A-macro, S-unactionable
