### ISSUE TITLE
rust-analyzer is confused both by async_std::fs::File::write and std::fs::File::write [Linux vscode 0.4 dev]

### ISSUE THREAD

**Issue by fengjian** [rust-analyzer/rust-analyzer#5435] opened 2020-07-19 09:25 UTC
git log 

commit 130e7632acef435caa9bf56e7333e4c28c7dffc7
 
```
use async_std::fs::OpenOptions;
use crossbeam_channel::{bounded, Receiver, Sender};


async fn access_log_process<T:AsRef<Path>>(path:T, recv: Receiver<String>) -> io::Result<()> {
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .await.expect("open failed");

    let interval = 5;
    loop {
        if let Ok(s) = recv.try_recv() {
            file.write(s.as_bytes()).await. // complete not working. as std::fs::File::write
        } else {
            task::sleep(Duration::from_secs(interval)).await;
        }
    }
}
```

**Comment by lnicola** [comment] 2020-07-19 09:42
Probably duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5287, let's track it there.

**Closed by lnicola** 2020-07-19 09:42 UTC
