### ISSUE TITLE
proc-macro panicked: ParseFloatError { kind: Invalid }

### ISSUE THREAD

**Issue by lvella** [rust-analyzer/rust-analyzer#9045] opened 2021-05-29 15:04 UTC
I think I stumbled upon a `rust-analyzer` bug. Upon trying to make YouCompleteMe work with latest nightly of rust-analyzer, it panicked with the following error message:

`proc macro returned error: proc-macro panicked: called Result::unwrap() on an Err value: ParseFloatError { kind: Invalid }`

But "cargo build" succeeded using the same nightly toolchain. The code that fails is this one (very small, just one file): https://github.com/lvella/bastroblasto

The offending version: rust-analyzer 3022a2c 2021-05-28 dev

**Comment by lnicola** [comment] 2021-05-29 15:13
Duplicate of #8928. As a workaround you can use the stable toolchain or disable proc macro support.

**Closed by lnicola** 2021-05-29 15:13 UTC
