### ISSUE TITLE
Always loading on checking

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#8414] opened 2021-04-08 04:23 UTC
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/16152305/113968137-15375a00-9865-11eb-9ddd-430f2185dfa0.png">

Restart doesn't help.

I've to `killall && cargo build`. Otherwise I can't do any cargo operation.

**Comment by AurevoirXavier** [comment] 2021-04-08 04:23
I also disable the checkonsave in my settings.

**Comment by AurevoirXavier** [comment] 2021-04-08 05:09
BTW, I often get this error in recently updates:

```
[Error - 9:09:12 PM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:5384:23)
	at LanguageClient.onProgress (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:13071:45)
	at new ProgressPart (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:11050:41)
	at createHandler (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:14415:34)
	at handleRequest (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:4917:41)
	at processMessageQueue (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:4781:17)
	at Immediate._onImmediate (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.549-nightly/out/src/main.js:4771:13)
	at processImmediate (internal/timers.js:456:21)
	```

**Comment by lnicola** [comment] 2021-04-08 06:37
Is that on https://github.com/libp2p/rust-libp2p?

**Comment by AurevoirXavier** [comment] 2021-04-08 06:49
I'm on substrate.

Which is listed here https://github.com/libp2p/rust-libp2p#notable-users.

This is a sub-sub dep of my project.

**Comment by lnicola** [comment] 2021-04-08 07:04
I can't reproduce on substrate, but it does take ages to `check`.

**Comment by AurevoirXavier** [comment] 2021-04-08 07:05
> I can't reproduce on substrate, but it does take ages to `check`.

Does this whole process need a good network env?

**Comment by lnicola** [comment] 2021-04-08 07:10
It should be enough if `cargo check` works for you in a terminal.

**Comment by AurevoirXavier** [comment] 2021-04-08 07:39
> It should be enough if `cargo check` works for you in a terminal.

Cargo check works good. But curios why this always show loading.

Also there's a similar issue.

When I run cargo fmt in terminal directly, it response very quick.

But if I use rust-analyzer to call cargo fmt(such as format shortcut). It will show a loading bar at the top of the vscode and take a long time to finish the format.

**Comment by lnicola** [comment] 2021-04-08 13:04
> But if I use rust-analyzer to call cargo fmt(such as format shortcut). It will show a loading bar at the top of the vscode and take a long time to finish the format.

I noticed this too. I'm not sure, but I think we might be busy processing some other requests, so we take a while to start `rustfmt`. Or it might be something completely different.

**Comment by lnicola** [comment] 2021-04-21 05:17
@AurevoirXavier would you mind trying a nightly version? The project loading hang might have been fixed in #8600 and the (harmless) progress handler error in #8606.

**Comment by AurevoirXavier** [comment] 2021-04-21 05:19
How?

It will be update automatically?

**Comment by lnicola** [comment] 2021-04-21 05:21
It will be updated on Monday or you can set `"rust-analyzer.updates.channel": "nightly"` in `settings.json`.

**Comment by AurevoirXavier** [comment] 2021-04-21 05:26
```
[Error - 9:25:10 PM] Registering progress handler for token rustAnalyzer/Indexing failed.
Error: Progress handler for token rustAnalyzer/Indexing already registered
	at Object.onProgress (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:5384:23)
	at LanguageClient.onProgress (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:13071:45)
	at new ProgressPart (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:11050:41)
	at createHandler (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:14415:34)
	at handleRequest (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:4917:41)
	at processMessageQueue (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:4781:17)
	at Immediate._onImmediate (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/out/src/main.js:4771:13)
	at processImmediate (internal/timers.js:456:21)
```

Loading passed.

But indexing stuck.

![Uploading image.png…]()

**Comment by AurevoirXavier** [comment] 2021-04-21 05:27
<img width="923" alt="image" src="https://user-images.githubusercontent.com/16152305/115501211-5ab44800-a2a5-11eb-813f-3c62cb2e54d7.png">

**Comment by lnicola** [comment] 2021-04-21 05:31
Hmm, that error should have been fixed in #8606..

**Comment by AurevoirXavier** [comment] 2021-04-21 05:32
I'm sure I set "rust-analyzer.updates.channel": "nightly"

And a update window pop-up and I click update

**Comment by AurevoirXavier** [comment] 2021-04-21 05:34
Solved by running cargo check manually.

Is this what you expect?

**Comment by lnicola** [comment] 2021-04-21 05:37
No, that sounds exactly like #8528 -- which I guess wasn't closed, but should have been fixed in #8600.

**Comment by AurevoirXavier** [comment] 2021-04-21 05:41
I close the vscode and reopen it

Happens again :(

**Comment by lnicola** [comment] 2021-04-21 05:59
What do you get if you run `/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly/rust-analyzer-linux --version`?

**Comment by AurevoirXavier** [comment] 2021-04-21 06:01
```
Wed Apr 21 22:00:59 2021 - 22%
✗ e /root/.vscode-server/extensions/matklad.rust-analyzer-0.3.566-nightly          .rw-r--r-- 2.3k root 21 Apr 21:24 .vsixmanifest
.rw-r--r--  15k root 21 Apr 21:24 icon.png
.rw-r--r--  970 root 21 Apr 21:24 language-configuration.json
drwxr-xr-x    - root 21 Apr 21:24 out
.rw-r--r-- 266k root 21 Apr 21:24 package-lock.json
.rw-r--r--  35k root 21 Apr 21:24 package.json
.rw-r--r--  770 root 21 Apr 21:24 ra_syntax_tree.tmGrammar.json
.rw-r--r-- 3.0k root 21 Apr 21:24 README.md
```

Can't find it

**Comment by lnicola** [comment] 2021-04-21 06:02
Sorry, that's probably `/root/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux`.

**Comment by AurevoirXavier** [comment] 2021-04-21 06:03
```
Wed Apr 21 22:03:19 2021 - 22%
✗ /root/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version
rust-analyzer 2021-04-19-1-gd906b7ad8
```

**Comment by lnicola** [comment] 2021-04-21 06:05
Yeah, I think that's not the nightly version (Code needs a separate `settings.json` for remote?), but there was an "emergency" release put out yesterday and you have it installed. That's probably why you still get the progress handler error message, since it wasn't included in the release.

On the other hand, looks like #8528 wasn't fully fixed.

**Comment by AurevoirXavier** [comment] 2021-04-21 06:12
Server's settings doesn't work. 

Weird.

**Comment by AurevoirXavier** [comment] 2021-04-22 01:18
rust-analyzer 2021-04-19-85-g1f1a1ce4f works good

**Comment by jonas-schievink** [comment] 2021-04-22 12:59
Closing as fixed, thanks for testing!

**Closed by jonas-schievink** 2021-04-22 12:59 UTC
Labels: S-unactionable

**Comment by AurevoirXavier** [comment] 2021-05-21 02:11
Reproduce in rust-analyzer eb08a27f1 2021-05-21 nightly

**Comment by AurevoirXavier** [comment] 2021-05-21 02:33
Seems not a same issue.

Just always stuck at `js_sys`
