### ISSUE TITLE
constants are not recognized when used inside of constant expressions

### ISSUE THREAD

**Issue by mj-64** [rust-analyzer/rust-analyzer#7623] opened 2021-02-10 08:44 UTC
rust-analyzer does not recognize consts if they are used inside expressions that define other consts
E.g.:

```rust
const N:usize = 2;

struct Test {
    b: [u32; N],
}
```

rust analyzer does not recognize N in the array declaration as contant, nor can it move to its definition with F12 in VS code. It shows "no definition found for N".

The same issue also appears if you try to use a const inside other expression in functions.

**Comment by Veykril** [comment] 2021-02-10 08:47
Duplicate of #7432

**Closed by Veykril** 2021-02-10 08:47 UTC
