### ISSUE TITLE
Typing escaped quotes is difficult

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1171] opened 2019-04-19 18:10 UTC
I've been having fun going through this [parser tutorial](https://bodil.lol/parser-combinators/#quoted-strings) with `rust-analyzer` and seeing how it holds up (hint: it's awesome, the only thing that I think is really missing is #1154). One pain point however is our handling of escaped quotes.

For instance:

If attempting to type `match_literal("\"")` the sequence goes as follows starting at `match_literal<|>`

1. User types `(`. Becomes `match_literal(<|>)`
2. User types `"`. Becomes `match_literal("<|>")`
3. User types `\`. Becomes `match_literal("\<|>")`
4. User types `"`. Becomes `match_literal("\"<|>)`
5. User types `"`. Becomes `match_literal("\""<|>")`

At this point if the user types backspace it goes back to 4. If instead the user types delete it becomes what we want: `match_literal("\"")`.

I think the fix would be to determine if we are in a string and if the user types `"` we should disable the automatic insertion of the next `"`. I haven't looked into it so am unsure if this is on the rust side or the typescript side.

**Comment by DJMcNab** [comment] 2019-04-20 07:43
At `"\"<|>` the string is never closed, so it doesn't make sense to insert a quote pair. Additionally, in `"\<|>"` the next quote is not actually closing the string, so pressing `"` shouldn't skip that quote.

**Comment by matklad** [comment] 2019-04-20 14:37
Yeah, we should totally implement better typing assists for string literals...

This is also a part of IntelliJ Rust which I am not entirely satisfied with.


The problem is, VS Code doesn't expose nice API for doing this stuff...

**Comment by lnicola** [comment] 2020-12-21 08:24
This is actually working fine now, presumably due to the recent language configuration changes.

**Closed by lnicola** 2020-12-21 08:24 UTC
