### ISSUE TITLE
Autocomplete `self` does not seem to work in methods with `macro!` calls and not in root crate

### ISSUE THREAD

**Issue by fedepiz** [rust-analyzer/rust-analyzer#7743] opened 2021-02-21 22:43 UTC
As per title, the autocomplete of `self` seems to be somewhat wonky in methods with any macro call, 
but only outside of the root crate. 
Interestingly, the autocomplete "half works" in the lines before the macro, and does not work at all after.

See the code below for the details and minimal example

```rust
fn main() {}

mod inner {
    pub struct HasProblem;

    impl HasProblem {
        //PROBLEM HERE
        fn foo(&self) {
            // Typing "self." suggests bar(). Tying 'b' makes the suggestion disappear
            self.bar(); 
            println!("test");
            // Typing "self." does not show bar(). bar() never shows.
            self.bar() 
        }

        fn bar(&self) {
            self.foo() // Was suggested
        }
    }


    pub struct HasNoProblem;

    impl HasNoProblem {
        fn foo(&self) {
            self.bar(); // Was suggested.
        }

        fn bar(&self) {
            self.foo() // Was suggested
        }
    }
}

pub struct HasNoProblem;

//In root crate - seems to work
impl HasNoProblem {
    fn foo(&self) {
        println!("test");
        self.bar() // Suggested
    }

    fn bar(&self) {
        self.foo() // Suggested
    }
}

**Comment by edwin0cheng** [comment] 2021-02-22 00:36
It could be duplicate to #7728.

**Comment by flodiebold** [comment] 2021-02-22 09:49
It's indeed a duplicate of #7728.

**Closed by flodiebold** 2021-02-22 09:49 UTC
