### ISSUE TITLE
Connection dies with chalk error

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#2739] opened 2020-01-03 17:19 UTC
Backtrace::

```
thread '<unnamed>' panicked at 'New answer was not ambiguous whereas previous answer was.', /home/95th/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/table.rs:129:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: chalk_engine::table::Table<C>::push_answer
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  14: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  15: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  16: chalk_engine::forest::Forest<C>::solve
  17: ra_hir_ty::traits::trait_solve_query
  18: salsa::runtime::Runtime<DB>::execute_query_implementation
  19: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<DB,Q,MP>::read
  21: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  22: salsa::QueryTable<DB,Q>::get
  23: ra_hir_ty::method_resolution::iterate_method_candidates_by_receiver
  24: ra_hir_ty::method_resolution::lookup_method
  25: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  26: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  30: ra_hir_ty::infer::infer_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: ra_hir::code_model::Function::diagnostics
  36: ra_hir::code_model::Module::diagnostics
  37: ra_ide::diagnostics::diagnostics
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: ra_db::CheckCanceled::catch_canceled
  41: ra_ide::Analysis::diagnostics
  42: ra_lsp_server::main_loop::handlers::publish_diagnostics
  43: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'New answer was not ambiguous whereas previous answer was.', /home/95th/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/table.rs:129:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: chalk_engine::table::Table<C>::push_answer
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  14: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  15: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  16: chalk_engine::forest::Forest<C>::solve
  17: ra_hir_ty::traits::trait_solve_query
  18: salsa::runtime::Runtime<DB>::execute_query_implementation
  19: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<DB,Q,MP>::read
  21: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  22: salsa::QueryTable<DB,Q>::get
  23: ra_hir_ty::method_resolution::iterate_method_candidates_by_receiver
  24: ra_hir_ty::method_resolution::lookup_method
  25: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  26: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  30: ra_hir_ty::infer::infer_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: ra_hir::code_model::Function::diagnostics
  36: ra_hir::code_model::Module::diagnostics
  37: ra_ide::diagnostics::diagnostics
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: ra_db::CheckCanceled::catch_canceled
  41: ra_ide::Analysis::diagnostics
  42: ra_lsp_server::main_loop::handlers::publish_diagnostics
  43: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'New answer was not ambiguous whereas previous answer was.', /home/95th/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/table.rs:129:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: chalk_engine::table::Table<C>::push_answer
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  14: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  15: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  16: chalk_engine::forest::Forest<C>::solve
  17: ra_hir_ty::traits::trait_solve_query
  18: salsa::runtime::Runtime<DB>::execute_query_implementation
  19: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<DB,Q,MP>::read
  21: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  22: salsa::QueryTable<DB,Q>::get
  23: ra_hir_ty::method_resolution::iterate_method_candidates_by_receiver
  24: ra_hir_ty::method_resolution::lookup_method
  25: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  26: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  30: ra_hir_ty::infer::infer_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: ra_hir::code_model::Function::diagnostics
  36: ra_hir::code_model::Module::diagnostics
  37: ra_ide::diagnostics::diagnostics
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: ra_db::CheckCanceled::catch_canceled
  41: ra_ide::Analysis::diagnostics
  42: ra_lsp_server::main_loop::handlers::publish_diagnostics
  43: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'New answer was not ambiguous whereas previous answer was.', /home/95th/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/table.rs:129:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: chalk_engine::table::Table<C>::push_answer
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  14: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  15: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  16: chalk_engine::forest::Forest<C>::solve
  17: ra_hir_ty::traits::trait_solve_query
  18: salsa::runtime::Runtime<DB>::execute_query_implementation
  19: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<DB,Q,MP>::read
  21: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  22: salsa::QueryTable<DB,Q>::get
  23: ra_hir_ty::method_resolution::iterate_method_candidates_by_receiver
  24: ra_hir_ty::method_resolution::lookup_method
  25: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  26: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  30: ra_hir_ty::infer::infer_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: ra_hir::code_model::Function::diagnostics
  36: ra_hir::code_model::Module::diagnostics
  37: ra_ide::diagnostics::diagnostics
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: ra_db::CheckCanceled::catch_canceled
  41: ra_ide::Analysis::diagnostics
  42: ra_lsp_server::main_loop::handlers::publish_diagnostics
  43: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'New answer was not ambiguous whereas previous answer was.', /home/95th/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/ff65b5a/chalk-engine/src/table.rs:129:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: chalk_engine::table::Table<C>::push_answer
  13: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
  14: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
  15: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext<TF>> for chalk_solve::solve::slg::SlgContextOps<TF>>::make_solution
  16: chalk_engine::forest::Forest<C>::solve
  17: ra_hir_ty::traits::trait_solve_query
  18: salsa::runtime::Runtime<DB>::execute_query_implementation
  19: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<DB,Q,MP>::read
  21: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  22: salsa::QueryTable<DB,Q>::get
  23: ra_hir_ty::method_resolution::iterate_method_candidates_by_receiver
  24: ra_hir_ty::method_resolution::lookup_method
  25: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_method_call
  26: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  27: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  28: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
  29: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
  30: ra_hir_ty::infer::infer_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: ra_hir::code_model::Function::diagnostics
  36: ra_hir::code_model::Module::diagnostics
  37: ra_ide::diagnostics::diagnostics
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: ra_db::CheckCanceled::catch_canceled
  41: ra_ide::Analysis::diagnostics
  42: ra_lsp_server::main_loop::handlers::publish_diagnostics
  43: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: thread '<unnamed>' panicked at 'Canceledcalled `Result::unwrap()` on an `Err` value: "SendError(..)"
', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at [Info  - 10:47:24 PM] Connection to server got closed. Server will restart.
[Error - 10:47:24 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:47:24 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:47:24 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:47:24 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3927:25)
	at Object.dispose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:8453:35)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10688:42)
	at LanguageClient.handleConnectionClosed (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:11896:15)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:10675:18)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at closeHandler (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:3263:26)
	at CallbackList.invoke (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2041:39)
	at Emitter.fire (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2225:27)
	at Socket.<anonymous> (/home/95th/.vscode-server/extensions/matklad.ra-lsp-0.0.1/out/main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

**Comment by bjorn3** [comment] 2020-01-03 17:21
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/2675

**Closed** 2020-01-03 18:18 UTC

**Comment by flodiebold** [comment] 2020-01-03 18:19
Although the connection dying may be new? I don't know, since I don't use VSCode...
