### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by smmalis37** [rust-analyzer/rust-analyzer#2992] opened 2020-02-02 23:54 UTC
My rust-analyzer version is a local build of commit dbb235ed0756233e669a9a460494ed24e815e8a8. I get the following stack trace printed in VS Code's extension logs when opening in a folder containing a rust project:

```
[2020-02-02 15:49:14.250] [exthost] [error] Activating extension matklad.rust-analyzer failed due to an error:
[2020-02-02 15:49:14.252] [exthost] [error] Error: Cannot find module 'tslib'
Require stack:
- c:\Users\smmal\.vscode\extensions\matklad.rust-analyzer-0.1.0\out\main.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.Module._load (internal/modules/cjs/loader.js:531:27)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\smmal\.vscode\extensions\matklad.rust-analyzer-0.1.0\out\main.js:4:17)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.Module._load (internal/modules/cjs/loader.js:560:12)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:32:963)
	at d._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:790:289)
	at d._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:694:547)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:582)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:534)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:21)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:632
	at Array.map (<anonymous>)
	at d._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:620)
	at d.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:514:413)
	at d._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:692:282)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:572
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by matklad** [comment] 2020-02-02 23:55
cc @Veetaha apparently something went wrong with bundling tslib?

**Comment by smmalis37** [comment] 2020-02-02 23:57
Tried deleting my rust-analyzer target folder and doing a clean `cargo xtask install`, no change.

**Comment by smmalis37** [comment] 2020-02-02 23:57
VS Code version:
```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by smmalis37** [comment] 2020-02-02 23:59
More versions:
```
> npm --version
6.13.1
> rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by Veetaha** [comment] 2020-02-03 07:57
Looking into that

**Comment by vipentti** [comment] 2020-02-03 08:13
@Veetaha this seems to be due to `tsconfig.jsons` module option being set to `commonjs`. Changing it to `ES2015` seems to fix it.

**Comment by Veetaha** [comment] 2020-02-03 08:22
I have very strange behaviour, that tslib is required even when `importHelpers` is not enabled

**Comment by Veetaha** [comment] 2020-02-03 08:46
Okay, so here are the result of my investigation:

It seems that the culprit is not `tslib` itself. We have [recently updated](https://github.com/rust-analyzer/rust-analyzer/pull/2991) the version of `@rollup/typescript-plugin` from `2.1.0` to `3.0.0`. The only breaking change that it was supposed to incur was adding type-checking while bundling.

However, this is not the sole breaking change. When bundling with `commonjs` target module system and `2.1.0` version of that plugin we get a wellformed bundle as expected. However `3.0.0`with the same setup produces a malformed bundle where not all code is in a single file, but only the original output of transpilation of `main.ts`.

As noted by @vipentti, `es2015` target module system does fix this. I'd need to investiage this more thoroughly to look at why bundling behaviour changed from `2.1.0` to `3.0.0`, but after work. Now I'll just switch to `es2015` to fix this.

**Comment by matklad** [comment] 2020-02-03 09:09
Hopefully closed by https://github.com/rust-analyzer/rust-analyzer/pull/2993#issuecomment-581308408

Thanks @Veetaha, @smmalis37 and @vipentti for quick diagnosis and a fix!

**Closed by matklad** 2020-02-03 09:10 UTC

**Comment by Veetaha** [comment] 2020-02-03 09:52
@matklad in order to prevent this kind of bugs in future we will need to setup a smoke test that the extension is able to load. If you don't want to install vscode GUI at ci, we will need to stub vscode module or install it from npm explicitly

**Comment by matklad** [comment] 2020-02-03 09:57
@Veetaha I actually think that the best way to catch these kinds of regressions are nightly/beta releases, when the users just try it out and complain if something doesn't work. 

The reason being is that we can't check that all the things work. The fact that extension just loads tells us nothing that it doesn't die in flames on the first executed action. 

So, we hit a point of diminishing returns, where writing test is hard, and where it tests a small slice of desired behavior. 

Optimizing "beta testing" process would be a better investment here. And, given that we've got a bug report a couple of hours after the change was introduced, makes me thing that it actually works OK right now.

**Comment by Veetaha** [comment] 2020-02-03 10:04
@matklad I know vscode has put some effort into [vscode-test](https://github.com/microsoft/vscode-test). Did you consider it? We could make same end-to-end tests with I guess. Though my initial proposal was just a smoke test which purpose is not to test the behaviour of an application anyway

**Comment by matklad** [comment] 2020-02-03 10:09
>We could make same end-to-end tests with it I guess.

I am skeptical that we can write an end-to-end test that will detect all interesting ways in which software might be broken. I'd love our strategy to be to just minimize the amount of code in typescript extension, and to move as much as possible to vscode-langauge-client library, so that it's not us who maintain the code. 

So, my gut feeling is that it isn't worth it.
