### ISSUE TITLE
Command 'rust-analyzer.onEnter' not found

### ISSUE THREAD

**Issue by Fullstop000** [rust-analyzer/rust-analyzer#3227] opened 2020-02-19 03:00 UTC
I'm getting `command 'rust-analyzer.onEnter' not found` error when I press the enter and it seems the normal enter can not work anymore unless ra is disabled. Is there any way to avoid this?

**Comment by lnicola** [comment] 2020-02-19 06:11
Thanks for the report. It's a duplicate of the confusingly-titled #3212, so let's keep the discussion there.

**Closed by lnicola** 2020-02-19 06:11 UTC
