### ISSUE TITLE
Unable to parse Args

### ISSUE THREAD

**Issue by Matelasse** [rust-analyzer/rust-analyzer#4504] opened 2020-05-18 21:21 UTC
Given the following line of code:
`let arg1 = &args[1].parse::<String>().unwrap();`
RA is unable to specify a correct inlay type hint for arg1. 
RA thinks `arg1` is of type `&{unknown}` and no helpful intellisense is being provided for it, even though it's easy to tell that `arg1` is `String`

**Comment by Matelasse** [comment] 2020-05-20 09:28
@matklad Sorry for tagging you, but do you know if this is expected? In hindsight, looks like this should already be addressed in the codebase. I'd appreciate insights on where to look for the fix

**Comment by flodiebold** [comment] 2020-05-20 09:41
This is a duplicate of #2534. Sadly, it's not at all easy to tell the type of `args[1]` (for details, see that issue).

**Closed by flodiebold** 2020-05-20 09:41 UTC
Labels: A-ty
