### ISSUE TITLE
Update Cargo.toml dependencies use is not recognized

### ISSUE THREAD

**Issue by xldsdr124** [rust-analyzer/rust-analyzer#4926] opened 2020-06-17 13:57 UTC
When I added a dependency library, the use statement vscode is not recognized, I need to restart vscode to re-analyze the dependency.

I also noticed another problem. Turning on this plugin makes my vscode not wrap normally. Is there any improvement needed?

**Comment by lnicola** [comment] 2020-06-17 13:59
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/3715.

> I also noticed another problem. Turning on this plugin makes my vscode not wrap normally. Is there any improvement needed?

If you end up with long inlay hints, yes. The workaround is to disable them. Long-term, LSP might have built-in support for those, like in https://github.com/microsoft/vscode-languageserver-node/pull/609.

**Closed by lnicola** 2020-06-17 13:59 UTC
