### ISSUE TITLE
Duplicate Quick Fix 'remove the unused import'

### ISSUE THREAD

**Issue by rherrmann** [rust-analyzer/rust-analyzer#7141] opened 2021-01-03 17:45 UTC
Opening the _Quick Fix_ context menu on an unused import shows the entry _remove the unused import_ twice.

Use the following example to reproduce:
```rust
use std::fs::copy;
use std::error::{Error, <|>Chain};

fn bar() -> Result<(), Box<dyn Error>> {
  Ok(())
}
```
Position the cursor on `Chain` and hit <kbd>Ctrl/Cmd</kbd>+<kbd>.</kbd>. The context menu shows the same entry twice:

<img width="481" alt="Screenshot 2021-01-03 at 18 23 12" src="https://user-images.githubusercontent.com/607182/103484904-9e686c00-4df2-11eb-8805-97c8c3a3bd27.png">

Possibly related, the quick fix to remove an entire `use` clause (`use std::fs::copy` in the above example) also shows up twice: 

<img width="481" alt="Screenshot 2021-01-03 at 18 24 00" src="https://user-images.githubusercontent.com/607182/103484926-c061ee80-4df2-11eb-85c5-a2d019a90e43.png">

Rust-analyzer version: 2020-12-21 (e1acb0c)

BTW, I was curious to see the code that that provides the quick fix(es) but couldn't find it.

**Comment by brightly-salty** [comment] 2021-01-03 18:27
I find this happens for almost any quick fix produced by rustc or rust-clippy. They are all listed twice, and sometimes fail. I'm on VSCodium on macOS Big Sur 11.1 with rust-analyzer nightly.

**Comment by flodiebold** [comment] 2021-01-03 19:31
Duplicate of #6851.

**Closed by flodiebold** 2021-01-03 19:31 UTC
