### ISSUE TITLE
'index out of bounds: the len is 108 but the index is 108', crates/ide_db/src/line_index.rs:107:9

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-analyzer/rust-analyzer#7917] opened 2021-03-08 13:37 UTC
I think I got this panic while I was renaming a structure inside an enum.
This isn't exactly the same version, but it was at this line: https://github.com/PaulGrandperrin/cachou/blob/c24d9ebc65b762942847f0813d06133011675c3f/common/src/api/call.rs#L14

I save my whole OS (a btrfs snapshot) at the moment of the panic.. if something needs to be recovered to help you, please tell me.

Unfortunately, I can't reproduce.

Here is the full trace:

```
[Error - 2:18:24 PM] Request textDocument/rename failed.
  Message: No references found at position
  Code: -32602 
[Error - 2:18:33 PM] Request textDocument/rename failed.
  Message: No references found at position
  Code: -32602 
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 14,
            character: 7,
        },
        end: Position {
            line: 14,
            character: 7,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 14,
                        character: 7,
                    },
                    end: Position {
                        line: 14,
                        character: 7,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rustc",
                ),
                message: "expected one of `(`, `,`, `=`, `{`, or `}`",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 15,
                                        character: 4,
                                    },
                                    end: Position {
                                        line: 15,
                                        character: 19,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 14,
                        character: 7,
                    },
                    end: Position {
                        line: 14,
                        character: 7,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rustc",
                ),
                message: "missing `,`",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 15,
                                        character: 4,
                                    },
                                    end: Position {
                                        line: 15,
                                        character: 19,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
        ],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 108 but the index is 108', crates/ide_db/src/line_index.rs:107:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: ide_db::line_index::LineIndex::offset
   4: rust_analyzer::from_proto::text_range
   5: rust_analyzer::handlers::handle_code_action
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 16,
            character: 29,
        },
        end: Position {
            line: 16,
            character: 29,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 108 but the index is 108', crates/ide_db/src/line_index.rs:107:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: ide_db::line_index::LineIndex::offset
   4: rust_analyzer::from_proto::text_range
   5: rust_analyzer::handlers::handle_code_action
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 16,
            character: 0,
        },
        end: Position {
            line: 17,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 16,
                        character: 8,
                    },
                    end: Position {
                        line: 16,
                        character: 23,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rustc",
                ),
                message: "expected one of `!`, `(`, `)`, `+`, `,`, `::`, or `<`, found `UserPrivateData`\nunexpected token",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 15,
                                        character: 23,
                                    },
                                    end: Position {
                                        line: 15,
                                        character: 23,
                                    },
                                },
                            },
                            message: "expected one of 7 possible tokens",
                        },
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 15,
                                        character: 23,
                                    },
                                    end: Position {
                                        line: 15,
                                        character: 23,
                                    },
                                },
                            },
                            message: "missing `,`",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 16,
                        character: 8,
                    },
                    end: Position {
                        line: 16,
                        character: 23,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0412",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0412",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "cannot find type `UserPrivateData` in this scope",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 92,
                                        character: 0,
                                    },
                                    end: Position {
                                        line: 92,
                                        character: 29,
                                    },
                                },
                            },
                            message: "similarly named struct `GetUserPrivateData` defined here",
                        },
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 16,
                                        character: 8,
                                    },
                                    end: Position {
                                        line: 16,
                                        character: 23,
                                    },
                                },
                            },
                            message: "there is an enum variant `crate::api::Call::UserPrivateData`; try using the variant\'s enum",
                        },
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 16,
                                        character: 8,
                                    },
                                    end: Position {
                                        line: 16,
                                        character: 23,
                                    },
                                },
                            },
                            message: "a struct with a similar name exists",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 16,
                        character: 8,
                    },
                    end: Position {
                        line: 16,
                        character: 23,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: Some(
                    String(
                        "E0412",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0412",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "there is an enum variant `crate::api::Call::UserPrivateData`; try using the variant\'s enum",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 16,
                                        character: 8,
                                    },
                                    end: Position {
                                        line: 16,
                                        character: 23,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 16,
                        character: 8,
                    },
                    end: Position {
                        line: 16,
                        character: 23,
                    },
                },
                severity: Some(
                    Hint,
                ),
                code: Some(
                    String(
                        "E0412",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0412",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "a struct with a similar name exists",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/paulg/Repositories/cachou/common/src/api/call.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 16,
                                        character: 8,
                                    },
                                    end: Position {
                                        line: 16,
                                        character: 23,
                                    },
                                },
                            },
                            message: "original diagnostic",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
        ],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 108 but the index is 108', crates/ide_db/src/line_index.rs:107:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: ide_db::line_index::LineIndex::offset
   4: rust_analyzer::from_proto::text_range
   5: rust_analyzer::handlers::handle_code_action
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment] 2021-03-08 13:38
Dupe of https://github.com/rust-analyzer/rust-analyzer/issues/4266, I guess.

**Closed** 2021-03-08 13:43 UTC
