### ISSUE TITLE
Semantic highlighting discrepancies with macro annotations

### ISSUE THREAD

**Issue by Zedjones** [rust-analyzer/rust-analyzer#4192] opened 2020-04-28 15:31 UTC
![image](https://user-images.githubusercontent.com/16535062/80506414-8a0ad000-8943-11ea-8957-087d6ddba83f.png)

These two symbols should be semantically the same, but appear differently. It seems like the definition under `#[cfg(not(debug_assertions))]` is the normal syntax highlighting for those tokens, while the `#[cfg(debug_assertions)]` is different.

**Comment by edwin0cheng** [comment] 2020-04-28 15:35
duplicated to #4041, I think

**Comment by lnicola** [comment] 2020-04-28 15:35
Probably a duplicate of #4041.

**Comment by Zedjones** [comment] 2020-04-28 15:36
Thanks, didn't see that! Appreciate the fast response.

**Closed** 2020-04-28 15:36 UTC
