### ISSUE TITLE
Errors and warnings from `cargo check` disappear for files when their corresponding tabs are closed

### ISSUE THREAD

**Issue by kotauskas** [rust-analyzer/rust-analyzer#9543] opened 2021-07-09 15:21 UTC
I'm using the official VS Code extension. This is especially problematic since it means I can't rely on the "Problems" view to display every single warning and error to me, forcing me to run my check command when I want to really make sure my code compiles without warnings (`cargo clippy`, which I have configured in editor options as well; irrelevant side note, detecting Clippy and using it by default if present would be really nice).

This put me in a couple of very confusing moments where I did `git commit --amend` and `git push --force-with-lease` and read the errors from CI before realizing that only open tabs contribute to the problem list, and it may well trick new users of rust-analyzer into pushing broken code into their central repo.

MCVE:
1. Open up VS Code with the rust-analyzer extension, do `cargo new`
2. Create a bunch of files which cause errors
3. Disable built-in diagnostics so that only `cargo check`/`cargo clippy` warnings and errors are delivered through the editor UI
4. Add `mod` declarations to `main.rs` to get those files to compile as well
5. Save all files
6. Close all tabs other than `main.rs` (though, for that matter, you can close `main.rs` too, it won't change anything as long as `main.rs` doesn't have errors)
7. Observe discrepancy between Cargo's command line output when checking and the Problems pane in VS Code

**Comment by bjorn3** [comment] 2021-07-09 16:51
Do you save after adding the `mod`s? `cargo check`/`cargo clippy` only runs when you save a file.

**Comment by kotauskas** [comment] 2021-07-09 19:21
Yes, I do save after performing the changes, i.e. a Cargo check invocation does happen.

Something else that I noticed is that closing an existing tab which had warnings or errors displayed on it immediately removes those from both the Problems pane and the file tree pane to the right of the editor.

**Comment by SomeoneToIgnore** [comment] 2021-07-10 07:15
Looks related to https://github.com/rust-analyzer/rust-analyzer/issues/6850

Possibly related to https://github.com/rust-analyzer/rust-analyzer/issues/8257

**Comment by jonas-schievink** [comment] 2021-07-10 18:05
This seems like a dupe of #6850, so closing in favor of that

**Closed by jonas-schievink** 2021-07-10 18:05 UTC
