### ISSUE TITLE
QuickFix context menu "items case quickfix" really converts; does not rename

### ISSUE THREAD

**Issue by shoffmeister** [rust-analyzer/rust-analyzer#11380] opened 2022-01-30 18:24 UTC
Identifiers should have snake case, so 
```
fn main() {
    let BadName = 0;
    let good_name = BadName;
}
```
is ... "bad". Invoking vscode QuickFix (Ctrl+.) yields a context menu with entries

* convert the identifier to snake_case: `bad_name`
* rename identifier to bad_name
* ...

The top-most item does what it says: It _converts_ exactly that span of text into the right shape. It does _not rename_ the identifier.

But why? Why would I change this specific sequence of characters instead of changing the name of the identifier at large?

IMHO, "convert the identifier" does what it promises, but it promises the wrong thing. The following item, "rename" is always what a user wants, without exception. Hence that specific "convert" quickfix (menu entry) seems to not add value. And because "convert" is at the top of the quickfix list, it's also an additional key-press to the Real Thing, "rename".

Should the "convert" quickfix just go? (The diagnostic is good!)

----

FWIW, rustc emits "convert the identifer", too - but ... why? It's not meaningful to convert characters in a single place, the identifier needs to be renamed wholesale, i.e. "help: rename the identifier to have snake case")

```
warning: variable `BadName` should have a snake case name
 --> src/main.rs:2:9
  |
2 |     let BadName = 0;
  |         ^^^^^^^ help: convert the identifier to snake case: `bad_name`
```

**Comment by Veykril** [comment] 2022-01-30 18:52
The first quickfix is the one generated from rustc's diagnostic item, the second one is our own custom one. So the first one not renaming all occurences is expected, we have yet to filter out rustc quickfixes if our own are applicable

**Comment by flodiebold** [comment] 2022-01-30 20:08
Duplicate of #7742.

**Closed by flodiebold** 2022-01-30 20:08 UTC
