### ISSUE TITLE
rust analyzer crashes

### ISSUE THREAD

**Issue by sehz** [rust-analyzer/rust-analyzer#4905] opened 2020-06-16 02:07 UTC
version: v0.3.208-nightly

```
thread '<unnamed>' panicked at 'Failed to make ast node `ra_syntax::ast::generated::nodes::Path` from text use ', crates/ra_syntax/src/ast/make.rs:308:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: ra_syntax::ast::make::path_from_text
   9: ra_syntax::ast::make::path_unqualified
  10: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix::split_path_prefix
  11: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix
  12: ra_assists::handlers::merge_imports::try_merge_trees
  13: <core::iter::adapters::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
  14: ra_assists::handlers::merge_imports::merge_imports
  15: ra_assists::Assist::unresolved
  16: ra_ide::Analysis::unresolved_assists
  17: rust_analyzer::main_loop::handlers::handle_code_action
  18: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 7:01:43 PM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'no value set for FileSourceRootQuery(FileId(554))', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:16:9
stack backtrace:
[Info  - 7:01:43 PM] Connection to server got closed. Server will restart.
[Error - 7:01:43 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
```

In the node.js, I see
```
[Error - 7:01:45 PM] Request textDocument/semanticTokens failed.
```

**Comment by kiljacken** [comment] 2020-06-16 06:58
Would you be able to share the project on which this is occurring? That
will help in reproducing the issue.

**Comment by jonas-schievink** [comment] 2020-06-16 15:17
Looks like https://github.com/rust-analyzer/rust-analyzer/issues/4368

**Comment by sehz** [comment] 2020-06-16 18:05
It's hard to reproduce, it only happens occasionally.

**Comment by lnicola** [comment] 2020-06-22 15:22
Closing as duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4368#issuecomment-633108688.

**Closed by lnicola** 2020-06-22 15:22 UTC
