### ISSUE TITLE
false unresolved imports for ed25519_dalek

### ISSUE THREAD

**Issue by OfekShochat** [rust-analyzer/rust-analyzer#10133] opened 2021-09-03 09:51 UTC
I use the vscode extension and I get unresolved imports for the ed25519-dalek crate even tho it compiles fine

**Comment by Veykril** [comment] 2021-09-03 10:13
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7243

**Closed by Veykril** 2021-09-03 10:13 UTC

**Comment by OfekShochat** [comment] 2021-09-03 10:14
oh right! havent found it!
