### ISSUE TITLE
Features not working in files outside the module tree

### ISSUE THREAD

**Issue by vikigenius** [rust-analyzer/rust-analyzer#7345] opened 2021-01-19 05:12 UTC
I am able to reproduce this on VSCode and Emacs (lsp-mode) with rust analyzer.

I created a minimal project and installed an external crate

```
[dependencies]
structopt = "0.3"
```

In src/main.rs I can get completion for the following

```
use structo   # Completions suggested perfectly (includes structopt)
```

However when I open a new file config.rs I don't get completion

```
use structo   # No  Completions suggested
```

Even after manually typing out the whole thing completion doesn't work at all for structopt. It is not specific to structopt either, I could reproduce this with multiple external crates.

other kinds of completion work such as struct, Option etc. but the external crates do not get completed, it is as if they are not installed at all, even though they work fine in main.rs

**Comment by vikigenius** [comment] 2021-01-19 05:17
Upon further debugging, it does work once I include the following in main.rs and then build the project.

```
mod config;
```

Is this the intended behaviour ?

**Comment by lnicola** [comment] 2021-01-19 06:14
Yes, some features only work on files in the module tree. I think there's an issue about it.

**Comment by lnicola** [comment] 2021-02-27 16:14
Duplicate of #6377.

**Closed by lnicola** 2021-02-27 16:14 UTC
Labels: S-unactionable
