### ISSUE TITLE
Auto-complete for primitive types

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#2647] opened 2019-12-22 17:41 UTC
Inherent methods for primitive types aren't available when auto-completing.

eg.

```rust
let a = [1, 2]; // array/slice (since arrays coerce to slice)
a.{len, first, last, ...}(...);

let b = u32::from_le(12);

...
```

**Comment by cynecx** [comment] 2019-12-22 17:43
This issues seems to be related: https://github.com/rust-analyzer/rust-analyzer/issues/1139. However that one is closed and this is still an issue.

**Comment by JoshMcguigan** [comment] 2020-03-01 16:21
I also see this issue for slices, even though [this test](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir_ty/src/tests/method_resolution.rs#L842) exists. 

My initial guess is the slice type needs to be added to [LangItemTarget](https://github.com/rust-analyzer/rust-analyzer/pull/1154/files#diff-5f6304fedafab409056ba0c4f3710e2eR11), and perhaps this causes things to work in the test, but not work when the slice implementation is from an external crate?

**Comment by flodiebold** [comment] 2020-03-01 16:38
@JoshMcguigan the slice methods work for me on current master. Are you sure you're running the newest version?

Completion for `u32::` doesn't work yet; I haven't investigated, but since the methods actually resolve once you've written them, it seems to be a problem in the completion code.

**Comment by JoshMcguigan** [comment] 2020-03-01 18:52
Ah yes, my issue here is that by default coc-rust-analyzer does not use the cargo installed version of rust analyzer. I pointed coc-rust-analyzer at the cargo installed binary and the slice completions and type inference started working.

**Comment by davemilter** [comment] 2020-03-02 15:23
Recent version (2020-03-02) seems changed behaviour
```rust
struct Foo {
    i: i32,
}

impl Foo {
    fn to_packet_bytes(self) -> [u8; 4] {
        self.i.to_le_bytes()
    }
}

fn main() {
    println!("Results:")
}
```

it recognize `self.i.to_le_bytes()`, but if I choose jump to source code it jumps to
.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/num/mod.rs:1440,
while first mention of to_le_bytes is on line 2230, but in the same module.

**Comment by edwin0cheng** [comment] 2020-03-02 15:53
@davemilter I can confirm that the `self.i.to_le_bytes()` jump to a wrong place.  

Note that `to_le_bytes` is defined in a big [macro_rules](https://github.com/rust-lang/rust/blob/c839a7b4c26e58319b0c40448dd423facff34cd0/src/libcore/num/mod.rs#L256), and related to some bulitn-macros (i.e. concat). 

So my wild guess is it related to #3368...

**Comment by Dushistov** [comment] 2020-04-10 12:34
No competition for `copy_from_slice` I suppose also should be related to this issue:

```rust
fn main() {
    let mut a = [0u8; 4];
    let b = [17u8; 3];
    a[0..3].|
//    a[0..3].copy_from_slice(&b);
    println!("a: {:?}", a);
}
```

**Comment by edwin0cheng** [comment] 2020-05-07 08:46
I just tested it , and the following works:
```rust
fn main() {
    let mut a = [0u8; 4];
    let b = [17u8; 3];
    a[0usize..3usize].
    println!("a: {:?}", a);
}
```

So I think the remain problem related to handle integer variables in Chalk. 

closed in favor of #2534

**Closed by edwin0cheng** 2020-05-07 08:46 UTC
Labels: A-completion, A-macro

**Comment by eric-burel** [comment] 2022-09-08 07:13
Sorry to fig and old thread but google will point me there when trying to understand why I have no autocompletion for primitive types.
I've noticed that VS Code suggest me to add `mod primitive_types;` in `src/main.rs` if I want primitive types (eg a Character) to be detected correctly. When I add this line, I indeed have the correct type hints and method completion for a variable that is a character.

However I couldn't achieve the same in the "rustling" tutorial.

Expected (I could only reproduce in an existing project by adding `mod primitive_types`, but not in "rustlings":
![image](https://user-images.githubusercontent.com/7983005/189058435-ac0c225c-c379-49ef-b7ca-714459042a29.png)

Actual (no auto-completion): 
![image](https://user-images.githubusercontent.com/7983005/189058225-98931f7a-dfef-44b0-917d-45fb25764097.png)


But it's totally unclear what happens, searching for "mod primitive_types" in Google points me to nothing. I'll update this message if I find more information but for beginners this is still quite confusing how to enable primitive_types completion in VS code.

**Comment by flodiebold** [comment] 2022-09-08 09:40
@eric-burel The `mod primitive_types` suggestion sounds very weird. Do you have a file `primitive_types.rs`? If you add the mod and ctrl-click on `primitive_types`, where does it take you? Can you show what exactly the error message and suggestion looks like?

**Comment by eric-burel** [comment] 2022-09-08 09:51
Updated my comment, this is because my file was named "primitive_types.rs" lol. And the code suggestion is not very clear:
![image](https://user-images.githubusercontent.com/7983005/189092048-40029377-bfd4-400c-8296-fe824318059f.png)

I thought "primitive_type" was some kind of module. If I rename the file to "test.rs" it will propose "test".

It could be interesting in this action to add more information (however I don't know how to do so without bloating the message), maybe about where the "mod foobar" will be added, since it's not the current file but the main.rs or the module root.

**Comment by flodiebold** [comment] 2022-09-08 09:54
I do think the code action should say "Insert `mod test;` in `main.rs`".
