### ISSUE TITLE
Struct add impl assist doesn't indent correctly

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#920] opened 2019-03-03 10:05 UTC
```rust
fn trans_fn() {
    {
        struct UI128Visitor;

impl UI128Visitor {

}
    }
}
```

**Comment by matklad** [comment] 2019-03-03 20:18
Yeah, we don't handle reformatting after applying assist. We need to design an API to handle this nicely...

**Comment by matklad** [comment] 2019-03-03 20:30
Opened https://github.com/rust-analyzer/rust-analyzer/issues/923 for the general problem

**Comment by lnicola** [comment] 2020-12-21 08:29
Closing as duplicate of #1645 (which is newer, but more complete).

**Closed by lnicola** 2020-12-21 08:29 UTC
Labels: E-hard, S-unactionable, fun
