### ISSUE TITLE
Failed to make ast node `syntax::ast::generated::nodes::Name`

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#10241] opened 2021-09-14 21:54 UTC
```
thread '<unnamed>' panicked at 'Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod 0_1;', crates/syntax/src/ast/make.rs:678:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/51e514c0fb4f9afcaae3b02dd9ccb93e15b30ef8/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/51e514c0fb4f9afcaae3b02dd9ccb93e15b30ef8/library/std/src/panicking.rs:460:5
   2: syntax::ast::make::ast_from_text
   3: syntax::ast::make::name
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: itertools::Itertools::join
   6: syntax::ast::make::param_list
   7: ide_assists::handlers::generate_function::fn_args
   8: ide_assists::handlers::generate_function::generate_function
   9: ide_assists::assists
  10: ide::Analysis::assists_with_fixes::{{closure}}
  11: std::panicking::try
  12: ide::Analysis::assists_with_fixes
  13: rust_analyzer::handlers::handle_code_action
  14: std::panicking::try
  15: <F as threadpool::FnBox>::call_box
```

Spotted on https://github.com/georust/gdal/blob/6ad95e7f977f5ef69d835d3507c93b884e4ae8ae/src/raster/rasterband.rs#L332. `gdal_sys` has some generated bindings, and we don't seem to resolve anything from it when used as a dependency.

**Comment by Veykril** [comment] 2021-09-14 23:06
Dupe of https://github.com/rust-analyzer/rust-analyzer/issues/10176, though closing that one in favour of this as this issue has a backtrace.

**Closed** 2021-09-17 18:43 UTC
Labels: S-actionable, A-assists, C-bug
