### ISSUE TITLE
Mismatching compile error with keyword use in macro

### ISSUE THREAD

**Issue by scoopr** [rust-analyzer/rust-analyzer#6434] opened 2020-11-01 17:32 UTC
I noticed a ra compiler error with this snippet, that doesn't happen in rustc.
```rust
fn main() {
    let file_name="";
    let _ = format!("{fn}", fn=file_name);
}
```
The issue is the `fn` keyword in the named format.

This is easily worked around, so not big deal, but the insidious thing is that the error displayed in the wrong place at the start of the file, so guessing the bit that caused the error needed some investigation.

**Comment by flodiebold** [comment] 2020-12-21 12:53
@scoopr I assume this is still happening in current RA? The error might be in the right place now though.

**Comment by lnicola** [comment] 2020-12-21 13:39
It works for me:

![image](https://user-images.githubusercontent.com/308347/102782886-c0013680-43a2-11eb-9663-0b82acbc7ec1.png)

**Comment by edwin0cheng** [comment] 2021-01-13 05:45
I can't reproduce either. Let close it first and feel free to reopen it if needed.

**Closed by edwin0cheng** 2021-01-13 05:45 UTC
Labels: A-macro, S-actionable

**Comment by scoopr** [comment] 2021-01-13 07:23
Sorry forgot to retest, couldn't reproduce it anymore either.
