### ISSUE TITLE
Cannot Update/Bootstrap `rust-analyzer` in Visual Studio Code

### ISSUE THREAD

**Issue by HTG-YT** [rust-analyzer/rust-analyzer#9284] opened 2021-06-15 07:46 UTC
Updating the `rust-analyzer` nightly distribution currently does not work in the Visual Studio Code Rust Analyzer Extension.

From the `OUTPUT` tab:
```
ERROR [15/06/2021, 15:42:43]: Bootstrap error [TypeError: Only absolute URLs are supported
	at getNodeRequestOptions (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:20682:9)
	at c:\Users\harry\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:20787:19
	at new Promise (<anonymous>)
	at Object.fetch (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:20784:9)
	at c:\Users\harry\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22713:36
	at downloadFile (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22714:7)
	at c:\Users\harry\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22693:15
	at C._withProgress (<path redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:44110)
	at C.withProgress (<path redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:43864)
	at Object.withProgress (<path redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:30045)
	at Object.download (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22687:45)
	at <path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:23057:19
	at downloadWithRetryDialog (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:23095:26)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async getServer (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:23056:5)
	at async bootstrapServer (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22957:18)
	at async bootstrap (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22893:18)
	at async tryActivate (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22778:24)
	at async activate (<path redacted>\.vscode\extensions\matklad.rust-analyzer-0.3.638\out\src\main.js:22769:5)]
```

**Comment by lnicola** [comment] 2021-06-15 07:50
Duplicate of #9280.

**Comment by HTG-YT** [comment] 2021-06-15 07:56
I updated the extension and now I am getting this error: `Bootstrap error [Error: ENOENT: no such file or directory, open 'C:\<path>\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc6e0f2e9b82']` :thinking:

**Comment by lnicola** [comment] 2021-06-15 08:01
`6e0f2e9b82` huh?

CC @wxb1ank ^.

**Comment by SomeoneToIgnore** [comment] 2021-06-15 08:18
In my case, the error is a bit different (macOs), but some similarity with the hash-on-the-end is definitely there:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/2690773/122018174-48e5b180-cdcb-11eb-9e10-69489e5a8f30.png">

**Comment by simbiont666** [comment] 2021-06-15 08:25
Have the same @SomeoneToIgnore

**Comment by lnicola** [comment] 2021-06-15 08:27
> In my case, the error is a bit different (macOs)

That sounds like it's already running?

**Comment by simbiont666** [comment] 2021-06-15 08:31
`rm rust-analyzer-x86_64-apple-darwin*` 
in ../matklad.rust-analyzer directory solved the problem for now..

**Comment by SomeoneToIgnore** [comment] 2021-06-15 08:33
I don't think so, at least custom r-a commands are not registered in VSCode by that time, I also don't see any `rust-analyzer` status in the VSCode footer:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2690773/122020411-6c116080-cdcd-11eb-910e-4b8193930c85.png">

Nothing in the `ps` output too.

I only start r-a when it happens.
First, it notices the client update and downloads it (the very first start, no updates on consequent restarts ofc) and then tries to update the server binary.

Before the client updates, it was able to do so and start the server, but not now.

**Comment by RagibHasin** [comment] 2021-06-15 09:04
> 
> 
> I updated the extension and now I am getting this error: `Bootstrap error [Error: ENOENT: no such file or directory, open 'C:\C:\Users\<user>\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc6e0f2e9b82']` 🤔

same here

**Comment by wxb1ank** [comment] 2021-06-15 09:28
This is a bit unexpected. It looks a lot like #8956, but the purpose of #8951 was fixing that. My recent client PR, #9281, doesn't touch this either. I'm tired and need to sleep; I'll look at this later in the morning.

**Comment by wxb1ank** [comment] 2021-06-15 09:45
Ah, I think I've got it, actually. Looks like another regression from #8956 :/. `Uri.path` is used in many places where `Uri.fsPath` should be. (Why is `vscode.Uri` so confusing?) I need to test to confirm such a Ctrl+R job would resolve this particular error.

I'll draft a PR for this issue along with [another bugfix](https://github.com/rust-analyzer/rust-analyzer/pull/8951#discussion_r651570446) in #8956.

**Comment by Xunjin** [comment] 2021-06-15 10:37
A manual fix which worked for me was deleted all targets in noted folder and restart VSCode, hope it helps until we have a solution.

PS: it's a dirty workaround, sorry :/

**Comment by wxb1ank** [comment] 2021-06-15 18:26
@HTG-YT, @SomeoneToIgnore, and anyone else with this issue: would you mind testing #9292? For convenience, I have attached the compiled VSIX.
[rust-analyzer.zip](https://github.com/rust-analyzer/rust-analyzer/files/6657838/rust-analyzer.zip)

**Comment by AaronKutch** [comment] 2021-06-15 18:31
It gives the `C:\C:\...` error to me. I'm not sure if I installed it properly, I have never used a VSIX before now.

**Comment by wxb1ank** [comment] 2021-06-15 18:42
> It gives the `C:\C:\...` error to me.

Weird... it works for me on Windows.

> I'm not sure if I installed it properly, I have never used a VSIX before now.

I'm not at my computer RN, but the process is something like `Extensions tab > small square dropdown > Install extension from VSIX... > reload VS Code`.

**Comment by AaronKutch** [comment] 2021-06-15 18:45
Before it asks me to download the server, it asks me to update the extension. Is it overwriting itself with the broken version?

**Comment by wxb1ank** [comment] 2021-06-15 19:08
> Is it overwriting itself with the broken version?

Yeah, funnily enough. After updating you *should* find that, in the VS Code Extensions tab, `rust-analyzer` v0.3.639 is installed.

> I got it to work by exiting out the update request, then the download server option pops up and then it works for me

So, the update request doesn't work then? That the language server can be downloaded is fine, but the intention of #9292 is to fix update functionality for the VS Code extension.

**Comment by SomeoneToIgnore** [comment] 2021-06-15 19:19
I have not understood how to test the server download.
I've triggered the "Install from VSIX..." menu, selected the custom plugin provided and reloaded the editor.

Then, if I disable `"rust-analyzer.updates.channel": "nightly",` item in the settings, no download happens (since I have the latest version).
If I enable it, I immediately get the other plugin version (nightly) which gets downloaded and fails for me, since it has the FS issue.

**Comment by wxb1ank** [comment] 2021-06-15 19:30
> I have not understood how to test the server download.

Sorry for the confusion; it was a poor explanation. Please see my updated reply with the VSIX attached.

**Comment by SomeoneToIgnore** [comment] 2021-06-15 19:33
No worries, I have not spotted that indeed there's a different plugin version after the update.
Alas, the server binary functionality is still not working for me:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/2690773/122112628-b6c0c600-ce29-11eb-9fb5-e7d5b106ac7a.png">

**Comment by wxb1ank** [comment] 2021-06-15 19:50
> No worries, I have not spotted that indeed there's a different plugin version after the update.
> Alas, the server binary functionality is still not working for me:

I'm a little confused; it looks like you now have 0.3.639 installed, which is the known broken version. If you updated to 0.3.639 from my VSIX (marked as version 0.2.637), that means #9292 worked for you.

**Comment by SomeoneToIgnore** [comment] 2021-06-15 19:53
Guess it works for me indeed then, sorry, late evening here and I'm still working on something else.

**Comment by wxb1ank** [comment] 2021-06-15 19:56
No worries :). It's a confusing procedure because the end result is that you've reinstalled the broken version.

**Comment by HTG-YT** [comment] 2021-06-16 02:36
@wxb1ank the plugin I installed from the `.vsix` is marked as version `0.3.640`, in which *it did work correctly*. Thanks!

**Comment by SomeoneToIgnore** [comment] 2021-06-16 06:01
Works for me on mac too, thank you!

HTG-YT is from Windows, so looks like we have both forms of path URLs tested and can safely close this issue.

Feel free to comment if any related issues occur.

**Closed by SomeoneToIgnore** 2021-06-16 06:01 UTC

**Comment by HTG-YT** [comment] 2021-06-16 06:29
> 
> 
> Works for me on mac too, thank you!
> 
> HTG-YT is on Windows judging from the error trace, so looks like we have both forms of path URLs tested and can safely close this issue.
> 
> Feel free to comment if any related issues occur.

Yes, I am indeed on Windows. It's great to see this issue fixed! Thanks all of you for your precious time and hard work.
