### ISSUE TITLE
Macros disallow item imports in test functions

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#8567] opened 2021-04-18 18:23 UTC
> rust-analyzer version: 2021-04-12-83-g19fc1f333

I'm writing a test in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/lib.rs

```rust
#[test]
fn feature() {
    RootDatabase$0

    let z = 3;
    // todo!()
}
```

and using an assist to import the `RootDatabase`

with `todo!` commented out, it works:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/2690773/115156277-29146480-a08c-11eb-95d0-11ad0a20e3ba.png">

but when I uncomment `todo!`, it stops working:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/2690773/115156291-392c4400-a08c-11eb-9534-613a6f37593f.png">

**Comment by jonas-schievink** [comment] 2021-04-18 18:29
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8519

**Closed by jonas-schievink** 2021-04-18 18:29 UTC
