### ISSUE TITLE
Incorrect mismatched-arg-count with nalgebra 0.26.2's Points

### ISSUE THREAD

**Issue by lasa01** [rust-analyzer/rust-analyzer#8896] opened 2021-05-20 15:01 UTC
The following code causes incorrect mismatched-arg-count, cargo check reports no problems.

`Cargo.toml`:
```toml
[dependencies]
nalgebra = "0.26.2"
```

`src/main.rs`:
```rust
use nalgebra::Point3;

fn main() {
    let _ = Point3::new(1.0, 2.0, 3.0);
}
```

Error: `Expected 1 argument, found 3 (rust-analyzer(mismatched-arg-count))`

Downgrading nalgebra to `0.25.*` or below fixes the issue.

Same happens with every Point* type except Point1, rust-analyzer thinks the constructor should have 1 argument.

Running on VSCode on Windows 10 with `rust-analyzer version: b82458818 2021-05-17 stable`.
Also tested on `rust-analyzer version: 764241e38 2021-05-20 nightly`, same issue.

**Comment by lnicola** [comment] 2021-05-20 15:02
Duplicate of #8654

**Closed by lnicola** 2021-05-20 15:02 UTC
