### ISSUE TITLE
Modules in paths are highlighted inconsistently

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#6842] opened 2020-12-12 14:05 UTC
![image](https://user-images.githubusercontent.com/23638587/101985952-f4654c00-3c58-11eb-9b77-88974be79aa9.png)

`ast::` is two different colors; it should be the same in both (maybe green is correct?).

https://github.com/rust-lang/rust/blob/c3ed6681ff8d446e68ce272be4bf66f4145f6e29/src/librustdoc/clean/types.rs#L620-L628

**Comment by lnicola** [comment] 2020-12-20 14:48
I can't reproduce this outside of `rustc`.

What do you get if you choose "Inspect Editor Tokens and Scopes" and move the cursor over the two `ast` instances?

**Comment by jyn514** [comment] 2020-12-20 16:52
> What do you get if you choose "Inspect Editor Tokens and Scopes" 

This hangs for me. How long does it normally take? It's been over a minute.

**Comment by jyn514** [comment] 2020-12-20 16:56
If it helps, 'go to definition' on `ast` correctly points to https://github.com/rust-lang/rust/blob/2ad5292aea6328113b55968b4322528d48261316/compiler/rustc_ast/src/lib.rs#L41 for both `ast` snippets (although it also shows https://github.com/rust-lang/rust/blob/2ad5292aea6328113b55968b4322528d48261316/src/tools/clippy/clippy_lints/src/utils/sugg.rs#L139 for some reason).

**Comment by lnicola** [comment] 2020-12-20 17:03
It should be instantaneous. It shows a pop-up with highlight information, without even calling into the LSP server.

**Comment by jyn514** [comment] 2020-12-20 17:06
Well it is definitely not instantaneous for me :laughing: in case it matters, I'm using VSCode Remote-SSH.

**Comment by jyn514** [comment] 2020-12-20 17:07
>  in case it matters, I'm using VSCode Remote-SSH.

this is unrelated, it works on a different project, just not rust-lang/rust.

**Comment by lnicola** [comment] 2020-12-20 17:09
I think @jonas-schievink might be able to test this.

**Comment by jonas-schievink** [comment] 2020-12-21 14:26
Can reproduce. None of the `ast` tokens resolve correctly for me. In fact, none of the `extern crate`s in librustdoc resolve. Is that the issue here? Do I have to do anything special for that to work, @jyn514?

(naturally, all tokens in the `from_ast` function header types are of type `unresolvedReference`, and the inconsistent colors are due to the textmate grammar)

The output panel contains this, normally this only breaks paths to libcore, but maybe it decided to break rustc crates this time:

```
[ERROR project_model::workspace] cyclic deps: cargo_test_support(CrateId(160)) -> cargo(CrateId(144))
[ERROR project_model::workspace] cyclic deps: rustc_std_workspace_core(CrateId(1142)) -> core(CrateId(226))
[ERROR project_model::workspace] cyclic deps: wasi(CrateId(1664)) -> rustc_std_workspace_alloc(CrateId(1141))
```

This is on rust-lang/rust@1e88a1769f69f944e16cba13ba174c1d6e494b36 with rust-analyzer 2020-12-14.

**Comment by jyn514** [comment] 2020-12-21 14:35
> In fact, none of the extern crates in librustdoc resolve.

Ahh, that's probably it - those crates are loaded from the sysroot, not from cargo. Didn't rust-analyzer add support for rustc_private recently? Or am I misremembering? If it helps, you don't need to use the toolchain directly (and it would be hard because it's a stage 1 build), you can just look at the sources in compiler/.

**Comment by jonas-schievink** [comment] 2020-12-21 15:02
Oh, yeah, if they're from the sysroot then that explains it. I'm not sure how our support looks there.

**Comment by jonas-schievink** [comment] 2021-06-26 14:54
This can be fixed by setting `"rust-analyzer.rustcSource": "./Cargo.toml",` in the rust-lang/rust workspace. I don't think that's the correct path, but stage0 does not download rustc-src, so you'd have to manually install the beta compiler and point it there.

Closing as fixed in any case!

**Closed by jonas-schievink** 2021-06-26 14:54 UTC
Labels: S-actionable

**Comment by jyn514** [comment] 2021-08-16 02:19
> I don't think that's the correct path, but stage0 does not download rustc-src, so you'd have to manually install the beta compiler and point it there.

This seems wrong, it should use the in-tree sources, not the sources of the beta compiler. I think `./Cargo.toml` is correct.

Thanks for the workaround :) I'll add this to the dev-guide.

**Comment by jyn514** [comment] 2021-08-16 02:22
> That seems wrong, it should use the in-tree sources, not the sources of the beta compiler. I think ./Cargo.toml is correct.

Err, I guess it depends if it's building with stage 0 or stage 1. But I doubt there's any way to get rust-analyzer to know about both, so hard-coding stage1 seems fine, that's the one `download-rustc` uses and what I'd expect most rustdoc contributors to be using.

**Comment by jyn514** [comment] 2021-08-16 02:24
> Err, I guess it depends if it's building with stage 0 or stage 1. 

Wait no, I was right the first time. The sysroot for stage 0 tools is newly built compiler. https://github.com/rust-lang/rust/blob/2bd17c1d43bba43412cc2f051323a279d6751e43/src/bootstrap/builder.rs#L1080
