### ISSUE TITLE
textDocument/references does not work with traits.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#4179] opened 2020-04-28 00:10 UTC
```
pub trait Tr {
    fn f(&self);
}

pub struct S;

impl Tr for S {
    fn f(&self) {
        println!("Hello, world!");
    }
}

impl S {
    pub fn g(&self) {
        println!("Hello, world!");
    }
}

pub fn h() {
    let s = S;
    s.f();
    s.g();
}
```

`textDocument/references` on `f` will find not find the use in `h`.

`textDocument/references` on `g` _will_ find the use in `h`.

**Comment by matklad** [comment] 2020-04-29 07:51
I think this is the same root cause as https://github.com/rust-analyzer/rust-analyzer/issues/4188, not handing visbility. Closing in favor of that.

**Closed by matklad** 2020-04-29 07:51 UTC
