### ISSUE TITLE
Rename doesn't affect at-bindings

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-analyzer/rust-analyzer#11543] opened 2022-02-24 01:02 UTC
In this situation, with the cursor represented as `<|>`...
```rust
fn main() {
    match (false, false) {
        (true, should_foo) | (false, should_foo @ false) => {
            if should_<|>foo {
                panic!();
            }
        },

        _ => todo!(),
    }
}
```

I tried to rename `should_foo` to `should_panic`. This updated the binding in the first pattern, but not the second:
```rust
fn main() {
    match (false, false) {
        (true, should_panic) | (false, should_foo @ false) => {
            if should_<|>panic {
                panic!();
            }
        },

        _ => todo!(),
    }
}
```

... which causes compilation to fail:
```
error[E0408]: variable `should_foo` is not bound in all patterns
 --> src/main.rs:3:9
  |
3 |         (true, should_panic) | (false, should_foo @ false) => {
  |         ^^^^^^^^^^^^^^^^^^^^           ---------- variable not in all patterns
  |         |
  |         pattern doesn't bind `should_foo`

error[E0408]: variable `should_panic` is not bound in all patterns
 --> src/main.rs:3:32
  |
3 |         (true, should_panic) | (false, should_foo @ false) => {
  |                ------------    ^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern doesn't bind `should_panic`
  |                |
  |                variable not in all patterns
```

**rust-analyzer version**: `db2a7087b 2021-12-13 stable` (unfortunately, I'm using VSCodium, so I don't really have a good way to test a newer version right now)

**rustc version**:
```
rustc 1.60.0-nightly (f624427f8 2022-02-06)
binary: rustc
commit-hash: f624427f8771c00819684c783bb841bf72095704
commit-date: 2022-02-06
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

**Comment by jonas-schievink** [comment] 2022-02-24 03:53
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8860, I think

**Comment by Veykril** [comment] 2022-03-07 16:51
Yes, that should be fixed now!

**Closed by Veykril** 2022-03-07 16:51 UTC
Labels: E-hard, C-bug, A-ide
