### ISSUE TITLE
Unresolved-import error but nothing is wrong

### ISSUE THREAD

**Issue by HungPham3112** [rust-analyzer/rust-analyzer#10465] opened 2021-10-06 03:24 UTC
I use` coc-rust-analyzer` for checking my rust file. 

```
use rand::Rng;
use std::io;
use std::cmp::Ordering;

fn main() {
    println!("Welcome to my game!!!");
    let random_number: u32 = rand::thread_rng().gen_range(1..101);
    loop {
        let mut guess = String::new();
        println!("Guess a number between 1 and 100");
        io::stdin()
            .read_line(&mut guess)
            .expect("Cannot read_line");

        let guess: u32 = match guess.trim().parse() {
            Ok(num) => num,
            Err(_) => {
                println!("You must type a number");
                continue;
            }
        };
        match guess.cmp(&random_number) {
            Ordering::Less => println!("Higher!!!"),
            Ordering::Greater => println!("Lower!!!"),
            Ordering::Equal => {
                println!("You win!!!");
                break;
            }
        }
    }
}
```

However, it highlight `use rand::Rng` but the code still run normally.

![bandicam 2021-10-06 10-21-02-390](https://user-images.githubusercontent.com/75968004/136135657-74662f63-cd5b-43c1-9961-881b479013bc.gif)

I also add dependencies in Cargo.toml

![image](https://user-images.githubusercontent.com/75968004/136135826-85ab63fc-162a-4594-9b1c-4d76857d2f6a.png)

**Comment by Veykril** [comment] 2021-10-07 19:52
This works fine for me and I don't see why it shouldn't. Do you still encounter this after restarting your editor session?

**Comment by HungPham3112** [comment] 2021-10-08 04:30
I restarted my editor many time but it still error. Today, I open it and it doesn't happen anymore. That's a miracle!!!

**Comment by Veykril** [comment] 2021-11-25 15:24
Closing this as the problem is with the `test` cfg gate which is tracked in other issues already

**Closed by Veykril** 2021-11-25 15:24 UTC
Labels: S-unactionable, C-bug
