### ISSUE TITLE
signatureHelp doesn't work depending on the code that follows the opening parentheses

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#4751] opened 2020-06-05 07:24 UTC
```rust
fn main() {
    let foo = Some(42);
    // works:
    // foo.map(
    if true {}
    // stops working:
    // foo.map(
}
```

**Comment by kjeremy** [comment] 2020-06-07 22:27
I can't reproduce with

```rust
fn main() {
    let foo = Some(42);
    if true {}
    foo.map(<|>)
}
```

**Comment by oblitum** [comment] 2020-06-08 03:33
@kjeremy though you're not replicating the use case as requested.

**Comment by kjeremy** [comment] 2020-06-08 08:05
Am I misinterpreting your instruction?

**Comment by oblitum** [comment] 2020-06-08 11:40
@kjeremy you're either letting the editor auto pair parentheses or you're expanding snippet for that. My example doesn't have that, it's just bare typing an opening parentheses without having it auto-closed.

**Comment by kjeremy** [comment] 2020-06-08 13:14
I still can't repeat this setting `editor.autoClosingbrackets` to `never` and typing `foo.map(<|>`.

**Comment by oblitum** [comment] 2020-06-08 17:04
I don't use vscode. But I'm not sure how it should make a difference at all, so I'm not believing clients are at issue here. I'm using coc-rust-analyzer and this is [the full LSP communication log for the issue](https://gist.githubusercontent.com/oblitum/fa846f53275b237b45cdf3259729518a/raw/33d646613e68d4bf478ac6bcf7eeca1e74ab9d63/CocInfo), where the signatureHelp fails at the end with no results.

For this case I started with:

```rust
fn main() {
    let _x = Some(42);
}
```

And just typed "_x.map(":

```
fn main() {
    let _x = Some(42);
    _x.map(
}
```

**Comment by matklad** [comment] 2020-07-11 20:44
Seems like vim and vscode interpret offset differently?

VS Code:

```

[Trace - 10:42:08 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/matklad/tmp/hello/src/main.rs",
        "version": 12
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 10
                },
                "end": {
                    "line": 2,
                    "character": 10
                }
            },
            "rangeLength": 0,
            "text": "("
        }
    ]
}
[Trace - 10:42:08 PM] Sending request 'textDocument/signatureHelp - (59)'.
Params: {
    "textDocument": {
        "uri": "file:///home/matklad/tmp/hello/src/main.rs"
    },
    "position": {
        "line": 2,
        "character": 11
    },
    "context": {
        "isRetrigger": false,
        "triggerCharacter": "(",
        "triggerKind": 2
    }
}
```

VIm

```
[Trace - 1:46:54 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 7,
        "uri": "file:///home/francisco/Projects/samples/rust/src/main.rs"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 10
                },
                "end": {
                    "line": 2,
                    "character": 10
                }
            },
            "rangeLength": 0,
            "text": "("
        }
    ]
}
[Trace - 1:46:54 PM] Sending request 'textDocument/signatureHelp - (9)'.
Params: {
    "textDocument": {
        "uri": "file:///home/francisco/Projects/samples/rust/src/main.rs"
    },
    "position": {
        "line": 2,
        "character": 12
    }
}
```

Note that offests for changes are the same, but offsets for signature help are different.

**Comment by oblitum** [comment] 2020-07-11 20:48
Yep, I noticed. Now, I don't have any idea regarding what's the proper fix in this case.

cc @chemzqm, @fannheyward.

**Comment by oblitum** [comment] 2020-07-11 20:50
fwiw, I notice this issue with coc-rust-analyzer in many other situations, meaning that it isn't rare to happen.

**Comment by kjeremy** [comment] 2020-07-11 20:59
I see in the client capabilities:

```
 "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
```

We do not support label offset. I would make sure that it's not tripping up over that,

**Comment by oblitum** [comment] 2020-07-11 21:17
Good point, though label offsets are the best route to attain highlight of current parameter for signatureHelp, see discussion about the issues that exist before it was introduced:

* https://github.com/neoclide/coc.nvim/issues/269
* https://github.com/neoclide/coc.nvim/issues/269#issuecomment-447619288
* https://github.com/microsoft/language-server-protocol/issues/640

**Comment by kjeremy** [comment] 2020-07-11 21:57
Right. In thinking about it more I don't think the label offsets would impact you since we aren't seeing the reply.

**Comment by fannheyward** [comment] 2020-07-14 11:07
This is a client issue, has been fixed in https://github.com/fannheyward/coc-rust-analyzer/issues/321

**Closed** 2020-07-14 11:08 UTC
