### ISSUE TITLE
Unresolved macro on re-export (`mark::hit!`)

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7515] opened 2021-02-02 07:25 UTC
Spotted in `crates/hir_def/src/nameres/path_resolution.rs`:

![image](https://user-images.githubusercontent.com/308347/106566164-9bb77e80-6538-11eb-9eb0-e5795b7442af.png)

![image](https://user-images.githubusercontent.com/308347/106566173-9f4b0580-6538-11eb-8cdd-d8c11a4146f1.png)

We emit the diagnostic, but hover and go to definition actually work.

**Comment by lnicola** [comment] 2021-02-02 07:27
We actually point to `_hit`, of which `hit` which is a re-export:

```rust
pub use _hit as hit;
```

**Comment by edwin0cheng** [comment] 2021-02-02 07:43
But it works in the same file line 66 ?! 

![Screenshot](https://user-images.githubusercontent.com/11014119/106567823-61b49f80-656d-11eb-8506-5c679e0724be.png)

**Comment by lnicola** [comment] 2021-02-02 07:45
It also works if you add in another call:

![image](https://user-images.githubusercontent.com/308347/106568014-5ba5cb00-653b-11eb-9f64-e383e42f2ca3.png)

I think we might need an `A-nameres` label.

**Comment by jonas-schievink** [comment] 2021-02-02 13:38
Caused by https://github.com/rust-analyzer/rust-analyzer/pull/7506

Fixed by https://github.com/rust-analyzer/rust-analyzer/pull/7516

It only happens in blocks whose parents contain no macro invocations or inner items because of the optimization added in https://github.com/rust-analyzer/rust-analyzer/pull/7506/commits/b4aa860cac98d69fe4e38602904a6e9e6569e5a6.

I was not able to derive a test case, even though this is very easy to reproduce in-editor:

```rust
macro_rules! m {
    () => {};
}

fn f() {
    {
        m!(a);
    }
}
```

(this is from Zulip here: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/BlockDefMap/near/224746034)

**Comment by lnicola** [comment] 2021-02-02 13:47
Verified fixed. Do you want to keep this open while you figure why it works in a test?

**Comment by jonas-schievink** [comment] 2021-02-02 13:50
I'd also be fine with closing this. It will only become relevant when the user-facing body_def_map changes (finally) land.

**Closed** 2021-02-02 13:52 UTC
Labels: A-macro, S-actionable
