### ISSUE TITLE
Handle visibility (privacy) in field/method completion

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#824] opened 2019-02-13 20:46 UTC
We currently don't handle visibility at all. This means that we provide lots of private fields and methods for completions outside of modules where you can actually access them. We should fix this. I think the basic steps for this will be:
 - add visibility to the HIR for `StructField` and `Function` (probably also `Const`, `Type` etc.)
 - implement the code to check whether a field/method is visible from a certain module (basically, if the item is private, are we in the module where it's defined or a submodule? notably, for impl items, the privacy is determined by the module containing the impl, not the one containing the type, I think)
 - filter out completions that are not visible in `complete_dot.rs`

A different, but related issue is handling visibility of items, for example when doing glob imports.

**Comment by sirgl** [comment] 2019-02-14 04:24
I think, that it would be better not to filter out items, but make it less relevant and sort completion results by relevancy. Very often I forget to add pub and try to complete it somewhere else, so it is not very convenient to go there and add visibility manually. I think, that assist to add pub for not visible entry should be created. It would be much better user experience, I think

**Comment by DJMcNab** [comment] 2019-02-14 06:41
But do filter it out for external crates?

**Comment by flodiebold** [comment] 2019-02-14 07:58
It probably makes sense to treat the local source roots differently than the other ones (i.e. provide private items only from crates you can edit).

**Comment by pksunkara** [comment] 2020-11-01 17:10
#2830 seems a duplicate of this.

**Comment by jonas-schievink** [comment] 2021-07-22 16:07
Hmm, this seems to be mostly implemented now. Is anything missing here?

**Comment by Veykril** [comment] 2021-07-22 17:06
We still got two visibility related FIXMEs here https://github.com/rust-analyzer/rust-analyzer/blob/444679f202742c8fd00e9d1c7fddfaa9a067e640/crates/ide_completion/src/completions/dot.rs#L59-L78

**Closed** 2021-07-23 18:28 UTC
Labels: A-completion, S-actionable
