### ISSUE TITLE
Feature request: Add field assist

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#10279] opened 2021-09-19 08:20 UTC
```Rust
struct Foo {
    field1: i32,
}

fn main() {
    let foo = Foo { field1: 42 };
    foo.field2/*add field assist requested here*/
}
```
The following would happen:
```Rust
struct Foo {
    field1: i32,
    field2: /*editor focus and cursor jumps here*/,
}
```

Motivation: It can be tedious to jump to the type definition and type out the field name.
The user might not even remember the name of the type, so has to click on "go to type definition" on `foo` first.

**Comment by Veykril** [comment] 2021-09-19 10:01
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4563

**Closed by Veykril** 2021-09-19 10:01 UTC
