### ISSUE TITLE
Slow startup of semantic highlighting, autocomplete, formatting, etc

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#4586] opened 2020-05-23 20:35 UTC
Upon loading a project, I see rust-analyzer check all my dependencies (which finishes quickly), but it takes another 10+ seconds for semantic highlighting to kick in, formatting to work (really annoying with format on save, as it prevents the save from working until everything finishes loading), auto complete to work, type hints to work, etc.

**Comment by Keavon** [comment] 2020-05-23 21:14
I believe it also requires that you switch to another tab and back before you see the syntax highlighting. I didn't realize that and I've spent minutes on several occasions waiting for it to show up and thought it was bugged, but eventually it somehow started working again. It should definitely be fixed to refresh on the same file as soon as the highlighting is ready, without requiring the user to switch tabs to refresh it. Showing the progress in the status bar would also be an improvement.

**Comment by matklad** [comment] 2020-05-24 08:42
dupe of #1650 -- our initial loading is indeed slower than it should be, and as of yet uncached.

**Closed by matklad** 2020-05-24 08:42 UTC

**Comment by Keavon** [comment] 2020-05-24 08:49
@matklad Does that issue #1650 also include the detail I wrote about failing to show syntax highlighting upon loading until switching to another tab and back, and the lack of status bar indication that this is still occurring? Should I post that as a separate issue?

**Comment by matklad** [comment] 2020-05-24 10:21
That would be https://github.com/microsoft/vscode-languageserver-node/issues/576
