### ISSUE TITLE
unresolved macro `phf_map!`  

### ISSUE THREAD

**Issue by Zerowalker** [rust-analyzer/rust-analyzer#10238] opened 2021-09-14 17:06 UTC
main.rs
```
use phf::phf_map;

pub static A: phf::Map<&'static str, &'static str> = phf_map! {
    "a"=> "b"
};

fn main() {}
```

cargo.toml
```
[dependencies]
phf = { version = "0.10.0", features = ["macros"] }
```

Result: unresolved macro
Expected: no error

Same results with proc macro enabled or disabled in rust analyzer.
tested on stable release and nightly `v0.3.744`

It seems to sometime not throw an error, but i can't reproduce it, so it might just be that there's a delay before it actually shows sometimes?.

Project will build just fine.

**Comment by lnicola** [comment] 2021-09-14 17:15
Looks like we still don't support `proc_macro_hack`.

**Comment by lnicola** [comment] 2021-09-14 17:17
Duplicate of #9606 and #6835.

**Closed by lnicola** 2021-09-14 17:17 UTC
Labels: A-macro, S-actionable, C-bug
