### ISSUE TITLE
Semantic highlighting: Crate name is incorrectly marked as function when importing a function that has the same name

### ISSUE THREAD

**Issue by KSXGitHub** [rust-analyzer/rust-analyzer#8850] opened 2021-05-16 07:34 UTC
## What happened?

![screenshot: importing a function named "terminal_size" from crate "terminal_size" causes the name of the crate to be incorrectly highlighted with color of a function](https://user-images.githubusercontent.com/11488886/118389291-78ca5980-b653-11eb-9c85-b19aad9ca242.png)

## System Information

```text
rust-analyzer fd109fb58 2021-05-10 dev
```

VS Code extension: matklad.rust-analyzer v0.2.591

**Comment by Veykril** [comment] 2021-05-23 17:14
duplicate of #7763

**Closed by Veykril** 2021-05-23 17:14 UTC
Labels: S-actionable
