### ISSUE TITLE
Incorrect function declaration display when using macros

### ISSUE THREAD

**Issue by zhongjn** [rust-analyzer/rust-analyzer#7042] opened 2020-12-26 08:04 UTC
Hi everyone,

I came across this problem while playing with tokio, as you can see in the picture, there are some display problems with spaces.
![tokio](https://user-images.githubusercontent.com/34117545/103147577-e273c500-4791-11eb-965d-ca9d37727a41.png)

After some investivation I found that it's related to macro. I believe this would be the smallest code piece to reproduce:
![min](https://user-images.githubusercontent.com/34117545/103147699-cb81a280-4792-11eb-990f-c4f0e848da75.png)

I'm willing to solve this issue, but I'm not very familiar with the code base. If someone could tell me which place I should look at, that would be great.

**Comment by Veykril** [comment] 2020-12-26 09:34
This is a known issue with macro expansion not having whtiespace between tokens, see #6588. I don't think there is a proper solution to this yet in regards to rendering those.

**Comment by flodiebold** [comment] 2020-12-26 10:00
Yeah, this is a duplicate of #2765.

**Closed by flodiebold** 2020-12-26 10:00 UTC
