### ISSUE TITLE
Constants used as array size [T; N] are reported as unresolvedReference

### ISSUE THREAD

**Issue by f32by** [rust-analyzer/rust-analyzer#8980] opened 2021-05-25 00:47 UTC
VSCode extension: 0.3.613 (Nightly)
rust-analyzer version: 6d473c0a8 2021-05-25 nightly

<img width="895" alt="CleanShot 2021-05-25 at 08 41 47@2x" src="https://user-images.githubusercontent.com/12209857/119423315-96737f00-bd35-11eb-9fc2-db58b2996ac4.png">

**Comment by Veykril** [comment] 2021-05-25 08:09
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7432

**Closed by Veykril** 2021-05-25 08:09 UTC
