### ISSUE TITLE
Generating `impl` block generate $0 symbol instead of placing the cursor there.

### ISSUE THREAD

**Issue by oOBoomberOo** [rust-analyzer/rust-analyzer#7124] opened 2021-01-01 17:28 UTC
OS: `Windows 10`
editor: `VS Code 1.52.1`
rust-analyzer version: `2020-12-28 (1d53075)`

The issue:
When generating an impl block via rust-analyzer it will generate `$0` symbol along with the impl block
![image](https://user-images.githubusercontent.com/26600816/103443338-e1123300-4c90-11eb-8ac7-b014387c16f0.png)
![image](https://user-images.githubusercontent.com/26600816/103443346-ff782e80-4c90-11eb-934b-b2315fc5bb21.png)
And I can only assume that it's supposed to be a marker to tell where the cursor should be moved to.

This also affected other generation such as `derive` block
![image](https://user-images.githubusercontent.com/26600816/103443373-4a924180-4c91-11eb-9136-ae41947a8348.png)

**Comment by lnicola** [comment] 2021-01-01 17:31
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7037.

**Closed by lnicola** 2021-01-01 17:31 UTC
