### ISSUE TITLE
Hovering Over Items Doesn't Work in Nested Crates

### ISSUE THREAD

**Issue by HTG-YT** [rust-analyzer/rust-analyzer#6605] opened 2020-11-22 09:38 UTC
I have a project with file structure like this:
![image](https://user-images.githubusercontent.com/39023054/99900164-2e41d300-2ce9-11eb-9376-8bff04fcdfb9.png)

The problem is that when I hover over definitions of Rust source files in the root `src` folder (not the one in `lightsaber_bootlaoder`), it works as expected.

For some unknown reason, when I hover over definitions of Rust source files in the `src` folder in `lightsaber_bootloader`, no information popped up. It works at a bare minimum in `main.rs` in that folder:
![image](https://user-images.githubusercontent.com/39023054/99900250-706b1480-2ce9-11eb-92db-601fcbea7741.png)

And everything else, straight up doesn't work.

**Comment by bjorn3** [comment] 2020-11-22 09:43
I assume you don't use a cargo workspace. Rust-analyzer runs `cargo metadata` in the project root. Because `lightsaber_bootloader` is not part of the workspace, `cargo metadata` will ignore it and thus rust-analyzer won't know about it either. You can set `"rust-analyzer.linkedProjects": ["lightsaber_bootloader/Cargo.toml"]` to also run `cargo metadata` for `lightsaber_bootloader`.

**Comment by HTG-YT** [comment] 2020-11-22 10:30
I am actually using workspaces

**Comment by HTG-YT** [comment] 2020-11-23 02:08
Nevermind I figured it out, I needed to have the module included ._.

**Comment by flodiebold** [comment] 2020-11-23 09:46
Maybe we could show some kind of big warning banner in such cases, with a button to automatically insert the `mod` statement...

**Comment by HTG-YT** [comment] 2020-11-23 11:01
Yes, that's what I used to have when I was using IntelliJ Rust

**Comment by jonas-schievink** [comment] 2020-11-24 18:14
We can emit an "unused" diagnostic spanning the whole file, like we do for code that's `#[cfg]`'d out.

**Comment by lnicola** [comment] 2020-12-21 15:31
@flodiebold dupe of #6377?

**Comment by flodiebold** [comment] 2020-12-21 15:50
Yeah, I'd say so.

**Closed by flodiebold** 2020-12-21 15:50 UTC
Labels: A-diagnostics, S-actionable
