### ISSUE TITLE
rust-analyzer not compiling (build errors)

### ISSUE THREAD

**Issue by jasonwilliams** [rust-analyzer/rust-analyzer#2038] opened 2019-10-20 11:54 UTC
```
λ cargo xtask install
    Updating crates.io index
    Updating git repository `https://github.com/rust-lang/chalk.git`
  Downloaded pico-args v0.3.0
  Downloaded serde v1.0.101
  Downloaded either v1.5.3
  Downloaded serde_derive v1.0.101
  Downloaded bitflags v1.2.1
  Downloaded proc-macro2 v1.0.5
   Compiling proc-macro2 v1.0.5
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.5
   Compiling winapi v0.3.8
   Compiling byteorder v1.3.2
   Compiling serde v1.0.101
   Compiling bitflags v1.2.1
   Compiling either v1.5.3
   Compiling pico-args v0.3.0
   Compiling itertools v0.8.0
   Compiling base64 v0.10.1
   Compiling quote v1.0.2
   Compiling winapi-util v0.1.2
   Compiling same-file v1.0.5
   Compiling walkdir v2.2.9
   Compiling serde_derive v1.0.101
   Compiling ron v0.5.1
   Compiling xtask v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\xtask)
    Finished dev [unoptimized + debuginfo] target(s) in 40.35s
     Running `target\debug\xtask.exe install`

will run: cargo install --path crates/ra_lsp_server --locked --force
  Installing ra_lsp_server v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_lsp_server)
    Updating crates.io index
  Downloaded flexi_logger v0.14.4
  Downloaded once_cell v1.2.0
  Downloaded serde_json v1.0.41
  Downloaded rand v0.7.2
  Downloaded backtrace v0.3.39
  Downloaded arrayvec v0.5.1
  Downloaded salsa v0.13.2
  Downloaded smol_str v0.1.15
  Downloaded arrayvec v0.4.12
  Downloaded stacker v0.1.6
  Downloaded ra_vfs v0.5.0
  Downloaded indexmap v1.2.0
  Downloaded salsa-macros v0.13.2
  Downloaded backtrace-sys v0.1.32
  Downloaded libc v0.2.64
  Downloaded nodrop v0.1.14
  Downloaded relative-path v1.0.0
  Downloaded ryu v1.0.2
  Downloaded cc v1.0.46
  Downloaded ena v0.13.1
  Downloaded psm v0.1.5
  Downloaded notify v4.0.14
   Compiling proc-macro2 v1.0.5
   Compiling serde v1.0.101
   Compiling cc v1.0.46
   Compiling libc v0.2.64
   Compiling arrayvec v0.4.12
   Compiling bitflags v1.2.1
   Compiling getrandom v0.1.12
   Compiling cfg-if v0.1.10
   Compiling nodrop v0.1.14
   Compiling ryu v1.0.2
   Compiling either v1.5.3
   Compiling once_cell v1.2.0
   Compiling arrayvec v0.5.1
   Compiling indexmap v1.2.0
   Compiling relative-path v1.0.0
   Compiling chalk-macros v0.1.1 (https://github.com/rust-lang/chalk.git#13303bb0)
   Compiling ra_parser v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_parser)
   Compiling crossbeam-utils v0.6.6
   Compiling log v0.4.8
   Compiling filetime v0.2.7
   Compiling itertools v0.8.0
   Compiling proptest v0.9.4
   Compiling ena v0.13.1
   Compiling globset v0.4.4
   Compiling rand_core v0.5.1
   Compiling num_cpus v1.10.1
   Compiling notify v4.0.14
   Compiling time v0.1.42
   Compiling threadpool v1.7.1
   Compiling crossbeam-queue v0.1.2
   Compiling crossbeam-channel v0.3.9
   Compiling rand_pcg v0.2.0
   Compiling rand_chacha v0.2.1
   Compiling rand v0.7.2
   Compiling chrono v0.4.9
   Compiling quote v1.0.2
   Compiling syn v1.0.5
   Compiling flexi_logger v0.14.4
   Compiling psm v0.1.5
   Compiling stacker v0.1.6
   Compiling backtrace-sys v0.1.32
   Compiling backtrace v0.3.39
   Compiling chalk-engine v0.9.0 (https://github.com/rust-lang/chalk.git#13303bb0)
   Compiling ra_prof v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_prof)
   Compiling chalk-ir v0.1.0 (https://github.com/rust-lang/chalk.git#13303bb0)
   Compiling ra_text_edit v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_text_edit)
   Compiling chalk-rust-ir v0.1.0 (https://github.com/rust-lang/chalk.git#13303bb0)
   Compiling chalk-solve v0.1.0 (https://github.com/rust-lang/chalk.git#13303bb0)
   Compiling serde_derive v1.0.101
   Compiling derive-new v0.5.8
   Compiling salsa-macros v0.13.2
   Compiling serde_repr v0.1.5
   Compiling semver v0.9.0
   Compiling smol_str v0.1.15
   Compiling serde_json v1.0.41
   Compiling url v2.1.0
   Compiling rowan v0.6.2
   Compiling ra_tt v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_tt)
   Compiling rustc_version v0.2.3
   Compiling memoffset v0.5.1
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling crossbeam-epoch v0.7.2
   Compiling ra_syntax v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_syntax)
   Compiling test_utils v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\test_utils)
   Compiling cargo_metadata v0.8.2
   Compiling lsp-server v0.2.0
   Compiling lsp-types v0.61.0
   Compiling crossbeam-deque v0.7.1
   Compiling crossbeam v0.7.2
   Compiling rayon-core v1.6.0
   Compiling salsa v0.13.2
   Compiling ra_vfs v0.5.0
   Compiling rayon v1.2.0
   Compiling ra_vfs_glob v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_vfs_glob)
   Compiling ra_cfg v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_cfg)
   Compiling ra_mbe v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_mbe)
   Compiling ra_fmt v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_fmt)
   Compiling ra_db v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_db)
   Compiling ra_hir v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_hir)
   Compiling ra_project_model v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_project_model)
error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates\ra_hir\src\ty.rs:330:18
    |
330 |                 .collect(),
    |                  ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates\ra_hir\src\ty.rs:341:18
    |
341 |                 .collect(),
    |                  ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[impl_block::ImplBlock]>` cannot be built from an iterator over elements of type `impl_block::ImplBlock`
  --> crates\ra_hir\src\ty\traits.rs:92:23
   |
92 |     impls.into_iter().collect()
   |                       ^^^^^^^ a collection of type `std::sync::Arc<[impl_block::ImplBlock]>` cannot be built from `std::iter::Iterator<Item=impl_block::ImplBlock>`
   |
   = help: the trait `std::iter::FromIterator<impl_block::ImplBlock>` is not implemented for `std::sync::Arc<[impl_block::ImplBlock]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `_`
   --> crates\ra_hir\src\ty\traits\chalk.rs:129:14
    |
129 |             .collect();
    |              ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=_>`
    |
    = help: the trait `std::iter::FromIterator<_>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
  --> crates\ra_hir\src\ty\lower.rs:36:75
   |
36 |                     inner.iter().map(|tr| Ty::from_hir(db, resolver, tr)).collect();
   |                                                                           ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
   |
   = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
  --> crates\ra_hir\src\ty\lower.rs:61:89
   |
61 |                 let sig = Substs(params.iter().map(|tr| Ty::from_hir(db, resolver, tr)).collect());
   |                                                                                         ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
   |
   = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from an iterator over elements of type `ty::GenericPredicate`
  --> crates\ra_hir\src\ty\lower.rs:71:22
   |
71 |                     .collect();
   |                      ^^^^^^^ a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from `std::iter::Iterator<Item=ty::GenericPredicate>`
   |
   = help: the trait `std::iter::FromIterator<ty::GenericPredicate>` is not implemented for `std::sync::Arc<[ty::GenericPredicate]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from an iterator over elements of type `ty::GenericPredicate`
  --> crates\ra_hir\src\ty\lower.rs:81:22
   |
81 |                     .collect();
   |                      ^^^^^^^ a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from `std::iter::Iterator<Item=ty::GenericPredicate>`
   |
   = help: the trait `std::iter::FromIterator<ty::GenericPredicate>` is not implemented for `std::sync::Arc<[ty::GenericPredicate]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from an iterator over elements of type `ty::GenericPredicate`
   --> crates\ra_hir\src\ty\lower.rs:562:10
    |
562 |         .collect()
    |          ^^^^^^^ a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from `std::iter::Iterator<Item=ty::GenericPredicate>`
    |
    = help: the trait `std::iter::FromIterator<ty::GenericPredicate>` is not implemented for `std::sync::Arc<[ty::GenericPredicate]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from an iterator over elements of type `ty::GenericPredicate`
   --> crates\ra_hir\src\ty\lower.rs:586:10
    |
586 |         .collect()
    |          ^^^^^^^ a collection of type `std::sync::Arc<[ty::GenericPredicate]>` cannot be built from `std::iter::Iterator<Item=ty::GenericPredicate>`
    |
    = help: the trait `std::iter::FromIterator<ty::GenericPredicate>` is not implemented for `std::sync::Arc<[ty::GenericPredicate]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates\ra_hir\src\ty\lower.rs:600:10
    |
600 |         .collect();
    |          ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates\ra_hir\src\ty\infer\unify.rs:156:82
    |
156 |         let new_vars = Substs((0..solution.num_vars).map(|_| ctx.new_type_var()).collect());
    |                                                                                  ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from an iterator over elements of type `ty::Ty`
   --> crates\ra_hir\src\ty\infer\pat.rs:120:22
    |
120 |                     .collect();
    |                      ^^^^^^^ a collection of type `std::sync::Arc<[ty::Ty]>` cannot be built from `std::iter::Iterator<Item=ty::Ty>`
    |
    = help: the trait `std::iter::FromIterator<ty::Ty>` is not implemented for `std::sync::Arc<[ty::Ty]>`

error[E0277]: a collection of type `std::sync::Arc<[attr::Attr]>` cannot be built from an iterator over elements of type `attr::Attr`
  --> crates\ra_hir\src\attr.rs:58:80
   |
58 |         Some(attrs.flat_map(|ast| Attr::from_src(Source { file_id, ast }, db)).collect())
   |                                                                                ^^^^^^^ a collection of type `std::sync::Arc<[attr::Attr]>` cannot be built from `std::iter::Iterator<Item=attr::Attr>`
   |
   = help: the trait `std::iter::FromIterator<attr::Attr>` is not implemented for `std::sync::Arc<[attr::Attr]>`

error[E0277]: a collection of type `std::sync::Arc<[T]>` cannot be built from an iterator over elements of type `T`
 --> crates\ra_hir\src\util.rs:9:32
  |
9 |         *a = a.iter().cloned().collect();
  |                                ^^^^^^^ a collection of type `std::sync::Arc<[T]>` cannot be built from `std::iter::Iterator<Item=T>`
  |
  = help: the trait `std::iter::FromIterator<T>` is not implemented for `std::sync::Arc<[T]>`

error: aborting due to 15 previous errors
```
latest master - 6b9bd7bdd2712a7e85d6bfc70c231dbe36c2e585

**Comment by flodiebold** [comment] 2019-10-20 12:17
Please install the newest stable compiler. (duplicate of #2022)

**Closed by flodiebold** 2019-10-20 12:17 UTC
