### ISSUE TITLE
Postfix suggestions on types

### ISSUE THREAD

**Issue by jeffa5** [rust-analyzer/rust-analyzer#9714] opened 2021-07-28 13:57 UTC
When writing and updating function signatures, struct field types etc. it can be repetitive to convert, for example, `u32` to `Option<u32>`, or `u32` to `Vec<u32>`.

Would it be possible to have a postfix for these such that:

```rust
fn f(u: u32.opt$0) {}
```

becomes
```rust
fn f(u: Option<u32>$0) {}
```
Similarly there could be a postfix for `vec`, `result` (not sure how to populate the error variant, perhaps use a tabstop?) and probably others but I think it would be better to start small.

**Comment by Veykril** [comment] 2021-07-28 14:00
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4360

**Closed by Veykril** 2021-07-28 14:00 UTC

**Comment by jeffa5** [comment] 2021-07-28 14:07
Ah, thanks!
