### ISSUE TITLE
Refactor action only changes last occurence of identifier under cursor.

### ISSUE THREAD

**Issue by iago-lito** [rust-analyzer/rust-analyzer#4831] opened 2020-06-10 09:35 UTC
I have been redirected here from [this nvim-coc-rust-analyzer issue](https://github.com/fannheyward/coc-rust-analyzer/issues/280) for it seems to @fannheyward that the problem is on RA side.

But I am not sure how to reformulate it in an LSP-client-agnostic + editor-agnostic way :(

Can I just assume that [this description](https://github.com/fannheyward/coc-rust-analyzer/issues/280#issue-635554470) of the problem will be explicit enough?

**Comment by fannheyward** [comment] 2020-06-10 09:58
`coc-refactor` is a feature that coc.nvim provided to refactor code, it does `rename` on current symbol within a buffer  preview. It needs LS, here RA, provides `provideRenameEdits` for current position symbol. https://github.com/neoclide/coc.nvim/blob/2984f288554ce1713d63465da0201bc22436e9fd/src/handler/index.ts#L1117

Maybe there is something wrong in RA on `provideRenameEdits`?

**Comment by matklad** [comment] 2020-07-11 20:12
Yeah, I am pretty sure this is a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/4831

**Closed by matklad** 2020-07-11 20:12 UTC

**Comment by iago-lito** [comment] 2020-07-15 07:23
@matklad Well, I'm a little confused now, but I suspect your intent was to close #4901 instead? X)

**Comment by matklad** [comment] 2020-07-15 07:27
Right, it should be #4901. Sorry to everyone who got stuck in a loop :-)
