### ISSUE TITLE
Wrong type on result of std::ops impl

### ISSUE THREAD

**Issue by aLagoG** [rust-analyzer/rust-analyzer#7086] opened 2020-12-30 01:06 UTC
As the title says, I'm getting the wrong type on the result of `std::ops` implementations (exemplified here by the `let` code lens). In this case `wrong_f64` is incorrectly assigned the type `f64` while the exact same operation with `non_ops` is assigned the correct type `A`.

```rust
struct A {
    a: f64,
    b: f64,
}

impl A {
    fn non_ops(self, rhs: f64) -> Self {
        A {
            a: self.a * rhs,
            b: self.b * rhs,
        }
    }
}

impl std::ops::Mul<f64> for A {
    type Output = A;

    fn mul(self, rhs: f64) -> Self::Output {
        A {
            a: self.a * rhs,
            b: self.b * rhs,
        }
    }
}

fn main() {
    let st = A { a: 1.0, b: 2.0 };
    let fl = 3.0;

    let wrong_f64 = st * fl;
    let correct_A = st.non_ops(fl);
}
```

It goes even further, if I write `let wrong_i32 = st * 1` even tough there's an error stating that you can't multiply those types the code lens still shows the `i32` type. 

This is all with rust-analyzer 0.2.432 and the latest server version.

**Comment by lnicola** [comment] 2020-12-30 07:43
I think this is a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/5685.

**Closed** 2020-12-30 07:43 UTC
Labels: A-ty, S-actionable
