### ISSUE TITLE
test_attr_macro segmentation fault with nightly rustc

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#9525] opened 2021-07-07 19:36 UTC
When I run `cargo test` in the rust-analyzer repo, I get a segmentation fault on `test_attr_macro`.

Here is the full backtrace:
```
Starting program: $HOME/projects/github/rust-analyzer/target/debug/deps/proc_macro_srv-8d2efebd948afd81 --test-threads=1 test_attr_macro
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

running 1 test
test tests::test_attr_macro ...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dac5aa in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7dac5aa in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
#1  0x000055555590c2e5 in core::intrinsics::copy_nonoverlapping ()
#2  0x000055555590bf2f in alloc::vec::Vec<T,A>::append_elements ()
#3  0x000055555590be3b in <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<&T,core::slice::iter::Iter<T>>>::spec_extend ()
#4  0x000055555590bff6 in alloc::vec::Vec<T,A>::extend_from_slice ()
#5  0x000055555575ff6a in proc_macro_srv::proc_macro::bridge::buffer::{impl#14}::from::extend_from_slice<u8> (b=..., xs=...) at crates/proc_macro_srv/src/proc_macro/bridge/buffer.rs:139
#6  0x00007ffff7b4fbca in proc_macro::bridge::buffer::Buffer::extend_from_slice<u8> ()
    at library/proc_macro/src/bridge/buffer.rs:70
#7  proc_macro::bridge::buffer::{impl#6}::write_all () at library/proc_macro/src/bridge/buffer.rs:100
#8  proc_macro::bridge::rpc::{impl#12}::encode<()> () at library/proc_macro/src/bridge/rpc.rs:212
#9  proc_macro::bridge::rpc::{impl#14}::encode<()> () at library/proc_macro/src/bridge/rpc.rs:227
#10 proc_macro::bridge::client::{impl#154}::from_str::{closure#0} ()
    at library/proc_macro/src/bridge/client.rs:242
#11 proc_macro::bridge::client::{impl#9}::with::{closure#0}<proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#154}::from_str::{closure#0}> ()
    at library/proc_macro/src/bridge/client.rs:336
#12 proc_macro::bridge::client::{impl#8}::with::{closure#0}::{closure#0}<proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#9}::with::{closure#0}> ()
    at library/proc_macro/src/bridge/client.rs:293
#13 proc_macro::bridge::scoped_cell::ScopedCell::replace<proc_macro::bridge::client::BridgeStateL, proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#8}::with::{closure#0}::{closure#0}>
    () at library/proc_macro/src/bridge/scoped_cell.rs:75
#14 proc_macro::bridge::client::{impl#8}::with::{closure#0}<proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#9}::with::{closure#0}> () at library/proc_macro/src/bridge/client.rs:291
#15 std::thread::local::LocalKey::try_with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>, proc_macro::bridge::client::{impl#8}::with::{closure#0}, proc_macro::bridge::client::TokenStream> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/thread/local.rs:399
#16 std::thread::local::LocalKey::with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>, proc_macro::bridge::client::{impl#8}::with::{closure#0}, proc_macro::bridge::client::T--Type <RET> for more, q to quit, c to continue without paging--c
okenStream> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/thread/local.rs:375
#17 proc_macro::bridge::client::BridgeState::with<proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#9}::with::{closure#0}> () at library/proc_macro/src/bridge/client.rs:290
#18 proc_macro::bridge::Bridge::with<proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#154}::from_str::{closure#0}> () at library/proc_macro/src/bridge/client.rs:329
#19 proc_macro::bridge::client::TokenStream::from_str () at library/proc_macro/src/bridge/client.rs:237
#20 proc_macro::{impl#8}::from_str () at library/proc_macro/src/lib.rs:138
#21 0x00007ffff7b42864 in core::str::{impl#0}::parse<proc_macro::TokenStream> (self=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/str/mod.rs:2221
#22 0x00007ffff7b3f508 in proc_macro_test_impl::attr_error (args=..., item=...) at src/lib.rs:37
#23 0x00007ffff7b3e33c in core::ops::function::FnOnce::call_once<fn(proc_macro::TokenStream, proc_macro::TokenStream) -> proc_macro::TokenStream, (proc_macro::TokenStream, proc_macro::TokenStream)> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/ops/function.rs:227
#24 0x00007ffff7b37f93 in proc_macro::bridge::client::{impl#11}::expand2::run::{closure#0}<fn(proc_macro::TokenStream, proc_macro::TokenStream) -> proc_macro::TokenStream> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:426
#25 0x00007ffff7b37bee in proc_macro::bridge::client::run_client::{closure#0}::{closure#0}<(proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::TokenStream), proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#11}::expand2::run::{closure#0}> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:377
#26 0x00007ffff7b3c237 in proc_macro::bridge::scoped_cell::{impl#3}::set::{closure#0}<proc_macro::bridge::client::BridgeStateL, (), proc_macro::bridge::client::run_client::{closure#0}::{closure#0}> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/scoped_cell.rs:80
#27 0x00007ffff7b3d303 in proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>::replace<proc_macro::bridge::client::BridgeStateL, (), proc_macro::bridge::scoped_cell::{impl#3}::set::{closure#0}> (self=0x555555996298, replacement=..., f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/scoped_cell.rs:75
#28 0x00007ffff7b3c1f4 in proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>::set<proc_macro::bridge::client::BridgeStateL, (), proc_macro::bridge::client::run_client::{closure#0}::{closure#0}> (self=0x555555996298, value=..., f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/scoped_cell.rs:80
#29 0x00007ffff7b38b0c in proc_macro::bridge::client::{impl#9}::enter::{closure#1}<(), proc_macro::bridge::client::run_client::{closure#0}::{closure#0}> (state=0x555555996298) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:325
#30 0x00007ffff7b40c6f in std::thread::local::LocalKey<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::try_with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>, proc_macro::bridge::client::{impl#9}::enter::{closure#1}, ()> (self=0x7ffff7c3a508, f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/thread/local.rs:399
#31 0x00007ffff7b4057a in std::thread::local::LocalKey<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>, proc_macro::bridge::client::{impl#9}::enter::{closure#1}, ()> (self=0x7ffff7c3a508, f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/thread/local.rs:375
#32 0x00007ffff7b4009a in proc_macro::bridge::Bridge::enter<(), proc_macro::bridge::client::run_client::{closure#0}::{closure#0}> (self=..., f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:325
#33 0x00007ffff7b37804 in proc_macro::bridge::client::run_client::{closure#0}<(proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::TokenStream), proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#11}::expand2::run::{closure#0}> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:370
#34 0x00007ffff7b44280 in std::panic::{impl#30}::call_once<(), proc_macro::bridge::client::run_client::{closure#0}> (self=..., _args=()) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panic.rs:347
#35 0x00007ffff7b3bdba in std::panicking::try::do_call<std::panic::AssertUnwindSafe<proc_macro::bridge::client::run_client::{closure#0}>, ()> (data=0x7fffffffb618) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:401
#36 0x00007ffff7b3c0ad in __rust_try () from $HOME/projects/github/rust-analyzer/target/debug/build/proc_macro_test-b51de50a18bbc323/out/target/debug/libproc_macro_test_impl.so
#37 0x00007ffff7b3bb91 in std::panicking::try<(), std::panic::AssertUnwindSafe<proc_macro::bridge::client::run_client::{closure#0}>> (f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:365
#38 0x00007ffff7b44320 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<proc_macro::bridge::client::run_client::{closure#0}>, ()> (f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panic.rs:434
#39 0x00007ffff7b3738f in proc_macro::bridge::client::run_client<(proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::TokenStream), proc_macro::bridge::client::TokenStream, proc_macro::bridge::client::{impl#11}::expand2::run::{closure#0}> (bridge=..., f=...) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:369
#40 0x00007ffff7b37f1c in proc_macro::bridge::client::{impl#11}::expand2::run<fn(proc_macro::TokenStream, proc_macro::TokenStream) -> proc_macro::TokenStream> (bridge=..., f=0x7ffff7b3f370 <proc_macro_test_impl::attr_error>) at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/proc_macro/src/bridge/client.rs:425
#41 0x0000555555728386 in proc_macro_srv::proc_macro::bridge::server::{impl#0}::run_bridge_and_client<fn(proc_macro_srv::proc_macro::bridge::client::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream) -> proc_macro_srv::proc_macro::bridge::client::TokenStream, proc_macro_srv::proc_macro::bridge::server::Dispatcher<proc_macro_srv::proc_macro::bridge::server::MarkedTypes<proc_macro_srv::rustc_server::Rustc>>> (self=0x5555555ca53d, dispatcher=0x7fffffffbb28, input=..., run_client=0x7ffff7b37ed0 <proc_macro::bridge::client::{impl#11}::expand2::run<fn(proc_macro::TokenStream, proc_macro::TokenStream) -> proc_macro::TokenStream>>, client_data=0x7ffff7b3f370 <proc_macro_test_impl::attr_error>, force_show_panics=false) at crates/proc_macro_srv/src/proc_macro/bridge/server.rs:158
#42 0x00005555557288d2 in proc_macro_srv::proc_macro::bridge::server::run_server<proc_macro_srv::rustc_server::Rustc, (proc_macro_srv::proc_macro::bridge::Marked<proc_macro_srv::rustc_server::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream>, proc_macro_srv::proc_macro::bridge::Marked<proc_macro_srv::rustc_server::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream>), proc_macro_srv::proc_macro::bridge::Marked<proc_macro_srv::rustc_server::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream>, fn(proc_macro_srv::proc_macro::bridge::client::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream) -> proc_macro_srv::proc_macro::bridge::client::TokenStream, proc_macro_srv::proc_macro::bridge::server::SameThread> (strategy=0x5555555ca53d, handle_counters=0x7ffff7c46698 <proc_macro::bridge::client::HandleCounters::get::COUNTERS>, server=..., input=..., run_client=0x7ffff7b37ed0 <proc_macro::bridge::client::{impl#11}::expand2::run<fn(proc_macro::TokenStream, proc_macro::TokenStream) -> proc_macro::TokenStream>>, client_data=0x7ffff7b3f370 <proc_macro_test_impl::attr_error>, force_show_panics=false) at crates/proc_macro_srv/src/proc_macro/bridge/server.rs:294
#43 0x000055555578c0ee in proc_macro_srv::proc_macro::bridge::client::Client<fn(proc_macro_srv::proc_macro::bridge::client::TokenStream, proc_macro_srv::proc_macro::bridge::client::TokenStream) -> proc_macro_srv::proc_macro::bridge::client::TokenStream>::run<proc_macro_srv::rustc_server::Rustc, proc_macro_srv::proc_macro::bridge::server::SameThread> (self=0x555555999368, strategy=0x5555555ca53d, server=..., input=..., input2=..., force_show_panics=false) at crates/proc_macro_srv/src/proc_macro/bridge/server.rs:337
#44 0x0000555555791b3b in proc_macro_srv::dylib::Expander::expand (self=0x7fffffffc7f0, macro_name=..., macro_body=0x7fffffffc8d0, attributes=...) at crates/proc_macro_srv/src/dylib.rs:153
#45 0x0000555555778432 in proc_macro_srv::tests::utils::assert_expand_impl (macro_name=..., input=..., attr=..., expect=...) at crates/proc_macro_srv/src/tests/utils.rs:33
#46 0x00005555557781e2 in proc_macro_srv::tests::utils::assert_expand_attr (macro_name=..., ra_fixture=..., attr_args=..., expect=...) at crates/proc_macro_srv/src/tests/utils.rs:24
#47 0x00005555557828df in proc_macro_srv::tests::test_attr_macro () at crates/proc_macro_srv/src/tests/mod.rs:63
#48 0x000055555578a86a in proc_macro_srv::tests::test_attr_macro::{closure#0} () at crates/proc_macro_srv/src/tests/mod.rs:59
#49 0x000055555577b0de in core::ops::function::FnOnce::call_once<proc_macro_srv::tests::test_attr_macro::{closure#0}, ()> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/ops/function.rs:227
#50 0x00005555557e92c3 in core::ops::function::FnOnce::call_once<fn(), ()> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/ops/function.rs:227
#51 test::__rust_begin_short_backtrace<fn()> () at library/test/src/lib.rs:577
#52 0x00005555557e7d50 in alloc::boxed::{impl#44}::call_once<(), dyn core::ops::function::FnOnce<()>, alloc::alloc::Global> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/alloc/src/boxed.rs:1572
#53 std::panic::{impl#30}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<()>, alloc::alloc::Global>> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panic.rs:347
#54 std::panicking::try::do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<dyn core::ops::function::FnOnce<()>, alloc::alloc::Global>>, ()> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:401
#55 std::panicking::try<(), std::panic::AssertUnwindSafe<alloc::boxed::Box<dyn core::ops::function::FnOnce<()>, alloc::alloc::Global>>> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:365
#56 std::panic::catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<dyn core::ops::function::FnOnce<()>, alloc::alloc::Global>>, ()> () at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panic.rs:434
#57 test::run_test_in_process () at library/test/src/lib.rs:600
#58 test::run_test::run_test_inner::{closure#0} () at library/test/src/lib.rs:492
#59 0x00005555557e717d in test::run_test::run_test_inner () at library/test/src/lib.rs:530
#60 0x00005555557e5b0d in test::run_test () at library/test/src/lib.rs:564
#61 0x00005555557e0720 in test::run_tests<test::console::run_tests_console::{closure#2}> () at library/test/src/lib.rs:305
#62 0x00005555557d1b31 in test::console::run_tests_console () at library/test/src/console.rs:290
#63 0x00005555557de85f in test::test_main () at library/test/src/lib.rs:122
#64 0x00005555557df941 in test::test_main_static () at library/test/src/lib.rs:141
#65 0x000055555578afe3 in proc_macro_srv::main () at crates/proc_macro_srv/src/lib.rs:1
```

Tested with commit 11f3231a75f74e87074bd6e4c9d61c635adffce1
rustc version: rustc 1.55.0-nightly (885399992 2021-07-06)

**Comment by bjorn3** [comment] 2021-07-07 19:39
Proc macros are currently unsupported on nightly rustc due to an abi change. Try switching to stable.

Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8925

**Closed** 2021-07-07 19:40 UTC

**Comment by flodiebold** [comment] 2021-07-07 19:59
I don't think we should be getting a segfault though, should we? :thinking:

**Comment by bjorn3** [comment] 2021-07-07 21:52
I believe there have also been changes around the buffer management in proc-macro recently, so a segfault is not unexpected I think.
