### ISSUE TITLE
Weird autocomplete order now

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#6615] opened 2020-11-24 04:22 UTC
Hi all! sorry for making another issue on the magic imports (I really like this feature and just want it to be great!), but it's made for some very weird ordering problems:

![Screenshot 2020-11-23 at 20 17 15](https://user-images.githubusercontent.com/31973761/100048353-733d3680-2dc9-11eb-94ce-82459a399db6.png)

As you can see in the above, it's selected a specific iterator method over the local variable. It consistently does this, and it's making typing a bit tough. For now, I've rolled back to last week.

EDIT: just to be clear, the first result SHOULD be "success". The entire file, except the return statement of that function, is present. there are no imports at the top of the file (I just started writing!)

**Comment by SomeoneToIgnore** [comment] 2020-11-24 07:16
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4922

**Closed** 2020-11-24 07:18 UTC

**Comment by sanbox-irl** [comment] 2020-11-24 19:05
@SomeoneToIgnore I understand why you closed this, but I would argue that it should either be re-opened, or a new issue should be made for both of thse.

The problem has existed for awhile, but didn't matter a particular amount, since nothing was in scope except what the user chose to bring into scope.

Now, though, with anything being in hte autocomplete, totally unrelated things are suddenly at the top of my autocomplete that have nothing to do with what I'm programming. It's a big productivity loss

**Comment by SomeoneToIgnore** [comment] 2020-11-24 19:14
I understand that it may cause issues, thanks to you we have one more to tackle now.

I don't understand how reopening this duplicate issue helps: the original issue describes the task better and we can continue the discussion there in case you want to contribute to the actual order import issue.
Note that the order import task is tagged as "hard" which most probably means that it will take months to implement, so I would not expect it to be fixed in the near future.

In the other ticket, which is close to "autocomplete had broken my workflow" by the contents, I've proposed to add a setting to disable the new completion, as a middleground:
https://github.com/rust-analyzer/rust-analyzer/issues/6612#issuecomment-732511567

and also I'm open to other ideas, if you have any.
Should we continue the discussion there?

**Comment by sanbox-irl** [comment] 2020-11-24 19:27
alright, let's relax -- I'm just posting issues here, don't mean to be insulting or anything.

The other issue's problem is both hard and trivial -- scoping isn't extremely important when there are few imports. Scoping is now, suddenly, much more important. That's why I've brought it up -- the previous issue hadn't been tackled because it wasn't very important. IMO, it has gotten much more important!

**Comment by SomeoneToIgnore** [comment] 2020-11-24 20:41
I'm pretty relaxed, neither I am angry or anyhow feeling bad about our current conversation.
Maybe my wording was not right because I've tried to keep it short and simple, let me try once more, in a longer format.


What I'm trying to explain is that the import ordering implementation will take time, I don't even know how to tackle it yet. 
And I don't think I can work on this particular card in my near future too, despite the awareness of the issue importance (I've mentioned the issue in the original completion import PR, I realise it's needed).

Also, different people consider diffrent issues to be the most important to them: some people still think RA is unusable at its curent state, for example; the imports on completion feature took almost 2 years to get it done despite the plenty of people considering it to be very important.

Last but not least, the development mainly done by the people in their free time: they need mentoring, useful comments with instructions and hints and good elaborations on the technical side of the issues to be able to hold the context in their head and pass it on to other people.

I don't think that keeping the duplicate issues open help in any way: they take time to manage, they fragment the vision and just bloat the information, distracting contributors' attention.
I also believe that comments about the issue's importance to a certain user or comments that try to "ping" the development are useful: they bring no value and state the obvious at best.

So, I strive to be constructive, on topic and to channel the talks into something actionable: code snippets, repro examples, implementation ideas, etc.
And I also prefer to review or create PRs instead of creating such comments: this single one had devoured more than an hour and gave zero satisfaction to me personally (mainly because it dissonates with the constructiveness principle stated above).

This all combined with my experience on the development here tell me that there will be no ordering feature anytime soon unless a miracle happens.
Still, I want to help you to get back on track with the latest stable RA.
For this, I'm trying to find a compromise and my current idea is described here: https://github.com/rust-analyzer/rust-analyzer/issues/6612#issuecomment-732511567
Please join me there and also add your constructive input to the original import order issue, if you want to.
