### ISSUE TITLE
No diagnostics are showing

### ISSUE THREAD

**Issue by MarkSwanson** [rust-analyzer/rust-analyzer#2780] opened 2020-01-09 18:31 UTC
cargo-check from the command line shows lots of warnings.
VSCode shows no warnings/diagnostics.

Currently VSCode shows errors in the editor pane. I can jump to the next/previous error easily.
I'd like warnings to work the same way. Is this possible?

My vscode settings.json:
````
{
    "git.confirmSync": false,
    "rust-analyzer.enableEnhancedTyping": false,
    "editor.minimap.enabled": false,
    "rust-analyzer.lruCapacity": 99999,
    "rust-analyzer.rainbowHighlightingOn": true,
    "vim.debug.loggingLevelForAlert": "verbose",
    "vim.debug.loggingLevelForConsole": "info",
    "vim.useSystemClipboard": true,
    "rust-analyzer.highlightingOn": true,
    "rust-analyzer.cargo-watch.allTargets": true,
    "rust-analyzer.displayInlayHints": false,
    "rust-analyzer.enableCargoWatchOnStartup": true,
    "rust-analyzer.cargo-watch.command": "check",
    "problems.showCurrentInStatus": true,
    "extensions.showRecommendationsOnlyOnDemand": true,
    "rust-analyzer.cargoFeatures.allFeatures": true,
    "completion.enable-postfix": true,
    "lsp.diagnostics": true,
    "notifications.workspace-loaded": true,
    "notifications.cargo-toml-not-found": false,
    "rust-analyzer.trace.server": "verbose",
}
````

**Comment by bjorn3** [comment] 2020-01-09 18:49
Probably duplicate of #2707. It should work if you open the file containing the warnings. If not, then this is not a duplicate.

**Comment by MarkSwanson** [comment] 2020-01-09 19:28
Thanks, but I'm not getting any warnings on any files - open or not.

**Comment by kiljacken** [comment] 2020-01-09 20:06
@MarkSwanson Wait, so am I reading this right: You're getting the compiler error message (specifically one from rustc), but not the warnings?

**Comment by MarkSwanson** [comment] 2020-01-10 03:10
Right.

**Comment by kiljacken** [comment] 2020-01-10 08:46
I've added some extra output over on the `watch-debug` branch of [my fork](https://github.com/kiljacken/rust-analyzer/tree/watch-debug). Would you mind giving that a go and sharing the text from the Output tab from "Rust Analyzer Language Server".

**Comment by MarkSwanson** [comment] 2020-01-10 14:06
Ok, TIL there is a drop-down in the Output window. I compiled/used your 'watch-debug' branch, selected Output / "Rust Analyzer Language Server" and the problem is immediately apparent to me: VSCode (or maybe? rust-analyzer) is selecting the wrong directory.
Or, since I just started using VSCode I could be using Workspaces incorrectly.

Workspace dir == /Users/maswanso/src/test/<various git repos are cloned in here>

The Output window error is:
[WatchThread] Command and args: cargo ["check", "--message-format=json", "--manifest-path", "/Users/maswanso/src/test/Cargo.toml", "--all-targets"]

So obviously that's not going to work. There will never be a Cargo.toml file there.

Note: when I start VSCode, RA is smart enough to make 2 attempts:
1. .../test/Cargo.toml -> fails, and I get this popup: rust-analyzer failed to load workspace: can't find Cargo.toml at ../test/Cargo.toml
2. Success: RA found and loaded 141 crates -> and hover, tab-completion etc. work.

The 141 crates are found via: .../test/ratest1/Cargo.toml

It seems inconsistent to my newbie VSCode eyes that tab-completion etc. work, but cargo-watch does not.

Am I abusing the VSCode Workspace concept? It really seemed obvious to me that VSCode wants a 'Workspace' to contain a bunch of git repos. Again, I'm a VSCode newbie. If I'm wrong please help me understand what I should be doing.

Thanks!

**Comment by kiljacken** [comment] 2020-01-10 15:09
Okay, that makes a lot of sense.

Rust-analyzer currently works best when the editor workspace root is the root of a rust project. Your not doing anything wrong per-say, we just haven't gotten around to investigating what the best way of handling workspaces with rust "sub projects" in them.

So if you want to get the best experience, you have to open vscode in the root of a rust project. I'll leave the issue open, especially because the rest of rust analyzer picks up the right Cargo.toml in this case, as there's a lot of room for improvement.

**Comment by MarkSwanson** [comment] 2020-01-10 17:37
Cool.
I generally have a bunch of Rust git repos open at the same time. TIL VSCode switches between windows just fine with CMD-~, and I'm perfectly happy to work on a git repo per window.

Everything else worked ootb. It was even easy to get it all working remotely via VSCode remote development using the instructions in the RA user docs.

**Comment by kiljacken** [comment] 2020-01-10 21:13
@MarkSwanson Could you give #2791 a try? I believe it should fix your original issue.

**Closed** 2020-01-11 20:51 UTC
