### ISSUE TITLE
Use branch, not tag, for nightly

### ISSUE THREAD

**Issue by tmandry** [rust-analyzer/rust-analyzer#5562] opened 2020-07-28 23:18 UTC
The fact that the nightly tag regularly changes causes errors while fetching rust in our infrastructure:

```
Fetching submodule src/tools/rust-analyzer
From https://github.com/rust-analyzer/rust-analyzer
 + 8f51657c6...def1a2c14 gh-pages   -> origin/gh-pages  (forced update)
   41feb816c..5a8124273  master     -> origin/master
   8b0983e89..8ff40af72  release    -> origin/release
   41feb816c..5a8124273  staging    -> origin/staging
 * [new tag]             2020-07-13 -> 2020-07-13
 * [new tag]             2020-07-20 -> 2020-07-20
 * [new tag]             2020-07-27 -> 2020-07-27
 ! [rejected]            nightly    -> nightly  (would clobber existing tag)
Errors during submodule fetch:
        src/tools/rust-analyzer
```

There are options to fix this I'm sure, but tags aren't expected to change like this (certainly not on a regular basis); that's what branches are for.

**Comment by matklad** [comment] 2020-07-29 10:09
Using tags is more convenient for us -- plays well with github releases & we can re-use wasmtime release infra. Our general stance for "packaging" in the general sense is that we only ship github releases, and downstream packages need to implement pacakging outside of rust-analyzer infrastrucutre. 

So, closing as won't fix -- the problem is real, but it's not hight priority for rust-analyzer.

**Closed by matklad** 2020-07-29 10:09 UTC

**Comment by Walther** [comment] 2021-07-27 10:59
Ran into this problem in the `rust-lang/rust` repository when doing a `git pull`. With a bit of searching, found this issue. Leaving this comment in order to possibly help the next person: you can overwrite the existing tags by doing `git fetch --tags --force` in the repository.
