### ISSUE TITLE
Feature request: being able to follow internal links in the documentation

### ISSUE THREAD

**Issue by irevoire** [rust-analyzer/rust-analyzer#9708] opened 2021-07-27 13:21 UTC
Hello,

It would be great if we could follow links in the code documentation / comments in the same way rustdoc handle it.
For example for this snippet of code:

```rust
#[async_trait::async_trait]
#[cfg_attr(test, automock)]
pub trait DumpActorHandle {
    /// Start the creation of a dump
    /// Implementation: [handle_impl::DumpActorHandleImpl::create_dump]
    async fn create_dump(&self) -> Result<DumpInfo>;

    /// Return the status of an already created dump
    /// Implementation: [handle_impl::DumpActorHandleImpl::dump_info]
    async fn dump_info(&self, uid: String) -> Result<DumpInfo>;
}
```
I would like to put my cursor on the `handle_impl::DumpActorHandleImpl::create_dump` and jump to the definition.

**Comment by Veykril** [comment] 2021-07-27 13:25
That is actually already implemented, but our doc path resolution isn't fully working yet(I'm currently trying to fix that up) which is why it doesn't work in your case here.

**Comment by Veykril** [comment] 2021-07-27 13:44
As such I'll close this as an indirect dupe of #9694

**Closed by Veykril** 2021-07-27 13:44 UTC
