### ISSUE TITLE
Function syntax highlighting with attribute proc macro 

### ISSUE THREAD

**Issue by gtsiam** [rust-analyzer/rust-analyzer#9513] opened 2021-07-06 16:30 UTC
So, I turned on experimental proc attr macro expansion for a custom macro, but syntax highlighting seems to really not like it when I pass expressions from the attributes to the output. Here's the macro (well, the shortest version of it where I could get the error):

```rust
struct FilterAttr {
    filters: Vec<Expr>,
}

// Parse attributes as Punctuated<_, Token![,]>
// impl Parse for FilterAttr { ... }

#[proc_macro_attribute]
pub fn filter_minimal(attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let attr = parse_macro_input!(attr as FilterAttr);

    let filters = attr.filters;
    let vis = func.vis;
    let name = func.sig.ident;
    let tokens = quote! {
        #vis fn #name() {
            let dummy = 0i32 #( .wrapping_add(#filters) )*;
        }
    };

    tokens.into()
}
```
```rust
#[filter_minimal(1, 2, 3)]
pub async fn test() {}
```

Here's the problematic highlighting:

![εικόνα](https://user-images.githubusercontent.com/7459196/124634580-3113c180-de8f-11eb-9206-da99c75d6ef8.png)
![εικόνα](https://user-images.githubusercontent.com/7459196/124634643-3f61dd80-de8f-11eb-9e70-34fb40f80b5d.png)

From some testing, it seems that the issue only appears when I try to put the attributes in the output. In every other case, highlighting seemed to work correctly. I also tried changing `FilterAttr::filters` to `Vec<Lit>`, but the issue persists.

**Comment by Veykril** [comment] 2021-07-06 16:33
Dupe of https://github.com/rust-analyzer/rust-analyzer/issues/9185 I believe?

**Comment by gtsiam** [comment] 2021-07-06 16:38
Possibly? It's hard to tell, since I'm not familiar with rust-analyzer's internals.

**Comment by Veykril** [comment] 2021-07-06 16:41
On a second look ye this seems to be a dupe of that one, closing in favor of it.

**Closed by Veykril** 2021-07-06 16:41 UTC
