### ISSUE TITLE
Can we have rust-analyzer support for Visual Studio 2022?

### ISSUE THREAD

**Issue by soumesh2002** [rust-analyzer/rust-analyzer#11428] opened 2022-02-07 07:42 UTC
Visual Studio is one of the best IDE of C++ and C# for windows. So can we have rust lang support for Visual Studio?

**Comment by lnicola** [comment] 2022-02-07 07:46
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8729.

**Closed by lnicola** 2022-02-07 07:46 UTC

**Comment by parthopdas** [comment] 2023-01-30 12:32
@soumesh2002 here it is https://marketplace.visualstudio.com/items?itemName=kitamstudios.RustAnalyzer&ssr=false#overview

For now the following are functional - please feel free to use it or even better, help me out
- Build, Clean (errors in Error list with details in output window).
- Debug & Run without debugging.
- Workspace support (continuing to get enhanced as I find more examples).
- Intellisense / Auto-complete / Goto definition / Code actions / Find references etc. all features from Rust language server.
- Tested above features with top Rust OSS projects like [cargo](https://github.com/rust-lang/cargo), [ruffle](https://github.com/ruffle-rs/ruffle), [iced](https://github.com/iced-rs/iced), [geo](https://github.com/georust/geo), [ruff](https://github.com/charliermarsh/ruff), [reqwest](https://github.com/seanmonstar/reqwest), [wasmtime](https://github.com/bytecodealliance/wasmtime).

Coming up shortly: examples integration, clippy/fmt, unit testing etc.

**Comment by aiyou9** [comment] 2023-04-20 01:48
https://github.com/kitamstudios/rust-analyzer.vs
