### ISSUE TITLE
go to definition cannot be used in the first few minutes when opening a very large project

### ISSUE THREAD

**Issue by w93163red** [rust-analyzer/rust-analyzer#3914] opened 2020-04-09 13:22 UTC
Hi all, 
go to definition cannot be used in the first few minutes when opening a very large project. It is not very convenient when I need to close the vim and open the vim frequently.

**Comment by matklad** [comment] 2020-04-09 13:55
duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1650

TL;DR: This is a current limitation of rust-analyzer, which doesn't persist caches to disk. But it's also a fundamental nature of rust-analyzer that it is optimized for a long-running daemon mode, and, as this reports are most often comming from vim users, I wonder if something can be done on vim's side to persist connection between sessions....

**Closed by matklad** 2020-04-09 13:55 UTC

**Comment by lnicola** [comment] 2020-04-09 13:57
There's a related conversation [here](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/rust-project.2Ejson/near/191030259).

**Comment by matklad** [comment] 2020-04-09 14:13
Actually, let's cc @norcalli (who is invovled wit neovim-lsp) just in case. 

@norcalli, my understanding is that vim users often work by creating and killing a vim process for each file and that "vim", by default, creates a new instance of language server pre file. This can be considered suboptimal, as language servers are organized around the idea of a persistent daemon process, which watches the changes. 

Now, rust-analyzer is a particularly egregious offender here, as we don't do any kind of on-disk caching whatsoever (mostly to drastically simplify the architecture while we are in the experimentation phase). I do believe that, long term, we'll be able to get a "not so bad" startup time. However, it would be nice if neovim-lsp supported the daemon use-case (which it might already do, I don't really know).

**Comment by w93163red** [comment] 2020-04-09 14:19
You might need to cc the author of coc.nvim. Lots of people use coc.nvim for the language server.

**Comment by matklad** [comment] 2020-04-09 14:26
Hm, I was under the impression that coc.rust-anlayzer doesn't have this problem, but let's ask @fannheyward :-)

**Comment by w93163red** [comment] 2020-04-09 14:28
I use the coc.rust-analyzer. It also has this question.

**Comment by w93163red** [comment] 2020-04-09 14:29
I don't know if generating the tags file can help to boost the go-to time.
